### ISSUE TITLE
nerveunity.wad autoload

### ISSUE THREAD

**Issue by kewalsky** [ZDoom/gzdoom#1263]
Using the following files verified against SHA1s on https://github.com/Doom-Utils/iwad-patches :
- nerveunity.wad (v1.3)
- nerve.wad (vBFG)
- doom2unity.wad (v1.3)

The file nerveunity.wad replaces the "Hell on Earth" episode with "No Rest for the Living" and does not give an episode select screen. If renamed to "nerveunity" nerve.wad's BFG version will show the episode select screen with doom2unity.wad when autoloaded.

**Comment by kewalsky** [comment]
Just to note this is how the Doom 2 Classic client even displays the Nerve content. When enabled it removes the "New Game" option under Single Player and forces you to use the level select.

![image](https://user-images.githubusercontent.com/10713450/103383407-9f329280-4ac0-11eb-9d04-3c9f2634413c.png)

**Comment by madame-rachelle** [comment]
Partially fixed, however GZDoom is still *not* able to find the addon version of Nerve.wad yet. Someday I'll get around to that - it'll be when TNT.wad and Plutonia.wad get autofound as well. (Having to search the system user's folders for these files is *not* ideal)
