### ISSUE TITLE
Mouse cursor briefly seen on-screen while turning since 4.6.0

### ISSUE THREAD

**Issue by pagb666** [ZDoom/gzdoom#1402]
I've been experiencing this distracting bug since I upgraded to 4.6.0. When moving the mouse, sometimes the mouse cursor can be seen on screen for what seems the duration of a frame, it is very distracting, and also can been be seen when recording game footage. Switching to OpenGL or Vulkan doesn't make a difference.

**Comment by pagb666** [comment]
I can add more insight about this. Tried unplugging my second display and it got fixed. However, this didn't happen before 4.6.0

**Comment by madame-rachelle** [comment]
There is no info to go by here. Are you using windowed? Fullscreen? And what operating system are you using? Just for good measure are your GPU drivers up to date? What GPU are you using?

**Comment by pagb666** [comment]
Fullscreen. Win10. GTX 1070. Drivers are (of course) up to date.
