### ISSUE TITLE
[BUG]  No fallback to GLES2 if OpenGL 3.3 is unavailable

### ISSUE THREAD

**Issue by Eonfge** [ZDoom/gzdoom#1480]
### GZDoom version

GZDoom 4.7.0 Flatpak

### Which game are you running with GZDoom?

Heretic

### What Operating System are you using?

Linux ARM (Raspberry Pi)

### Relevant hardware info

Pinebook Pro

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When I start GZDooom for the first time on a Pinebook Pro, it will tell me that I don't have OpenGL 3.3 support. And that's where it stops. It would be much better if the application tries GLES2 if OpenGL 3.3 is unsupported.

The only available workaround, is to manually set  `vid_preferbackend 3` 

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Get a terribly underpowered ARM laptop
2. Install GZDoom and try to run it

**Comment by coelckers** [comment]
This will be changed for the 5.0 legacy release.
