### ISSUE TITLE
[BUG] Ambient Occlusion messed up

### ISSUE THREAD

**Issue by NineKain** [ZDoom/gzdoom#1481]
### GZDoom version

gzdoom-x64-g4.8pre-27-gd0975467f

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 10

### Relevant hardware info

R5 5600x, 3060ti, 16gb RAM

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Ambient occlusion it's dissapearing, warping, flickering etc, its may more noticeable with night vision on.

Video compression wont let me showcase the issue properly.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Get in any level
2. Put Ambient Occlusion to any value and night vision (not the enhanced one)
3. Check the walls, the floors, whatever while moving, it will start flickering and warping

**Comment by Calinou** [comment]
> Video compression wont let me showcase the issue properly.

Could you try to take several screenshots and see if the issue is visible on them?

**Comment by NineKain** [comment]
I cant right now, ill try tomorrow, also happens in Raze (although its unsupported), regardless of setting, on a screenshot it doesn't look as bad, it just warping and flickering in motion

**Comment by Ao1Pointblank** [comment]
does it look like this? i get it all the time. the problem goes away when dynamic lighting is turned off.
running v4.7.1 on linux mint.
![Screenshot_Doom_20220516_180627](https://user-images.githubusercontent.com/88149675/168690206-15bbb630-a385-4208-9c96-08fcab67cf3b.png)

**Comment by Ao1Pointblank** [comment]
the checkerboard pattern flashes between white, black, and blue. it happens even without nightvision.

**Comment by madame-rachelle** [comment]
This looks like either a bad custom shader, or a driver problem.

Is it still an issue today?

**Comment by NineKain** [comment]
> This looks like either a bad custom shader, or a driver problem.
> 
> Is it still an issue today?

I dont use any shaders and my drivers are latest nvidia with ddu previously
