### ISSUE TITLE
[BUG] GLES not working with RK3326 devices (e.g Anbernic RG351, Odroid Go Advance, Odroid Go Super)

### ISSUE THREAD

**Issue by dhwz** [ZDoom/gzdoom#1485]
### GZDoom version

GZDoom g4.8pre-28-gbc75dc056 - 2021-10-13 22:42:36 +0200 - SDL version

### Which game are you running with GZDoom?

Doom

### What Operating System are you using?

Other

### If Other OS, please describe

OS: 351ELEC (Community - 351ELEC IS FREE AND NOT FOR SALE!) 20210603, Linux 4.4.189 on aarch64

### Relevant hardware info

CPU: RK3326 SoC, GPU: Mali-G31

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Unable to launch GZDoom with GLES, but hardware is fully compatible to OpenGL ES 11/2.0/3.2
(some previously "hacked ES version of GZDoom https://github.com/fdboi/gzdoom already worked, but that wasn't really properly coded I think)

### Steps to reproduce the behaviour.

Launched with:
LD_PRELOAD=./libzmusic.so.1.1.8 ./gzdoom +vid_preferbackend 3 -IWAD /storage/roms/doom/doom.wad

### Provide a Log

GZDoom g4.8pre-28-gbc75dc056 - 2021-10-13 22:42:36 +0200 - SDL version
Compiled on Oct 15 2021

OS: 351ELEC (Community - 351ELEC IS FREE AND NOT FOR SALE!) 20210603, Linux 4.4.189 on aarch64
M_LoadDefaults: Load system defaults.
W_Init: Init WADfiles.
 adding /storage/.config/gzdoom/gzdoom.pk3, 666 lumps
 adding /storage/.config/gzdoom/game_support.pk3, 2514 lumps
 adding /storage/roms/doom/doom.wad, 2306 lumps
 adding /storage/.config/gzdoom/game_widescreen_gfx.pk3, 196 lumps
I_Init: Setting up machine state.
V_Init: allocate screen.
S_Init: Setting up sound.
I_InitSound: Initializing OpenAL
  Opened device ALSA Default
  EFX enabled
ST_Init: Init startup screen.
Checking cmd-line parameters...
S_InitData: Load sound definitions.
G_ParseMapInfo: Load map definitions.
Texman.Init: Init texture manager.
ParseTeamInfo: Load team definitions.
LoadActors: Load actor definitions.
script parsing took 1311.20 ms
R_Init: Init Doom refresh subsystem.
DecalLibrary: Load decals.
M_Init: Init menus.
P_Init: Init Playloop state.
ParseSBarInfo: Loading custom status bar definition.
D_CheckNetGame: Checking network game status.
player 1 of 1 (1 nodes)
Using video driver KMSDRM

Could not create OpenGL window:
Could not initialize OpenGL / GLES library

**Comment by Cacodemon345** [comment]
Append `+set gl_es 1` to the arguments and run GZDoom.

**Comment by Cacodemon345** [comment]
What error do you get?

**Comment by Cacodemon345** [comment]
Like I said you append `+set gl_es 1` to the command line and run.

**Comment by dhwz** [comment]
And as I already wrote above yes that works, BUT the color format is wrong so nothing is visible on the screen unless I patch the above code parts to rotate BGRA with RGBA and vice versa.

**Comment by Cacodemon345** [comment]
Then you are free to do a PR on this.

**Comment by mjr4077au** [comment]
The values probably just need some endianess swapping I imagine, shouldn't be too hard to fix in a compatible way for both platforms.

**Comment by emileb** [comment]
Hi, the problem is the 'USE_GLES2' define is not actually exposed to the make system.


The USE_GLES2 define is not very clear sorry. On PC builds USE_GLES2 is never set, this means there are slight difference such as texture type issue you have found.

To enable this path edit 'gles_system.h' and **uncomment the '#define USE_GLES2 1' line ** and rebuild. This should build it in a 'pure' GLES2 mode

**Comment by dhwz** [comment]
ok thx I'll try that

**Comment by emileb** [comment]
OK this has never been done for other platforms. As a hack put this at the top of the code in gles_system.cpp

#define __ANDROID__


That might allow it to build, but there could be runtime issues as never tried.

**Comment by dhwz** [comment]
Ok thx I'll try tomorrow

**Comment by dhwz** [comment]
@emileb 
Ok that worked, color format is now correct without patching.

**Comment by dhwz** [comment]
@emileb 
Just some reply after I tried it also with Raze, there it breaks the emulation I only get stuttery 3fps after using the USE_GLES2 and ``` #define __ANDROID__```

**Comment by emileb** [comment]
> @emileb Just some reply after I tried it also with Raze, there it breaks the emulation I only get stuttery 3fps after using the USE_GLES2 and ` #define __ANDROID__` so I've reverted it back and replaced texformat = GL_RGBA; with texformat = GL_BGRA; in my code.

Thanks for this update, it is strange because the USE_GLES2 does not change much. The main difference is the stuff at the bottom of the gles_system.cpp file. You could try forcing these TRUE at the bottom of the file:

		gles.depthStencilAvailable = true;
		gles.npotAvailable = true;
		gles.useMappedBuffers = true;

Those are the only options I can think of which would cause such a performance issue.

**Comment by Cacodemon345** [comment]
I think the CPU itself is too weak to run GZDoom as it uses the ARM Cortex-A35 which seems to be weaker than the ARM Cortex-A53.

**Comment by coelckers** [comment]
Consider this hardware officially unsupported.
