### ISSUE TITLE
[Feature] "Additional Parameters" input in IWAD selection box on Windows

### ISSUE THREAD

**Issue by ghost** [ZDoom/gzdoom#1495]
### GZDoom version

GZDoom 4.6.1, but latest is the same according to changelog

### What Operating System are you using?

Other

### If Other OS, please describe

Windows

### Is your feature request related to a problem? Please describe.

Not having the "Additional Parameters" input in the IWAD selection box on Windows is a barrier to entry for multiplayer. The player has to (know to, and know how to) open the command line, know where they installed GZDoom (can be different between players), navigate to it and launch it with `gzdoom`.

### Describe the solution you'd like

The same "Additional Parameters" input box that there is in the Mac version of GZDoom.

**Comment by MasterO2** [comment]
@coelckers 

I definitely second this feature for GZdoom in Windows.  I'm more surprised no one's proposed it until now.

**Comment by Cacodemon345** [comment]
Actually he wanted that feature but couldn't add it because it would be obstructive for debugging.

**Comment by willnwhite** [comment]
Could the IWAD selection box (with "Additional Parameters" input) be a separate program that invokes `gzdoom [additional parameters]`?
