### ISSUE TITLE
[Feature] Make SSAO conditional for brightly lit areas only

### ISSUE THREAD

**Issue by markanini** [ZDoom/gzdoom#1540]
### GZDoom version

GZDoom v4.7.1

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 11

### Is your feature request related to a problem? Please describe.

Appearance of SSAO in darkly lit areas of maps.

### Describe the solution you'd like

In brightly lit areas of maps SSAO looks very good. 

In darkly lit areas it looks "not good", kind of murky.

That's why I think a menu option for making SSAO work conditionally based on brightness would bring the best appearance for this postprocessing shader

### Add any other context or screenshots about the feature request here.

![Screenshot_Doom_20220201_222330](https://user-images.githubusercontent.com/15148553/152054306-5fbb9ee7-6e8b-4f70-a167-99cdd6fd0f78.png)
![Screenshot_Doom_20220201_222349](https://user-images.githubusercontent.com/15148553/152054310-cc5ea1de-effd-4734-ab7e-04428fbc67db.png)
![Screenshot_Doom_20220201_221905](https://user-images.githubusercontent.com/15148553/152054317-d9800029-d1c1-43c9-bbda-5fadb05ce4fa.png)
![Screenshot_Doom_20220201_221857](https://user-images.githubusercontent.com/15148553/152054322-ab515188-d12e-44b8-a189-7424ed284a5e.png)

**Comment by mc776** [comment]
Last screenshot looks fine to me tbh... are dark places not dark and murky? (I can understand intellectually that the darkening might make dark areas *too* dark but I sincerely think the bottom screenshot looks decent...)

Where would the cutoff threshold be? Or is it a continuum of intensity porportional to the light?

**Comment by markanini** [comment]
> Last screenshot looks fine to me tbh... are dark places not dark and murky? (I can understand intellectually that the darkening might make dark areas _too_ dark but I sincerely think the bottom screenshot looks decent...)

Does it look the same when opening min an external image viewer? On my system the browser brightens dark areas unlike in game.

> Where would the cutoff threshold be? Or is it a continuum of intensity porportional to the light?

I don't know. Experimentation might be required, at the very least I'll be willing to test.

**Comment by Calinou** [comment]
In real life, ambient occlusion only applies to indirect lighting. If you want to emulate this in an engine that does not distinguish between direct and indirect lighting, the best way to do this is to only apply SSAO in dark areas, not light areas.
