### ISSUE TITLE
[BUG] Segmentation Fault during launch.

### ISSUE THREAD

**Issue by Mesmer55** [ZDoom/gzdoom#1552]
### GZDoom version

GZDoom g4.7.1-m - SDL version

### Which game are you running with GZDoom?

Doom

### What Operating System are you using?

Linux x86_64

### If Other OS, please describe

EndeavorOS/Arch

### Relevant hardware info

AMD Ryzen 3 3250U with Radeon Graphics, AMD GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Segmentation Fault error when trying to launch the game. Happens right after selecting an .IWAD. 

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Open the Linux terminal and type in the command to launch GZDoom (gzdoom).
2. Select the .IWAD file you want to launch GZDoom with.

### Your configuration

```ini
No changes made to the default config, aside from the .IWAD folder.
https://gist.github.com/Mesmer55/3f10d8e6b4ae7d8b5a38ee4f1a9df68e
```

### Provide a Log

```$ gzdoom
GZDoom g4.7.1-m - 2021-10-20 08:18:37 +0200 - SDL version
Compiled on Feb 17 2022

OS: EndeavourOS, Linux 5.16.9-arch1-1 on x86_64
M_LoadDefaults: Load system defaults.
W_Init: Init WADfiles.
[...]

*** Fatal Error ***
!!! Failed to exec debug process
Segmentation fault (core dumped)
```
https://gist.github.com/Mesmer55/bdc3f7f63698e43b17d8a2b75907941a

**Comment by coelckers** [comment]
Without a stack trace we cannot do anything here. It seems to be something system specific or more people would have reported it.

**Comment by coelckers** [comment]
Nothing here to work on.

**Comment by Contmotore** [comment]
Think I have the exact same issue.

### GZDoom version
GZDoom g4.9.0-m  - SDL version
 
### Which game are you running with GZDoom?
Doom

### What Operating System are you using?
Linux x86_64

### If Other OS, please describe
Arch Linux

### Relevant hardware info
AMD Ryzen 7 4700U with Radeon Graphics

### Provide a Log
```
GZDoom g4.9.0-m - 2022-11-05 14:00:59 +0100 - SDL version
Compiled on Nov  8 2022

OS: Arch Linux, Linux 6.0.7-zen1-1-zen on x86_64
GZDoom version g4.9.0-m


*** Fatal Error ***
!!! Failed to exec debug process
Segmentation fault (core dumped)
```

**Comment by mjr4077au** [comment]
> Think I have the exact same issue.
> 
> ### GZDoom version
> GZDoom g4.9.0-m - SDL version
> 
> ### Which game are you running with GZDoom?
> Doom
> 
> ### What Operating System are you using?
> Linux x86_64
> 
> ### If Other OS, please describe
> Arch Linux
> 
> ### Relevant hardware info
> AMD Ryzen 7 4700U with Radeon Graphics
> 
> ### Provide a Log
> ```
> GZDoom g4.9.0-m - 2022-11-05 14:00:59 +0100 - SDL version
> Compiled on Nov  8 2022
> 
> OS: Arch Linux, Linux 6.0.7-zen1-1-zen on x86_64
> GZDoom version g4.9.0-m
> 
> 
> *** Fatal Error ***
> !!! Failed to exec debug process
> Segmentation fault (core dumped)
> ```

Please open a new report for this.
