### ISSUE TITLE
[BUG] Linux git build errors: ‘[...]Pointer’ causes a section type conflict with ‘_[..]_HookPtr’

### ISSUE THREAD

**Issue by jeremywh7** [ZDoom/gzdoom#1569]
### GZDoom version

latest Git as of 10 Mar 2022 (same error with 4.7.1 release)

### What Operating System are you using?

Linux x86_64

### If Other OS, please describe

Arch Linux, GCC 11.2.0

### Relevant hardware info

Ryzen 3700X, 32GB DDR4-3600, B550 chipset, RTX2070 Super

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Build failure in Arch Linux using AUR 'gzdoom-git' - I've also reported this via the AUR package page.  I get the same error building the 4.7.1 release from AUR 'gzdoom'.

### Steps to reproduce the behaviour.

Explain how to reproduce
1.  Build from AUR 
2.  Let it install dependencies
3.  Build fails

### Your configuration

```ini
Build failure
```

### Provide a Log

```
./src/common/objects/autosegs.cpp:72:1: error: ‘ActionFunctonsDummyPointer’ causes a section type conflict with ‘_PlayerInfo_GetDisplayColor_HookPtr’
./src/d_netinfo.cpp:219:1: note: ‘_PlayerInfo_GetDisplayColor_HookPtr’ was declared here
./src/common/objects/autosegs.cpp:74:1: error: ‘ClassFieldsDummyPointer’ causes a section type conflict with ‘VMField_DBot_dest_HookPtr’
./src/playsim/bots/b_bot.cpp:66:1: note: ‘VMField_DBot_dest_HookPtr’ was declared here
```

**Comment by jhonny-oliveira** [comment]
I get the same error in Ubuntu Jammy. Please review the build log for further details: [GZDoom_failed_build_on_Ubuntu_Jammy.txt](https://github.com/coelckers/gzdoom/files/8500679/GZDoom_failed_build_on_Ubuntu_Jammy.txt).

Thank you!

**Comment by jhonny-oliveira** [comment]
I was able to overcome this issue by adding the following line to the debian/rules

export CXX=g++-12

After doing so, I got the error below at the very end of the build

lto1: fatal error: bytecode stream in file ‘CMakeFiles/zdoom.dir/common/platform/posix/sdl/crashcatcher.c.o’ generated with LTO version 11.3 instead of the expected 12.0

Then, I also added the following line and it worked

export DEB_CXXFLAGS_MAINT_APPEND=-fno-lto

Not sure how good/bad this workaround is, but the build was successful and the game is playable.

PS: I also had to apply b132d2c3fe7f9074e1c08dbab77fc1270e8736fb.

**Comment by alexey-lysiuk** [comment]
We do not support link-time optimization (LTO). Its options should not be added to C++ compiler and linker command lines. If your build environment does so, it's a problem of your build environment. If you desperately want to use LTO despite being unsupported, please do not ask our assistance with this.

**Comment by jeremywh7** [comment]
Ah, I had long forgotten that I added -flto to my makepkg.conf CFLAGS; thanks!

**Comment by jhonny-oliveira** [comment]
> If you desperately want to use LTO despite being unsupported, please do not ask our assistance with this.

I did not add it, debhelper does it on its own (defaults). I was also not aware you did not support it.

Then, I guess my solution is good. Or even better, since now I'm not doing anything unsupported in terms of LTO.

Thank you!
