### ISSUE TITLE
[BUG] Doesn't open on MacOS if I have no Wi-Fi.

### ISSUE THREAD

**Issue by WindowToaster** [ZDoom/gzdoom#1571]
### GZDoom version

GZDoom 4.7.1

### What Operating System are you using?

Mac OS

### Relevant hardware info

MacBook Pro 13-inch, Intel Core i7, Intel Iris Plus (Graphics)

### Have you checked that no other similar issue already exists?

- [x] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

GZDoom does not open if I have my Wi-Fi off, or if I have a bad connection. The icon just bounces until I press "Force Quit" or turn the Wi-Fi back on. If I have a good connection, it opens instantly.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Turn off Wi-Fi on your computer
2. Open GZDoom

**Comment by alexey-lysiuk** [comment]
Run Activity Monitor, select GZDoom process when it doesn't start, do [Sample Process](https://support.apple.com/guide/activity-monitor/run-system-diagnostics-actmntr2225/mac), and post its output.

**Comment by WindowToaster** [comment]
[Sample of GZDoom.txt](https://github.com/coelckers/gzdoom/files/8312061/Sample.of.GZDoom.txt)
Edit: I realized that it does open, but takes about two minutes to open the launcher. Then I get a spinning wheel which means my computer could freeze. Then after I select my IWAD, it takes another two minutes while it does the whole thing again.

Since I am not playing multiplayer, the only thing I can think of that uses the Wi-Fi is GZStats, which is specifically reported to avoid taking up extra time by only attempting to notify the server once.

**Comment by WindowToaster** [comment]
Also I forgot to mention I'm on MacOS Catalina 10.15.5.

**Comment by alexey-lysiuk** [comment]
It waits for something inside `TTC.framework` during application initialization. As this thing is responsible for infamous privacy popup windows, I would look for GZDoom permissions in _System Preferences ➡️ Security & Privacy ➡️ Privacy_ tab.
GZDoom stats reporting is asynchronous, so it cannot block loading for a noticeable amount of time. Moreover, it's not present in 4.7.1.

**Comment by WindowToaster** [comment]
I have enabled GZDoom in all the lists under the Privacy tab, but the issue still persists.

**Comment by madame-rachelle** [comment]
Does it still happen if you use a devbuild? https://devbuilds.drdteam.org/gzdoom-mac/

Please run it first with Wi-Fi and override the security popup. After that is done then switch off the Wi-Fi and see if it continues to run.

I somewhat suspect this may have something to do with the bundle signing, I don't even remember whether or not the bundles get notarized, but if not then I'm thinking it might be trying to verify the signature.

**Comment by madame-rachelle** [comment]
Closing due to lack of feedback.
