### ISSUE TITLE
[BUG] Git crashes on Linux

### ISSUE THREAD

**Issue by telanus** [ZDoom/gzdoom#1596]
### GZDoom version

https://github.com/coelckers/gzdoom/commit/265122bb978007f3ccefb27d71ac432d352650bb

### What Operating System are you using?

Linux x86_64

### If Other OS, please describe

Kubuntu 20.04

### Relevant hardware info

Intel i3 GT630

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Updated to the latest git, and after compiling and installing it, when run with gzdoom, it'll come up saying it can't find gzdoom.pk3, then it crashes with 

`*** Fatal Error ***
!!! Failed to exec debug process
Segmentation fault (core dumped)
`

running it from Lutris (a Linux Frontend) I got the following GDB code: https://gist.github.com/telanus/0ad3ccc3636a8dee4599f355c9767683

### Steps to reproduce the behaviour.

Explain how to reproduce
1.  Update to https://github.com/coelckers/gzdoom/commit/265122bb978007f3ccefb27d71ac432d352650bb
2. Compile && install (under linux)
3. run gzdoom. And it'll crash

### Your configuration

```ini
Not used, crashes before it even try to load the ini file
```

### Provide a Log

https://gist.github.com/telanus/0ad3ccc3636a8dee4599f355c9767683

**Comment by madame-rachelle** [comment]
Is this still a problem now?

**Comment by telanus** [comment]
seems it was fixed :D
