### ISSUE TITLE
[BUG] Mouse not captured on Linux

### ISSUE THREAD

**Issue by KingNullpointer** [ZDoom/gzdoom#1600]
### GZDoom version

GZDoom g4.7.1 - 2021-10-20 08:18:37 +0200 - SDL version

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Linux x86_64

### If Other OS, please describe

Linux Mint 20.3,  Linux 5.4.0-109-generic

### Relevant hardware info

AMD Ryzen 7 3700X CPU, AMD Radeon RX 5700 XT GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When playing, the window does not capture the mouse properly. It is possible to move the mouse out of the fullscreen window, it will even keep the rabbit's-head cursor for a second. It happens in both gameplay & menus.

video: https://youtu.be/X9W76i3gdv0 

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Run game
2. Move mouse outside of window
3. Click to defocus the window

### Your configuration

```ini
No changes from install/settings autogenerated
```

### Provide a Log

GZDoom g4.7.1 - 2021-10-20 08:18:37 +0200 - SDL version
Compiled on Oct 22 2021

OS: Linux Mint 20.3, Linux 5.4.0-109-generic on x86_64
M_LoadDefaults: Load system defaults.
W_Init: Init WADfiles.
 adding /opt/gzdoom/gzdoom.pk3, 666 lumps
 adding /opt/gzdoom/game_support.pk3, 2514 lumps
 adding /home/kingnullpointer/.config/gzdoom/DOOM2.WAD, 2919 lumps
 adding /opt/gzdoom/game_widescreen_gfx.pk3, 216 lumps
I_Init: Setting up machine state.
CPU Vendor ID: AuthenticAMD
  Name: AMD Ryzen 7 3700X 8-Core Processor 
  Family 23 (23), Model 113, Stepping 0
  Features: SSE2 SSE3 SSSE3 SSE4.1 SSE4.2 AVX AVX2 F16C FMA3 BMI1 BMI2 HyperThreading
V_Init: allocate screen.
S_Init: Setting up sound.
I_InitSound: Initializing OpenAL
  Opened device Scarlett Solo USB Analog Stereo
  EFX enabled
ST_Init: Init startup screen.
Checking cmd-line parameters...
S_InitData: Load sound definitions.
G_ParseMapInfo: Load map definitions.
Texman.Init: Init texture manager.
ParseTeamInfo: Load team definitions.
LoadActors: Load actor definitions.
script parsing took 144.64 ms
R_Init: Init Doom refresh subsystem.
DecalLibrary: Load decals.
M_Init: Init menus.
P_Init: Init Playloop state.
ParseSBarInfo: Loading custom status bar definition.
D_CheckNetGame: Checking network game status.
player 1 of 1 (1 nodes)
Using video driver x11
GL_VENDOR: AMD
GL_RENDERER: AMD Radeon RX 5700 XT (navi10, LLVM 14.0.1, DRM 3.35, 5.4.0-109-generic)
GL_VERSION: 4.6 (Core Profile) Mesa 22.0.3 - kisak-mesa PPA (Core profile)
GL_SHADING_LANGUAGE_VERSION: 4.60

Max. texture size: 16384
Max. texture units: 32
Max. varying: 128
Max. combined shader storage blocks: 80
Max. vertex shader storage blocks: 16
Resolution: 2560 x 1440
fluidsynth: warning: SDL2 not initialized, SDL2 audio driver won't be usable

**Comment by bobbyboy5069** [comment]
Does this happen in other fullscreen games?
Does this happen during actual gameplay? Moving the mouse outside of the menu screen should be possible.

**Comment by madame-rachelle** [comment]
Closing due to lack of feedback.
