### ISSUE TITLE
[Feature] [Bug] Sector light mode: Build: Sector aquires light by linedef, not by sector & Linedef light issues.

### ISSUE THREAD

**Issue by DDaggers** [ZDoom/gzdoom#1623]
### GZDoom version

GZDoom 4.7.1

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 10

### Relevant hardware info

-

### Is your feature request related to a problem? Please describe.

Sector Light mode: Build
Renderer;  Hardware Open GL/OpenGL ES
Map Format: UDMF
Possible relevant information: Used Ultimate Doom Builder for Wad file.

Issue: 
_When building my maps using the build mode, I noticed that some places have shadows or darker sector lights flickering. Mostly caused by Octagonal or other nonstandard shape sectors.
Possible reason: 
During my build, I managed to fix most of the issues by aligning linedefs to grid properly, as long  as the shape was rectangular or consisted of multiple rectangles in different angles.
Line curve requires proper alignment to fix the glitching sector into dark or black issue, but is possible to work around. 
Octagonal shapes however, glitch out when you add another rectangle inside the octagon or the other way around. The same happens in line curved sectors._ 
**As a result, i theorize the reason is:** Linedefs try to influence sector lighting by copying previous sector. But due to sector being a different type or not having any straight angles, the linedef can not copy the sectors light settings. As a result, it instead copys the default darkness setting of previous sector. But since it can not find the sector, it copys the darkness and sector settings of the void, like the linedef or sector was missing the texture.

**Possible related bug:**

Sector light mode: Any, including Standard.
Map Format UDMF
Builder used: UDB

Issue: Lower, middle or Upper linedef brightness values do not get read in the wad file when launching the file. As a result, when using seperate lower and upper linedef brightness settings, the game just loads in default sector brightness, no matter the sector light mode or renderer settings.

### Describe the solution you'd like

Unfortunately i do not know if it is a bug or my own lack of knowledge, so at first I would like an answer.

### Describe alternatives you've considered

none. Most of the alternative was adjusting sector shape so that atleast one linedef aligns with blockmap grid. This seemed to fix the random black sectors issue, but it did not fix the issue with linedef brightness levels not working properly on any map mode.

### Add any other context or screenshots about the feature request here.

The screenshots are from a map I'm building
[Uploading Screenshots.zip…]()

**Comment by coelckers** [comment]
You got to take it as it is. It was a freebie from developing Raze but there won't be any improvements on this light mode - even in Raze we ultimately decided to do something better because it sucks so much.
