### ISSUE TITLE
[Feature] Add vpx to the installation command on the wiki

### ISSUE THREAD

**Issue by ancientstraits** [ZDoom/gzdoom#1649]
### What Operating System are you using?

Linux x86_64

### Is your feature request related to a problem? Please describe.

The [GZDoom wiki page for compiling on linux](https://zdoom.org/wiki/Compile_GZDoom_on_Linux) does not tell the reader to download the `libvpx` development library. However, `libvpx` is a dependency of GZDoom.

### Describe the solution you'd like

For each Linux distro, add the corresponding `libvpx` package to the command to install dependencies. For instance, on Ubuntu, add `libvpx6-dev` to the command.

**Comment by madame-rachelle** [comment]
This is the wrong place to suggest it - the devs rarely touch the wiki. You might have better luck here:
https://forum.zdoom.org/viewtopic.php?f=4&t=20573
