### ISSUE TITLE
[Feature] Skewed wall textures

### ISSUE THREAD

**Issue by UnizoneDev** [ZDoom/gzdoom#1650]
### GZDoom version

GZDoom 4.8.0

### Which game are you running with GZDoom?

Other

### What Operating System are you using?

Windows 10

### Is your feature request related to a problem? Please describe.

This feature is for dealing with sloped walls, mainly the ones with textures that contain trims, wallpaper, and other kinds of textures with horizontal lines.

### Describe the solution you'd like

I propose that we could have the option for setting the skew angle directly, as well as adding linedef flags to align the upper, middle, and lower textures to the floor or ceiling, whether on the front or back side. Although these features probably are a pain to implement in the classic software renderer.

**Comment by UnizoneDev** [comment]
> I'm pretty sure vertical skewing would be doable in software, since walls are rendered column by column.

That's a fair enough response, the reason why I did this request was because of this thread right below:
https://forum.zdoom.org/viewtopic.php?f=15&t=66031

**Comment by UnizoneDev** [comment]
I know I shouldn't be impatient for this to get added, but I await for another answer, whether from Graf or someone else.

**Comment by MajorCooke** [comment]
You're gonna be waiting a lot longer than just a few days. Graf is a busy person.

**Comment by Gaerzi** [comment]
This has been suggested since 2004, so impatience will only result in a locked thread...

**Comment by madame-rachelle** [comment]
I don't see any reason why a hwrenderer-exclusive feature for this, and also for rotating textures, couldn't be done. All that would need to be done for that is to modify the UV maps for the wall triangle points. Of course - depending on the code we're talking about here, THAT may also be easier said than done, too ...

However, this will very likely never happen in the software renderer.

**Comment by UnizoneDev** [comment]
> I don't see any reason why a hwrenderer-exclusive feature for this, and also for rotating textures, couldn't be done. All that would need to be done for that is to modify the UV maps for the wall triangle points. Of course - depending on the code we're talking about here, THAT may also be easier said than done, too ...
> 
> However, this will very likely never happen in the software renderer.

I understand that. But as a reminder, there is one link to a thread by RocketstarRaccoon I would like to show all of you, just to get other ideas that is: https://forum.zdoom.org/viewtopic.php?f=15&t=74586

**Comment by yum13241** [comment]
> I don't see any reason why a hwrenderer-exclusive feature for this, and also for rotating textures, couldn't be done. All that would need to be done for that is to modify the UV maps for the wall triangle points. Of course - depending on the code we're talking about here, THAT may also be easier said than done, too ...
> 
> However, this will very likely never happen in the software renderer.

And it should be VERY clear that GZDoom just doesn't care for the S/W renderer anymore (it's on life support). When was the last time the Carmack renderer had new features added to it? 10 years ago? The TC S/W renderer is a bit of a weird thing. Who'd want true color and y-shearing? The only reason I'd use the Carmack renderer is for that software aesthetic.

**Comment by coelckers** [comment]
This feature got added to the hardware renderer recently. 
If anyone wants to know why it took so long, the answer is that previously it was deemed necessary to add it to the software renderer as well, unfortunately there it is a bit more involved and I never could figure it out. Since nobody with the ability to add it seems to care the software renderer will have to make do without it,
