### ISSUE TITLE
[Feature] Support for HEXDD.WAD

### ISSUE THREAD

**Issue by axet** [ZDoom/gzdoom#1676]
### GZDoom version

4.7.1

### Which game are you running with GZDoom?

Hexen

### What Operating System are you using?

Linux x86_64

### Is your feature request related to a problem? Please describe.

Hello!

I'm tyring to run HEXDD.WAD using gzdoom and it does not see the game.

I tried the following:

gzdoom -iwad "/media/axet/128GB//hexen-dk/drive_c/GOG Games/HeXenDK/HEXDD.WAD"

gzdoom -iwad "/media/axet/128GB//hexen-dk/drive_c/GOG Games/HeXenDK/HEXEN.WAD" -iwad "/media/axet/128GB//hexen-dk/drive_c/GOG Games/HeXenDK/HEXDD.WAD"

gzdoom -iwad "/media/axet/128GB//hexen-dk/drive_c/GOG Games/HeXenDK/HEXEN.WAD" -wad "/media/axet/128GB//hexen-dk/drive_c/GOG Games/HeXenDK/HEXDD.WAD"

None of above is working. GZDoom requires hexen.wad to start the game, using HEXDD.WAD as iwad does not help. Adding HEXDD.WAD as -wad also fails.

Seems like gzdoom does not support Hexen Darkknigts addon (1996)

https://www.gog.com/ru/game/hexen_deathkings_of_the_dark_citadel

**Comment by Blue-Shadow** [comment]
While I can't help you figure out how to run it (I don't have it), the add-on has been [supported](https://zdoom.org/wiki/IWAD#Commercial_games) since the days of ZDoom.

**Comment by axet** [comment]
Ok. I figurate it out. To run a game you have to put all wads into current PWD dirrectory and start game normally. Then game asks if you want hexdd. Type 3 and you go... But if you trying to run hexdd.wad using iwad argument it fails.

I have no issues running other games using -iwad: doom2, heretic, hexen1. But hexen dk fails.

doom2:

```
axet@axet-laptop:/media/axet/128GB$ gzdoom  -iwad "DOOM2/steamapps/common/Doom 2/base/DOOM2.WAD"
GZDoom g4.7.1 - 2021-10-20 08:18:37 +0200 - SDL version
Compiled on Jul 12 2022

OS: Debian GNU/Linux bookworm/sid, Linux 5.18.0-2-amd64 on x86_64
M_LoadDefaults: Load system defaults.
W_Init: Init WADfiles.
 adding /media/axet/128GB/GZDoom/gzdoom.pk3, 666 lumps
 adding /media/axet/128GB/GZDoom/game_support.pk3, 2514 lumps
 adding ./DOOM2/steamapps/common/Doom 2/base/DOOM2.WAD, 2919 lumps
 adding /media/axet/128GB/GZDoom/game_widescreen_gfx.pk3, 216 lumps
I_Init: Setting up machine state.
```

gzdoom -iwad "HexenDK/drive_c/GOG Games/HeXenDK/HEXDD.WAD"

```
GZDoom g4.7.1 - 2021-10-20 08:18:37 +0200 - SDL version
Compiled on Jul 12 2022

OS: Debian GNU/Linux bookworm/sid, Linux 5.18.0-2-amd64 on x86_64
M_LoadDefaults: Load system defaults.
axet@axet-laptop:/media/axet/128GB$ gzdoom -iwad "HexenDK/drive_c/GOG Games/HeXenDK/HEXDD.WAD"
GZDoom g4.7.1 - 2021-10-20 08:18:37 +0200 - SDL version
Compiled on Jul 12 2022

OS: Debian GNU/Linux bookworm/sid, Linux 5.18.0-2-amd64 on x86_64
M_LoadDefaults: Load system defaults.
```

showing "cannot find a game IWAD..." dialog.

gzdoom -iwad "HexenDK/drive_c/GOG Games/HeXenDK/HEXEN.WAD"

```
GZDoom g4.7.1 - 2021-10-20 08:18:37 +0200 - SDL version
Compiled on Jul 12 2022

OS: Debian GNU/Linux bookworm/sid, Linux 5.18.0-2-amd64 on x86_64
M_LoadDefaults: Load system defaults.
W_Init: Init WADfiles.
 adding /media/axet/128GB/GZDoom/gzdoom.pk3, 666 lumps
 adding /media/axet/128GB/GZDoom/game_support.pk3, 2514 lumps
 adding ./HexenDK/drive_c/GOG Games/HeXenDK/HEXEN.WAD, 4270 lumps
 adding /media/axet/128GB/GZDoom/game_widescreen_gfx.pk3, 216 lumps
I_Init: Setting up machine state.
```

gzdoom -iwad "HexenDK/drive_c/GOG Games/HeXenDK/HEXEN.WAD" -iwad "HexenDK/drive_c/GOG Games/HeXenDK/HEXDD.WAD" 

missing "hexdd.wad", game hexen starts but not hexen darkknights:

```
GZDoom g4.7.1 - 2021-10-20 08:18:37 +0200 - SDL version
Compiled on Jul 12 2022

OS: Debian GNU/Linux bookworm/sid, Linux 5.18.0-2-amd64 on x86_64
M_LoadDefaults: Load system defaults.
W_Init: Init WADfiles.
 adding /media/axet/128GB/GZDoom/gzdoom.pk3, 666 lumps
 adding /media/axet/128GB/GZDoom/game_support.pk3, 2514 lumps
 adding ./HexenDK/drive_c/GOG Games/HeXenDK/HEXEN.WAD, 4270 lumps
 adding /media/axet/128GB/GZDoom/game_widescreen_gfx.pk3, 216 lumps
I_Init: Setting up machine state.
```

gzdoom -iwad "HexenDK/drive_c/GOG Games/HeXenDK/HEXEN.WAD" -wad "HexenDK/drive_c/GOG Games/HeXenDK/HEXDD.WAD" 

same for -wad, does not see hexdd.wad:

```
ZDoom g4.7.1 - 2021-10-20 08:18:37 +0200 - SDL version
Compiled on Jul 12 2022

OS: Debian GNU/Linux bookworm/sid, Linux 5.18.0-2-amd64 on x86_64
M_LoadDefaults: Load system defaults.
W_Init: Init WADfiles.
 adding /media/axet/128GB/GZDoom/gzdoom.pk3, 666 lumps
 adding /media/axet/128GB/GZDoom/game_support.pk3, 2514 lumps
 adding ./HexenDK/drive_c/GOG Games/HeXenDK/HEXEN.WAD, 4270 lumps
 adding /media/axet/128GB/GZDoom/game_widescreen_gfx.pk3, 216 lumps
I_Init: Setting up machine state.
```

**Comment by Dasperal** [comment]
You can run gzdoom like this:
```gzdoom -iwad "HexenDK/drive_c/GOG Games/HeXenDK/HEXEN.WAD" -file "HexenDK/drive_c/GOG Games/HeXenDK/HEXDD.WAD"```
to play Deathkings. But in this case, you won't get widescreen graphics for Deathkings as the game will be recognized as Hexen, not Hexen Deathkings.

The only way I know to play Deathkings properly is to add a directory with the `HEXEN.WAD` to the `[IWADSearch.Directories]` section of the config file and then run gzdoom like this:
```gzdoom -iwad "HexenDK/drive_c/GOG Games/HeXenDK/HEXDD.WAD"```

This is due to the `HEXDD.WAD` is marked as an iwad but practically it is a pwad, so it requires `HEXEN.WAD` to run.

**Comment by madame-rachelle** [comment]
This is already in.

**Comment by coelckers** [comment]
Not really. What fails is loading it explicitly with -iwad.The dialog works.

**Comment by axet** [comment]
My mistake. I suppose to use -iwad and -file arguments (not -wad). It works! Thanks!
