### ISSUE TITLE
[BUG] gzdoom trying to run gxmessage when not exists

### ISSUE THREAD

**Issue by axet** [ZDoom/gzdoom#1684]
### GZDoom version

4.7.1

### Which game are you running with GZDoom?

Other

### What Operating System are you using?

Linux x86_64

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

when crashing gzdoom trying to run gxmessage even when it is not installed

### Steps to reproduce the behaviour.

crash the game
it will try to run gxmessage

**Comment by coelckers** [comment]
This should serve as an example for "how not to report a bug".
I'm closing it because I have no idea what to do with it.

**Comment by axet** [comment]
When gzdoom crashes, it trying to execute gxmessage binary to show error message. This binary hardcoded into source code without any checks if binary exists as result gzdoom showing 'no such file or bla bla bla' about gxmessage.

**Comment by mjr4077au** [comment]
> When gzdoom crashes, it trying to execute gxmessage binary to show error message. This binary hardcoded into source code without any checks if binary exists as result gzdoom showing 'no such file or bla bla bla' about gxmessage.

I'll patch this tonight or tomorrow in Raze, we had a similar reported issue where `kxdialog` was presumably available because it was detected Raze was being ran in a KDE session when it wasn't exactly.

Once its in Raze, it'll come in via a backend sync. Since I work on Raze primarily, its easier for me to incorporate it there rather than setting up a new environment for GZDoom.

**Comment by axet** [comment]
Modern linux handle crashes very well using coredumpctl. If system is configured correctly all crash dumps written to the system folder and can be debugged at any time using 'coredumpctl gdb [pid]' command. Easy to use / debug even when source code or debug symbols are not installed (can be installed at any time then debugged saved crashed dump). I guess we need gxmessage onlyl if coredumpctl not enabled.

**Comment by mjr4077au** [comment]
@axet I've handled it this way for now in https://github.com/ZDoom/Raze/commit/70b6aa848f45bebde46b55045075ea4003be2df8. It'll come into GZDoom at some point.

Agreed that this code probably requires a thorough rework, some of the stuff in there is quite deprecated and you're right, with systemd being fairly well used, it should be tested for availability.
