### ISSUE TITLE
[BUG] Software renderer: Things render with the wrong sector's lighting

### ISSUE THREAD

**Issue by InsanityBringer** [ZDoom/gzdoom#1692]
### GZDoom version

GZDoom 4.8.2

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When playing with the software renderer (either original or truecolor), some objects will be rendered with the lighting traits (light level, color, fog, etc) from a sector possibly far away from where they actually are. 

I've found a reliable place to reproduce this is MAP02. By using noclip and notarget to sneak into the super shotgun room, with the 4 zombiemen at the entrance, the zombiemen will be lit by the strobing light in the half of the room where you get the super shotgun. 

These two screenshots show the problem:

This first one shows the zombiemen as you would expect, since they're far away from any of the lights, they should be dimmer like this
![Screenshot_Doom_20220803_104939](https://user-images.githubusercontent.com/1504999/182654588-29b901f4-c855-4e5d-9737-a4eee9d40bf2.png)

But when the strobe light on the other side of the wall behind the player here is on, the zombiemen will suddenly light up.
![Screenshot_Doom_20220803_104945](https://user-images.githubusercontent.com/1504999/182654564-f896864f-3e35-46ff-9c51-16a9fcddb7f6.png)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Enable the software renderer
2. use noclip/notarget (to avoid waking up any of the monsters) to go to the super shotgun room in Doom 2 MAP02
3. Watch as the zombiemen at the silver computers are effected by the strobe light in another part of a room.

**Comment by InsanityBringer** [comment]
I went spelunking in the source code to see if I can fix this issue, I tracked down the problem to commit 344c634, the parent commit does not seem to exhibit this bug, or it's more elusive. I'm trying to figure out what occurred in that commit to break it.

**Comment by coelckers** [comment]
I reverted the software renderer to the old state in 500e2d6c5ad592b3e7bceea14617591410bc93bc
