### ISSUE TITLE
[BUG] ternary _much_ slower than if/else

### ISSUE THREAD

**Issue by RicardoLuis0** [ZDoom/gzdoom#1696]
### GZDoom version

4.8.2

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 10

### Relevant hardware info

CPU i5 7600K OC'd to 4.49 GHz

### Have you checked that no other similar issue already exists?

- [x] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When the branch uses a ternary, it runs ~100x slower than when it uses a simple if/else.

## With ternary
```
marker.A_SpawnParticle(hit_monster?"#FF0000":"#00FF00",SPF_FULLBRIGHT,2,clamp(dist/100,2.5,75));
```
![ternary](https://user-images.githubusercontent.com/15188209/183300297-88ffecd0-6390-4efb-b24e-ff28fefc2b2b.png)
*last 10 tics 231 ms*

## Without ternary (if/else)
```
if(hit_monster){
    marker.A_SpawnParticle("#FF0000",SPF_FULLBRIGHT,2,clamp(dist/100,2.5,75));
} else {
    marker.A_SpawnParticle("#00FF00",SPF_FULLBRIGHT,2,clamp(dist/100,2.5,75));
}
```
![if_else](https://user-images.githubusercontent.com/15188209/183300345-310ccba4-e35a-4d0f-9bb1-129b910efd88.png)
*last 10 tics 2.5 ms*

### Steps to reproduce the behaviour.
* Get [ternary_bug.zip](https://github.com/ZDoom/gzdoom/files/9277125/ternary_bug.zip);
* Set `sv_fill_trace` to `true` to enable drawing the dot grid;
* Comment in/out the lines at `L97`~`L104` in `ZScript.zs` to switch between ternary and if/else.

**Comment by coelckers** [comment]
You are running into a very tricky thing here.
The first parameter is a color. If you pass in a string literal it will be converted at compile time - but the compiler cannot do that for the ternary and will do the conversion at run time - which is a lot slower. 
You can avoid the full duplication by just assigning the color value to a variable up front and then only have one function call.
