### ISSUE TITLE
[Feature] Support Final/Master Levels in Steam Doom 2

### ISSUE THREAD

**Issue by vitalkanev** [ZDoom/gzdoom#1698]
### GZDoom version

4.7.1 and 4.8.2

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 10

### If Other OS, please describe

Windows 10 build 19044.1826

### Relevant hardware info

Doesn't generally matter, as it could happen on any system.

### Is your feature request related to a problem? Please describe.

Technically not a problem. Doom 2 on Steam (which includes both Unity Doom 2 and classic Doom 2) now includes WAD files for TNT/Plutonia and Master Levels since very recent update.

To reproduce, uninstall Final Doom/Master Levels, launch GZDoom via the EXE directly and see that some entries are missing.

### Describe the solution you'd like

Might be simple. Include the following folders in `steam_dirs` array from `I_GetSteamPath` function:
```
"doom 2/finaldoombase",
"doom 2/masterbase",
```

If user already has installed retired products, it could cause duplicates entries to appear. But I am not sure how it works.

### Describe alternatives you've considered

Don't have any alternatives considered.

### Add any other context or screenshots about the feature request here.

Related SteamDB links on that change:
- https://steamdb.info/patchnotes/9237723/#changed-files (includes new files in depot relating TNT/Plutonia/Master)
- https://steamdb.info/app/2300/history/?changeid=15607706 (new launch option related to TNT/Plutonia)

The original Master Levels/Final Doom Steam apps have also been retired by publisher.

**Comment by Yarn366** [comment]
I have just made pull request #1704, which adds detection for the new Final Doom WAD location.
