### ISSUE TITLE
[Feature] Update Steam IWAD Detection for New Final Doom Distribution

### ISSUE THREAD

**Issue by TheKins** [ZDoom/gzdoom#1699]
### GZDoom version

GZDoom 4.8.2

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 10

### Is your feature request related to a problem? Please describe.

The Steam distributions of the Doom games have updated to remove the DOS versions of Final Doom from sale and just include them all as part of Doom 2. Which is nice, because now it's free for all Steam Doom 2 owners, but it means a new line has to be added to i_steam.cpp for GZDoom to detect the new means of distribution.

### Describe the solution you'd like

Detect DOS Final Doom IWADs in the `Doom 2/finaldoombase` subfolder.

Master Levels are in `Doom 2/masterbase/master/wads` should you wish to do anything with them.

**Comment by Yarn366** [comment]
I have just made pull request #1704, which adds detection for the new Final Doom WAD location.
