### ISSUE TITLE
[BUG] Crash when the player is killed

### ISSUE THREAD

**Issue by OrdinaryMagician** [ZDoom/gzdoom#1705]
### GZDoom version

g4.9pre-183-g1b4357558

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Linux x86_64

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

If the player is killed by an enemy, the game will crash. This does not happen on suicide or death from environmental hazards. The crash happens consistently within the `ClientObituary()` function since the specified version.

**Comment by coelckers** [comment]
fixed in e27e3453f91a4780c5c85525b1878d64ae0730ed
