### ISSUE TITLE
[BUG] Shell command handling for folder names is not correct

### ISSUE THREAD

**Issue by ericonr** [ZDoom/gzdoom#1707]
### GZDoom version

master

### Please describe your specific OS version

Linux, but also valid for Mac

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

https://github.com/ZDoom/gzdoom/commit/259a8e0f7496ddd47866dcb5a7aff8075b09ea76 attempts to fix possible issues with directory names with spaces in them, but doesn't deal with the case where a name might contain quotes or semicolons and lead to command execution.

`posix_spawnp` + `waitpid` should be enough to get the same effect as using system, but in a safe manner, by passing a command array comprised of `{"xdg-open", folder.c_str(), NULL}`. It might also make sense, at least for `xdg-open`, to sanitize values which start with `-` or `--`, since it can't deal with those.

**Comment by madame-rachelle** [comment]
The documentation for posix_spawnp is needless to say, quite poor. Furthermore, I would like to avoid using waitpid(), there is really no need to freeze the game while the shell process is open and I really don't understand why everyone and their grandmother is obsessed with having it there. I would prefer to respect the user's preferences with how GZDoom behaves in the background. A simple hit-and-run call and returning to the main game loop is quite sufficient for this.

**Comment by ericonr** [comment]
Thanks for the implemented fix!

> Furthermore, I would like to avoid using waitpid(), there is really no need to freeze the game while the shell process is open

Per https://man7.org/linux/man-pages/man3/system.3.html : 

> system() returns after the command has been completed.

I don't think using `waitpid` would be a change of behavior... `system` *has* to wait for the process in order to not leave a zombie laying around (or you'd have to install a `SIGCHLD` handler).
