### ISSUE TITLE
[Bug] Obituary via LANGUAGE doesn't work

### ISSUE THREAD

**Issue by Blue-Shadow** [ZDoom/gzdoom#1711]
**Tested with:** 4.9pre-189-ga9cadd345 (a9cadd345)
**Test material:** https://www.dropbox.com/s/laomibp16zqz0j7/obit_bug_demo.pk3?dl=1

Assigning obituaries through LANGUAGE doesn't seem to work. The demo file has the following in a LANGUAGE lump:
```
[enu default]

Obituary_Zombieman = "%o was shot down by a green-haired former human.";
```
However, the Zombieman's own obituary is what is printed, still, not the one assigned to it through the lump.

**Comment by coelckers** [comment]
fixed in a2369b945c6d60aa837562c9ac01729f4920eebe
