### ISSUE TITLE
Heretic backgrounds not filling screen

### ISSUE THREAD

**Issue by Q3BFG10K** [ZDoom/gzdoom#1712]
GZDoom 4.8.2, Win10-64, Steam Heretic. 

Unsure if this is a bug or limitation of widescreen content.

Walk through the end level teleporter, the blue background fills the screen with level stats. But when the next level starts, the blue background is 4:3

[quick0.zip](https://github.com/ZDoom/gzdoom/files/9352582/quick0.zip)

**Comment by coelckers** [comment]
fixed in 1940527dba3832dfa26aa2d72b1d9564a6414c6f
