### ISSUE TITLE
[BUG] Peculiar crash in mod if fonts are missing

### ISSUE THREAD

**Issue by OrdinaryMagician** [ZDoom/gzdoom#1713]
### GZDoom version

g4.9pre-190-gee132372d

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Linux x86_64

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

If the fonts folder is missing in [Codename: Demolitionist](https://forum.zdoom.org/viewtopic.php?f=43&t=67687), the mod should normally cause a VM abort as soon as anything tried to load and use the missing fonts. However, if one launches with the `-warp` command, this instead causes a crash to desktop.

I personally still think this isn't worth reporting considering it's something that happened by mistake, but nevertheless, I'll do as asked.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Download the mod
2. Delete the fonts folder
3. Run GZDoom with it and the -warp command

### Provide a Log

[gzdoom-crash.log](https://github.com/ZDoom/gzdoom/files/9355057/gzdoom-crash.log)

**Comment by coelckers** [comment]
My guess is a problem with the JIT-generated unwind metadata. The stack trace looks fine until deep in the POSIX backtrace code something goes wrong.

**Comment by coelckers** [comment]
Works fine on Windows. I find it peculiar that it even manages to run some scripts after getting a fatal error in the compiler.
Since I cannot seem to trigger it, you got to help me out here.
Set a breakpoint on the first lines of DEFINE_ACTION_FUNCTION(FFont, BreakLines) and try to get a stack trace. If it does not work with JIT enabled try the same with JIT disabled.
I need to find out where the script call originates from

**Comment by OrdinaryMagician** [comment]
I haven't been able to get a usable trace of where the issue is coming from. With JIT disabled I just get a seemingly unending loop of the HUD being sent a message to print, breaklines being called with a null font, the vm aborts, the HUD is sent the abort message to print, breaklines is called... etc, etc.

It's too late into the night for me to be doing this, so I'll try to isolate things tomorrow.

**Comment by OrdinaryMagician** [comment]
It seems that disabling the ProcessNotify override in the mod's hud prevents the crash, and it gives a normal VM abort.

**Comment by OrdinaryMagician** [comment]
Ah, there we go, editing the `Printf` calls in `CVMAbortException::MaybePrintMessage()` to have `PRINT_NONOTIFY` fixes the crash.

**Comment by coelckers** [comment]
Thanks. Fixed in ef887403cf20ea5ddbd424aba56a3270535f001a
