### ISSUE TITLE
[BUG] Wads.ReadLump returns a zero-terminated string

### ISSUE THREAD

**Issue by mmaulwurff** [ZDoom/gzdoom#1715]
### GZDoom version

GZDoom 4.8.0

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Manjaro Linux, Version: 21.3.7 (Ruah), Linux 5.15.60-1-MANJARO

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

`Wads.ReadLump` returns a string that is zero-terminated. It doesn't cause issues until you concatenate such a string with any other string. The concatenated string will contains '\0', and `console.print` will show only the first part of it.

Having zero-terminated strings is inconsistent with typical ZScript strings, and I suppose such strings will be extremely unclear to people without programming background.

Attached: a runnable example
[readlump-zero-terminated.zip](https://github.com/ZDoom/gzdoom/files/9365001/readlump-zero-terminated.zip)

```
version 4.8

class rz_EventHandler : EventHandler
{
  override void PlayerEntered(PlayerEvent event)
  {
    int    lumpIndex = Wads.findLump("mylump");
    string lump      = Wads.readLump(lumpIndex);
    console.printf("lump: length: %d:", lump.length()); // 'A', '\0'.
    for (int i = 0; i < lump.length(); ++i)
      console.printf("lump: char %d: %d", i, lump.byteAt(i)); // 'A', '\0'.

    string fromLiteral = "B";
    console.printf("fromLiteral: length: %d", fromLiteral.length());

    string concatenated = lump .. fromLiteral;
    console.printf("concatenated: length: %d, printed: %s", concatenated.length(), concatenated);
  }
}
```

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load `readlump-zero-terminated.zip` with GZDoom.
2. Start any map.
3. Read the console log.
4. The last string prints "A" instead of "AB".

### Provide a Log

```
lump: length: 2:
lump: char 0: 65
lump: char 1: 0
fromLiteral: length: 1
concatenated: length: 3, printed: A
```

**Comment by coelckers** [comment]
fixed in 513d8cea8ddbd62cdd17e017403e07052a8ac021
This added space for the terminating \0 twice
