### ISSUE TITLE
[BUG] ArtiTeleport/Chaos Device and ArtiTeleportOther/Banishment Device ignore UsePlayerStartZ

### ISSUE THREAD

**Issue by RusselCS** [ZDoom/gzdoom#1720]
### GZDoom version

g4.9pre-204-gf27acfa6b

### Which game are you running with GZDoom?

Hexen

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

Windows 10 Pro

### Have you checked that no other similar issue already exists?

- [x] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When the Chaos Device, Banishment Device and any items inheriting from them are activated, the resulting teleportation ignores the player start's Z position, even if MAPINFO has the UsePlayerStartZ flag.

### Steps to reproduce the behaviour.

1. Run [this wad](https://cdn.discordapp.com/attachments/369619975876640768/1012228400057954415/ChaosBanishmentTest.wad) with Hexen. This wad replaces MAP01 with a simple two-floor structure with player starts on the upper floor and a Chaos Device and Banishment Device.
2. Start a new game to enter MAP01.
3. Pick up the Chaos Device and use it.
4. **Expected outcome:** you should return to a spawn on the upper level (brown brick color).
5. **Actual outcome:** you teleport to the lower level (gray brick color).

Same occurs with the Banishment Device when used on a target player.

**Comment by madame-rachelle** [comment]
fixed in commit 6741c11244
