### ISSUE TITLE
LEVEL_ enum constants are exported, but the Levels.flags that use them are not?

### ISSUE THREAD

**Issue by madame-rachelle** [ZDoom/gzdoom#1722]
When fixing [this bug here](https://github.com/ZDoom/gzdoom/issues/1720) I saw that the LEVEL_* constants that I needed were exported, but the Level->flags that they are used for is not.

Is there any particular reason for this? I ended up fixing this myself by just exporting the flag I needed, but I think it would be better to either export the flags* globals directly, or export all level flags (probably way less desirable), or both.

**Comment by coelckers** [comment]
Looks like an abandoned leftover that got scrapped when the flags were done as bits

**Comment by madame-rachelle** [comment]
Should we delete those enums zscript-side since these are taking up space (and potentially causing confusion) then, or do you want to leave them be?

**Comment by Blue-Shadow** [comment]
No. These [were exported](https://github.com/ZDoom/gzdoom/commit/a172513535486e870baf2d0328d11bbba32042f7#diff-ab6ab4b5ee142fe1e287989498f7d87fd907c4eac175f47e918b040a3a89d69f) alongside `LevelInfo` struct, as they're used with its flags fields.

**Comment by madame-rachelle** [comment]
Oh - that's where it ended up - didn't see this at first. Alright, well, that answers my question then.

**Comment by coelckers** [comment]
Shit. Someone screwed this up big time. That should have been done with bit flags, just like the main struct.

**Comment by OrdinaryMagician** [comment]
That might in fact be my fault. Should have thought about parity there, my bad. I can revise it when I have time, if no one else does it first.

**Comment by madame-rachelle** [comment]
It looks like the whole entire struct was just simply exposed. There is nothing on the ZScript side except the reference to the struct itself.

**Comment by OrdinaryMagician** [comment]
Yeah, that's basically all I did.

**Comment by coelckers** [comment]
This has been in the wild for too long, it cannot be undone anymore. :(

**Comment by OrdinaryMagician** [comment]
Were there a macro for what I need, I could have fixed it, I swear.
