### ISSUE TITLE
[BUG] missing anisotropic filtering when using GLES rendering API 

### ISSUE THREAD

**Issue by liPillON** [ZDoom/gzdoom#1723]
### GZDoom version

4.8.2

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

Windows 10 x64 Enteprise LTSC 

### Relevant hardware info

Intel Core (i7-8565U) +Intel (UHD Graphics 620) +Nvidia (GeForce MX110)

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When using the "OpenGL ES" rendering API, the "Anisotropic Filter" option has no effect - regardless of the "Texture Filtering mode" and of the "Notebook Switchable GPU" settings.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. download gzdoom latest release and unzip it to a new folder in a write-enabled location (this is to start from a fresh config)
2. place one of the supported IWAD in the same folder
3. run gzdoom and change the rendering API to "OpenGL ES", then close gzdoom
4. run gzdoom again and change the "Texture Filtering mode" option to any value (except NONE)
5. start a new game 
6. set the "Anisotropic Filter" value to 2x, 4x, 8x, 16x

The rendered image has no anisotropic filter applied to any surface.
This is always happening, regardless of the enabled GPU in my system.

I've looked up for the "anisotropic" keyword in both the "issue" section here on GitHub and the "Bugs", "OpenGLES Renderer Bugs", "Closed Bugs" sections over @zdoom.org forums.

### Your configuration

```ini
The issue is present also when letting gzdoom create a new .ini from scratch.

Details about both GPUs (level of GL support, driver version):

Integrated GPU:
GL_VENDOR: Intel
GL_RENDERER: Intel(R) UHD Graphics 620
GL_VERSION: 4.6.0 - Build 30.0.100.9805
GL_SHADING_LANGUAGE_VERSION: 4.60 - Build 30.0.100.9805
GL_EXTENSIONS:
GL_MAX_TEXTURE_SIZE: 16384

GL_VENDOR: NVIDIA Corporation
GL_RENDERER: GeForce MX110/PCIe/SSE2
GL_VERSION: 4.6.0 NVIDIA 457.63
GL_SHADING_LANGUAGE_VERSION: 4.60 NVIDIA
GL_EXTENSIONS:
GL_MAX_TEXTURE_SIZE: 16384
```

**Comment by madame-rachelle** [comment]
I think this counts as an unsupported scenario. Anisotropic filtering is something that requires a bit more intense work from the GPU than OpenGL ES was designed to accomodate for to begin with.

But this begs the question - while I can understand needing the UHD for power savings, is OpenGL ES really that much better on it?

And the NVidia - that's a clear case of "I'm recommending against that and won't support that scenario" - you should be running OpenGL at least on that, maybe even Vulkan.

OpenGL ES is designed for a computer that is clearly well below the graphics capabilities that your's has, on either processor.

**Comment by liPillON** [comment]
I use GLES out of necessity, since:
- with OpenGL I'm facing this issue https://forum.zdoom.org/viewtopic.php?f=50&t=70121
- with Vulkan on Intel the texture filtering is broken (ie: both "None (Trilinear)" and "Trilinear" have the same effect on the 3D scene)(I'm blaming the drivers here, since the same behaviour can be observed with other engines such as vkQuake)


I realize that these blocking conditions are self-imposed, since I probably would resolve them by switching to the NVIDIA dGPU which has better drivers.. I'd prefer however to keep using the Intel iGPU since it has less of an impact on the thermals and battery of my notebook.

Let's not forget also that a lot of laptops nowadays are sporting only the Intel iGPU.
I think that enabling Anisotropic Filtering under the GLES API would grant users more flexibility.

**Comment by madame-rachelle** [comment]
You are well within your rights to decide what GPU you want to use, there's a reason why laptops typically have 2, I am not going to impose on you that you have to use your NVidia.

But OpenGL ES does come with compromises. I'll raise the issue with our resident GLES coder but I can't promise anything will be done.

**Comment by liPillON** [comment]
That's fine by me! 
I opened this issue mainly to have some clarifications if the current behaviour originates from design choices, technical constraints or driver/renderer bugs.
If we're in a scenario where nothing can be done, then I'll live with that.
At the end of the day; your house, your rules :)

**Comment by madame-rachelle** [comment]
I just got word back that this is something that will be added.

**Comment by liPillON** [comment]
sweet, thanks to all people involved!

**Comment by emileb** [comment]
https://github.com/ZDoom/gzdoom/pull/1726
