### ISSUE TITLE
[BUG] Controller support not working on Flatpak builds on Linux.

### ISSUE THREAD

**Issue by Sparkwave2** [ZDoom/gzdoom#1728]
### GZDoom version

GZDoom 4.8.2, Flatpak

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

SteamOS 3.0, Arch Linux-based

### Relevant hardware info

Steam Deck 64 GB model

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Whenever I try to run any game inside GZDoom, using Steam Deck's Gaming Mode, everything runs correctly except, even with the controller support enabled and after restarting it, it doesn't detect the controller of the Steam Deck. Seems to only happen on the Flatpak version, and with no other software that I tried.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Download the Flatpak version of GZDoom
2. Launch it with a controller plugged in
3. Enable controller support and restart
4. Try using or binding the controller in the game

### Your configuration

```ini
https://gist.github.com/Sparkwave2/86ad0c549d83ccf8e2237df156ce5e79
```

### Provide a Log

Cannot run GZDoom with +logfile due to it being in a flatpak

**Comment by nashmuhandes** [comment]
Steam Deck controller appears to be working correctly as of the latest release on the Discover store.

Personally tested on my own Steam Deck.

If there are any more issues, please make a new ticket
