### ISSUE TITLE
[Feature] Option to skip the confirmation screen on quicksave/quickload

### ISSUE THREAD

**Issue by in1tiate** [ZDoom/gzdoom#1733]
### GZDoom version

GZDoom v4.8.2

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 10

### Relevant hardware info

N/A

### Is your feature request related to a problem? Please describe.

It's annoying to have to confirm quicksaves and quickloads. I understand why it's like this, but as someone who used to need a lot of quicksaves it was frustrating to have everything stop in its tracks until I pressed enter.

### Describe the solution you'd like

I'd like it if there was an option to skip this confirmation screen, off by default, for people who would rather not have to hit two buttons to quicksave instead of one.

### Describe alternatives you've considered

I don't have any alternative ideas, but I do have a potential problem with this; being that file I/O might not be performant enough to avoid a small hitch when this instant quicksave is performed. I don't know if that's enough of a problem to scrap this idea but it is a potential issue.

**Comment by OrdinaryMagician** [comment]
This is already present and accounted for in the miscellaneous options.
