### ISSUE TITLE
[BUG] Unable to host multiplayer game, "BindToPort: Address already in use"

### ISSUE THREAD

**Issue by mikeangelparra** [ZDoom/gzdoom#1734]
### GZDoom version

4.8.2

### Which game are you running with GZDoom?

Doom

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Fedora 36

### Relevant hardware info

RTX 3080, i7-10700k

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When I try to host a basic co-op game via terminal, the above message appears. When I try and see what app is hogging the default port of 5029, I get this.

[miguel@theseuslinux ~]$ lsof -i:5029
COMMAND   PID   USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
gzdoom  10395 miguel   46u  IPv4  98419      0t0  UDP *:infobright 

I attempted to launch a game via a port I verified was not in use prior to launching. Port 5037. After attempting to launch and getting the same error, I checked lsof and see that gzdoom is now using 5037.

[miguel@theseuslinux ~]$ lsof -i:5037
COMMAND   PID   USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
gzdoom  13525 miguel   62u  IPv4 109182      0t0  UDP *:5037 

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Run a simple -host command via terminal. GZDoom will ask for an IWAD. Select doom.wad
2. Error will populate
3.

**Comment by madame-rachelle** [comment]
Try `killall -9 gzdoom` and launch again.

**Comment by mikeangelparra** [comment]
Fixed by using tar version provided. The flatpak version seems to have this issue even after killing the process.
