### ISSUE TITLE
-savedir command line operation does not work on macOS

### ISSUE THREAD

**Issue by ninjacatz** [ZDoom/gzdoom#1736]
### GZDoom version

4.8.2

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Mac OS

### Please describe your specific OS version

Monterey 12.5.1

### Relevant hardware info

64bit Intel Macbook

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I can write a command on macOS to open GZDoom with various wads.
Example:
`open /Applications/GZDoom.app -iwad /Users/ninjacats/Documents/GZDoom/ERADICATION_MAPSET_2_0.wad /Users/ninjacats/Documents/GZDoom/ALIENS_ERADICATION_TC_2_0.pk3`
This works fine.
Where I run into trouble is when I try to use the -savedir command found here:
https://zdoom.org/wiki/Command_line_parameters#savedir
I add this to the end of my command:
`-savedir /Users/ninjacats/Documents/GZDoom/Savegames/alienseradication`
This also does not work:
`+save_dir "/Users/ninjacats/Documents/GZDoom/Savegames/alienseradication"`
It also does not matter what order I put the arguments.

The only solution is to change `save_dir` in game, but this is tedious.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Try to change save_dir with command line in macOS
2.
3.

### Your configuration

```ini
# Relevant variable:
save_dir=/Users/ninjacats/Documents/GZDoom/Savegames
```

### Provide a Log

No log, `-savedir` simply does nothing.

**Comment by alexey-lysiuk** [comment]
Please read man page of `open` carefully. Correct usage is `open /Applications/GZDoom.app --args ...`. If you do `ps -x | fgrep GZDoom` after running GZDoom without `--args`, you will notice that none of command line arguments were passed to executable.
