### ISSUE TITLE
[BUG] Launching gzdoom + voxel doom instead launches Heretic

### ISSUE THREAD

**Issue by juj** [ZDoom/gzdoom#1737]
### GZDoom version

GZDoom 4.8.2

### Which game are you running with GZDoom?

Doom

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When downloading a new offline/portable version of GZDoom plus an add-on, another version (maybe earlier installed? I can't remember?) of GZDoom launches instead.

### Steps to reproduce the behaviour.

1. I was excited by this video https://www.youtube.com/watch?v=M-aVt77epQ4 and decided to try out the new Voxel Doom
2. I downloaded GZDoom from latest release on the releases page: https://github.com/ZDoom/gzdoom/releases/tag/g4.8.2 -> https://github.com/ZDoom/gzdoom/releases/download/g4.8.2/gzdoom-4-8-2-Windows-64bit.zip
3. I unzipped the newly downloaded file gzdoom-4-8-2-Windows-64bit.zip to C:\Users\clb\Downloads\gzdoom-4-8-2-Windows-64bit (the directory did not exist before)
4. I downloaded Voxel Doom add-on from https://www.moddb.com/mods/doom-voxel-project/addons/voxel-doom
5. I followed the instructions inside the .zip file:

"Place the cheello_voxels.zip file in your GZDoom folder. Drag the file onto you
gzdoom.exe and select a WAD file to run."

6. I dragged `cheello_voxels.zip` over to `gzdoom.exe`

Observed: The game Heretic launches:

![image](https://user-images.githubusercontent.com/225351/189411987-7f82ccde-32b9-44a0-a44f-b2679af77e4f.png)

![image](https://user-images.githubusercontent.com/225351/189412087-abb37285-fe1b-4708-a71d-4ff01f79250e.png)

Expected: GZDoom with Voxel Doom add-on should launch.

I notice I do have Heretic bought from https://www.gog.com/en/game/heretic_shadow_of_the_serpent_riders , so maybe I have installed that before. It is unexpected that having installed that game once is able to hijack new portable downloads and unzips of GZDoom. That should not happen?

**Comment by coelckers** [comment]
You are aware that this was GZDoom launching Heretic, aren't you? It looks you did something wrong, like not having a Doom IWAD available. If Heretic is the only game GZDoom can find, it won't ask you but just launch it,

**Comment by juj** [comment]
Yeah, obviously the user was doing something wrong here. When one pauses for a second to think about the above UX flow, it looks obvious that there is a UX bug somewhere in gzdoom's lookup architecture.

For example, if user is running with the explicit command line "gzdoom.exe cheello_voxels.zip", where cheello_voxels.zip is a file in the gzdoom.exe CWD, it is unlikely that they would want to launch gzdoom with C:/GoG Games/Heretic/Heretic.wad.
