### ISSUE TITLE
[Feature] Scale the lens distortion effect with the FOV of the game

### ISSUE THREAD

**Issue by Hydra-Spectre** [ZDoom/gzdoom#1748]
### GZDoom version

GZDoom 4.8.2

### Which game are you running with GZDoom?

Doom

### What Operating System are you using?

Windows 11

### Is your feature request related to a problem? Please describe.

I love playing DOOM in letterboxed ultrawide and I love how the lens distortion effect looks with extremely wide aspect ratios.
My only problem is that they don't hit that hard unless you set it to extremely wide aspect ratios, and they don't scale with the FOV slider (a stronger lens distortion effect when the FOV is higher).

I have already maxed out the FOV in addition to playing in 21:9 and the effect is still not as strong as I would wish, while 32:9 and other aspect ratios crop the vertical view in comparison to 21:9.

### Describe the solution you'd like

I would love a slider to customise the strength of the lens distortion effect.

**Comment by logiota** [comment]
I would love to reduce the lens effect :) a slider would be great!

**Comment by coelckers** [comment]
Won't happen, there's no interest working on these effects.
