### ISSUE TITLE
[BUG] StatusBar.DrawString text is always shifted to the right for non-monospaced fonts

### ISSUE THREAD

**Issue by Player701** [ZDoom/gzdoom#1750]
### GZDoom version

At least 4.2.1 and up to the current master g4.9pre-234-g78360c188)

### Please describe your specific OS version

N/A

### Relevant hardware info

N/A

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When used with a non-monospaced font, ```StatusBar.DrawString``` always shifts the text to the right by 1 pixel (further multiplied by the HUD scale). ```Screen.DrawText``` does not exhibit this behavior.

**NB:** This behavior has been present since before the scale parameter was introduced (e.g.: version 4.2.1).

Example screenshot: top = non-monospaced font, bottom = monospaced font. This behavior occurs with every font I've tried so far (big font, small font etc. in every game). HUD scale is maxed out for clarity.

![image](https://user-images.githubusercontent.com/9046118/193264290-e0ca358d-e9f5-427e-878e-0d4d338f7e76.png)

### Steps to reproduce the behaviour.

Example ZScript for small font (text alignment doesn't matter), works with older versions also:
```
class TestStatusBar : DoomStatusBar
{
    private HUDFont _bigFnt, _bigFntMono;

    override void Init()
    {
        Super.Init();
        let fnt = SmallFont;
        _bigFnt = HUDFont.Create(fnt);
        _bigFntMono = HUDFont.Create(fnt, fnt.GetCharWidth("0"), 1);
    }

    override void Draw(int state, double ticFrac)
    {
        if (state == HUD_Fullscreen)
        {
            FillAndDraw(100, 100, "0123456789", _bigFnt);
            FillAndDraw(100, 120, "0123456789", _bigFntMono);
        }
    }

    private void FillAndDraw(double x, double y, string str, HUDFont fnt)
    {
        double w = fnt.mFont.StringWidth(str);
        double h = fnt.mFont.GetHeight();

        Fill(Color(255, 0, 255, 0), x, y, w, h);
        Fill(Color(255, 255, 255, 0), x, y, 1, 1);

        int flags = BaseStatusBar.DI_TEXT_ALIGN_LEFT
              | BaseStatusBar.DI_SCREEN_LEFT
              | BaseStatusBar.DI_SCREEN_TOP;

        DrawString(fnt, str, (x, y), flags, Font.CR_RED, 1.0);
    }
}
```

### Your configuration

```ini
N/A
```

### Provide a Log

N/A

**Comment by Player701** [comment]
So, apparently, [the "+1" part in line 768](https://github.com/ZDoom/gzdoom/blob/78360c188/src/common/statusbar/base_sbar.cpp#L767-L768) is the cause of this issue.

Judging by the commit history, it was there since the very beginning, precisely: 6760e01a0d6f9bca3961c084dc2b2d2f9583e0d9. I don't really know why, could anyone perhaps shed some light on this?

Removing the "+1" (and "-1" further below on line 822) appears to fix this. But I'd really like to know if there is some actual purpose behind this behavior.

**Comment by coelckers** [comment]
This is so old that any fix would do more harm than good. 
All HUDs made for this would be affected by it.

**Comment by Player701** [comment]
I see. Why not add a flag to toggle between old (wrong) and new (fixed) behavior manually then? Would it be a good idea?

**Comment by Player701** [comment]
**UPD:** Seems that compensating for the shift by subtracting 1 from the X coordinate works fine. I've used this method to fix this issue in my own mod.
