### ISSUE TITLE
check out Selaco performance tweaks [Feature] 

### ISSUE THREAD

**Issue by Daveed93** [ZDoom/gzdoom#1752]
### Which game are you running with GZDoom?

Other

### What Operating System are you using?

Windows 10

### Is your feature request related to a problem? Please describe.

https://steamcommunity.com/app/1592280/eventcomments/3371531430937344387?snr=2_groupannouncements_detail_

just wanted to tall you about Selaco devs sayig that they made some performance tweaks and they will be publishing the source code with their demo

> The source code will be provided with the demo, so any of the GZDoom devs is more than welcome to add the improvements to the main branch!
> We would do it ourselves, but we are very tight on time given our backlog.

**Comment by madame-rachelle** [comment]
Nobody's got time to deal with this kind of thing unless someone else can get a diff of the changes and create a PR with only the performance improvements themself.

**Comment by Chatplosion** [comment]
My thoughts about this are: Wait until finishing the next release, then freeze the main development, apply the patches for performance tweaks and move on later with the main development.
It is true that a higher performance is possible and more than urgent necessary for SOC arm platforms and other weak multi-core processors.

**Comment by madame-rachelle** [comment]
> My thoughts about this are: Wait until finishing the next release, then freeze the main development, apply the patches for performance tweaks and move on later with the main development. It is true that a higher performance is possible and more than urgent necessary for SOC arm platforms and other weak multi-core processors.

You are welcome to do that in a fork, but SOC ARM platforms are not the main target of GZDoom outside of Mac OS, which runs just fine anyhow with full Metal (MoltenVK) support. Sorry but until ARM platforms improve considerably in performance and become mainstream, they will always be sidelined as a niche platform. So there is no urgency here.

**Comment by coelckers** [comment]
Equally important, as long as ARM on Windows cannot be handled with Vulkan it will never be a first class target.
