### ISSUE TITLE
[BUG] Recent commit causes crashing on ZScript calls to DrawThickLine

### ISSUE THREAD

**Issue by OrdinaryMagician** [ZDoom/gzdoom#1759]
### GZDoom version

c0c9f8e15

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Linux x86_64

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

One quick way to trigger this bug is to start the game with [this mod](https://marisakirisa.me/tmp/minimap_m.pk3). It draws a minimap on the hud using various DrawThickLine calls.

Immediately upon starting a map, GZDoom will crash. Judging from debugger output, it appears that the vectors passed to AddThickLine are invalid pointers.

The DrawLine function is likely affected as well, but this is the one that tripped up first for me.

### Provide a Log

[gzdoom-crash.log](https://github.com/ZDoom/gzdoom/files/9790188/gzdoom-crash.log)

**Comment by mjr4077au** [comment]
There possibly shouldn't be backend updates between projects until Raze's work branch is fully merged into master. This issue is fixed in a commit that has yet to make it to master (https://github.com/ZDoom/Raze/commit/3c72ce531f4f0338d3ed86b6e999e512266a2b6b) and this backend update adds utilities such as `interpolatedvec3()`, etc that are removed for something templatised later on.

**Comment by coelckers** [comment]
Essentially correct, but I had to do an update to get the new movieplayer code in.
I fixed the interface in GZDoom.

**Comment by OrdinaryMagician** [comment]
The issue doesn't seem fully fixed. Now the rendering is corrupted.
![Screenshot_Doom_20221015_103206](https://user-images.githubusercontent.com/2286785/195977361-339c77c5-9dd5-41ec-a1c5-25935a59dd4c.png)

**Comment by SanyaWaffles** [comment]
There was another commit or two since the fix @OrdinaryMagician. Is it still corrupted there?

**Comment by OrdinaryMagician** [comment]
It still is.

**Comment by SanyaWaffles** [comment]
Should probably open another issue then.
