### ISSUE TITLE
[BUG] ReFire doesn't work

### ISSUE THREAD

**Issue by Reycko** [ZDoom/gzdoom#1761]
### GZDoom version

V4.8.2

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

Windows 10 Family Edition

### Relevant hardware info

GeForce NVIDIA GTX 970; AMD Ryzen 1500X Quad-Core

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When using GZDoom. This issue is nonexistent in Zandronum or the DOS version.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Start up GZDoom with the DOOM2 IWAD and no external WADs.
2. Either Load or Make a new game.
3. Hold the fire key, Notice that A_ReFire is skipped or broken.

### Your configuration

```
https://gist.github.com/Reycko/78d808eb4ccbf463b1ee7c10e6027c8a
```

### Provide a Log

I do not know how to make a log.

**Comment by coelckers** [comment]
"is broken" does not say anything, You have di describe your problem in more detail.

**Comment by mc776** [comment]
Also what is the expected behaviour versus the actual?

**Comment by OrdinaryMagician** [comment]
`
Mouse1=+attack; wait 1; -attack
Mouse2=+altattack;wait 1; -altattack
`
I believe these binds might be responsible.

**Comment by madame-rachelle** [comment]
Ooof. Yep that'll do it.
