### ISSUE TITLE
[Feature] custom config path

### ISSUE THREAD

**Issue by axet** [ZDoom/gzdoom#1763]
### GZDoom version

GZDoom g4.7.1 

### What Operating System are you using?

Linux x86_64

### Is your feature request related to a problem? Please describe.

Having multiple games in one folder causing crating unrelated saves files which is not loadable due to missing map / wad files. I prefer to have multiple saves folder for every game / wad file.

### Describe the solution you'd like

gzdoom --home /path/to/new/home

or --save folder location

### Describe alternatives you've considered

export HOME=/adsfdf gzdoom

but this causing all other configs to be recreated inside new home folder after starting a game (pulseaudio for example)

**Comment by coelckers** [comment]
A "-config" option already exists.
A "-savedir" option also already exists.
