### ISSUE TITLE
Sound is a lot worse in 4.8.2 [BUG] 

### ISSUE THREAD

**Issue by Tasosgemah** [ZDoom/gzdoom#1764]
### GZDoom version

4.8.2

### Which game are you running with GZDoom?

Doom

### What Operating System are you using?

Windows 10

### Relevant hardware info

i5 4670, GTX 1060

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I noticed that the  game was sounding weird. Like there was a complete lack of bass from the SFX, as if they sound from an old radio. Then the same thing happened in Raze 1.5.0 (which is based on GZDoom 4.8.2). The sound in Duke Nukem had the same issues.

Turns out, if i use the openal.dll file from an older version (like 4.6.0) if fixes the sounds for both GZDoom and Raze.

### Steps to reproduce the behaviour.

Just play any DOOM game and listen to it.

**Comment by Tasosgemah** [comment]
After some troubleshooting, it appears that it has something to do with the 5.1 mode not working as it should. In Stereo (changed with the openal tool) it sounds good but obviously it's only stereo.

**Comment by coelckers** [comment]
I never had issues with OpenAL's 5.1 mode, even with the most recent DLL.

**Comment by Tasosgemah** [comment]
Latest version (4.9.0) still gives me the same issues.

Thankfully, replacing the openal32.dll with an older one (from GZDoom 4.6.0), fixes it. But i don't know for how long this will be viable.

**Comment by coelckers** [comment]
Please clear this with https://github.com/kcat/openal-soft
Since the problem lies in a third party dependency we cannot fix it.
