### ISSUE TITLE
Chapter 3 of Blade of Agony doesn't start anymore[BUG] 

### ISSUE THREAD

**Issue by x3003** [ZDoom/gzdoom#1768]
### GZDoom version

gzdoom-x64-g4.9pre-329-g671b8696b

### Which game are you running with GZDoom?

Other

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

home 10

### Relevant hardware info

amd r5, gtx 1060

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Chapter 3 of BOA (git) doesn't start anymore. No problem w/ chapters 1 & 2.
Loading an existing chapter 3 savefile also works.
Looks like it hangs, coz gzdoom isn't responding to other keys anymore. Need the taskmanager to quit.
Last version that worked correctly was 4.9 - pre 280. The problems starts w/ pre 281.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Start BoA
2. Select the 3rd chapter and user level.
3. Wait......

**Comment by Talon1024** [comment]
The error message I'm getting is:

    VM execution aborted: array access out of bounds. Negative current index = -1
    
    Called from ScreenJobRunner.CanWipe at gzdoom.pk3:zscript/engine/screenjob.zs, line 374

Repeated ad infinitum

**Comment by Talon1024** [comment]
[Here's a simple test mod](https://github.com/ZDoom/gzdoom/files/9946425/intermission.zip). To reproduce this issue, enter `netevent intermission` into the console.

**Comment by coelckers** [comment]
fixed in fdeec5e0a55818e551077e58562df697bf02edd0

**Comment by x3003** [comment]
The fix seems to work, only now you'll get a double melt effect before starting the level.
Dunno if the error is in gzdoom or in boa itself.

**Comment by Talon1024** [comment]
The thing is, BoA uses an intermission as a "hack" to forcefully close the automap if it's open. This is important for cutscenes.
