### ISSUE TITLE
[BUG] Specific portal setups cause the game to crash when an explosion occurs right at the start of a map

### ISSUE THREAD

**Issue by inkoalawetrust** [ZDoom/gzdoom#1769]
### GZDoom version

g4.9pre (Basically, a RelWithDebInfo build using the latest commits as of October 23rd, 2022)
4.8.2 (It also happens there)

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

Windows 10 Pro

### Relevant hardware info

Ryzen 5600X, RTX 2060, the hardware doesn't really matter in this case.

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

UPDATE: While doing some testing, it seems that this crash also happens on the 4.8.2 stable build, and in addition to the conditions specified below that are needed for it to happen, the player also needs to be visible to actor, if the actor is moved out of sight of the player, but all the conditions are otherwise met, then it will still NOT crash.

The bug that occurs is that under specific portal setups, A_Explode/RadiusAttack calls that are called right at the start of the map, will cause GZDoom to hard crash, I discovered this while working on a mod, and deciding to give an actor that explodes on death a health value of 0 in the editor (So that it will die upon map start). Then after encountering the bug and rulling out my own code, I ran a stack trace on the crash with a debug build and discovered the cause. This crash only happens on one map that I know of, again, probably due to its' specific portal setup.

I have attached the crash report of the bug. Along with a link to the map where it happens, and the mod with the actor that explodes upon dying.

https://drive.google.com/file/d/1vm9y2V-9cG7dD2SFwvyAl-5E5grqGWNu/view?usp=sharing

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Open up ZDL.
2. Add the "Military Vehicles Pack" and "gz_bigcity" folders in the External Files
3. Run GZDoom.
4. Pick the episode called "Sandbox".
5. Run the map (I have already placed the specific actor that causes the bug on the map, and given it a spawn health of zero.)

### Provide a Log

[CrashReport.zip](https://github.com/ZDoom/gzdoom/files/9845338/CrashReport.zip)

**Comment by coelckers** [comment]
fixed in 435e7dddcd14ab364095e28bcd9961104de728fa
