### ISSUE TITLE
[BUG] GZDoom crashes when my mods and Brutal Doom v21 run together

### ISSUE THREAD

**Issue by inkoalawetrust** [ZDoom/gzdoom#1771]
### GZDoom version

g4.9pre (Basically, a RelWithDebInfo build using the latest commits as of Oct 23, 2022)
4.8.2 stable (Also happens there)

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 10

### Relevant hardware info

Ryzen 5600X, RTX 2060, the hardware doesn't really matter in this case.

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

NOTE: I wasn't going to report this, due to how vague the conditions to trigger it are, plus I doubt NPC battles are that fun for you to sit around and watch as they are to me. But Rachael told me to report it here anyway, so here it is.

UPDATE: After making this report, I booted up GZDoom 4.8.2 stable instead, and basically replicated the same scenario again, and it seems that the game also crashes in 4.8.2 under the exact same circumstances (My marines and vehicles fighting BD's monsters on the latters' test map). Naturally, I have no stack trace of this, since it's the stable build, but I do have the CrashReport.zip, uploaded below.

UPDATE 2: Due to the circumstances surrounding both this issue and #1769, I suspected that perhaps my Army Truck NPC was also the cause of this issue, but after doing the same scenario (With a debugger and all), but without any trucks involved, the battle was certainly able to last longer before it crashed. But well, it still crashed, in addition the crash is the EXACT same, same source and stack trace and all, so that hypothesis of mine is inconclusive, but perhaps it IS still being caused when one of my NPCs die, since both the Truck and Army Car call A_Explode right when they enter their Death state.

Okay, this is a bit of a vague one, and not as easily reproducible as #1769, but, for some reason, the very latest GZDoom dev build seems to crash out of nowhere when I have NPC battles with two of my mods and Brutal Doom's monsters.

So basically, I've spent the past few hours as of the time writing this, messing around in Brutal Doom's test map using my marine and vehicle NPCs, and spawning in BD's monsters using the long row of spawn switches. And having them fight each other, this was going normally (All problems were just issues with BD itself not working with my mods perfectly, broken behavior and such). I was going up the ladder of BD's monsters, from the Former Humans and Imps up to BD's own enemy vehicles. And once I begun spawning in enemy vehicles from BD like the attack helicopter, issues begun.

When I first spawned in a helicopter for my NPCs to fight, the game had its' first crash. I'm not sure why, nor did I save the report, but since I had already set up (And was already playing these battles with) the debug build of GZDoom I created yesterday, I started up the game again, except this time I attached a debugger in case I catch another crash. This time around, the game didn't instantly crash when I spawned in BD's helicopters, so I spawned a few BD vehicles to fight my own NPCs, had a grand old time, then once I spawned in a bunch more BD vehicles (Some mechs, tanks, and helicopters), the game crashed once again...

... and that leads me to now, Visual Studio caught the crash, and the source seems to be that the _origin_ pointer in _FMultiBlockThingsIterator::FMultiBlockThingsIterator_ was null.

![image](https://user-images.githubusercontent.com/56005600/197404174-fe3497a4-96b7-4396-8970-4296970661d7.png)

I have attached the full stack trace below. I will also link my marine and vehicle mod, so that you can try to replicate the crash if possible, as for BD, it's just stock BDv21 so you can get it online from ModDB. I would include the CrashReport.zip too, but for some reason GZDoom shut down without showing the crash handler the second time.

The marine mod: https://github.com/inkoalawetrust/Smart-Marines/releases/tag/1.3.6
The vehicle mod: https://drive.google.com/file/d/1vm9y2V-9cG7dD2SFwvyAl-5E5grqGWNu/view?usp=sharing
Brutal Doom: https://www.moddb.com/mods/brutal-doom/downloads/brutal-doom-v21-beta

The vehicle mod is slightly out of date from yesterday (For example, the classes to spawn through the console below are brand new), but it's still more or less the same code.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Download the Smart Marines, the Military Vehicles Pack dev build, and Brutal Doom.
2. Load them all up in the latest dev build as of October 23rd, 2022.
3. Open up the Brutal Doom test map (Either through the mod settings, or by typing _map test_ in the console.)
4. Go into the city, spawn in some vehicles (Use summonfriend mvp_apc_mg, mvp_armytruck_ramming and mvp_armycar_painray to spawn in the friendly vehicle actors I spawned in my own battles, the marines will be naturally spawned by them.)
5. Go to the long row of all Brutal Doom monsters, for the sake of time, just try skipping straight to spawning in vehicles, I myself spawned in attack helicopters, MBTs (Not the Artillery Tank vehicle.), mechs, and Juggernauts.
6. Spawn in those BD vehicles, have them fight with my own, and, here comes the vague and not as easily reproducible part, just rinse and repeat this battle by spawning in more combatants, until the game eventually crashes.

### Provide a Log

**_The stack trace:_**
>	gzdoom.exe!FMultiBlockThingsIterator::FMultiBlockThingsIterator(FPortalGroupArray & check, AActor * origin, double checkradius, bool ignorerestricted) Line 1065	C++
 	[Inline Frame] gzdoom.exe!DBlockThingsIterator::{ctor}(AActor *) Line 180	C++
 	gzdoom.exe!Create<DBlockThingsIterator,AActor * &,double &,bool &>(AActor * & <args_0>, double & <args_1>, bool & <args_2>) Line 363	C++
 	gzdoom.exe!CreateBTI(AActor * origin, double radius, bool ignore) Line 202	C++
 	[External Code]	
 	gzdoom.exe!VMCall(VMFunction * func, VMValue * params, int numparams, VMReturn * results, int numresults) Line 580	C++
 	[Inline Frame] gzdoom.exe!VMCallAction(VMFunction * numparams, VMValue *) Line 494	C++
 	gzdoom.exe!FState::CallAction(AActor * self, AActor * stateowner, FStateParamInfo * info, FState * * stateret) Line 215	C++
 	gzdoom.exe!AActor::SetState(FState * newstate, bool nofunction) Line 580	C++
 	gzdoom.exe!AActor::Tick() Line 4177	C++
 	gzdoom.exe!AF_DThinker_Tick(VMValue * param, int numparam, VMReturn * ret, int numret) Line 884	C++
 	gzdoom.exe!VMNativeFunction::NativeScriptCall(VMFunction * func, VMValue * params, int numparams, VMReturn * returns, int numret) Line 315	C++
 	[External Code]	
 	gzdoom.exe!VMCall(VMFunction * func, VMValue * params, int numparams, VMReturn * results, int numresults) Line 580	C++
 	[Inline Frame] gzdoom.exe!DThinker::CallTick() Line 893	C++
 	[Inline Frame] gzdoom.exe!FThinkerList::TickThinkers(FThinkerList *) Line 618	C++
 	gzdoom.exe!FThinkerCollection::RunThinkers(FLevelLocals * Level) Line 147	C++
 	gzdoom.exe!P_Ticker() Line 175	C++
 	gzdoom.exe!G_Ticker() Line 1292	C++
 	gzdoom.exe!TryRunTics() Line 1991	C++
 	gzdoom.exe!D_DoomLoop() Line 1221	C++
 	gzdoom.exe!D_DoomMain_Internal() Line 3680	C++
 	gzdoom.exe!GameMain() Line 3706	C++
 	gzdoom.exe!DoMain(HINSTANCE__ * hInstance) Line 266	C++
 	gzdoom.exe!wWinMain(HINSTANCE__ * hInstance, HINSTANCE__ * nothing, wchar_t * cmdline, int nCmdShow) Line 556	C++
 	[External Code]	

**_GZDoom 4.8.2 Crash Report:_**
[CrashReport.zip](https://github.com/ZDoom/gzdoom/files/9847114/CrashReport.zip)

**Comment by coelckers** [comment]
fixed in ec1525b0c4034a848d5fbc5fe1c931ee6a937cf1

You still have a problem on your side as you somehow manage to pass a null pointer to the Blockmap iterator creation function.
