### ISSUE TITLE
[BUG] gzdoom stucked on fedora 36

### ISSUE THREAD

**Issue by Bibobu** [ZDoom/gzdoom#1772]
### GZDoom version

g4.9pre-331-g2b805e196-m

### Please describe your specific OS version

OS: Fedora Linux 36 (Workstation Edition), Linux 5.19.16-200.fc36.x86_64 on x86_64

### Relevant hardware info

CPU: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz, GPU: NVIDIA GeForce GTX 970M

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When launching any WAD, the game freezes before showing any window:
* the progress bar is stuck at some point (which depends on the WAD)
* a program appears to be launched in the desktop program list 
* a window exist for the window manager,  but it contains nothing.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. I compiled gzdoom. Compilation went fine.
2. Launched gdb ./gzdoom
3. Typed run
4. Waited until program is stuck
5. CTRL+C and `backtrace`

### Your configuration

```ini
https://gist.github.com/Bibobu/97b048bd9191a0f0efed0fc96fb1c75b
```

### Provide a Log

[gzdoomdebug.log](https://github.com/ZDoom/gzdoom/files/9854887/gzdoomdebug.log)

**Comment by coelckers** [comment]
It's stuck inside the Vulkan driver. Have you tried OpenGL?

**Comment by madame-rachelle** [comment]
Please report it to the Fedora maintainers.

Fedora is a "cutting edge" distro which means a lot of the fuckery that happens there gets passed down to other distros eventually. Naturally we don't really offer prime support for it, either, because library changes like this are so often problematic.

**Comment by Bibobu** [comment]
Thanks @madame-rachelle. I will do so and hope they can find/do something about it, but since this is about vulkan drivers, my hopes are not that high.

Obviously this is out of the scope of GZDoom devs.
Thank for the support. I think we can then consider this issue closed for now.
