### ISSUE TITLE
[BUG] gl_lightmode behaviour with the OpenGLES renderer

### ISSUE THREAD

**Issue by liPillON** [ZDoom/gzdoom#1774]
### GZDoom version

both 4.8.2 and git

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

Windows 10 Enterprise LTSC 19044.2193

### Relevant hardware info

Intel i7-8565U +UHD Graphics 620

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

On my machine I can only use OpenGLES due its buggy Intel graphics drivers.
With this renderer I've noticed that the "Vanilla" lightmode give the same results as the "Software" one.

I've tried using the OpenGL renderer and "Vanilla" does indeed look darker than "Software".
This is consistent with the documentation here: https://zdoom.org/wiki/CVARs:Display#gl_lightmode

Is this intended/expected, due to the two renderers' different capabilities?

### Steps to reproduce the behaviour.

1. download the latest gzdoom release
2. unzip it to a writable directory (ie: your desktop)
3. launch gzdoom (this will create a new config.file from scratch)
4. switch to the OpenGLES renderer and exit
5. launch gzdoom and start a game
6. toggle the gl_lightmode cvar between the 8 (software) and 16 (vanilla) values

sample screenshots: [opengles-gl_lightmode-screenshots.zip](https://github.com/ZDoom/gzdoom/files/9879107/opengles-gl_lightmode-screenshots.zip)

**Comment by yum13241** [comment]
OpenGLES doesn't support shaders AFAIK, and some `gl_lightmode` values use shaders. (GLSL shaders to be precise)

**Comment by coelckers** [comment]
I wouldn't be surprised if the vanilla shader was disabled due to its complexity and poor performance on low end hardware.
