### ISSUE TITLE
[Feature] FSR2 upscaling support

### ISSUE THREAD

**Issue by jan-kleks** [ZDoom/gzdoom#1776]
### Which game are you running with GZDoom?

Other

### What Operating System are you using?

Windows 10

### Is your feature request related to a problem? Please describe.

Have you considered implementing FSR2 ([it's open-source](https://github.com/GPUOpen-Effects/FidelityFX-FSR2)) in gzdoom? Maybe it could additionally boost performance/help reduce power usage?

Check out as well [PrBoom: Ray Traced](https://github.com/sultim-t/prboom-plus-rt/releases) which already supports DLSS.

**Comment by coelckers** [comment]
This does not really fit into GZDoom's roadmap and would necessitate quite substantial changes to how rendered frames are being handled internally..
