### ISSUE TITLE
[Feature] Coop-Multiplayer support

### ISSUE THREAD

**Issue by wothke** [ZDoom/gzdoom#1780]
### GZDoom version

4.8.2

### Which game are you running with GZDoom?

Doom

### What Operating System are you using?

Windows 10

### Is your feature request related to a problem? Please describe.

I am trying to play a coop-game of Doom with a friend over the internet - but quite frankly I am quite confused by GZDoom's respective functionality. 

There actually seem to be some multiplayer (and even coop) related settings in the settings screen. But I have no idea what might need to be done to actually start a coop-game or to join it. Also I found some old discussions (back from 2012) where ppl commented that - at the time - GZDoom apparently was quite limited with regard to multiplayer support (as compared to zandronum). 

What is the actual state of respective functionality? Is there any documentation that explains potential limitions and/or how to use it?

### Describe the solution you'd like

Other Doom engines seem to be nicely integrated with tools like "Doom Explorer" - which make playing multiplayer Doom rather user friendly (except for the ugly 1990 pixel GFX that those other Doom engines still seem to be using..)

I would like to be able to start/join a coop game from GZDoom's main menu - or to have a "Doom Explorer" integration that provides respective functionality (i.e. that allows to play the game across multiple levels in coop-multiplayer mode).

### Describe alternatives you've considered

Alternatively we could just burry our Doom nostalgia and move on to more recent coop games (unfortunately there seem to be very few recent games that actually have a coop mode that merits that name..).

**Comment by mc776** [comment]
https://zdoom.org/wiki/Multiplayer#Technical_details

**Comment by wothke** [comment]
> https://zdoom.org/wiki/Multiplayer#Technical_details

that worked. thanks!

I think it would be really useful to have that kind of information (or a link to it) contained within the respective gzdoom "release" binaries (e.g. a README with respective links).

**Comment by madame-rachelle** [comment]
Documentation is beyond the scope of the engine, and current work with multiplayer is stalled. What we have now works though, not perfectly, but it's as good as it's going to get for the near foreseeable future.
