### ISSUE TITLE
[BUG]  /run/build/gzdoom/src/d_anonstats.cpp:14:10: fatal error: i_mainwindow.h: No such file or directory

### ISSUE THREAD

**Issue by Eonfge** [ZDoom/gzdoom#1793]
### GZDoom version

GZDoom 4.9.0

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Flathub FreeDesktop 22.08

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

```
/run/build/gzdoom/src/d_anonstats.cpp:14:10: fatal error: i_mainwindow.h: No such file or directory
   14 | #include "i_mainwindow.h"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
```

[gzdoom_4.9.0_log.txt](https://github.com/ZDoom/gzdoom/files/9946676/gzdoom_4.9.0_log.txt)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. https://github.com/flathub/org.zdoom.GZDoom check out (including submodules)
2. Change submodule gzdoom versions to 4.9.0
3. Run quick-compile script (download dependencies when prompted)

```
#!/usr/bin/env bash

clear
flatpak-builder --repo=testing-repo --force-clean build-dir org.zdoom.GZDoom.yaml
flatpak --user remote-add --if-not-exists --no-gpg-verify gzd-testing-repo testing-repo
flatpak --user install gzd-testing-repo org.zdoom.GZDoom -y
flatpak --user install gzd-testing-repo org.zdoom.GZDoom.Debug -y
flatpak update -y
```

**Comment by coelckers** [comment]
Use tag g4.9.0a.
We cannot change the tag for an already released build.
