### ISSUE TITLE
[BUG] Segmentation Fault during launch.

### ISSUE THREAD

**Issue by Contmotore** [ZDoom/gzdoom#1797]
### GZDoom version

GZDoom g4.9.0-m - SDL version

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Arch Linux

### Relevant hardware info

AMD Ryzen 7 4700U with Radeon Graphics

### Have you checked that no other similar issue already exists?

- [X] I have searched, found a similar issues at https://github.com/ZDoom/gzdoom/issues/1552, but was already closed.

### A clear and concise description of what the bug is.

Segmentation Fault error when trying to launch the game. With or without any parameters.
The error appears after the hardware data submission popup window. It happens when I press either Yes or No.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Open a terminal and type the command "gzdoom" to launch the game.
2. Press Yes or No in the hardware data submission popup window.

### Your configuration

```ini
No changes made to the default config file.
```

### Provide a Log
```
GZDoom g4.9.0-m - 2022-11-05 14:00:59 +0100 - SDL version
Compiled on Nov  8 2022

OS: Arch Linux, Linux 6.0.7-zen1-1-zen on x86_64
GZDoom version g4.9.0-m


*** Fatal Error ***
!!! Failed to exec debug process
Segmentation fault (core dumped)
```

**Comment by Contmotore** [comment]
> Install GDB, and post `gzdoom-crash.log` created by GZDoom. Without this info such reports are useless.

```
Starting program: /usr/bin/gzdoom 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7ffff26b66c0 (LWP 9823)]
[New Thread 0x7ffff1eb56c0 (LWP 9824)]
[Detaching after vfork from child process 9825]
[Detaching after fork from child process 9826]
[Detaching after fork from child process 9827]

Thread 1 "gzdoom" received signal SIGSEGV, Segmentation fault.
0x0000555555dd5ee4 in FileSystem::InitMultipleFiles(TArray<FString, FString>&, bool, LumpFilterInfo*, bool, _IO_FILE*) ()
#0  0x0000555555dd5ee4 in FileSystem::InitMultipleFiles(TArray<FString, FString>&, bool, LumpFilterInfo*, bool, _IO_FILE*) ()
#1  0x0000555555dd60c1 in FileSystem::InitSingleFile(char const*, bool) ()
#2  0x0000555555a07d21 in FIWadManager::ScanIWAD(char const*) ()
#3  0x0000555555a0a583 in FIWadManager::ValidateIWADs() ()
#4  0x0000555555a0ac63 in FIWadManager::IdentifyVersion(TArray<FString, FString>&, char const*, char const*, char const*) ()
#5  0x0000555555a0c11d in FIWadManager::FindIWAD(TArray<FString, FString>&, char const*, char const*, char const*) ()
#6  0x0000555555a13b44 in GameMain() ()
#7  0x00005555557b4784 in main ()
```

**Comment by coelckers** [comment]
Insufficient info to investigate further.  While we get the function where it crashes there's nothing to narrow it down.
