### ISSUE TITLE
4.9.0 Quicksave rotation not working

### ISSUE THREAD

**Issue by Q3BFG10K** [ZDoom/gzdoom#1798]
4.9.0, Win10-64, tested with Heretic and TNT. Was working fine on 4.8.2 and earlier. 

I converted 4.8.2 to a portable install, still shows 2 rotating files in the menu option, but it always saves to **quick-1.zds**

**Comment by axredneck** [comment]
I just noticed this and wanted to report but i see it's already reported.

**Comment by axredneck** [comment]
Edit: now it started working for some reason. On MAP01 it didn't work but now on MAP02 it works.

**Comment by Talon1024** [comment]
With the quicksave rotation on, I noticed it would sometimes save as quick-1.zds, and it would sometimes save as quick01.zds.

**Comment by eirc** [comment]
Same here, there's only quick-1.zds, looks like quicksave rotation does nothing.

**Comment by Strate** [comment]
@Q3BFG10K @eirc this fixed in 4.11
