### ISSUE TITLE
[Feature] Move existing savegames into their new appropriate iwad save subdirectories?

### ISSUE THREAD

**Issue by ipaqmaster** [ZDoom/gzdoom#1807]
### GZDoom version

gzdoom 4.9.0-1

### Which game are you running with GZDoom?

Doom

### What Operating System are you using?

Linux x86_64

### If Other OS, please describe

Linux 6.0.8-arch1-1

### Relevant hardware info

11th Gen Intel(R) Core(TM) i7-1195G7 [Iris Xe Graphics]

### Is your feature request related to a problem? Please describe.

I now have to specify -savedir $HOME/.config/gzdoom to continue a playthrough or revisit old ones.

The save games are zip files and contain the IWAD used to save the under info.json is described in the save 

### Describe the solution you'd like

Would it be possible to enumerate the original savedir (In the gzdoom config root) and appropriately dish out seen `*.zds` out to their new save destination so that -savedir doesn't need to be specified?

### Describe alternatives you've considered

At the moment, I'm considering writing a little bash loop which will enumerate and move each of them to the new subdir system of 4.9.0 for me.

**Comment by coelckers** [comment]
I'm sorry but the needed work here stands in no relation to the minor gain in convenience. If you still need to load them and do not want to look them up, just use -savedir to point to the old directory.
