### ISSUE TITLE
[BUG] 4.9.0 - Survey repop on every program launch

### ISSUE THREAD

**Issue by silverlays** [ZDoom/gzdoom#1811]
### GZDoom version

GZDoom 4.9.0

### What Operating System are you using?

Windows 11

### Please describe your specific OS version

Windows 11 Pro N 22H2

### Relevant hardware info

Ryzen 5 5600x / RTX 3060

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

After updating to 4.9.0 (and choosing portable mode), every time I run GZDoom it offers me the survey (which I answered **YES** the first time). I of course tried to put **NO** to the survey afterwards, but same result, the survey keeps coming back

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Update 4.9.0 from 4.8.2
2. Select portable mode
3. Say **YES** to the survey
4. Launch & play
5. Quit
6. Relaunch GZDoom

### Your configuration

```ini
https://gist.github.com/silverlays/519636d533b74420d04ff291abfaea66
```

**Comment by madame-rachelle** [comment]
This generally means that the new portable .ini is not writeable. Where did you put the installation?

**Comment by silverlays** [comment]
> This generally means that the new portable .ini is not writeable. Where did you put the installation?

In a subfolder of my D drive, not read-only or any security issues. I am in the field of programming. The solution is unfortunately not so simple :(

**Comment by coelckers** [comment]
Works fine for me. 
Are you sure it is actually using that INI? Type 'whereisini' in the console to check.

**Comment by silverlays** [comment]
> Works fine for me. Are you sure it is actually using that INI? Type 'whereisini' in the console to check.

I confirm, it is the correct file.

**Could someone possibly give me the name of the variable and associated value that controls the display of the survey?**
