### ISSUE TITLE
[BUG] Cutscene: Setting a map as "nointermission" blocks that map's cutscene along with the intermission tally.

### ISSUE THREAD

**Issue by Acts19quiz** [ZDoom/gzdoom#1812]
### GZDoom version

GZDoom 4.9.0

### Which game are you running with GZDoom?

Doom

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

Windows 10 LTSC 21H2

### Relevant hardware info

Intel 6700k, NVIDIA GeForce 980Ti

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

[The Wiki](https://zdoom.org/wiki/Cutscene) lays out that either an individual map or a cluster can have an outro cutscene. However, if either the map with the outro or the cluster's final map have "nointermission" set, the cutscene won't play. There may be certain creative reasons why a modder might want a traditional DOOM 1 episode to end without a level intermission or tally, but still play an ending cinematic (after all, you wouldn't set "nointermission" to block a cutscene you yourself went through the trouble of adding!). In other words, have an end cinematic without an intermission tally.

If this is intentional, as mentioned, there may be stylistic or creative reasons to play a movie without an intermission. Along with the fact that the Wiki doesn't list any requirements for outro cutscenes needing "intermission" set, that's why I figured this was a bug.

This doesn't affect intros in my testing.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Script either a map or cluster outro cutscene definition.
2. Set either that scripted map or the cluster's final map as "nointermission".
3. Exit the level normally (without console commands like "map" or "changemap").
4. The cutscene will be skipped along with the level's intermission.

[Here are two test files](https://github.com/ZDoom/gzdoom/files/10008785/SMKtest.zip) to assist with reproduction. One has E1M8 set to "nointermission", while the other doesn't. These are meant to be played with DOOM 1/Ultimate DOOM (doom.wad). Finish E1M8 with both PK3s to observe the difference.

**Comment by coelckers** [comment]
fixed in d0c86952ee76dcd4e1294dd3cbe8846c8abde67d
