### ISSUE TITLE
[Feature] Expose the 'IWAD selection box' to users with older hardware unable to use the standard renderer(s) that by default never actually see it.

### ISSUE THREAD

**Issue by Acts19quiz** [ZDoom/gzdoom#1814]
### GZDoom version

GZDoom 4.9.0

### Which game are you running with GZDoom?

Other

### What Operating System are you using?

Windows 7

### If Other OS, please describe

Windows 7 SP1 x64

### Relevant hardware info

Intel(R) Core(TM) i3-2310M, Intel(R) HD Graphics 3000

### Is your feature request related to a problem? Please describe.

Let me set the stage here: I have an older Windows 7 laptop. Its specs cap out at OpenGL 3.1 (and no Vulkan). The bad news is that it can't run GZDoom 4.9.0's OpenGL 3.3 renderer. The good news is that 4.9.0's OpenGL ES 2.0 works just fine (if set to that)!

Here is where things fall apart. When I run the program normally and place the desired IWAD (it could be DOOM II, Chex Quest/3, whatever) in the program directory like the average user would, GZDoom fails to start, citing the incompatible OpenGL 3.3 requirement.

One of the sources of the problem here is that (at least for Windows) '[IWAD selection box](https://zdoom.org/wiki/IWAD_selection_box)' is a misnomer here: It's a more featured launcher with a number of options, including auxiliary add-ons like brightmaps, and most relevantly here the **_renderer of choice_**. But if, like me or my typical user, you either only have one game (i.e., IWAD) or want to play only one game, the 'IWAD selection box' doesn't display on launch, even if it is enabled by default within the in-game options. Which you can't access anyway.

You can go into "/Users/Documents/My Games/GZDoom/gzdoom.ini" and manually change "vid_preferbackend", but this is not at all intuitive if you're new to the game, new to GZDoom, not familiar with the intricacies of the GZDoom ecosystem, don't know exactly where the INI file is (or where to even look for it), don't know what to look for inside the INI file (there's no real user guide for that), or don't know what number corresponds to what renderer. Or if you're developing a new game and delivering it to super-inexperienced users that have 'never heard of a gzdoom before'.

The bottom line and end result is that newcomers or people that don't know GZDoom inside out, and have older hardware that can still run modern GZDoom, get told by GZDoom that 4.9.0 (or whatever) is incompatible, and are often by default not given any recourse to address it, leaving the impression that they just can't run it. When in fact there's a very simple fix hidden within a line in an INI file that makes it work just fine.

### Describe the solution you'd like

Given that the 'IWAD selection box' actually handles a lot more functions (really important ones at that that can break or make the game) than just what game to pick, I would suggest:

If within options it's set to display on launch (which by default it is), launch it even if only one IWAD is present. Since, like mentioned, it handles a lot more than just IWAD selection. The renderer is the focus here, but other cool options like dynamic lights and brightmaps are also available here, along with other important options like "fullscreen". The only time that it really needs to not display is if it's explicitly told to not display in options (which is currently not how GZDoom handles this option).

A nice addition would be to, in the launch failure message, direct users to try a different renderer (like OpenGL ES) so that those less familiar with GZDoom and why things sometimes break will have a clear idea of what to do to 'fix the error' and make GZDoom work. Instead of simply,
> Unsupported OpenGL version.
At least OpenGL 3.3 is required to run GZDoom.

try something intuitive, like:
> Unsupported OpenGL version.
At least OpenGL 3.3 is required to run GZDoom.
In the launch box, try a different renderer under "Video settings" like OpenGL ES and see if that fixes the problem.

The icing on the cake would be, in the 'IWAD selection box', relabeling "OpenGL ES" to "OpenGL ES (for older PCs)".

### Describe alternatives you've considered

An alternative would be to, if GZDoom fails to launch due to incompatible OpenGL version (or some other incompatibility), automatically relaunch with a different renderer other than the one selected, try a third one if the second time fails, and if one of the alternates results in a successful launch, make that the default instead.

The good thing about this fix is that it gives a lifeline for people where a version of GZDoom with a compatible OpenGL/Vulkan gets updated to a version with an incompatible one, but the INI in "My Games" still points to the now-incompatible renderer (I've crossed this threshold a couple of times on older laptops where I went from the latest version of GZDoom working to the next version not working). If those users are locked into a situation where the 'IWAD selection box' has been turned off, instead of getting put into a Catch-22 where GZDoom fails to start, they'll get sent a lifeline. Maybe here include a pop-up saying that the render was changed.

A third alternative would be to just make OpenGL ES the default. It's the simplest fix, but it doesn't do anything to address the other underlying issues.

**Comment by coelckers** [comment]
This should resolve itself once we split up the release for 5.0.
