### ISSUE TITLE
[BUG] Since GZDoom g4.0.0, Bloodbath text string replacements no longer work.

### ISSUE THREAD

**Issue by Acts19quiz** [ZDoom/gzdoom#1817]
### GZDoom version

GZDoom 4.9.0

### Which game are you running with GZDoom?

Doom

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

Windows 10 x64 LTSC 21H2

### Relevant hardware info

Intel 6700k, NVIDIA GeForce 980Ti

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Since GZDoom g4.0.0, [Bloodbath](https://zdoom.org/wiki/Bloodbath_announcer) (netgame option) text string replacement haven't worked, either in the pre-g4.#.# LANGUAGE lump, or included in the new CSV format. The last versions they worked in were the g3-series, including g3.7.1 and g3.8.2_legacy. Bloodbath strings are still **_present_** in g4.#.# (including g4.9.0), and they work just fine for vanilla play. They just can't be **_replaced_**.

Bloodbath text string replacements are important, as one might would want to make a mod (or for that matter, independent game) for modern GZDoom, and not have the violent (and not to mention vulgar) Blooodbath text strings present. However unlikely, it is certainly within the realm of possibility that one could arrange a net game with this new mod or game, and somewhere online get wind of the cl_bbannounce CVAR. Them boom, your family game turned into Kill Bill.

An independent game could have the source code edited, though that's an extra complication, and this option doesn't work for mods.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Make Bloodbath text string replacements. It doesn't matter if it's in the pre-g4.#.# LANGUAGE format, or if the language keys are transplanted into a g4.#.#-style CSV format.
2. Load one of the Bloodbath text replacement PK3s. Try both for full illustration.
3. Make extra sure you're enabling the Bloodbath text strings for netplay! (covered below)
4. Start a net deathmatch game. You can use [ZDL](https://zdoom.org/wiki/ZDL), or as a quick launch sequence, "+cl_bbannounce 1 -host 1 -deathmatch".
5. If necessary, get some bots in (like [ZCajun](https://github.com/ZDoom/gzdoom/files/10016764/zcajun.zip)). +addbot in the console works for this.
6. Start the fragging, or wait for it to happen--the text strings will be the original Bloodbath ones.

[Test files have been included](https://github.com/ZDoom/gzdoom/files/10016768/Bloodbath_test.zip) to assist with reproduction. One has CSV Bloodbath text string replacements, and the other has LANGUAGE format. Note that neither one will work with GZDoom g4.#.# (including g4.9.0). In fact, by default, GZDoom's language.csv doesn't even include the text rows for them! The CSV provided makes them from scratch.

Both text files have, as sample text, replacement strings for HUSTR_E1M1 in order to illustrate replacement text is working (and what version, if CSV or LANGUAGE). Try both in GZDoom 4.#.#. Neither PK3 will correctly replace Bloodbath strings (though the automap should confirm with either file that replacement strings **_are_** being read). Then try the LANGUAGE PK3 with a version of GZDoom before g4.#.#, like a g3-era release. The Bloodbath replacements will work.

To get things rolling, you will also probably want some bots to fight or to start fighting each other, like ZDoom's old [ZCajun bots](https://github.com/ZDoom/gzdoom/files/10016764/zcajun.zip) (that still work with GZDoom!).

**Comment by coelckers** [comment]
The texts are still there, but the labels were renamed in 4.0.0.

`
static const SoundAndString WorldKillSounds[] =
{
	{ "TXT_SELFOBIT1",	"VO7.SFX" },		// Excrement
	{ "TXT_SELFOBIT2",	"VO8.SFX" },		// Hamburger
	{ "TXT_SELFOBIT3",	"VO9.SFX" },		// Scrotum separation
};

static const SoundAndString SuicideSounds[] =
{
	{ "TXT_SELFOBIT5",	"VO13.SFX" },		// Unassisted death
	{ "TXT_SELFOBIT5",	"VO5.SFX" },		// Kevorkian approves
	{ "TXT_SELFOBIT4",	"VO12.SFX" },		// Population control
	{ "TXT_SELFOBIT6",	"VO16.SFX" }		// Darwin award
};

static const SoundAndString KillSounds[] =
{
	{ "TXT_OBITUARY1",	"BONED.SFX" },		// Boned
	{ "TXT_OBITUARY3",	"CREAMED.SFX" },	// Creamed
	{ "TXT_OBITUARY4",	"DECIMAT.SFX" },	// Decimated
	{ "TXT_OBITUARY5",	"DESTRO.SFX" },		// Destroyed
	{ "TXT_OBITUARY6",	"DICED.SFX" },		// Diced
	{ "TXT_OBITUARY7",	"DISEMBO.SFX" },	// Disembowled
	{ "TXT_OBITUARY8",	"FLATTE.SFX" },		// Flattened
	{ "TXT_OBITUARY9",	"JUSTICE.SFX" },	// Justice
	{ "TXT_OBITUARY10",	"MADNESS.SFX" },	// Madness
	{ "TXT_OBITUARY11",	"KILLED.SFX" },		// Killed
	{ "TXT_OBITUARY12",	"MINCMEAT.SFX" },	// Mincemeat
	{ "TXT_OBITUARY13",	"MASSACR.SFX" },	// Massacred
	{ "TXT_OBITUARY14",	"MUTILA.SFX" },		// Mutilated
	{ "TXT_OBITUARY15",	"REAMED.SFX" },		// Reamed
	{ "TXT_OBITUARY16",	"RIPPED.SFX" },		// Ripped
	{ "TXT_OBITUARY17",	"SLAUGHT.SFX" },	// Slaughtered
	{ "TXT_OBITUARY18",	"SMASHED.SFX" },	// Smashed
	{ "TXT_OBITUARY19",	"SODOMIZ.SFX" },	// Sodomized
	{ "TXT_OBITUARY20",	"SPLATT.SFX" },		// Splattered
	{ "TXT_OBITUARY21",	"SQUASH.SFX" },		// Squashed
	{ "TXT_OBITUARY22",	"THROTTL.SFX" },	// Throttled
	{ "TXT_OBITUARY23",	"WASTED.SFX" },		// Wasted
	{ "TXT_OBITUARY24",	"VO10.SFX" },		// Body bagged
	{ "TXT_OBITUARY28",	"VO25.SFX" },		// Hosed
	{ "TXT_OBITUARY26",	"VO27.SFX" },		// Toasted
	{ "TXT_OBITUARY25",	"VO28.SFX" },		// Sent to hell
	{ "TXT_OBITUARY29",	"VO35.SFX" },		// Sprayed
	{ "TXT_OBITUARY30",	"VO36.SFX" },		// Dog meat
	{ "TXT_OBITUARY31",	"VO39.SFX" },		// Beaten like a cur
	{ "TXT_OBITUARY27",	"VO41.SFX" },		// Snuffed
	{ "TXT_OBITUARY2",	"CASTRA.SFX" },		// Castrated
};
`

**Comment by Acts19quiz** [comment]
Thank you for the clarification. Wondering why the updated GZDoom was breaking my mod was driving me up a wall.
