### ISSUE TITLE
[BUG] GLES IQM models distorted in complex scenes

### ISSUE THREAD

**Issue by MrRaveYard** [ZDoom/gzdoom#1820]
### GZDoom version

commit: 29b4418c3a6b85a775e476b0ece470a2d430b43c

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

GLES renderer shows distorted IQM bones in complex scenes. My guess is that it's hitting a limit of some kind.

![image](https://user-images.githubusercontent.com/29225776/202520818-52f69a6a-1bbe-41c1-8dac-a709bb091361.png)
![image](https://user-images.githubusercontent.com/29225776/202520849-6ad9db59-dc28-4b97-b423-a1aacf28b29b.png)

### Steps to reproduce the behaviour.

How to reproduce:

Run Nash's IQM example with GLES backend: https://forum.zdoom.org/viewtopic.php?t=76766

1. console command `summon monke`
2. repeat until something starts glitching out

Alternatively, run it as: `gzdoom.exe -file IQMTest.pk3 +gles_max_lights_per_surface 4`
The last parameter makes it easier to reproduce the glitch because the gles_max_lights_per_surface happens to determine size of some kind of bone array in the shader, which is kinda sus.

**Comment by coelckers** [comment]
Too bad, but with the GLES backend soon to become a legacy feature it's off the book for the main developers here. Sorry.
