### ISSUE TITLE
Abort in debug-enabled build upon loading KDiZD v1.2's Z1M10

### ISSUE THREAD

**Issue by NY00123** [ZDoom/gzdoom#1823]
### GZDoom version

g4.10pre-52-g0f7e7744b

### Which game are you running with GZDoom?

Doom

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Ubuntu 20.04.5

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I'm not actually sure this is a proper bug, and if it's a problem in GZDoom, the map or both.

It's only reproduced in a debug-enabled build, due to a failed assert at src/maploader/maploader.cpp:522:

`seg->PartnerSeg = partner == 0xffffffffu? nullptr : &Level->segs[partner];`

The problem is that the value of `partner` is 28342072, but according to the assert, the array has 129414 elements.
Since there isn't a direct memory dereference here, this might not be observable as a bug in a build without asserts.

The first commit exposing this might (or might not) be b9ac44e8f21a8c751b53aad7f41a44045e9bdc9e.

### Steps to reproduce the behaviour.

Use the Ultimate Doom's IWAD with kdizd_12.pk3 (24851052 bytes long, md5 f6f56f2a45e8cc743e313b8288959a32) and try loading Z1M10:

`gzdoom -iwad /path/to/DOOM.WAD  -file /path/to/kdizd_12.pk3 +map Z1M10`

### Your configuration

```ini
Reproducible with no gzdoom.ini file present.
```

**Comment by coelckers** [comment]
Addressed in ea51c92fda93dedfd36e60a3ab2504e10aa9a80f
This OOB access is now being checked for and will trigger a node rebuild.
