### ISSUE TITLE
Unable to retrieve known folder.

### ISSUE THREAD

**Issue by FrogMaster-jpg** [ZDoom/gzdoom#1824]
Hello everyone! 

I was upgrading my GZDoom files from version [4.8.2](https://github.com/ZDoom/gzdoom/releases/tag/g4.8.2) to [4.9.0](https://github.com/ZDoom/gzdoom/releases/tag/g4.9.0), but I keep receiving the following error message. All I did was replace the files with the new versions. Is there something additional that needs to be configured for this version? 

![image](https://user-images.githubusercontent.com/60360142/202763475-9f29ed56-b1b9-41d6-a03e-2ab639b437eb.png)

As a heads up, 4.8.2 starts up with no issues: 

![image](https://user-images.githubusercontent.com/60360142/202763875-fddf2393-427b-424c-8a37-5e19e2677ccb.png)

**Comment by FrogMaster-jpg** [comment]
Actually, I resolved the issue. I needed to use GZDoom_portable.ini, as mentioned in instructions for version 4.9.0. Thank you. 🙂

**Comment by madame-rachelle** [comment]
That message should never appear unless there's a critical issue with the operating system.

It's a failure of the "SHGetKnownFolderPath" function. I would look into this, were I you, and ensure your Windows files are intact and that there is no malware on your system.
