### ISSUE TITLE
[Feature] Customizable and breakable mirrors

### ISSUE THREAD

**Issue by UnizoneDev** [ZDoom/gzdoom#1825]
### GZDoom version

GZDoom 4.9.0

### Which game are you running with GZDoom?

Other

### What Operating System are you using?

Windows 10

### Is your feature request related to a problem? Please describe.

The Line_Mirror special is rather great to have, but I'm looking forward to it being more editable.

### Describe the solution you'd like

Since there is an environment mirror texture, I was wondering if the Line_Mirror special could have an argument so that a different environment map could be used. And perhaps the action special could also have a choice to make the mirror unbreakable, or breakable after being hit with a weapon of some kind à la Duke Nukem 3D.

**Comment by coelckers** [comment]
Making the mirror brekable is clearly DIY. That can easily be done in ACS with existing engine features.

**Comment by UnizoneDev** [comment]
> Making the mirror brekable is clearly DIY. That can easily be done in ACS with existing engine features.

True, but I was looking forward to having it disable the mirror reflection when broken, rather than the other ways.

**Comment by coelckers** [comment]
Like I said, that is what ACS is there for.
