### ISSUE TITLE
Portable INI file remains as is after first launch if IWADs couldn't be found

### ISSUE THREAD

**Issue by Blue-Shadow** [ZDoom/gzdoom#1826]
Let's assume you want to use a portable installation. What you're supposed to do is create an empty file named gzdoom_portable.ini and put it where GZDoom is installed. Let's also assume that the IWADs aren't in locations where they can be automatically detected by GZDoom. If you run GZDoom, you'll get the "IWADs couldn't be found" window. After you close the window, the INI file will still be as it was before running GZDoom (empty, in this case), meaning there isn't anything to edit in order to add the path to where the IWADs are.

In the case of non-portable installations, GZDoom created (and still does as of 4.9.0) the INI file with a few sections already in it, including the [IWADSearch.Directories] section, so one can add the path to the IWADs.

**Comment by CandiceJoy** [comment]
I believe it only generates defaults if the file doesn't exist, which of course it can't for portable because the config is gzdoom.ini in the user's application data directory.  BUT, if you use -config "gzdoom-portable.ini",  it will generate the defaults for you.
