### ISSUE TITLE
[BUG] Sounds intermittently broken with recent sound code changes

### ISSUE THREAD

**Issue by SanyaWaffles** [ZDoom/gzdoom#1842]
### GZDoom version

GZDoom git 58a64e4

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 11

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

As of the commit [58a64e4](https://github.com/ZDoom/gzdoom/commit/58a64e4f5d26ef2dcd97726b51d1cf1624bfeeaf) GZDoom tends to not play most sounds. I am building these builds in Release mode, dunno if that plays a role.

I was able to reproduce this in vanilla using DOOM2.WAD with no mods. Some of the menu sounds were broken (specifically the 'activate' pistol sound) and the zombiemen in MAP01 were not playing their death screams at all.

This also does it with other projects and mods in GZDoom, but I isolated it to stock DOOM2.WAD to be sure.

### Steps to reproduce the behaviour.

1. Fire up Doom2.wad
2. Use menus to start the game. Note the bugged, missing sounds.
3. Shoot the zombiemen in MAP01 and note their bugged sounds.

**Comment by coelckers** [comment]
fixed in 473221bb339944ff9205e29a6a958d4c2c52e945
The bug is old, but the function was only used in the sound precaching code before where the problem only resulted in some sounds not being cached.
