### ISSUE TITLE
[BUG] Pull Request #1836 Breaks custom game menus

### ISSUE THREAD

**Issue by SanyaWaffles** [ZDoom/gzdoom#1855]
### GZDoom version

gzdoom git version dccd9ad2ec8095607c9296c5efa67a72e

### Which game are you running with GZDoom?

Other

### What Operating System are you using?

Windows 11

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The recent pull request [to make it so certain text in menus was not localized](https://github.com/ZDoom/gzdoom/pull/1836) (... I think that's what it's supposed to do? I'm not exactly sure what it's supposed to do.) seems to have broken custom menus entirely in Project Absentia:

![image](https://user-images.githubusercontent.com/1550098/205475988-d52fc5dc-6f5a-4caf-8f93-59237ba91f47.png)

DOOM 2 however doesn't do this.

![image](https://user-images.githubusercontent.com/1550098/205476026-f1a4ce7b-c9eb-43f8-ab0f-0af1bfd33ce6.png)

I've yet to find a way to make a minimal example due to the size of Project Absentia, but nothing exactly stands out in the MENUDEF scripts for PA. The only difference I can think of is PA doesn't use patch graphics at all for any of the menu labels.

I've tried this with vanilla git builds of GZDoom to rule out some fudged git merge on our in-house fork and the problem exists in vanilla. Reverting the PR in question fixes it.

If it helps, I am compiling with VS2022.

**Comment by madame-rachelle** [comment]
Effect is easily observed on Heretic.

**Comment by coelckers** [comment]
Ok then, I reverted this. If it completely changes how menus work the thing is not usable. Period.

TBH, I'm a bit puzzled that this was even submitted - the titles in option menus were also broken.

**Comment by Gutawer** [comment]
> The recent pull request to make it so certain text in menus was not localized (... I think that's what it's supposed to do? I'm not exactly sure what it's supposed to do.)

The pull request was only supposed be in effect for things like text boxes, I'm honestly not at all sure how I missed this breaking other things in the week or so I've been running with the PR active. I'll submit a fixed version relatively soon, sorry about this!
