### ISSUE TITLE
[Feature]  Vulkan Ray tracing support ?

### ISSUE THREAD

**Issue by SpidFightFR** [ZDoom/gzdoom#1856]
### GZDoom version

GZDoom g4.9.0-m

### Which game are you running with GZDoom?

Doom

### What Operating System are you using?

Linux x86_64

### Relevant hardware info

R5 2600, GTX 1060, 16GB RAM DDR4

### Is your feature request related to a problem? Please describe.

Recently, a rtx port of DOOM was released (using [prboom](https://github.com/sultim-t/prboom-plus-rt) ) and i was wondering if it was possible to do the same but with vulkan ray tracing. If possible, FSR could be added to the game too ?

**Comment by coelckers** [comment]
Some sort of raytracing will eventually come, but never - ever - like this port. It's wrong on virtually all accounts
