### ISSUE TITLE
[BUG] Custom STARTUP lumps are ignored sometimes

### ISSUE THREAD

**Issue by OrdinaryMagician** [ZDoom/gzdoom#1864]
### GZDoom version

4.10.0

### Which game are you running with GZDoom?

Hexen

### What Operating System are you using?

Linux x86_64

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

STARTUP lump in specific mods is ignored when playing Hexen.

Simple example here: [teststartup.zip](https://github.com/ZDoom/gzdoom/files/10157015/teststartup.zip)

I've noticed that the bug doesn't happen if a mod is loaded as a folder, rather than as an archive, so there's that.

### Steps to reproduce the behaviour.

1. Load the mod with Hexen
2. The startup screen will still show the vanilla picture, though the notch graphic is changed
3. Load the mod with Doom or Heretic
4. The startup screen will be replaced, as expected

**Comment by OrdinaryMagician** [comment]
May be user error, as moving all images to the graphics directory fixes the issue.

**Comment by coelckers** [comment]
That demo file works fine for me and the code already checks both namespaces.
