### ISSUE TITLE
[BUG] vanilla donut handling does not work with ZMAPINFO compat_floormove

### ISSUE THREAD

**Issue by andrikpowell** [ZDoom/gzdoom#1872]
### GZDoom version

GZDoom 4.10.0

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 11

### Please describe your specific OS version

Windows 11 Home

### Relevant hardware info

Intel i9-9900k, Geforce RTX 3080

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

In the GZDoom update 4.9.0, in the details, it had this line: "vanilla donut handling to compat_floormove".

This is incorrect, well sorta. GZDoom will only use vanilla donut handling if "compat_floormove" is turned on in the compatibility settings or if "Doom (Strict)" compatibility settings are toggled.

But if I include "compat_floormove = 1" in ZMAPINFO, the fix will not be applied.
This makes using ZMAPINFO to force compatibility not that useful if you use this vanilla donut behaviour.

### Steps to reproduce the behaviour.

1. Download [200 Line Massacre](https://drive.google.com/file/d/12t1lQHhf4cvPkl4iRZ8QI3vTLKGeMTN_/view?usp=share_link) WAD
2. Open **200lnm.wad** in GZDoom 4.10.0, open console and type "map map35"
3. Make sure your compatibly setting are set to "Default"
4. Progress through the map (less than a minute), once you press a switch on a pillar, the blood sector in the middle will instantly raise up, but the sector surrounding the player will not lower as intended (Vanilla Donut Handling).
5. If you try pressing the same switch with "Doom (Strict)"compatibility set or just the manual setting "Map/Action behavior -> Use Doom's floor motion behavior" set to yes, the outer walls will lower as intended.

It's worth noting that the WAD's ZMAPINFO includes "Compat_floormove = 1" in both the "defaultmap" and specific MAP35 "map" section.

**Comment by coelckers** [comment]
fixed in d596e5a8fab1bda6d207b363c427e95c45e2d186
