### ISSUE TITLE
Save folder

### ISSUE THREAD

**Issue by Somie98** [ZDoom/gzdoom#1879]
Hello man where the save location and folder in GZDOOM 4.10 ???

**Comment by mjr4077au** [comment]
`Documents\My Games\GZDoom`

**Comment by Somie98** [comment]
I just check but don't have a save folder like GZDOOM 4.8.2 ???

**Comment by coelckers** [comment]
It is now in the place the system deems proper:

{Your user folder}\Documents\My Games\GZDoom

If you want it to remain in your installation folder read the first paragraph here: https://forum.zdoom.org/viewtopic.php?t=76741
