### ISSUE TITLE
[QUESTION] Nightmare difficulty font for other languages doesn't apply?

### ISSUE THREAD

**Issue by Blueberryy** [ZDoom/gzdoom#1882]
I noticed that GZDoom has Google Sheet character support of fonts, but there's no font that used in "Nightmare!" difficulty text.
![gzdoom_1kKe5uK7Q6](https://user-images.githubusercontent.com/36592509/207950135-b637f4e6-e123-4b03-8ee9-e6c3e9a33169.png)
**Russian language**:
![gzdoom_wv5D7FUGMN](https://user-images.githubusercontent.com/36592509/207950644-dbe470de-6d93-421f-ae20-88a887baa175.png)

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

**Comment by madame-rachelle** [comment]
This is not as easy as it seems at first glance. In order for this to work it would require making glyph symbols for that special font, in all languages with all letters, and considering its extremely limited use that was deemed as just not worth it.

*However* - that being said - if someone is willing to make multilingual glyphs for those letters (including latin, greek, cyrillic, etc) I am certain that we'd be happy to include them and possibly including the code to do a font change for this.

**Comment by Blueberryy** [comment]
> This is not as easy as it seems at first glance. In order for this to work it would require making glyph symbols for that special font, in all languages with all letters, and considering its extremely limited use that was deemed as just not worth it.
> 
> _However_ - that being said - if someone is willing to make multilingual glyphs for those letters (including latin, greek, cyrillic, etc) I am certain that we'd be happy to include them and possibly including the code to do a font change for this.

Can you send link to it's font files? I would like to take a look at this font

**Comment by coelckers** [comment]
There is no font. That "Nightmare" writing is a single graphic - those 9 letters and the exclamation mark is all we got.

**Comment by mc776** [comment]
Would it be possible to do some kind of post-processing melt effect on the phrase so it works without a whole new font?

**Comment by coelckers** [comment]
Some good news. I remembered that there had been some discussion in the past about this when the translation was started.
Here's a sheet with all standard Latin characters for such a font. Obviously that is hardly enough to work with as it needs all accented characters plus Cyrillic done first, but it'd be a start for anyone interested. But please note: Doing it just for Russian is not enough - we'd need the full set as laid out here (all marked green) for Doom's BigFont. That's a lot of work.

https://forum.zdoom.org/viewtopic.php?p=1092702#p1092702

If you can find someone willing to bring this font in shape we might continue, but please also read my follow up posts why I ultimately don't think this is such a good idea.

**Comment by Blueberryy** [comment]
> Some good news. I remembered that there had been some discussion in the past about this when the translation was started.
> Here's a sheet with all standard Latin characters for such a font. Obviously that is hardly enough to work with as it needs all accented characters plus Cyrillic done first, but it'd be a start for anyone interested. But please note: Doing it just for Russian is not enough - we'd need the full set as laid out here (all marked green) for Doom's BigFont. That's a lot of work.
> 
> https://forum.zdoom.org/viewtopic.php?p=1092702#p1092702
> 
> If you can find someone willing to bring this font in shape we might continue, but please also read my follow up posts why I ultimately don't think this is such a good idea.
> 

Thanks for the info. I think someone should hire some artist to do all this. Closing this issue now
