### ISSUE TITLE
[Feature] Option to disable view bobbing while fly console command is enabled

### ISSUE THREAD

**Issue by OrdinaryVanity** [ZDoom/gzdoom#1883]
### GZDoom version

4.10.0

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 11

### Relevant hardware info

Ryzen 7 5800X, Sapphire Nitro+ 6900XT, 16GB DDR4

### Is your feature request related to a problem? Please describe.

Using `fly` to take screenshots in-game can be tricky because of view bobbing.

### Describe the solution you'd like

Maybe a flag or a CVar to enable/control the amount of bobbing?

### Describe alternatives you've considered

Look around in the 3D editor of UDB. Same kind of functionality would be perfect for taking screenshots in-game.

### Add any other context or screenshots about the feature request here.

Have fun @CandiceJoy!

**Comment by CandiceJoy** [comment]
Yep, I'll see what I can do with this and pass it on to someone else if I can't manage it :)

**Comment by madame-rachelle** [comment]
This has been added.

**Comment by OrdinaryVanity** [comment]
Awesome! Hopefully it wasn't too much of a hassle.
