### ISSUE TITLE
[BUG] Crash on loading actor definitions

### ISSUE THREAD

**Issue by cyberc001** [ZDoom/gzdoom#1885]
### GZDoom version

Git version

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Manjaro Linux 22.0.0

### Relevant hardware info

CPU: AMD Ryzen 3 4300GE, GPU: NVIDIA GeForce GTX 950

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When attempting to launch gzdoom while loading certain mods, it outright crashes.
Console output:
```
[cyb3rc001@cyb3rc001 ~]$ gzdoom ~/Downloads/hd-4.10.0a.pk7
GZDoom g4.11pre-11-ga0cd1ba04 - 2022-12-17 01:23:22 -0500 - SDL version
Compiled on Dec 17 2022

OS: Manjaro Linux, Linux 5.15.78-1-MANJARO on x86_64
GZDoom version g4.11pre-11-ga0cd1ba04
W_Init: Init WADfiles.
 adding /home/cyb3rc001/.config/gzdoom/gzdoom.pk3, 672 lumps
 adding /home/cyb3rc001/.config/gzdoom/game_support.pk3, 2558 lumps
 adding /home/cyb3rc001/.config/gzdoom/DOOM2.WAD, 2956 lumps
 adding /home/cyb3rc001/.config/gzdoom/game_widescreen_gfx.pk3, 214 lumps
 adding /home/cyb3rc001/Downloads/hd-4.10.0a.pk7, 723 lumps
S_Init: Setting up sound.
I_InitSound: Initializing OpenAL
  Opened device Family 17h/19h HD Audio Controller Analog Stereo
  EFX enabled
I_Init: Setting up machine state.
CPU Vendor ID: AuthenticAMD
  Name: AMD Ryzen 3 4300GE with Radeon Graphics
  Family 23 (23), Model 96, Stepping 1
  Features: SSE2 SSE3 SSSE3 SSE4.1 SSE4.2 AVX AVX2 F16C FMA3 BMI1 BMI2 HyperThreading
V_Init: allocate screen.
ST_Init: Init startup screen.
Checking cmd-line parameters...
S_InitData: Load sound definitions.
G_ParseMapInfo: Load map definitions.
Texman.Init: Init texture manager.
ParseTeamInfo: Load team definitions.
LoadActors: Load actor definitions.
gzdoom: /home/cyb3rc001/build/gzdoom/src/common/scripting/backend/codegen.cpp:2603: virtual ExpEmit FxAssignSelf::Emit(VMFunctionBuilder*): Assertion `ValueType == Assignment->ValueType' failed.
Aborted (core dumped)
```
This appears not to be related to a particular mod, since it happens with several mods.
It also rarely happens when loading into a new map in a completely vanilla game (for example, when transitioning from E3M1 to E3M2 in Heretic).

### Steps to reproduce the behaviour.

1. Download any mod that causes the issue (https://codeberg.org/attachments/46e7b98a-bfae-4a67-ab45-ccc583697ace or https://gitlab.com/accensi/deathstrider/-/archive/master/deathstrider-master.zip)
2. Run gzdoom with this mod loaded.
3. It should immediately crash after selecting an IWAD and clicking the "Play Game!" button.

### Your configuration

```ini
https://gist.github.com/cyberc001/229c1739ea6adfd9f359a370f9196e4c
```

**Comment by cyberc001** [comment]
> I cannot reproduce this issue, but I suspect the mods are at fault. Note that the error is from the vm and is "Assertion `ValueType == Assignment->ValueType' failed." To me, this implies that a mod is trying to assign a variable a value of the wrong type.

As I mentioned above, it happens without mods aswell, but it's a much rare occurance.
Also, are you implying that mods causing a hard crash (not a VM abort) is an intended behavior? Considering that it doesn't happen on Windows, as far as I am aware.

**Comment by CandiceJoy** [comment]
No, clearly, it should VM abort.  But without being able to reproduce it, I can't throw a debugger on it to get a proper stack trace :P

**Comment by coelckers** [comment]
Assert removed in d001c3464d22d5d65845b7bfb5367bc719418bb2
