### ISSUE TITLE
Omission in UDMF ZDoom Spec

### ISSUE THREAD

**Issue by kraflab** [ZDoom/gzdoom#1905]
https://github.com/ZDoom/gzdoom/blob/master/specs/udmf_zdoom.txt

Version 1.32 mentions the blocklandmonsters flag:
```
1.32 28.06.2021
Blocklandmonsters MBF21 flag
```

But it doesn't appear to be documented in the specification itself.

By the way, the spec header still says `v1.15 - 14.12.2010`.

**Comment by kraflab** [comment]
Another note on the spec, there are both `<int>` and `<integer>` fields.

**Comment by coelckers** [comment]
fixed in e522260037fdcc5924f825a6153046b08f666403
There's probably more stuff missing here.
