### ISSUE TITLE
[Feature] Disable sliding up walls in water without disabling all wall sliding

### ISSUE THREAD

**Issue by OrdinaryMagician** [ZDoom/gzdoom#1906]
### GZDoom version

4.10.0

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Linux x86_64

### Is your feature request related to a problem? Please describe.

Currently, the behavior where players automatically get pushed upwards when they run into a wall and are not fully submerged cannot be disabled without entirely getting rid of all forms of sliding against walls/actors _(that is, removing the `SLIDESONWALLS` flag from the player)_. If one were to design a custom player incapable of swimming _(i.e.: a player that walks underwater)_, this would cause issues where they'd have the ability to still float, rather than sink, as long as they kept pushing against a wall.

### Describe the solution you'd like

Possibly some virtual function to override this behavior, as adding a specific flag for just this might be excessive.

### Describe alternatives you've considered

Simply not ever implementing a custom player incapable of swimming _(which isn't what I want)_.

**Comment by coelckers** [comment]
Got just PR'd in.
