### ISSUE TITLE
[Feature][elf/linux] c++/libgcc ABI issues

### ISSUE THREAD

**Issue by sylware** [ZDoom/gzdoom#1912]
### GZDoom version

selaco game version (steam)

### Which game are you running with GZDoom?

Other

### What Operating System are you using?

Linux x86_64

### Relevant hardware info

AMD Zen2+RX 5600XT(6GB)

### Is your feature request related to a problem? Please describe.

c++(mostly) and libgcc ABI issues on elf/linux.

### Describe the solution you'd like

For gcc/clang toolchains, add the "-static-libstdc++" and "-static-libgcc" compile and link options.

It will zap all c++ and libgcc ABI issues for good.

To think about: all system (symbol/version)s should be libdl-ed(dlopen/dlsym/dlclose) (probably the same on other OSes).

### Describe alternatives you've considered

fire all c++ gcc devs.

**Comment by madame-rachelle** [comment]
Definitely worth trying - but this has to be done carefully and very conservatively, making sure to target very specific build setups (i.e. Release only) and doing it in such a way that it does not affect Mac OS compilation. (Static libc libraries are not available in the XCode SDK)

**Comment by OrdinaryMagician** [comment]
> fire all c++ gcc devs.

I wholly understand your frustration.

**Comment by sylware** [comment]
Indeed, the idea is to make those options defaults for release build on elf/linux for the gcc toolchain.

Off-topic but colateral, since the genius es which are c++ gcc devs have not added a libdl mode to their static library, maybe in the documentation, in elf/linux section, to put forward the fact that game binaries need linking with _really_ old glibc libs, that to avoid to being "hard linked" to recent symbol/modules versions (which is by default and not disable-able in binutils).

Yes, game binaries on elf/linux platform should libdl(dlopen/dlsym/dlclose) 100% of their system symbols/modules(shared libs). But thx to those "geniuses", it is unreasonable to do properly, only mitigation is reasonably possible with linking with a _really_ old glibc. In the end, game binaries should be pure and simple (the least amount of relocation types) ELF64 binaries (no C/c++ main(), but the sysv ABI entry, which is a "main" anyway).

That said, it should be the same on other OSes.

We can set in ice the set of module/symbol versions with glibc 2.17 as it is with those versions AAA vulkan games were build for elf/linux (shadow of the tomb raider/metro exodus).

A  "readelf" audit should hely to spot everything which is wrong.

GODOT does something like this and they go even further with "old glibc" containers to generate builds (and to avoid GNU symbol/module versioning planned obsolescence).

**Comment by sylware** [comment]
We got worse: a genius from the glibc devs did add a new version to the libc_start_main symbol which is in the libc shared object in glibc 2.34.

It means any executable linked with a glibc 2.34 will refuse to load on a system with a glibc <2.34.

Can we fire all glibc devs with the c++ gcc devs?

**Comment by coelckers** [comment]
I understand your problem but the ones responsible for this mess sit elsewhere, and if we alter our project some of their disciples will come here whining why we're violating the Holy Ways of Linux Software Distribution.

It's a lose-lose situation, IMO you should use either Flatpak or AppImage if you want stable and reliable Linux builds because we will never be able to convince people that how they handle things is wrong and do their best to make it harder for us.
