### ISSUE TITLE
ARM64 Windows Release Build No Mod Sound [Fix] 

### ISSUE THREAD

**Issue by smb123w64gb** [ZDoom/gzdoom#1918]
### GZDoom version

4.10.0

### Which game are you running with GZDoom?

Doom

### What Operating System are you using?

Windows 11

### Please describe your specific OS version

Windows 11 ARM64

### Relevant hardware info

Qualcomm 8cx Gen 2

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Make sure that ARM64 Builds have libsndfile-1 not sndfile dll. If you dont rename sndfile any mods that have audio involve will be mute.

**Comment by madame-rachelle** [comment]
Are you sure you are experiencing this problem on 4.10.0? I just tested the binary myself on a fresh VM running from UTM on my iMac, and it works perfectly fine, I get both music and sound.

**Comment by CandiceJoy** [comment]
@madame-rachelle I can confirm that this is an issue and that renaming the file fixes it.  Given that it's expecting a linux-style filename instead of a windows one, i suspect it's something in cmake or the CI/build that's genning something for the wrong arch.  I'll look into it and let you know if I find anything <3

**Comment by CandiceJoy** [comment]
When building, we need to include ENABLE_COMPATIBLE_LIBSNDFILE_NAME as per https://github.com/libsndfile/libsndfile/commit/61c416219c62b6ce642312ae6d2c06bcb1cd5d99

If we already do that, then I guess someone will need to fix in libsndfile and make a PR :)

**Comment by madame-rachelle** [comment]
Yeah looks like I fucked this one up, gonna rebuild from scratch.
