### ISSUE TITLE
[Debian/Ubuntu/Pop!_OS] Configuring SSGL to work with GZdoom, can't find binary.

### ISSUE THREAD

**Issue by aknight2015** [ZDoom/gzdoom#1919]
### GZDoom version

GZDoom 4.10.0

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Pop!_OS

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

In order to get SSGL to work with any source port I have to point it to the binary file. Where is the binary file located as it's not in ~./bin
![Screenshot from 2023-01-06 20-26-09](https://user-images.githubusercontent.com/47067592/211125001-4ef2e79b-c26c-49ad-9d1c-2c13f67684b3.png)
 
As you can see GZDoom isn't there.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. sudo apt install gzdoom
2. Run the SSGL AppImage
3. Add Sourceport
4. Try to find the binary.

**Comment by alexey-lysiuk** [comment]
Do `which gzdoom` in Terminal to output absolute path to executable.
