### ISSUE TITLE
[BUG] checkswitchrange fails if multiple switch textures are on one sidedef

### ISSUE THREAD

**Issue by kraflab** [ZDoom/gzdoom#1921]
### GZDoom version

GZDoom 4.10.0

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

If there are multiple switch textures on one sidedef (for instance, a top texture and a bottom texture), the `checkswitchrange` flag causes the top-most texture to be treated as the only switch.

`P_CheckSwitchRange` only checks the first switch texture it finds and then returns.

### Steps to reproduce the behaviour.

See the attached wad. You can press the switch from the top of the stairs, but the switch on the bottom cannot be pressed.

[switchheight.zip](https://github.com/ZDoom/gzdoom/files/10367093/switchheight.zip)

**Comment by coelckers** [comment]
fixed in ef79ec193f5335de0ef451ed73dcde6e8c500e7e
