### ISSUE TITLE
[BUG] doublebind is always invoked when automap is displayed

### ISSUE THREAD

**Issue by oncipriani** [ZDoom/gzdoom#1933]
### GZDoom version

4.10.0

### Which game are you running with GZDoom?

Hexen

### What Operating System are you using?

Windows 11

### Please describe your specific OS version

Windows 11 Pro

### Relevant hardware info

Xbox controller

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I binded `Pad_B` to `+speed` and double-binded it to `use ArtiBlastRadius`. It works perfectly during normal gameplay, but pressing B when the automap is displayed (just a simple press) uses a Disc of Repulsion.

### Steps to reproduce the behaviour.

How to reproduce:

1. Double-bind a button on the controller to some action;
2. Make sure the automap is open (`DPadUp` or `Tab` by default);
3. Press the button you double-binded while the automap is open.

### Your configuration

```ini
[Hexen.Bindings]
Pad_B=+speed

[Hexen.DoubleBindings]
Pad_B=use ArtiBlastRadius
```

**Comment by coelckers** [comment]
fixed in b082c5050261cc215b641269013cd5c6b841950f
