### ISSUE TITLE
[BUG] optimized sheet font scrambles text in BoA

### ISSUE THREAD

**Issue by x3003** [ZDoom/gzdoom#1937]
### GZDoom version

gzdoom-x64-g4.11pre-41-g9777cfd50

### Which game are you running with GZDoom?

Other

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

windows 10 home

### Relevant hardware info

amd r5. gtx 1060

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

In Blade of Agony when you come to a paper w/ text, like here in c2m3, all text is scrambled.

![letter1_1](https://user-images.githubusercontent.com/77861029/212424661-7836481f-449c-4c94-956c-4701dc83fe95.jpg)

![letter2](https://user-images.githubusercontent.com/77861029/212424691-439106ee-aab3-4f1b-8705-5af70ed435f7.JPG)

This was still working correctly in 4.11 pre34, but not in pre 38.
According to talon1024 this commit could have broken it: https://github.com/ZDoom/gzdoom/commit/aceafecce6cd0552e395a1265f9e556c7cf38b97

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Run boa.
2. Read text paper on table or wall.
3.

**Comment by Talon1024** [comment]
[Here's a small demo mod that replaces smallfont with the "MavenProSmall" font from Wolfenstein: Blade of Agony](https://github.com/ZDoom/gzdoom/files/10416280/sheetfont.zip)

**Comment by x3003** [comment]
Thx for the fix, but it would be nice to test it w/ an updated windows build. ¯\_(ツ)_/¯

**Comment by madame-rachelle** [comment]
Updated builds are always available from the following locations:
- https://github.com/ZDoom/gzdoom/actions has artifacts uploaded with every commit (less reliable, harder to search, but far more frequent)

- https://devbuilds.drdteam.org/gzdoom/

**Comment by Blue-Shadow** [comment]
Dev builds on DRDTeam appear to have stopped. The latest build is from the 9th.
