### ISSUE TITLE
[BUG] Compiler does not detect invalid types set via Actor properties.

### ISSUE THREAD

**Issue by Magdiel012** [ZDoom/gzdoom#1956]
### GZDoom version

4.10.0

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 11

### Please describe your specific OS version

N/A

### Relevant hardware info

N/A

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Ordinarily assigning nonexistent types to `class<T>` fields results in a compiler error, and trying to pass nonexistent types as strings to the `new()` operator rightfully makes the VM abort. However, `class<T>` fields assigned via an Actor's `Default` block are not checked at compile time, and can therefore be passed to the `new()` operator, crashing the engine.

Attached is a minimal reproduction mod to showcase this:
[repro.zip](https://github.com/ZDoom/gzdoom/files/10448056/repro.zip)

Additionally, the crash report generated from attempting to run the repro mod on my machine:
[CrashReport.zip](https://github.com/ZDoom/gzdoom/files/10448066/CrashReport.zip)

### Steps to reproduce the behaviour.

The reproduction mod should crash as soon as it is launched. Note how the custom player class has an invalid type assigned via an Actor property, and then tries to instantiate it in `BeginPlay()`.

**Comment by CandiceJoy** [comment]
Fix in progress :)

**Comment by CandiceJoy** [comment]
Fix is https://github.com/ZDoom/gzdoom/pull/1969
