### ISSUE TITLE
QZDoom Tracker (01-21-2023)

### ISSUE THREAD

**Issue by MajorCooke** [ZDoom/gzdoom#1965]
QZDoom is designed for testing specific pull requests (PR for short) for any bugs/problems that might occur. Help would be appreciated. If a PR can be proven it's stable via a comment and proof, or if it's merged, the check box will be filled.

Whenever a new round of testing occurs, the old issue will be replaced with a new one to keep things clean.

-----
Downloads for QZDoom can be found here: [Windows](https://devbuilds.drdteam.org/qzdoom/) | [Macintosh](https://devbuilds.drdteam.org/qzdoom-mac/)

Desired versions should be 4.11+.
-----
The current round of testing includes the following:
- [x] #1967 
- [x] #1964
- [ ] #1960 
- [ ] #1959 
- [ ] #1957 
- [ ] #1953
- [ ] #1950
- [ ] #1949
- [ ] #1927 
- [ ] #1924
- [ ] #1920
- [ ] #1902
- [ ] #1894
- [x] #1878
- [x] #1541
- [x] #1394
- [x] #633

This will be a place to discuss any issues with QZDoom in particular. Any issues with any specific PRs should be done in the specific PR itself.

**Comment by MajorCooke** [comment]
Added #1967 and #1924 .

**Comment by MajorCooke** [comment]
Since this has 17 things merged now, I'm going to end accepting of more features to avoid the risk of potential merge conflicts. Bug fixes will still be accepted though.

**Comment by madame-rachelle** [comment]
Prebuilt binaries:
Windows: https://cdn.discordapp.com/attachments/1052963709775003739/1067423509166436483/qzdoom-g4247d97908.7z
Linux: https://cdn.discordapp.com/attachments/1052963709775003739/1067423509778812978/qzdoom-g4247d97908.tar.xz
MacOS: https://cdn.discordapp.com/attachments/1052963709775003739/1067423509451653171/qzdoom-g4247d97908.dmg

**Comment by CandiceJoy** [comment]
When I host a game via the CCMD command with a number greater than 1, the game simply freezes.  It's probably waiting for a connection, but without a message or SOMETHING....that's not good IMHO :P  https://github.com/ZDoom/gzdoom/pull/1927

**Comment by CandiceJoy** [comment]
#1878 Has issues as well.

<img width="677" alt="image" src="https://user-images.githubusercontent.com/8854890/214434632-2299cc99-14ee-4ca6-9e8f-82f5b730583d.png">
<img width="662" alt="image" src="https://user-images.githubusercontent.com/8854890/214434890-5555f3b6-52cb-4d4c-935a-4e00c14b4a93.png">

**Comment by MajorCooke** [comment]
Can you report these directly to their PRs? That way the authors know of them directly.

**Comment by CandiceJoy** [comment]
#1541 Appears to work as intended.

**Comment by MajorCooke** [comment]
#1964 works.

**Comment by CandiceJoy** [comment]
#1394 seems to work as intended.

**Comment by CandiceJoy** [comment]
#1878 works as intended from what I can tell.

**Comment by MajorCooke** [comment]
Now it does? Are you certain? That's the custom cvars one.

**Comment by MajorCooke** [comment]
I've received word that the networking stuff was tested by Nash, for a portion of it.

From Ricardo:
>the networking part of the host/join ccmds was tested by nash, all that's left is figuring out any issues that might be caused by the restarting itself, and that can be tested with host 1 without going over the internet

**Comment by Acts19quiz** [comment]
> #1878 works as intended from what I can tell.

Just now noticed this. I tried the g4.11-149 dev build ([the latest available](https://devbuilds.drdteam.org/gzdoom/) as of this post), and the bug is still present.

**Comment by inkoalawetrust** [comment]
Is QZDoom testing on hiatus ?

**Comment by MajorCooke** [comment]
No. We're just having trouble getting people to test some things. This always happens. The only true way to get it tested is if it's merged into GZDoom itself, in all honesty.

**Comment by coelckers** [comment]
I consider this one dead by now.
