### ISSUE TITLE
[BUG] GZDoom Crash when launching Dragon Sector Map 1 from New Game menu

### ISSUE THREAD

**Issue by FDinolfo** [ZDoom/gzdoom#1966]
There's is a crash that happens when GZDoom tries to load Dragon Sector Map 1 on Windows at Skill higher than 3 and with the Melt screen effect. Making this ticket here to make things easier, but the forum thread is below.

https://forum.zdoom.org/viewtopic.php?p=1235961#p1235961

To summarize the steps to reproduce and the workaround found.

Using either Vulkan or OpenGL, launching the Dragon Sector PK3 on GZDoom 4.9/10 causes GZDoom to crash when the screen melt effect happens. The skill level seems to be a factor, as skills HMP did allow me to start the maps just fine. The workaround found by PlayerLin was to change Screen Wipe Effect to anything other than Melt.

Hopefully this will help to keep track of things. CandiceJoy suggested I open the issue, even though she notified someone about it.  So, here's an issue ticket you can use.

**Comment by CandiceJoy** [comment]
Can reproduce and confirm.  The crash happens in the assert before this line in debug, and on release or when the assert is removed, it proceeds then crashes later in asm.  
https://github.com/ZDoom/gzdoom/blob/e268a4195c5c8ee0c34f01ddde6d6bf1d3c82b50/src/common/rendering/hwrenderer/data/hw_bonebuffer.cpp#L88
@ShinyMetagross

**Comment by coelckers** [comment]
Please don't open duplicate reports. The one on the forum was enough.
And Candice's crash location seems to confirm my suspicion that the game runs out of GPU memory. I never even get this far.
