### ISSUE TITLE
[Feature] Voxel loader can't handle arch vile's ^ / backslash state

### ISSUE THREAD

**Issue by nashmuhandes** [ZDoom/gzdoom#1973]
### GZDoom version

4.10

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 10

### Is your feature request related to a problem? Please describe.

The voxel loader can't seem to handle the `\` or `^` frame of the Arch Vile. Example attached.
[archvile-vox.zip](https://github.com/ZDoom/gzdoom/files/10509744/archvile-vox.zip)

**Comment by prof-hastig** [comment]
This works:

vile] = "vile]" {}
vile\ = "vile^" {}

which would be the obvious way to try.

**Comment by coelckers** [comment]
If that works there's nothing wrong here.
