### ISSUE TITLE
Replacing `SmallFont` screws up font color in menus

### ISSUE THREAD

**Issue by Blue-Shadow** [ZDoom/gzdoom#1976]
**Tested with:** 4.11pre-76-g4c0b5cbb3 and 4.8.2
**Test material:** https://www.dropbox.com/s/nc9862za1e482yh/font_color_bug_demo.pk3?dl=1

I have a font replacing the `SmallFont`. The odd thing is, this seems to affect the font color of some elements in the menus; see how the options' labels in the screenshot below drawn in black.

![gfhdfhfghd](https://user-images.githubusercontent.com/4287687/215268287-7119d84e-53a9-465f-ae1c-dfb6f5c25656.png)

**Comment by coelckers** [comment]
What this does is adapt the 'untranslated' color of the stock fonts to the hue of the actual SmallFont to better match the current mod.  Of course this won't work well if the new SmallFont cannot be properly colorized.
