### ISSUE TITLE
Font colors are too dark with custom font

### ISSUE THREAD

**Issue by Blue-Shadow** [ZDoom/gzdoom#1977]
**Tested with:** 4.11pre-76-g4c0b5cbb3 and 4.8.2
**Test material:** https://www.dropbox.com/s/nc9862za1e482yh/font_color_bug_demo.pk3?dl=1

The font in the attached test file, when translated using the stock font colors from GZDoom, appears very dark. Untranslated, the font is white, for the record.

Notice how dark the logged messages and map's statistics are.

![Screenshot_Doom_20230128_154918](https://user-images.githubusercontent.com/4287687/215268561-dda24a78-42a2-4f40-b2bf-86d1d3523668.png)

**Comment by coelckers** [comment]
The font colorization code does not work well with single colored fonts because there's no way to build a color ramp from it. The best you can do is add a single character in an unused slot with darker colors for the font code to pick up.

**Comment by Blue-Shadow** [comment]
> The best you can do is add a single character in an unused slot with darker colors for the font code to pick up.

Thanks. That did the trick.
