### ISSUE TITLE
[Feature] Discord Rich Presence expansion and improvement

### ISSUE THREAD

**Issue by spiral6** [ZDoom/gzdoom#1994]
### GZDoom version

GZDoom 4.10.0

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 10

### Relevant hardware info

AMD Ryzen 5 5600X, NVIDIA GeForce RTX 3060, 16 GB DDR4 RAM

### Is your feature request related to a problem? Please describe.

Playing GZDoom with Discord open shows the rich presence for the engine. 
For some PWADs, it works really well.
![image](https://user-images.githubusercontent.com/2887489/217933674-b4e43f44-b0c4-49aa-a044-1a754102fac4.png)
But for others, not as much.
![image](https://user-images.githubusercontent.com/2887489/217933868-fbd8d715-da8f-4a84-870e-1de45d6c57c4.png)

It was determined that the lack of information there was due to the WAD itself, but we can still add more things to the rich presence such as ClassName (for Heretic) and Difficulty/Skill.

### Describe the solution you'd like

We can still add more things to the rich presence such as ClassName (for Heretic) and Difficulty/Skill.

### Add any other context or screenshots about the feature request here.

https://discord.com/channels/268086704961748992/340199158772269056/1073104767989059584

![image](https://user-images.githubusercontent.com/2887489/217935867-c035dae5-9ed6-4212-a290-ab7896d22628.png)

**Comment by coelckers** [comment]
Closing because not even the assignee seems to care.

**Comment by spiral6** [comment]
Sorry, I should have closed this a while back. This was due to an issue with the WAD's metadata itself. For other games, i.e. Heretic, those aren't something I'm terribly interested in but documented here for the sake of posterity.
