### ISSUE TITLE
[BUG] Zipped Strife IWAD

### ISSUE THREAD

**Issue by RetroGamer2023** [ZDoom/gzdoom#1995]
### GZDoom version

GZDoom 4.10.0

### Which game are you running with GZDoom?

Strife

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

x64

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The game has missing textures when loading strife when the IWAD has been zipped.

![image](https://user-images.githubusercontent.com/124946575/217979358-3e66ce2d-fb2b-484f-b0f5-f00aab52a16e.png)

### Your configuration

```ini
I've tested this with a clean download of GZDoom with zero addons etc..
```

**Comment by RetroGamer2023** [comment]
Here's it running non-zipped with a ton of mods.

![image](https://user-images.githubusercontent.com/124946575/217979780-3a3ceea4-dda2-47dd-a8e0-97b728545f36.png)

**Comment by SanyaWaffles** [comment]
Why would you zip Strife's IWAD? Makes no sense to me.

**Comment by madame-rachelle** [comment]
> Why would you zip Strife's IWAD? Makes no sense to me.

Agreed - what exactly are you trying to accomplish?

**Comment by RetroGamer2023** [comment]
When you have a lot of wads, you wonna zip them all to save space. Just mark at as low priority if most people don't care.

**Comment by CandiceJoy** [comment]
I can confirm the reported behaviour.

**Comment by coelckers** [comment]
This is completely unsupported behavior. IWADs are not supposed to be zipped.

**Comment by RetroGamer2023** [comment]
I'm sure the zip functionality (that I'm assuming is still supported for WADS), has no issue though, just a weird Strife only thing.
