### ISSUE TITLE
ZDoom forum registration is broken.

### ISSUE THREAD

**Issue by GrayFace** [ZDoom/gzdoom#1997]
Sorry for reporting it here, but I'm forced to, because there are no contacts listed on ZDoom forum/site.

When you try to register on the forum, the following messages appear:

The password you entered is too short.
The password does not contain the required characters.
The password confirmation you entered is too short.
The email address you entered is not allowed to be used.

No "required characters" listed at all. 13 character password (marked as "Very Strong" by the board) is somehow "too short", again not even an indication of how long it has to be.

**Comment by Player701** [comment]
The password requirements are visible in the registration form:

![image](https://user-images.githubusercontent.com/9046118/218186133-0ab3989b-b645-4c1e-9c84-2188d6ff94e5.png)

As for the your email address not being allowed, I have no idea, but I can say for sure I wouldn't be happy if I got such an error message when attempting to register. IMO, any non-disposable email address should be allowed.

**Comment by madame-rachelle** [comment]
If you still have problems please go to the Discord server
https://forum.zdoom.org/viewtopic.php?f=48&t=54921

https://discord.gg/zdoom

**Comment by GrayFace** [comment]
Thanks. I was a bit blind I guess. Or maybe password hint isn't shown if the errors are shown, I don't know.
