### ISSUE TITLE
[BUG] "Cannot convert Pointer<NativeStruct<Line>> to Pointer<Type>"

### ISSUE THREAD

**Issue by ipaqmaster** [ZDoom/gzdoom#2001]
### GZDoom version

gzdoom-git-4.11pre+131+g17800f250-1

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Archlinux. Kernel version 6.1.11-arch1-1

### Relevant hardware info

NA - Not a hardware problem

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Starting the game against hd-4.8.2a.pk7 throws a few zscript errors:

```
Script error, "hd-4.8.2a.pk7:zscript/function.zs" line 815:
Cannot convert Pointer<NativeStruct<Line>> to Pointer<Type>
Script error, "hd-4.8.2a.pk7:zscript/function.zs" line 748:
Cannot convert Pointer<NativeStruct<Line>> to Pointer<Type>
Script error, "hd-4.8.2a.pk7:zscript/function.zs" line 884:
Cannot convert Pointer<NativeStruct<Line>> to Pointer<Type>
Script error, "hd-4.8.2a.pk7:zscript/function.zs" line 906:
Cannot convert Pointer<NativeStruct<Line>> to Pointer<Type>
Script error, "hd-4.8.2a.pk7:zscript/bullet.zs" line 658:
Cannot convert Pointer<NativeStruct<Line>> to Pointer<Type>
```

When I downgrade to the previous version I were running (gzdoom-git-4.11pre+127+g1355b9669-1) via `pacman -U --noconfirm /var/cache/pacman/pkg/gzdoom-git-4.11pre+127+g1355b9669-1-x86_64.pkg.tar.zst` the game starts with this mod just fine.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Launch game with this particular PK3
2. It errors out as per codeblock above.
3. :frowning_face: 

### Your configuration

```ini
NA
```

### Provide a Log

W_Init: Init WADfiles.
 adding /usr/share/gzdoom/gzdoom.pk3, 672 lumps
 adding /usr/share/gzdoom/game_support.pk3, 3151 lumps
 adding ./tnt.wad, 3101 lumps
 adding /usr/share/gzdoom/lights.pk3, 7 lumps
 adding /usr/share/gzdoom/brightmaps.pk3, 499 lumps
 adding /usr/share/gzdoom/game_widescreen_gfx.pk3, 214 lumps
 adding /home/meDesktop/hd-4.8.2a.pk7, 723 lumps
S_Init: Setting up sound.
I_InitSound: Initializing OpenAL
  Opened device WH-1000XM5
  EFX enabled
I_Init: Setting up machine state.
CPU speed: 3793 MHz
CPU Vendor ID: AuthenticAMD
  Name: AMD Ryzen 9 3900X 12-Core Processor 
  Family 23 (23), Model 113, Stepping 0
  Features: SSE2 SSE3 SSSE3 SSE4.1 SSE4.2 AVX AVX2 F16C FMA3 BMI1 BMI2 HyperThreading
V_Init: allocate screen.
ST_Init: Init startup screen.
Checking cmd-line parameters...
S_InitData: Load sound definitions.
G_ParseMapInfo: Load map definitions.
Texman.Init: Init texture manager.
ParseTeamInfo: Load team definitions.
LoadActors: Load actor definitions.
Script error, "hd-4.8.2a.pk7:zscript/function.zs" line 815:
Cannot convert Pointer<NativeStruct<Line>> to Pointer<Type>
Script error, "hd-4.8.2a.pk7:zscript/function.zs" line 748:
Cannot convert Pointer<NativeStruct<Line>> to Pointer<Type>
Script error, "hd-4.8.2a.pk7:zscript/function.zs" line 884:
Cannot convert Pointer<NativeStruct<Line>> to Pointer<Type>
Script error, "hd-4.8.2a.pk7:zscript/function.zs" line 906:
Cannot convert Pointer<NativeStruct<Line>> to Pointer<Type>
Script error, "hd-4.8.2a.pk7:zscript/bullet.zs" line 658:
Cannot convert Pointer<NativeStruct<Line>> to Pointer<Type>

**Comment by ipaqmaster** [comment]
If anybody recalls my previous gzdoom issue #1876 ; Yeah still not done with my Doom1+doom2+tnt+plutonia run with this wad!

**Comment by coelckers** [comment]
This one's already fixed.

**Comment by ipaqmaster** [comment]
Ah I should've just re-run my nightly build before posting. Thank you
