### ISSUE TITLE
[Feature] in game mod menu

### ISSUE THREAD

**Issue by powerpuffboysz** [ZDoom/gzdoom#2004]
### GZDoom version

GZDOOM 4.10.0

### Which game are you running with GZDoom?

Doom

### What Operating System are you using?

Other

### If Other OS, please describe

windows 64 EXE on manjaro linux 22 through wine/proton

### Relevant hardware info

5900x cpu, 1080 ti gpu, 32gb ram

### Is your feature request related to a problem? Please describe.

would it be possible to add a menu option to the title screen to look for a mod folder and list playable mods in a similar fassion to the likes of vkquake?

### Describe the solution you'd like

add an ingame menu on startup to pick a wad from within the folder to boot

**Comment by CandiceJoy** [comment]
This won't happen, sorry D:

**Comment by mc776** [comment]
By the time GZDoom has started it will have loaded the mods it's going to use, so anything of this sort is going to be in the form of an external launcher... given the options that already exist out there it seems counterproductive for the GZDoom dev team to spend limited resources on a new one (or repackaging any particular existing one and all the compatibility issues and drama that might cause).

**Comment by coelckers** [comment]
Doom's file system cannot do this easily, so we defer this to external launchers which are better suited to the task

**Comment by CortexReaver** [comment]
If you have hundreds of WADS, like I do, try using Doom Launcher: https://github.com/nstlaurent/DoomLauncher It uses SQL database for mod management, allows you assign mods to a different tabs categories and has sort and search features. Although, you need to pack all of your wads to zip archives and the interface seems not as rigid and customizable (especially in a case where you want to switch quickly between setups of gameplay mods), this is the only one and good third party launcher that I found useful.

**Comment by powerpuffboysz** [comment]
Any chance of reevaluating this as the recent kex port proved this is possble?
