### ISSUE TITLE
[BUG] Alt+Tab doesn't work in full screen mode

### ISSUE THREAD

**Issue by GrayFace** [ZDoom/gzdoom#2013]
### GZDoom version

GZDoom 4.10.0

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 7

### Please describe your specific OS version

Windows 7 x64

### Relevant hardware info

AMD Ryzen 5 2600, Radeon RX 570

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Pressing Alt+Tab doesn't remove Topmost attribute from Doom window and doesn't minimize it, thus Doom still stays on top of everything, only stops updating.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Run Doom, enter fullscreen mode
3. Load any save
4. Press Alt+Tab
5. Doom window would stay on top of everything, but would stop updating

### Your configuration

Here's my config: [gzdoom_portable.ini.txt](https://github.com/ZDoom/gzdoom/files/10807671/gzdoom_portable.ini.txt)

Here's my command line:
```
./gzdoom.exe -iwad "../plutonia.wad" -file "../pk3/DoomMetalVol5.wad" "../pk3/AggressiveBrutalityVol1.0.wad" "../pk3/NeuralUpscale2x_v1.0.pk3" "../PB/Project_Brutality-master.zip" "../PB/PBSoundPack_10.10.20.pk3" "../PB/SimpleHudAddons.pk3" "../PB/Mine" +sv_cheats 1
```

**Comment by CandiceJoy** [comment]
Does it do this with no mods?

**Comment by GrayFace** [comment]
> Does it do this with no mods?

Yes, problem persists.

**Comment by CandiceJoy** [comment]
Hmmm.  This could be an OS issue, it could be fixed in HEAD, or it could be a bug in GZDoom.  Is there any more information you can provide?  Please note that Windows 7 is in the "Loosely Supported" category, as defined below.

> The core development team will not assist with these issues by themselves, and to keep these working depends on user support and contributions. Bugs opened specific to these setups tend to take longer - they may work, but they're not a huge issue to the development team, and may frequently suffer regressions in the development cycle - the more unusual your setup, the more likely it is to break - support for these depend more or less on user contributions or fixes towards the affected third-party API's if applicable. Also, all older items on this list (WinXP, OGL2.0, etc) are on the chopping block for removal in the future.

**Comment by GrayFace** [comment]
This probably is related to bugs that happen even in Windowed mode. It's as if GZDoom creates a transparent topmost window that captures clicks and sometimes hides mouse pointer. When you Alt+Tab this strange window/hook stays for a while consuming clicks.
