### ISSUE TITLE
[BUG] gzdoom fails to build: "incomplete type 'PType' used in nested name specifier"

### ISSUE THREAD

**Issue by david-geiger** [ZDoom/gzdoom#2018]
### GZDoom version

GZDoom 4.10.0

### Which game are you running with GZDoom?

None

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Mageia Linux Cauldron

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Hi,

gzdoom 4.10.0 (also 4.3.3) fails to build with:

/home/david/mgarepo/gzdoom/BUILD/gzdoom-g4.10.0/src/d_main.cpp:3621:24: error: incomplete type 'PType' used in nested name specifier
 3621 |                 PType::StaticInit();

Attached full build log:
[log.gzdoom.txt](https://github.com/ZDoom/gzdoom/files/10833610/log.gzdoom.txt)

### Provide a Log

http://pkgsubmit.mageia.org/autobuild/cauldron/x86_64/core/2023-02-23/gzdoom-4.3.3-3.mga9.src.rpm/build.x86_64.0.20230224183237.log

**Comment by CandiceJoy** [comment]
Does HEAD fail to build?

**Comment by david-geiger** [comment]
Just tried a build with HEAD branch and yes it also fails to build with same error.

**Comment by CandiceJoy** [comment]
> Just tried a build with HEAD branch and yes it also fails to build with same error.

Could I get a compilation log from that attempt?  I'm unfamiliar with early versions.

**Comment by CandiceJoy** [comment]
Looks like the issue your compilation isn't including some of the include directories.  Below is my output for the file in question.  Your's isn't including the headers from src/common/scripting/core whereas mine is; that's where the PType class is declared, therefore it isn't finding it :P

>[ 80%] Building CXX object src/CMakeFiles/zdoom.dir/common/objects/dobjgc.cpp.o
cd /Users/candice/CLionProjects/gzdoom/cmake-build-debug/src && /usr/bin/g++ -DHAVE_DISPATCH_APPLY=1 -DNO_GTK -DTHIS_IS_GZDOOM -DUSE_LIBVPX=1 -D__FIXMATH__ -D__FP__ -D__forceinline=inline -Dstricmp=strcasecmp -Dstrnicmp=strncasecmp -I/Users/candice/vcpkg/installed/arm64-osx/include/AL -I/opt/homebrew/include -I/Users/candice/vcpkg/installed/arm64-osx/include -I/Users/candice/CLionProjects/gzdoom/libraries/lzma/C -I/usr/local/include -I/Users/candice/CLionProjects/gzdoom/libraries/discordrpc/include -I/Users/candice/CLionProjects/gzdoom/cmake-build-debug/src -I/Users/candice/CLionProjects/gzdoom/src/. -I/Users/candice/CLionProjects/gzdoom/src/common/audio/sound -I/Users/candice/CLionProjects/gzdoom/src/common/audio/music -I/Users/candice/CLionProjects/gzdoom/src/common/2d -I/Users/candice/CLionProjects/gzdoom/src/common/cutscenes -I/Users/candice/CLionProjects/gzdoom/src/common/thirdparty/libsmackerdec/include -I/Users/candice/CLionProjects/gzdoom/src/common/thirdparty -I/Users/candice/CLionProjects/gzdoom/src/common/textures -I/Users/candice/CLionProjects/gzdoom/src/common/textures/formats -I/Users/candice/CLionProjects/gzdoom/src/common/textures/hires -I/Users/candice/CLionProjects/gzdoom/src/common/models -I/Users/candice/CLionProjects/gzdoom/src/common/filesystem -I/Users/candice/CLionProjects/gzdoom/src/common/utility -I/Users/candice/CLionProjects/gzdoom/src/common/console -I/Users/candice/CLionProjects/gzdoom/src/common/engine -I/Users/candice/CLionProjects/gzdoom/src/common/menu -I/Users/candice/CLionProjects/gzdoom/src/common/statusbar -I/Users/candice/CLionProjects/gzdoom/src/common/fonts -I/Users/candice/CLionProjects/gzdoom/src/common/objects -I/Users/candice/CLionProjects/gzdoom/src/common/startscreen -I/Users/candice/CLionProjects/gzdoom/src/common/rendering -I/Users/candice/CLionProjects/gzdoom/src/common/rendering/hwrenderer/data -I/Users/candice/CLionProjects/gzdoom/src/common/rendering/gl_load -I/Users/candice/CLionProjects/gzdoom/src/common/rendering/gl -I/Users/candice/CLionProjects/gzdoom/src/common/rendering/gles -I/Users/candice/CLionProjects/gzdoom/src/common/rendering/gles/glad/include -I/Users/candice/CLionProjects/gzdoom/src/common/rendering/gles/Mali_OpenGL_ES_Emulator/include -I/Users/candice/CLionProjects/gzdoom/src/common/scripting/vm -I/Users/candice/CLionProjects/gzdoom/src/common/scripting/jit -I/Users/candice/CLionProjects/gzdoom/src/common/scripting/core -I/Users/candice/CLionProjects/gzdoom/src/common/scripting/interface -I/Users/candice/CLionProjects/gzdoom/src/common/scripting/frontend -I/Users/candice/CLionProjects/gzdoom/src/common/scripting/backend -I/Users/candice/CLionProjects/gzdoom/src/g_statusbar -I/Users/candice/CLionProjects/gzdoom/src/console -I/Users/candice/CLionProjects/gzdoom/src/playsim -I/Users/candice/CLionProjects/gzdoom/src/playsim/bots -I/Users/candice/CLionProjects/gzdoom/src/playsim/mapthinkers -I/Users/candice/CLionProjects/gzdoom/src/gamedata -I/Users/candice/CLionProjects/gzdoom/src/gamedata/textures -I/Users/candice/CLionProjects/gzdoom/src/gamedata/fonts -I/Users/candice/CLionProjects/gzdoom/src/rendering -I/Users/candice/CLionProjects/gzdoom/src/rendering/hwrenderer -I/Users/candice/CLionProjects/gzdoom/src/rendering/2d -I/Users/candice/CLionProjects/gzdoom/src/r_data -I/Users/candice/CLionProjects/gzdoom/src/sound -I/Users/candice/CLionProjects/gzdoom/src/menu -I/Users/candice/CLionProjects/gzdoom/src/sound/backend -I/Users/candice/CLionProjects/gzdoom/src/xlat -I/Users/candice/CLionProjects/gzdoom/src/utility -I/Users/candice/CLionProjects/gzdoom/src/utility/nodebuilder -I/Users/candice/CLionProjects/gzdoom/src/scripting -I/Users/candice/CLionProjects/gzdoom/src/scripting/zscript -I/Users/candice/CLionProjects/gzdoom/src/../libraries/gdtoa -I/Users/candice/CLionProjects/gzdoom/src/../libraries/ZVulkan/include -I/Users/candice/CLionProjects/gzdoom/cmake-build-debug/libraries/gdtoa -I/Users/candice/CLionProjects/gzdoom/src/common/platform/posix -I/Users/candice/CLionProjects/gzdoom/src/common/platform/posix/cocoa -DNO_SSE -Wall -Wextra -Wno-unused -Wno-unused-parameter -Wno-missing-field-initializers -ffp-contract=off -Wno-inconsistent-missing-override   -std=c++17 -ffp-contract=off -DHAVE_VULKAN -DHAVE_GLES2 -g  -D_DEBUG -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -mmacosx-version-min=10.12 -fcolor-diagnostics -std=c++17 -include g_pch.h -MD -MT src/CMakeFiles/zdoom.dir/common/objects/dobjgc.cpp.o -MF CMakeFiles/zdoom.dir/common/objects/dobjgc.cpp.o.d -o CMakeFiles/zdoom.dir/common/objects/dobjgc.cpp.o -c /Users/candice/CLionProjects/gzdoom/src/common/objects/dobjgc.cpp
[ 80%] Building CXX object src/CMakeFiles/zdoom.dir/common/objects/dobjtype.cpp.o
cd /Users/candice/CLionProjects/gzdoom/cmake-build-debug/src && /usr/bin/g++ -DHAVE_DISPATCH_APPLY=1 -DNO_GTK -DTHIS_IS_GZDOOM -DUSE_LIBVPX=1 -D__FIXMATH__ -D__FP__ -D__forceinline=inline -Dstricmp=strcasecmp -Dstrnicmp=strncasecmp -I/Users/candice/vcpkg/installed/arm64-osx/include/AL -I/opt/homebrew/include -I/Users/candice/vcpkg/installed/arm64-osx/include -I/Users/candice/CLionProjects/gzdoom/libraries/lzma/C -I/usr/local/include -I/Users/candice/CLionProjects/gzdoom/libraries/discordrpc/include -I/Users/candice/CLionProjects/gzdoom/cmake-build-debug/src -I/Users/candice/CLionProjects/gzdoom/src/. -I/Users/candice/CLionProjects/gzdoom/src/common/audio/sound -I/Users/candice/CLionProjects/gzdoom/src/common/audio/music -I/Users/candice/CLionProjects/gzdoom/src/common/2d -I/Users/candice/CLionProjects/gzdoom/src/common/cutscenes -I/Users/candice/CLionProjects/gzdoom/src/common/thirdparty/libsmackerdec/include -I/Users/candice/CLionProjects/gzdoom/src/common/thirdparty -I/Users/candice/CLionProjects/gzdoom/src/common/textures -I/Users/candice/CLionProjects/gzdoom/src/common/textures/formats -I/Users/candice/CLionProjects/gzdoom/src/common/textures/hires -I/Users/candice/CLionProjects/gzdoom/src/common/models -I/Users/candice/CLionProjects/gzdoom/src/common/filesystem -I/Users/candice/CLionProjects/gzdoom/src/common/utility -I/Users/candice/CLionProjects/gzdoom/src/common/console -I/Users/candice/CLionProjects/gzdoom/src/common/engine -I/Users/candice/CLionProjects/gzdoom/src/common/menu -I/Users/candice/CLionProjects/gzdoom/src/common/statusbar -I/Users/candice/CLionProjects/gzdoom/src/common/fonts -I/Users/candice/CLionProjects/gzdoom/src/common/objects -I/Users/candice/CLionProjects/gzdoom/src/common/startscreen -I/Users/candice/CLionProjects/gzdoom/src/common/rendering -I/Users/candice/CLionProjects/gzdoom/src/common/rendering/hwrenderer/data -I/Users/candice/CLionProjects/gzdoom/src/common/rendering/gl_load -I/Users/candice/CLionProjects/gzdoom/src/common/rendering/gl -I/Users/candice/CLionProjects/gzdoom/src/common/rendering/gles -I/Users/candice/CLionProjects/gzdoom/src/common/rendering/gles/glad/include -I/Users/candice/CLionProjects/gzdoom/src/common/rendering/gles/Mali_OpenGL_ES_Emulator/include -I/Users/candice/CLionProjects/gzdoom/src/common/scripting/vm -I/Users/candice/CLionProjects/gzdoom/src/common/scripting/jit -I/Users/candice/CLionProjects/gzdoom/src/common/scripting/core -I/Users/candice/CLionProjects/gzdoom/src/common/scripting/interface -I/Users/candice/CLionProjects/gzdoom/src/common/scripting/frontend -I/Users/candice/CLionProjects/gzdoom/src/common/scripting/backend -I/Users/candice/CLionProjects/gzdoom/src/g_statusbar -I/Users/candice/CLionProjects/gzdoom/src/console -I/Users/candice/CLionProjects/gzdoom/src/playsim -I/Users/candice/CLionProjects/gzdoom/src/playsim/bots -I/Users/candice/CLionProjects/gzdoom/src/playsim/mapthinkers -I/Users/candice/CLionProjects/gzdoom/src/gamedata -I/Users/candice/CLionProjects/gzdoom/src/gamedata/textures -I/Users/candice/CLionProjects/gzdoom/src/gamedata/fonts -I/Users/candice/CLionProjects/gzdoom/src/rendering -I/Users/candice/CLionProjects/gzdoom/src/rendering/hwrenderer -I/Users/candice/CLionProjects/gzdoom/src/rendering/2d -I/Users/candice/CLionProjects/gzdoom/src/r_data -I/Users/candice/CLionProjects/gzdoom/src/sound -I/Users/candice/CLionProjects/gzdoom/src/menu -I/Users/candice/CLionProjects/gzdoom/src/sound/backend -I/Users/candice/CLionProjects/gzdoom/src/xlat -I/Users/candice/CLionProjects/gzdoom/src/utility -I/Users/candice/CLionProjects/gzdoom/src/utility/nodebuilder -I/Users/candice/CLionProjects/gzdoom/src/scripting -I/Users/candice/CLionProjects/gzdoom/src/scripting/zscript -I/Users/candice/CLionProjects/gzdoom/src/../libraries/gdtoa -I/Users/candice/CLionProjects/gzdoom/src/../libraries/ZVulkan/include -I/Users/candice/CLionProjects/gzdoom/cmake-build-debug/libraries/gdtoa -I/Users/candice/CLionProjects/gzdoom/src/common/platform/posix -I/Users/candice/CLionProjects/gzdoom/src/common/platform/posix/cocoa -DNO_SSE -Wall -Wextra -Wno-unused -Wno-unused-parameter -Wno-missing-field-initializers -ffp-contract=off -Wno-inconsistent-missing-override   -std=c++17 -ffp-contract=off -DHAVE_VULKAN -DHAVE_GLES2 -g  -D_DEBUG -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -mmacosx-version-min=10.12 -fcolor-diagnostics -std=c++17 -include g_pch.h -MD -MT src/CMakeFiles/zdoom.dir/common/objects/dobjtype.cpp.o -MF CMakeFiles/zdoom.dir/common/objects/dobjtype.cpp.o.d -o CMakeFiles/zdoom.dir/common/objects/dobjtype.cpp.o -c /Users/candice/CLionProjects/gzdoom/src/common/objects/dobjtype.cpp

**Comment by david-geiger** [comment]
Here is full HEAD build log:
[log.HEAD-gzdoom.txt](https://github.com/ZDoom/gzdoom/files/10836006/log.HEAD-gzdoom.txt)

**Comment by alexey-lysiuk** [comment]
It's something on your side. [Here](https://github.com/alexey-lysiuk/gzdoom/actions/runs/4280097393) is successful build of Debug/RelWithDebInfo/Release with GCC 12.

Most likely, wrong `types.h` is included. It's picked from one of the following directories.
```
/usr/include/gtk-3.0
/usr/include/pango-1.0
/usr/include/glib-2.0
/usr/lib64/glib-2.0/include
/usr/include/harfbuzz
/usr/include/freetype2
/usr/include/libpng16
/usr/include/libmount
/usr/include/blkid
/usr/include/fribidi
/usr/include/libxml2
/usr/include/cairo
/usr/include/pixman-1
/usr/include/gdk-pixbuf-2.0
/usr/include/webp
/usr/include/gio-unix-2.0
/usr/include/cloudproviders
/usr/include/atk-1.0
/usr/include/at-spi2-atk/2.0
/usr/include/at-spi-2.0
/usr/include/dbus-1.0
/usr/lib64/dbus-1.0/include
/usr/include/SDL2
/usr/include/AL
```

**Comment by david-geiger** [comment]
You are write, on my system I have:

> $ find /usr/include -name types.h
./webp/types.h
./sys/types.h
./multiarch-x86_64-linux/gssrpc/types.h
./c++/12/parallel/types.h
./openssl/types.h
./brotli/types.h
./asm-generic/types.h
./gssrpc/types.h
./bits/types.h
./asm/types.h
./linux/types.h
./linux/sched/types.h
./linux/iio/types.h

**Comment by CandiceJoy** [comment]
Yeah, you'll have to fix compilation by using the right one.  If you have further issues, you can ask in the Discord [here](https://discord.gg/ZDoom) or on the forums [here](https://forum.zdoom.org), but since it's on your end, it isn't a bug, so I'm going to close this issue.  I'm happy to continue trying to help you elsewhere, though :) <3

**Comment by 0strodamus** [comment]
Just wanted to update this issue in case anyone else is still struggling to get an older version to compile.

I was able to get 4.10.0 to compile by patching in commit [b95dbaf914618cccaeaa95c650e02be669e477f8](https://github.com/ZDoom/gzdoom/commit/b95dbaf914618cccaeaa95c650e02be669e477f8).

**Comment by mbugni** [comment]
Similar issue when trying to build a GZDoom version 4.10.0 in order to keep alive an old game.
The build works fine if I compile the source code using this:

```shell
[📦 org.freedesktop.Sdk ~]$ gcc --version
gcc (GCC) 12.2.0
```

It doesn't work when I use the following from latest Flatpak runtime (24.08):

```shell
[📦 org.freedesktop.Sdk ~]$ gcc --version
gcc (GCC) 14.2.0
```

I'm not a C++ expert, but I found the following error in logs:

```
[271/691] Building CXX object src/CMakeFiles/zdoom.dir/d_main.cpp.o
FAILED: src/CMakeFiles/zdoom.dir/d_main.cpp.o 
/usr/bin/c++ -DARCH_IA32 -DDYN_GTK=1 -DDYN_OPENAL -DHAVE_MMX=1 -DHAVE_VM_JIT -DUSE_LIBVPX=1 -D__forceinline=inline -Dstricmp=strcasecmp -Dstrnicmp=strncasecmp -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/webp -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/atk-1.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/fribidi -I/usr/include/pixman-1 -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gio-unix-2.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/SDL2 -I/run/build/gzdoom/libraries/lzma/C -I/run/build/gzdoom/libraries/discordrpc/include -I/run/build/gzdoom/libraries/asmjit -I/run/build/gzdoom/src -I/run/build/gzdoom/src/. -I/run/build/gzdoom/src/common/audio/sound -I/run/build/gzdoom/src/common/audio/music -I/run/build/gzdoom/src/common/2d -I/run/build/gzdoom/src/common/cutscenes -I/run/build/gzdoom/src/common/thirdparty/libsmackerdec/include -I/run/build/gzdoom/src/common/thirdparty -I/run/build/gzdoom/src/common/textures -I/run/build/gzdoom/src/common/textures/formats -I/run/build/gzdoom/src/common/textures/hires -I/run/build/gzdoom/src/common/models -I/run/build/gzdoom/src/common/filesystem -I/run/build/gzdoom/src/common/utility -I/run/build/gzdoom/src/common/console -I/run/build/gzdoom/src/common/engine -I/run/build/gzdoom/src/common/menu -I/run/build/gzdoom/src/common/statusbar -I/run/build/gzdoom/src/common/fonts -I/run/build/gzdoom/src/common/objects -I/run/build/gzdoom/src/common/startscreen -I/run/build/gzdoom/src/common/rendering -I/run/build/gzdoom/src/common/rendering/hwrenderer/data -I/run/build/gzdoom/src/common/rendering/gl_load -I/run/build/gzdoom/src/common/rendering/gl -I/run/build/gzdoom/src/common/rendering/gles -I/run/build/gzdoom/src/common/rendering/gles/glad/include -I/run/build/gzdoom/src/common/rendering/gles/Mali_OpenGL_ES_Emulator/include -I/run/build/gzdoom/src/common/rendering/vulkan/thirdparty -I/run/build/gzdoom/src/common/scripting/vm -I/run/build/gzdoom/src/common/scripting/jit -I/run/build/gzdoom/src/common/scripting/core -I/run/build/gzdoom/src/common/scripting/interface -I/run/build/gzdoom/src/common/scripting/frontend -I/run/build/gzdoom/src/common/scripting/backend -I/run/build/gzdoom/src/g_statusbar -I/run/build/gzdoom/src/console -I/run/build/gzdoom/src/playsim -I/run/build/gzdoom/src/playsim/bots -I/run/build/gzdoom/src/playsim/mapthinkers -I/run/build/gzdoom/src/gamedata -I/run/build/gzdoom/src/gamedata/textures -I/run/build/gzdoom/src/gamedata/fonts -I/run/build/gzdoom/src/rendering -I/run/build/gzdoom/src/rendering/hwrenderer -I/run/build/gzdoom/src/rendering/2d -I/run/build/gzdoom/src/r_data -I/run/build/gzdoom/src/sound -I/run/build/gzdoom/src/menu -I/run/build/gzdoom/src/sound/backend -I/run/build/gzdoom/src/xlat -I/run/build/gzdoom/src/utility -I/run/build/gzdoom/src/utility/nodebuilder -I/run/build/gzdoom/src/scripting -I/run/build/gzdoom/src/scripting/zscript -I/run/build/gzdoom/src/../libraries/gdtoa -I/run/build/gzdoom/src/../libraries/glslang/glslang/Public -I/run/build/gzdoom/src/../libraries/glslang/spirv -I/run/build/gzdoom/libraries/gdtoa -I/run/build/gzdoom/src/common/platform/posix -I/run/build/gzdoom/src/common/platform/posix/sdl -I/run/build/gzdoom/libraries/glslang/glslang/.. -I/run/build/gzdoom/libraries/glslang/spirv/.. -Wall -Wextra -Wno-unused -Wno-unused-parameter -Wno-missing-field-initializers -ffp-contract=off -Wno-unused-result  -fno-strict-aliasing -std=c++17 -ffp-contract=off -DHAVE_VULKAN -DHAVE_GLES2 -fPIE -fopenmp  -fomit-frame-pointer -O3 -DNDEBUG  -std=c++17 -include g_pch.h -MD -MT src/CMakeFiles/zdoom.dir/d_main.cpp.o -MF src/CMakeFiles/zdoom.dir/d_main.cpp.o.d -o src/CMakeFiles/zdoom.dir/d_main.cpp.o -c /run/build/gzdoom/src/d_main.cpp
In file included from /run/build/gzdoom/src/g_pch.h:32,
                 from <command-line>:
/run/build/gzdoom/src/common/utility/tarray.h:672:9: warning: template-id not allowed for destructor in C++20 [-Wtemplate-id-cdtor]
  672 |         ~TDeletingArray<T, TT> ()
      |         ^
/run/build/gzdoom/src/common/utility/tarray.h:672:9: note: remove the ‘< >’
/run/build/gzdoom/src/d_main.cpp: In function ‘int D_DoomMain_Internal()’:
/run/build/gzdoom/src/d_main.cpp:3621:24: error: incomplete type ‘PType’ used in nested name specifier
 3621 |                 PType::StaticInit();
      |                        ^~~~~~~~~~
```

Is there any chance to have an official 4.10.1 version to address issues with modern compiler?

**Comment by RicardoLuis0** [comment]
this isn't an issue on our end, it's an issue of your build environment having the wrong include path

**Comment by mbugni** [comment]
Thanks to @0strodamus comment, I solved by applying this [cumulative patch](https://github.com/flathub/com.moddb.TotalChaosRetro/blob/77fc27c2fb708577c52ec8c6f1b83d3c83b89a9a/gcc14.patch)
