### ISSUE TITLE
[BUG] Array accesses causing game crashes when the game closes

### ISSUE THREAD

**Issue by inkoalawetrust** [ZDoom/gzdoom#2019]
### GZDoom version

g4.11pre-149-gc3d99fa69

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

Windows 10 Pro 21H2

### Relevant hardware info

Ryzen 5600X, RTX 2060, the hardware doesn't really matter in this case.

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The bug is a hard crash that occurs due to accessing an array of states. When the access occur often enough, the game will still run fine. But then proceed to hard crash when its' closed. The stack traces always report an exception in the Garbage Collector.

Here is a barebones mod with just the code needed to trigger the crash:
[GZDoom GC Crash.zip](https://github.com/ZDoom/gzdoom/files/10857446/GZDoom.GC.Crash.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load the example mod (It replaces Imps with actors that trigger the crash)
2. Load a map with Imps or spawn a few in.
3. Have them attack you a few times, triggering the array accesses and the "I'm attacking pew pew." message.
4. Close the game after having the Imps attack you for a bit.

### Provide a Log

Here is the stack trace the Visual Studio debugger always returns when the crash occurs.
>	[Inline Frame] gzdoom.exe!GC::SweepObjects(unsigned __int64 count) Line 245	C++
 	gzdoom.exe!GC::SingleStep() Line 460	C++
 	gzdoom.exe!GC::FullGC() Line 568	C++
 	gzdoom.exe!D_Cleanup() Line 3825	C++
 	gzdoom.exe!GameMain() Line 3732	C++
 	gzdoom.exe!DoMain(HINSTANCE__ * hInstance) Line 268	C++
 	gzdoom.exe!wWinMain(HINSTANCE__ * hInstance, HINSTANCE__ * nothing, wchar_t * cmdline, int nCmdShow) Line 558	C++
 	[External Code]

**Comment by coelckers** [comment]
Works fine for me with latest master.

**Comment by inkoalawetrust** [comment]
Yeah I also haven't encountered this shutdown crash in some time. I recall Ricardo saying it was probably something to do with his changes to how dynamic arrays work. So he must've pushed a commit that fixes this at some point.
