### ISSUE TITLE
[BUG] 16× MSAA and 32× MSAA look identical to 8× MSAA when using Vulkan (but not OpenGL)

### ISSUE THREAD

**Issue by Calinou** [ZDoom/gzdoom#2021]
### GZDoom version

Git 2809e09d5

### Which game are you running with GZDoom?

Other

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Fedora 37

### Relevant hardware info

GeForce RTX 4090 (NVIDIA 525.89.02)

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

16× MSAA and 32× MSAA look identical to 8× MSAA when using Vulkan (but not OpenGL).

MSAA level is set here in the Vulkan renderer: https://github.com/ZDoom/gzdoom/blob/c3d99fa699ddeb88657fb5b0ca810dd10c26750b/src/common/rendering/vulkan/textures/vk_renderbuffers.cpp#L42-L62

This may be a Vulkan limitation rather than a bug ([an example of this occurring in the wild](https://github.com/godotengine/godot/issues/37917)). In this case, a warning should be printed when selecting 16× MSAA or 32× MSAA when using Vulkan, and the user should be advised to use a resolution scale above `1.0` to achieve a similar effect instead.

*Click to view images at full size, then click again to use 1:1 scale in the browser.*

### OpenGL

Notice how the texture is antialiased, because 16× MSAA is actually implemented as 4× SSAA + 4× MSAA in the graphics driver. (This is what makes it slow at higher resolutions, since the 3D buffers are internally rendered at 8K when targeting a 4K resolution. Nonetheless, it's still viable on high-end GPUs, even at 120+ FPS.)

![Screenshot_20230304_100231](https://user-images.githubusercontent.com/180032/222887491-63f03420-2c86-47da-8d0b-6bd5210aa494.png)

### Vulkan

Notice how the texture is no longer antialiased by SSAA, but 8× MSAA is still working on the edge in the bottom-right corner:

![Screenshot_20230304_100259](https://user-images.githubusercontent.com/180032/222887506-f290c85f-26b1-4b8d-862e-91a4f820e55f.png)

### Steps to reproduce the behaviour.

1. While using OpenGL, enter `gl_multisample 16` or `gl_multisample 32` in the console.
2. Switch to Vulkan (**Options > Set Video Mode**, then restart).
3. Compare visual results using screenshots.

### Your configuration

[gzdoom.ini](https://github.com/ZDoom/gzdoom/files/10887921/gzdoom.txt)

**Comment by dpjudas** [comment]
This is indeed a Vulkan limitation, presumably because the hardware itself does not support more than 8x MSAA for a R16G16B16A16_SFLOAT frame buffer.

What OpenGL does instead is unknown - possibly it changes the frame buffer format itself from RGBA16F to RGBA8 or RGBA32F. Basically OpenGL gives some guarantees that the hardware cannot always do and then the actual hardware uses a different format than request. A different example of this is rgw D24S8 format, which AMD doesn't support. For OpenGL the AMD driver uses a different format, while Vulkan forces the application to pick something else.
