### ISSUE TITLE
[BUG] OkayToSwitchTarget not being called sometimes?

### ISSUE THREAD

**Issue by Derpford** [ZDoom/gzdoom#2024]
### GZDoom version

GZDoom 4.10.0

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 11

### Please describe your specific OS version

Windows 11 Home

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I dug up an [old, old project](https://github.com/Derpford/cyberpunkshootout) where I was trying to create some semi-complicated AI behavior. Basically, I have an Inventory called a NoiseMaker, and both the player and most monsters have a NoiseMaker, and monsters are intended to target whatever the *noisiest* thing they can detect is, assuming it's not of their species and it has enough noise to clear the monster's noise floor. I.e., a riot cop might target one of the random bystanders instead of the player, if that random bystander has enough noise.

I accomplish this by [overriding OkayToSwitchTarget](https://github.com/Derpford/cyberpunkshootout/blob/main/zscript/monsterbase.zs#L32), and returning true only if the new target is within detection range, above the noise floor, and is noisier than the current target. In theory, this should mean that monsters *only* switch to targets which have a NoiseMaker and meet the requirements for targeting the NoiseMaker's owner.

However, the behavior around OkayToSwitchTarget is weird. Sometimes, what I get out of my print debugging is baffling--like, for example, something inexplicably calls OkayToSwitchTarget on one of the player's weapons, even though it isn't even the weapon the player has out, and even though the function *should* return before printing anything if it's called on something that is neither +SHOOTABLE nor a NoiseMaker. In addition, if a monster kills its current target while the player is in LoS, OkayToSwitchTarget never gets called *at all*, but the monster switches targets to the player anyway. I can't tell where this target-switch is happening and it's driving me insane, because it retargets to the player even in situations where the player *shouldn't* be targetable (like when the player is emitting 0 noise).

### Steps to reproduce the behaviour.

To reproduce the unchecked target switch:
1. Override OkayToSwitchTarget in such a way that the player is no longer a valid target, but some other mobjs are.
2. Set up a monster so that it'll target something other than the player, while the player is within line of sight.
3. Wait for the monster to kill its current target. Make sure you're in LOS when this happens.
4. The monster will immediately switch targets to the player, without calling OkayToSwitchTarget.

**Comment by Derpford** [comment]
So I've worked out what was driving the weird "calling OkayToCheckTarget on an unready weapon" behavior. *That* was driven by me not realizing that items in a player's inventory will use FindInventory as if they're the player (since inventories are a linked list).

Still having the problem with unchecked target switches. And when I call a function every frame that sets the monster's target, it *STILL* targets the player instead...

**Comment by Derpford** [comment]
And if I set the target every tick *before* calling the function that picks a target based on noise...the monster stops targeting anything at all!?!? If I do all my target-checking logic before calling Super.Tick(), the logic for actually following a target seems to just *stop*.

How the hell does the `target` pointer even work? If I set it to something before calling `Super.Tick()`, then everything that runs in `Super.Tick()` should use the new target, not null. Since--near as I can tell--all state logic is handled by `Tick()`, this means that everything in the state logic should use the new target too. But instead, setting `target` before `Super.Tick()` makes the monster behave as if it has no target, and setting the target *after* `Super.Tick()`...means that the monster *ignores* my target selection logic. None of this makes any sense!

**Comment by Derpford** [comment]
I *have*, however, figured out that monsters automatically target...the player, when hurt. Which is counterintuitive, because this is infighting, and infighting monsters don't target the player, they target *each other*. I continue to wonder how the hell the target pointer even works, because it's not consistently pointing to things that a monster would be targeting. Maybe the +FRIGHTENED flag is causing weird behavior, I don't know.

**Comment by prof-hastig** [comment]
This is all because this is not what the function is for. Its only call is when a monster gets damaged for checking if it should switch its target to the one that just hurt it.

**Comment by coelckers** [comment]
Yeah, it's a clear case of misunderstanding the purpose of the function.
It cannot be changed because it is essential engine logic.

**Comment by Derpford** [comment]
The wiki just says it's called to see if switching targets is acceptable. It doesn't say anything about the function only being used for switching targets *when damaged* specifically. Someone should update that.

IMO, it would be really convenient for developing both mods and standalone games to be able to modify monster AI on that level, but at this point I'm already using a reimplementation of A_Chase in zscript to make it work (and also to use vel-based movement instead of step-based movement), so strictly speaking, I've already solved it on my end.

**Comment by coelckers** [comment]
That doesn't matter. The Wiki is wrong and the function cannot be changed to suit your needs because it'd break the engine.

**Comment by Derpford** [comment]
Could we expose this to zscript in another virtual function, then?

**Comment by Derpford** [comment]
I wish I could help, but I have basically no C++ experience, let alone experience with how GZDoom handles exposing logic to ZS. The dead-simple approach, from my perspective, would be to simply reimplement the existing enemy acquisition code in ZScript and then go from there--but I have no idea what that would actually entail.
