### ISSUE TITLE
[BUG] Plane equation slope rendering glitch with negative sector heights

### ISSUE THREAD

**Issue by biwa** [ZDoom/gzdoom#2026]
### GZDoom version

GZDoom 4.11pre-150

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

Windows 10 Home

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Example map: [slope-negative-sector-height.zip](https://github.com/ZDoom/gzdoom/files/10951003/slope-negative-sector-height.zip)

When having negative sector heights (i.e. the sector's ceiling is below the sector's floor) and using plane equation slopes 1-sided walls will be drawn around the sector. This only happens in with the hardware renderers, with the software renderers it works fine.

Vulkan/OpenGL:

![grafik](https://user-images.githubusercontent.com/6475593/224548470-3012cfac-fa01-4209-913b-1af8410ab0d4.png)

Software:

![grafik](https://user-images.githubusercontent.com/6475593/224548503-02ef0511-9d93-454f-9ef1-93cf96bdb58f.png)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. draw a sector with floor height of 0, ceiling height of 128
2. set a plane equation slope to the floor
3. set the sector's floor height to 256

**Comment by coelckers** [comment]
fixed in f7c379b7202dc04d35b2d85ade9d82ff88655eff
