### ISSUE TITLE
[Feature] on/off switch to look like software rendering

### ISSUE THREAD

**Issue by nr1995** [ZDoom/gzdoom#2028]
### Which game are you running with GZDoom?

None

### What Operating System are you using?

None

### Is your feature request related to a problem? Please describe.

There's no easy way to make the game look like software rendering,
while keeping the performance of hardware rendering.
You can go through and change multiple settings one-by-one,
but it's not convenient.

### Describe the solution you'd like

Add a toggle switch in the in-game menu,
which when enabled, gives the appearance of software rendering,
while actually using hardware rendering.
While this switch is enabled,
all the other settings which affect these aspects of appearance,
are greyed-out.
This way you can switch between your personal preference,
and a very vanilla look, easily.

**Comment by coelckers** [comment]
It doesn't work that way that a simple toggle as suggested is poss
ible

**Comment by nr1995** [comment]
> It doesn't work that way that a simple toggle as suggested is poss ible

There are a bunch of existing settings and sliders you can change
to get it looking really close to software rendering though, right?
They couldn't just be adjusted all at once?

**Comment by mc776** [comment]
You can set up an alias that enters a bunch of console commands to give yourself a bunch of presets...

**Comment by nr1995** [comment]
> You can set up an alias that enters a bunch of console commands to give yourself a bunch of presets...

Oh that doesn't sound bad.
Can I bind them all to a single key and toggle back and forth?
How would I do that?

**Comment by mc776** [comment]
I don't know which cvars would be needed to emulate vanilla, but as far as structuring it goes here's what I've got in my autoexec to toggle a heavily customized zoom view. The explicit alias redefinitions are because it was made before the "rebind" function but it should suffice.

```
//removes weapon sprite, zooms in, adds a subtle scope effect
alias zoomin "alias zoomtog zoomout; crosshair 0; r_drawplayersprites 0; movebob 0.64; stillbob 0.25; testcolor eaf7fe 32; fov 26; crosshair 2; crosshaircolor d0f0e0;"

//set things back to all my usualview settings
alias zoomout "alias zoomtog zoomin; crosshair 0; testcolor ffffff 0; fov 90; movebob 0.25; stillbob 0; r_drawplayersprites 1; crosshair 2; crosshaircolor d0f0e0;"

//the actual alias I bind to a key
alias zoomtog "zoomin;"

//set everything to default when the game starts
zoomout
```

**Comment by nr1995** [comment]
> I don't know which cvars would be needed to emulate vanilla, but as far as structuring it goes here's what I've got in my autoexec to toggle a heavily customized zoom view. The explicit alias redefinitions are because it was made before the "rebind" function but it should suffice.
> 
> ```
> //removes weapon sprite, zooms in, adds a subtle scope effect
> alias zoomin "alias zoomtog zoomout; crosshair 0; r_drawplayersprites 0; movebob 0.64; stillbob 0.25; testcolor eaf7fe 32; fov 26; crosshair 2; crosshaircolor d0f0e0;"
> 
> //set things back to all my usualview settings
> alias zoomout "alias zoomtog zoomin; crosshair 0; testcolor ffffff 0; fov 90; movebob 0.25; stillbob 0; r_drawplayersprites 1; crosshair 2; crosshaircolor d0f0e0;"
> 
> //the actual alias I bind to a key
> alias zoomtog "zoomin;"
> 
> //set everything to default when the game starts
> zoomout
> ```

Very helpful info, thanks.
