### ISSUE TITLE
[Feature] ACS: CVar variable "use_joystick" cannot be obtained via GetActivatorCVar or GetUserCVar. GetCVar only.

### ISSUE THREAD

**Issue by WNC12k** [ZDoom/gzdoom#2032]
### GZDoom version

4.10.0

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 10

### Is your feature request related to a problem? Please describe.

ACS: CVar variable "use_joystick" cannot be obtained via GetActivatorCVar or GetUserCVar. GetCVar only.

Is that what it's supposed to be? Or is it not a refinement?

### Describe the solution you'd like

Add ability to get value of CVar variable "use_joystick" via GetActivatorCVar and GetUserCVar.

**Comment by coelckers** [comment]
This is because use_joystick is not a user CVAR, it's an engine CVAR, so you got to fetch it with either GetCVar or by using 'use_joystick' directly.
