### ISSUE TITLE
[BUG] V-Sync issues with Vulkan and G-Sync Compatible

### ISSUE THREAD

**Issue by Player701** [ZDoom/gzdoom#2033]
### GZDoom version

4.10.0 and g4.11pre-153-gc041b437e

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 11

### Please describe your specific OS version

Windows 11 Pro 22H2 (Build 22621.1413)

### Relevant hardware info

NVIDIA GeForce RTX 4090, ASUS VG27AQL1A

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When using the Vulkan backend and G-Sync Compatible is enabled in NVIDIA Control Panel, every time the menu/console is opened and then closed, there is noticeable stuttering for a few seconds after that. I'm not exactly sure, but I think it's been happening ever since I built my new PC with an RTX 4090. The gzdoom.ini file is the same as it was on my old machine (RTX 2080 Ti).

The following workarounds can be used to mitigate this issue:

1. Using the OpenGL backend
2. Disabling G-Sync Compatible in NVIDIA control panel*
3. Setting `vid_maxfps` to a value slightly above the monitor's refresh rate of 144 Hz (e.g. 145)*
4. Forcing "Vertical sync" to "On" in NVIDIA control panel

Note that method no. 2 is not a viable solution because there are some maps where GZDoom cannot maintain a constant 144 FPS, and G-Sync Compatible helps provide a smooth gaming experience in such scenarios.

Method no. 3 also has side effects (visible screen tearing instead of stuttering).

Only methods no. 1 and no. 4 appear to have no significant side effects (but I guess OpenGL is slower?).

### Steps to reproduce the behaviour.

0. Make sure G-Sync Compatible is enabled.
1. Make sure the Vulkan backend is used and `vid_vsync` is `true`.
2. Launch GZDoom and load up any map.
3. Open the menu/console, wait a couple seconds, then close the menu/console.

Note that the in-game FPS counter briefly jumps above the monitor's refresh rate when the stuttering is triggered. It doesn't do this when any of the suggested workaround methods are used.

### Your configuration

https://gist.github.com/Player701/300f0c7464c99a90b01a5401eae75446

### Provide a Log

https://gist.github.com/Player701/5c5e912a36c940d09a27bc149e111772

**Comment by dezo2** [comment]
See #1813 - the problem is that Vulkan in GZDoom starts in some kind of borderless window, not in fullscreen. OpenGL works fine with GSync in GZDoom, but is slower in CPU intensive maps (i.e. Eviternity with weather effects active). I ended up with disabling VSync in GZDoom and forcing it in NV Control panel - seems much smoother that way, but no GSync with current build. Lets hope we get Vulkan exclusive fullscreen in some future version of GZDoom.

**Comment by Player701** [comment]
The problem is that I don't think I ever experienced this with my old PC. Perhaps it's something with the drivers, but I'm on the latest version, so not sure.

Also, forcing V-Sync in NVIDIA Control Panel does not disable G-Sync - I can confirm it according to the monitor's OSD. However, I would prefer not to fiddle with the control panel at all, if possible.

**Comment by dezo2** [comment]
I think the only option we have now is mentioned in #1813: Create a profile for GZDoom in NV control panel or NV profile inspector and set the "Vulkan/OpenGL present method" to "Prefer layered on DXGI swapchain" (0x00000001 in NVPI). It seems to be working on my GSync compatible monitor even with GZDoom 4.10.0 and Vulkan now. I am on driver 528.24 with my 3080ti.

**Comment by Player701** [comment]
It appears that something has changed in the recent NVIDIA driver release, and G-Sync no longer works in GZDoom with the Vulkan backend under the default setup. However, @dezo2's solution to enable "Prefer layered on DXGI swapchain" appears to solve the issue. Also, with that option enabled, forcing V-Sync in NVIDIA control panel causes some input lag, but ```vid_vsync``` does not.

**Comment by coelckers** [comment]
Exclusive fullscreen will come with the 5.0 update to vkDoom.
