### ISSUE TITLE
[Feature] UDMF 3D Floor Property

### ISSUE THREAD

**Issue by squidink7** [ZDoom/gzdoom#2035]
### GZDoom version

git master

### Which game are you running with GZDoom?

Other

### What Operating System are you using?

Linux x86_64

### Relevant hardware info

N/A

### Is your feature request related to a problem? Please describe.

Currently 3D floors are created through the use of Control Sectors, as WAD files traditionally couldn't contain enough information per-sector to support them, however now with modern extendable formats such as UDMF this workaround isn't needed anymore (for maps made using those formats anyway).

### Describe the solution you'd like

Adding a custom property to sectors and linedefs that contains all they need to be used as a 3D floor would reduce the need for control sectors and make mapping easier (assuming the editor supports these properties also), as a single sector could contain all the information it needs and can be configured all in one place, and doesn't cause a buildup of small triangles (or however one chooses to manage their control sectors) out of bounds that don't actually contribute to the level.

### Describe alternatives you've considered

I imagine this would be a gzdoom specific property (preferably designed with the assumption that other source ports may also choose to support it later down the line), however even better would be adding it to the UDMF specification, however as 3D floors aren't universally supported across ports that might pose a challenge.

### Add any other context or screenshots about the feature request here.

I'm new to Doom mapping so I don't know exactly where would be the best place to put this. I couldn't find a repo anywhere that tracked UDMF specifically, but even if there was one not every source port supports 3D floors so the next best place I thought of would be here. If there is anywhere better I should put then please let me know and I'll close the issue.

**Comment by coelckers** [comment]
Cannot be done, the control sectors are physically necessary to use a 3D floor.
