### ISSUE TITLE
[BUG] Commit with Turkish font system crashes on engine start

### ISSUE THREAD

**Issue by nashmuhandes** [ZDoom/gzdoom#2041]
### GZDoom version

7e1982fa65f154f5f99f9c39659a926bdc712434

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

GZDoom will crash upon engine start (after the IWAD picker). Caused by commit https://github.com/ZDoom/gzdoom/commit/7e1982fa65f154f5f99f9c39659a926bdc712434 and onwards.

Have 100% confirmed that one commit before that one, the app doesn't crash.

My build environment is: Windows 10, Visual Studio 2019, Windows SDK 10.0.19041.0

### Steps to reproduce the behaviour.

Explain how to reproduce
1. 
2.
3.

**Comment by coelckers** [comment]
That wasn't supposed to be committed. The code is completely untested right now.

**Comment by coelckers** [comment]
fixed in 25c984ff6e52d28d5a751da1dd1cf17d12281967
