### ISSUE TITLE
[BUG] MyHouse.pk3 crash reports with reproduction gamesave

### ISSUE THREAD

**Issue by Macil** [ZDoom/gzdoom#2050]
### GZDoom version

4.10.0

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

Windows 10 Home

### Relevant hardware info

Intel i7-6900K, Nvidia 2080 Ti

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Playing the new map [myhouse.pk3](https://gateway.pinata.cloud/ipfs/QmT7d1oUSHwoaQtNFSoaWN8RQzeCkNfcTcq9wPNKnZm7Eh/myhouse_20230326/myhouse.pk3) (the March 26 version, sha256 582D57710731400F14B39C9E4ADC48F6C67A835DE0C004B3529E2C33023BC433, which I've linked here because it's no longer the latest version linked from [the official thread](https://www.doomworld.com/forum/topic/134292-myhousewad/)) with Doom 2.

While playing late into the map, I saved the game, and then several minutes later seconds after getting killed by monsters, my game crashed. Crash 1: [CrashReport.zip](https://github.com/ZDoom/gzdoom/files/11227860/CrashReport.zip)

Next, I loaded my most recent save: [save00.zip](https://github.com/ZDoom/gzdoom/files/11227884/save00.zip). The menu melted away showing the loaded level, but the instant the animation finished, the game crashed again. Crash 2: [CrashReport2.zip](https://github.com/ZDoom/gzdoom/files/11227864/CrashReport2.zip). The game always crashes immediately after loading this save, unless I switch to the software renderer first.

(I assume these crashes are related. Sorry if they turn out to not be and I've unnecessarily grouped them.)

(Thankfully I had an older save within the level I was able to revert back to and make progress from. I have not crashed since except when using the bad save.)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Extract save00.zds from [save00.zip](https://github.com/ZDoom/gzdoom/files/11227884/save00.zip) into your save folder.
2. Launch Gzdoom with myhouse.pk3. Use OpenGL or Vulkan renderer.
3. Load the save. The game should crash as soon as the menu melt animation is over.

### Your configuration

```ini
(Very fresh config with just control changes)
```

**Comment by coelckers** [comment]
No crash for me with this savegame.

**Comment by coelckers** [comment]
I can't do anything here so off this goes.

**Comment by Macil** [comment]
Are the crash reports useful here?
