### ISSUE TITLE
[Feature] Pointer controls / movable crosshair

### ISSUE THREAD

**Issue by puddydoo** [ZDoom/gzdoom#2052]
### GZDoom version

4.10.0

### Which game are you running with GZDoom?

None

### What Operating System are you using?

None

### Is your feature request related to a problem? Please describe.

There could be added a mode for mouse control where the mouse moves the crosshair rather than the camera. This is like how motion controlled aiming works in Wii games, and it would be a good way to play GZDoom using motion controls (if using an external program to map mouse movement to the motion controller) or just a new way to aim with the mouse in GZDoom.

### Add any other context or screenshots about the feature request here.

https://www.gamedeveloper.com/design/point-and-shoot-lessons-in-wii-fps-control

**Comment by coelckers** [comment]
There's absolutely no context in which the game could do such a thing.
