### ISSUE TITLE
Missing patches in gzdoom.sf2 SFX kit

### ISSUE THREAD

**Issue by TristanClark97** [ZDoom/gzdoom#2054]
### GZDoom version

GZDoom 4.10.0

### Which game are you running with GZDoom?

Doom

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

In gzdoom.sf2, notes 27-38 are not defined for the SFX drum kit, so when using this soundfont, those notes will be silent. This is incompatible with the behaviour of the Microsoft GS Wavetable Synth, where notes 27-38 in the SFX kit are duplicated from the standard kit.

I've made a small WAD to demonstrate the issue, the test MIDI is for MAP01 of Doom 2. I've also included an edit of the soundfont which fixes the issue:
[SFXkit_test.zip](https://github.com/ZDoom/gzdoom/files/11261559/SFXkit_test.zip)
[gzdoomsf2-tristan.zip](https://github.com/ZDoom/gzdoom/files/11261555/gzdoomsf2-tristan.zip)

Sorry if this is in the wrong place or anything, I've never used github before!

### Steps to reproduce the behaviour.

Go to Doom 2 MAP01 with fluidsynth + gzdoom.sf2 set, you should hear the wind and nothing else.
In Microsoft GS Wavetable Synth, and when using gzdoom-tristan.sf2, you'll hear the rest of the notes - most importantly kick and snare drums.

**Comment by coelckers** [comment]
Sorry, I didn't realize you attached a fixed version. Surely we can use it then

**Comment by coelckers** [comment]
I replaced the sound font in the distribution package. Linux and macOS will have to update it once the Windows version is out.

**Comment by Eonfge** [comment]
@coelckers Can this updated file be added to the repository, replacing the old sf2 font? Right now, Linux downstream packages will use a different soundfont then intended.

**Comment by madame-rachelle** [comment]
I already updated it, but it's missing in the tag. Anybody who compiles from tag gets the old sound font. I'm hoping we get a 4.11.1 release to address this.
