### ISSUE TITLE
[BUG] Linux version of GZDoom puts saves in the wrong place.

### ISSUE THREAD

**Issue by yum13241** [ZDoom/gzdoom#2056]
### GZDoom version

GZDoom 4.10.0

### Which game are you running with GZDoom?

None relevant

### What Operating System are you using?

EndeavorOS Linux Rolling (basically arch)

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

On Linux, my save games get dumped into `~/.config/gzdoom/`. With all the filter folders there. So here's what the directory tree would look like
`autoexec.cfg doom.id.wadsmoosh fm_banks gzdoom.ini screenshots skins soundfonts`.

On Windows, they get saved into `$PROGDIR/Save`.

This makes it harder for me to seamlessly open my saves across OSes.

`-savedir` is also broken. If I set it to `~/path-to-ntfs-drive/Apps/GZDoom/Save` then it refuses to look inside filter folders.

### Steps to reproduce the behaviour.

Explain how to reproduce:
Prerequisites: You must have a Linux machine. 

1. Open GZDoom
2. Save a game.
3. Type `ls ~/.config/gzdoom`
4. You won't see a `Save` folder.

**Comment by vitalkanev** [comment]
> On Windows, they get saved into $PROGDIR/Save.

A quick correction:
They changed that recently. The save files now live in `[User folder]/Saved Games/GZDoom`.

**Comment by yum13241** [comment]
I use `gzdoom_portable.ini`, so no.

**Comment by alfred-don** [comment]
Can confirm.

**Comment by coelckers** [comment]
This was fixed recently
