### ISSUE TITLE
[BUG] ACS: repeat argument in SetLineActivation function does not work

### ISSUE THREAD

**Issue by franzmondlichtmann** [ZDoom/gzdoom#2058]
### GZDoom version

GZDoom 4.10.0

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

Pro

### Relevant hardware info

Nvidia RTX 2080 Super, Intel i7-6700K CPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Argument "repeat" does not work. And "repeat" argument is missing in the tooltip, too.

Following function as stated in the zdoom wiki:
`SetLineActivation (int lineid, int activation [, int repeat])`

Wiki further states:
Value Greater than 0 | Can be activated multiple times

Example: 
`SetLineActivation(42, GetLineActivation(42) | Spac_Use, 1);`
Gives an error:  Incorrect Number of Arguments.

**Comment by Blue-Shadow** [comment]
> And "repeat" argument is missing in the tooltip, too.

> Example: `SetLineActivation(42, GetLineActivation(42) | Spac_Use, 1);` Gives an error: Incorrect Number of Arguments.

The [ACC](https://zdoom.org/wiki/ACC) version that comes with [Ultimate Doom Builder](https://github.com/jewalky/UltimateDoomBuilder), which I'm assuming is what you're using as your map editor, is outdated.

**Comment by franzmondlichtmann** [comment]
Ultimate Doom Builder is using an old version of ACC (1.57), wile the newest Version is 1.59
I switched out the compiler with the newer version, and voila SetLineActivation(42, GetLineActivation(42) | Spac_Use, 1); works!
1.57 is from 30 Oct 2020
1.59 is from 9 Nov 2022
