### ISSUE TITLE
[BUG] The "restart" CCMD is broken.

### ISSUE THREAD

**Issue by yum13241** [ZDoom/gzdoom#2061]
The bug: Let's say you are in Freedoom. You, also have some mod in your autoloads (like Hellscape Navigator) which prints out the map name. It doesn't get updated. I've tested with Wadsmoosh.

How to reproduce:
1. Put a mod that prints the map name, like Hellscape Navigator, in your autoloads.
2. Launch FreeDM. (regular Freedoom works here but I'll be assuming that you use FreeDM)
3. Start a new game.
4. Type `restart -iwad doom_complete.pk3` in the console.
5. Start a new game.
6. Welcome to Tech Test (FreeDM's MAP01)? I thought I was in Entryway?!

**Comment by coelckers** [comment]
It has something to do with Hellscape Navigator's data storage in CVARs which manage to survive the restart. I'm not going to mess around with this as it may do more harm than good.

**Comment by coelckers** [comment]
Some weird C++ voodoo going on here, addressed in 7f7edc4f72417bed52c2aa7bbd8c2f73f7650ec3
