### ISSUE TITLE
[BUG] After an error, controllers don’t work for a while

### ISSUE THREAD

**Issue by G-F-D** [ZDoom/gzdoom#2063]
### GZDoom version

g4.11pre-178-g39cea95db

### Which game are you running with GZDoom?

None

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

Windows 10 Pro 22H2 (19045.2846)

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

After an error, it will take some time before controllers start working again. This seems to apply to both DirectInput and XInput controllers on Windows. The amount of time it takes until controllers start working again is equal to the amount of time that they had been working during the current session. (So, if an error occurs 20 seconds after starting GZDoom, it will take 20 seconds after the error until controllers start working again, and if a second error occurs 5 seconds after controllers started working again, it will take 20+5=25 seconds until controllers work again after that second error.)

This is reproducible with default settings (aside from having to enable controllers).

### Steps to reproduce the behaviour.

1. Start GZDoom with any IWAD and confirm that a controller device works.
2. Open the console and use the `error` CCMD.
3. Exit the console, hold a direction on the controller device, and wait for it to start working again.

**Comment by coelckers** [comment]
I have absolutely no idea what to do with this, and considering that it has gotten no feedback whatsoever I am forced to close it.
