### ISSUE TITLE
[BUG] Class selection screen does not translate colors

### ISSUE THREAD

**Issue by alfred-don** [ZDoom/gzdoom#2065]
### GZDoom version

4.10.0

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Ubuntu 22.04.2 LTS

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Player sprites are not color-translated in the class selection screen.
**How it looks in the class select screen:**
![image](https://user-images.githubusercontent.com/116238340/236370691-05db588b-d90b-47be-adaf-4cfb59778bc1.png)
**How it should look (and does in-game)**
![image](https://user-images.githubusercontent.com/116238340/236370804-6a1b073a-7af2-49f9-abb2-2b983c037489.png)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Create a new player class, and add it to the menu.
2. Change the default color translations for the class.
3. Notice the inconsistency.

**Comment by madame-rachelle** [comment]
Hey, one thing that would be really helpful is if you could tell us whether you are using OpenGL, OpenGLES, or Vulkan, and if the problem persists in the other renderers (if you are able to use them). Thank you!

**Comment by alfred-don** [comment]
> Hey, one thing that would be really helpful is if you could tell us whether you are using OpenGL, OpenGLES, or Vulkan, and if the problem persists in the other renderers (if you are able to use them). Thank you!

In all the rendering backends I experience the same issue. Also, same with the software renderers too. I normally use OpenGL though.

I don't think it's exactly related to the renderer, it's more of a design oversight.

**Comment by coelckers** [comment]
Please post a runnable example. Before fumbling around with this I'd like to see a player class that exhibits the problem.

**Comment by coelckers** [comment]
Closing due to lack of response by the OP.
