### ISSUE TITLE
[BUG] Actors using A_Wander and +CANTLEAVEFLOORPIC will not go up or down slopes

### ISSUE THREAD

**Issue by alfred-don** [ZDoom/gzdoom#2067]
### GZDoom version

GZDoom 4.10.0

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Ubuntu 22.04.2 LTS

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I have a car that traverses roads in my mod that uses A_Wander to go along the area and turn when necessary.
To keep the actor in roads, I use the actor flag `CANTLEAVEFLOORPIC`. If the car attempts to go up or down a slope, it turns around like it went onto a different flat.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Create an actor that uses a_wander (I use it like this: `A_Wander(CHF_NORANDOMTURN)`)
2. Give it the flag `+CANTLEAVEFLOORPIC`
3. Spawn it in a map with slopes.
4. Notice that it does not go up or down slopes, it instead turns around.

**Comment by prof-hastig** [comment]
This seems to be an inherent limitation of the CANTLEAVEFLOORPIC flag. This flag not only blocks moves into sectors with other textures but also into positions with different floor height, which by definition excludes slopes.

It was just a very crude means in Hexen to keep those Stalkers in the water and never got refined.

**Comment by coelckers** [comment]
I'M not going to change the handling of this flag.
