### ISSUE TITLE
[BUG] Gzdoom doesn't follow changes to default audio device

### ISSUE THREAD

**Issue by Macil** [ZDoom/gzdoom#2068]
### GZDoom version

4.10.0

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

If you change your default audio output while Gzdoom is running (such as switching from speakers to headphones), Gzdoom doesn't change audio output devices. Other programs and games I use do handle switching the audio output device while they're running.

I've found I can manually work around this by using the console command "snd_reset" which causes Gzdoom to respect the current output.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Start Gzdoom.
2. Switch your default output device (like by using the sound icon in the system tray).
3. Continue hearing Gzdoom output to the original device.

**Comment by Player701** [comment]
This has been present for ages, so I don't think it's really a bug; rather, an unimplemented feature or a limitation of the current system.

**Comment by coelckers** [comment]
Short of constantly polling the system this cannot be done easily. As it is more or less a fringe case I don't think we need to bother.
