### ISSUE TITLE
[Feature] Unified StartGame function for Zscript UIs

### ISSUE THREAD

**Issue by Lemon-King** [ZDoom/gzdoom#2070]
### GZDoom version

GZDoom 4.11-pre178

### Which game are you running with GZDoom?

Other

### What Operating System are you using?

Windows 11

### Relevant hardware info

NVidia, AMD CPU, 32 GB System Ram

### Is your feature request related to a problem? Please describe.

There is a lack of a clear custom start game function using when using a custom zscript ui - like with zforms.

Currently we have to stack calling Menus (Episode, Skill, StartGame) with the proper params to start the game when using a custom zscript ui.

### Describe the solution you'd like

Something akin to this: `Menu.StartGame(<PlayerClass>, <Episode>, <Skill Level>)` or a little more expanded where playerclass can be a string.

I do understand this would be far more flexible with supporting functions which would return information available in GameInfo, such as Player Classes, Episodes and SkillLevels by class as defined.

`Array<String> classes = Menu.GetPlayerClasses()`
`Array<String> episodes = Menu.GetEpisodes()`
`Array<String> skillLevels = Menu.GetSkillLevels(playerclass)`
_Id would be defined by array index._

### Describe alternatives you've considered

The current work around I'm using is just calling each menu consecutively, like such.

`Menu.SetMenu("EpisodeMenu", selectedClass);    // Class Selection Response`
`Menu.SetMenu("SkillMenu", selectedEpisode);    // Episode Selection Response`
`Menu.SetMenu("StartGame", selectedSkill);      // Skill Selection Response (Starts Game), Use StartgameConfirm for Nightmare skills`

### Add any other context or screenshots about the feature request here.

In-Game Demo: https://www.youtube.com/watch?v=M8oPTwD66k0

Example used in my project: https://github.com/Lemon-King/HXDD/blob/main/src/main/resources/assets/zscript/menu/newgame.zs#L31

**Comment by coelckers** [comment]
You know, I am just happy that your workaround actually works. :)

**Comment by nashmuhandes** [comment]
Implemented in 736d38e8c33d86f7e4f126839148bc78aeffab08, can be marked as done
