### ISSUE TITLE
[BUG] Setting "Jumping disable" to "thrue" via the game menu rresets to default (enabled again) after exitting the Game. Same with "crouch"

### ISSUE THREAD

**Issue by sportsterv90** [ZDoom/gzdoom#2080]
### GZDoom version

4.10.0 x64

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 11

### Please describe your specific OS version

Pro

### Relevant hardware info

r7 5700x/gtx1070

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Setting "Jumping disable" to "thrue" via the game menu resets to default (enabled again) after exiting the Game. Same with "crouch".

### Steps to reproduce the behaviour.

Explain how to reproduce
1. 
2.
3.

**Comment by Player701** [comment]
This is by design, see [here](https://forum.zdoom.org/viewtopic.php?f=4&t=70438) for a workaround. In your particular case, you can add the following commands to ```autoexec.cfg```:

```
sv_jump 1
sv_crouch 1
```

**Comment by sportsterv90** [comment]
Yea, it works! Thank you for respond!
