### ISSUE TITLE
[BUG] libvpk installed but not found by CMake

### ISSUE THREAD

**Issue by zackgreen16** [ZDoom/gzdoom#2082]
### GZDoom version

GZDoom 4.10.0, Git Version

### Which game are you running with GZDoom?

None

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Nobara Linux 37

### Relevant hardware info

Intel Celeron N3450 (4) @ 2.200GHz

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

While compiling gzdoom I ran the following command:

```
cd ~/gzdoom_build/gzdoom/build && rm -f output_sdl/liboutput_sdl.so && if [ -d ../fmodapi44464linux ]; then f="-DFMOD_LIBRARY=../fmodapi44464linux/api/lib/libfmodex${a}-4.44.64.so \ -DFMOD_INCLUDE_DIR=../fmodapi44464linux/api/inc"; else f='-UFMOD_LIBRARY -UFMOD_INCLUDE_DIR'; fi && cmake .. -DCMAKE_BUILD_TYPE=Release $f && make -j$c
```

And I got this error

```
CMake Error at src/CMakeLists.txt:373 (message):
  Could not find libvpx
```
Then I ran this command

```
sudo dnf install libvpx
```

And it output this

```
Last metadata expiration check: 2:19:12 ago on Mon 22 May 2023 11:14:05.
Package libvpx-1.12.0-1.fc37.x86_64 is already installed.
Package libvpx-1.12.0-1.fc37.i686 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
```

**Comment by Talon1024** [comment]
You may need to install `libvpx-devel`, since that package contains the header files that the compiler needs to link with `libvpx`.

**Comment by zackgreen16** [comment]
Thank you very much, It worked
