### ISSUE TITLE
[BUG] (MBF21) A_CheckAmmo not working

### ISSUE THREAD

**Issue by skillsawed** [ZDoom/gzdoom#2086]
### GZDoom version

Current dev build (gzdoom-x64-g4.11pre-185-g245dac814)

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 11

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

[checkammo_bug.zip](https://github.com/ZDoom/gzdoom/files/11671305/checkammo_bug.zip)

MBF21 codepointer A_CheckAmmo does not behave as it does in other ports - in this case, it fails to switch states when appropriate conditions are met.

The attached wad file contains a custom weapon in the chainsaw slot, which uses cell ammo. The weapon uses A_CheckAmmo to act as if it is in a powered up state if the player has 5 or more cells; otherwise, it should be in an unpowered state. This works as expected in DSDA-Doom (complevel 21) and Woof, but not in GZDoom.

I'm speculating but I wonder if this may have something to do with replacing the chainsaw and giving it an ammo type (cells), which may be causing a disconnect somewhere?

### Steps to reproduce the behaviour.

Explain how to reproduce
1. In GZDoom, run the attached wad file and go to MAP01 (using Doom 2 as IWAD).
2. Pick up the weapon and attack until you run out of ammo. Notice that the sword remains powered up (A_CheckAmmo is not changing states).
3. Run the attached wad file in DSDA-Doom (complevel 21) or Woof and go to MAP01. Attack until you run out of ammo. Notice that the sword powers down (A_CheckAmmo is changing states).

I included the decohack source as an embedded lump if that is helpful.

**Comment by Dynamo128** [comment]
This appears to have been fixed, at least as far as I can see from the post by RicardoLuis0, so it should probably be closed.
