### ISSUE TITLE
[BUG] GZdoom 4.10 Bad numeric constant with Dehacked patch and Samsara Reincarnation

### ISSUE THREAD

**Issue by LuciferSam8086** [ZDoom/gzdoom#2090]
### GZDoom version

GZDoom 4.10

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

Win 10 Pro 10.0.19044.2965

### Relevant hardware info

Ryzen 5 5600x , Nvidia RTX 3070-TI

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

It does occur when I use Samsara reincarnation mod and ABSCISSION.wad and there are problems with DeHacked patch.

The mods are from there:
Abscission : https://www.doomworld.com/forum/topic/132593-abscission-dark-atmospheric-doom-ii-megawad-32-vanilla-maps-now-on-idgames/
Samsara : https://forum.zdoom.org/viewtopic.php?t=74652 . You will need only the Samsara-Reincarnation_V1.0b.pk3 file.

GZDoom 4.6 does not show this problem

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load AB.wad and then Samsara-Reincarnation_V1.0b.pk3
2. You will get the warnings

### Your configuration

```ini
https://gist.github.com/LuciferSam8086/14788b7a62e5e9637a151dca656b59d7
```

### Provide a Log

https://gist.github.com/LuciferSam8086/b89f633c4dd5297737ba22312c6188dc

**Comment by coelckers** [comment]
This looks like something that got fixed shortly after the 4.10 release, I cannot reproduce it with current master
