### ISSUE TITLE
Bracket crosshair and splitted square crosshair

### ISSUE THREAD

**Issue by bendqh1** [ZDoom/gzdoom#2093]
### GZDoom version

4.10.0

### Which game are you running with GZDoom?

Original DOOM games from the nineties.

### What Operating System are you using?

Windows 11

### Is your feature request related to a problem? Please describe.

No problem.

### Describe the solution you'd like

Please add bracket crosshairs:

    [ ]

And also splitted square crossharis (screenshot attached)

### Add any other context or screenshots about the feature request here.

https://ibb.co/CW6PK0V

**Comment by RicardoLuis0** [comment]
crosshairs can be added as mods, here's a quick one that i've made that should do what you want: [new_xhairs.zip](https://github.com/ZDoom/gzdoom/files/11994211/new_xhairs.zip)

**Comment by coelckers** [comment]
Clearly DIY.
