### ISSUE TITLE
[Feature]  GZdoom compiling instructions could be improved

### ISSUE THREAD

**Issue by ffaf1** [ZDoom/gzdoom#2095]
### GZDoom version

GZDoom 4.10.0

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Linux x86_64

### Is your feature request related to a problem? Please describe.

I have downloaded GZdoom to compile it from source on my machine. In order:
- I open the readme
- I get sent to `https://zdoom.org/wiki/` and click "Programmer’s corner"
- I clicked on Linux

The page is quite scary, with blobs of script which I did not understand at all, like

```
a='' && [ "$(uname -m)" = x86_64 ] && a=64
cd ~/gzdoom_build/gzdoom/build &&
h="$(sed -n 's/.*#define GIT_HASH "\(.*\)".*/\1/p' ../src/gitinfo.h)" &&
if [ -z "$(git describe --exact-match --tags $h 2>/dev/null)" ]; then
d=-alpha; else d=''; fi &&
o=output_sdl/liboutput_sdl.so && if [ -f "$o" ]; then l="$o \
../fmodapi44464linux/api/lib/libfmodex${a}-4.44.64.so"; else l=''; fi &&
if [ game_support.pk3 -nt zd_extra.pk3 ]; then p=game_support.pk3; else p=zd_extra.pk3; fi &&
sudo cp -rv gzdoom gzdoom.pk3 lights.pk3 brightmaps.pk3 game_widescreen_gfx.pk3 $p soundfonts fm_banks $l \
/usr/games/gzdoom$d/
```

The usual way (creating a build folder, cd into it, `cmake ..`) does not work because gzdoom requires zmusic. There is no indication on how to link zmusic if you prefer not to install it, so after another search I ended up tweaking `-DZMUSIC_INCLUDE_DIR` and `-DZMUSIC_LIBRARIES` (again, with trial and error on what to pass on those).

### Describe the solution you'd like

A simpler way, with maybe `git clone`, `git submodules`, `cmake ..`, `make`.

**Comment by RicardoLuis0** [comment]
cmake is the way to compile gzdoom -- zmusic is not a submodule, but a separate library, so you'd need to compile it separately as well, and point cmake to it: https://github.com/ZDoom/ZMusic (IIRC, if you don't want to install it globally, you can just change the `CMAKE_INSTALL_PREFIX` to a different folder)

**Comment by RicardoLuis0** [comment]
as for the instructions on the wiki, those commands are just examples of how to install the required libraries in each distro's package manager, so you only need to care about the ones for the distro you're using

**Comment by ffaf1** [comment]
> (if you don't want to install it globally, you can just change the CMAKE_INSTALL_PREFIX to a different folder, and point cmake to that folder when compiling gzdoom

Thanks, that should be added to the page then (I am unwilling to do this myself as I might or might not understand the intricacies of the build system).

> as for the instructions on the wiki, most of those commands are just examples of how to install the required libraries in each distro's package manager, so you only need to care about the ones for the distro you're using, […]

I am not saying those scripts are wrong, I am saying they are a mess. Have [this](https://wiki.scummvm.org/index.php?title=Compiling_ScummVM/GCC) as an example of a non-intimidating, clear, concise page on how to compile a piece of software. After installing dependencies, it takes one scroll to read the `Configure` and `Make` part.

**Comment by coelckers** [comment]
I generally agree, but if we do not get input from actual users things won't change. I'm closing it for now.
