### ISSUE TITLE
[Feature] Allow for changing settings without automatically saving them

### ISSUE THREAD

**Issue by Tasosgemah** [ZDoom/gzdoom#2096]
### GZDoom version

GZDoom 4.10.0

### Which game are you running with GZDoom?

Doom

### What Operating System are you using?

Windows 10

### Relevant hardware info

i5 4670, 16GB RAM, GTX 1060 6GB

### Is your feature request related to a problem? Please describe.

GZDoom has _a lot_ of settings and I would like to be able to experiment without worrying GZDoom will save them and i have to revert them back, or use a backup of the gzdoom.ini file every time i want my main settings back.

### Describe the solution you'd like

Best solution would be a "**don't save settings automatically**" option. With this enabled, you will only be able to save any changes manually since there's already a "save current settings" function in the menu, which makes no sense being there if GZDoom saves all changes automatically anyway.

### Describe alternatives you've considered

Another solution would be to allow GZDoom to use "read-only" .ini files. This way the .ini will always be protected as you randomly test various settings no matter what. But right now, GZDoom doesn't want to read such files. If i make my ini read-only, GZDoom ignores it completely and loads with "factory defaults", like when you use it for the first time.

**Comment by madame-rachelle** [comment]
GZDoom already has this in the form of "revert to last saved" which is available in the Options menu.

Its matching console ccmd is `reset2saved`.
