### ISSUE TITLE
[BUG] A_ChangeModel with CMDL_USESURFACESKIN will set the wrong surface sometimes

### ISSUE THREAD

**Issue by OrdinaryMagician** [ZDoom/gzdoom#2097]
### GZDoom version

c6978c23a

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Linux x86_64

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Calls to `A_ChangeModel` with `CMDL_USESURFACESKIN` appear to sometimes assign textures to a lower surface than specified.

This appears to be very situational, however, and I have only been able to reproduce it under specific circumstances.

The issue only began happening since the #2083 merge.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load [Codename: DEMOLITIONIST](https://github.com/OrdinaryMagician/swwmgz_m).
2. Go into chasecam.
3. The animated face texture (surface 1) will be applied to the color tags (surface 0).

Alternatively
1. Load the mod.
2. IDFA.
3. Fire the Wallbuster (slot 4) once and then reload.
4. The shell texture (surfaces 4 through 8) will be applied to the weapon itself (surface 3).

**Comment by RicardoLuis0** [comment]
This seems like it might've been a bug with the previous A_ChangeModel implementation, it has some very fucky array manipulation, so it probably assigned skin 4 to skin 5 -- skin 4 appears to be the base texture -- changing it in the source code to use skin 5 as the base instead of skin 4 it works properly

**Comment by OrdinaryMagician** [comment]
The base texture is skin 3. The indices start at 0.

**Comment by RicardoLuis0** [comment]
hmm...

**Comment by OrdinaryMagician** [comment]
That did the trick, thanks!
