### ISSUE TITLE
[Feature] Option for resolution-independent mouse cursor rendering

### ISSUE THREAD

**Issue by nashmuhandes** [ZDoom/gzdoom#2108]
### Which game are you running with GZDoom?

None

### What Operating System are you using?

None

### Is your feature request related to a problem? Please describe.

Currently, the mouse cursor graphic isn't scaled at all, making it look ridiculously small in high resolutions (try going 4k and above...)

I'd like some options to scale it so it looks the same regardless of resolution. Perhaps one that sizes it like as if the screen was 320x200, and another one that's 640x400, if the former is too chunky/pixel-ey for some people.

Alternatively, just any arbitrary scale - maybe some mods would like to include high res cursors as part of their UI design.

**Comment by prof-hastig** [comment]
You have to complain to your operating system here, it's just the system's cursor with a custom image.

**Comment by coelckers** [comment]
That's indeed the problem. The mouse cursor is not application rendered, all it does is give the system cursor a custom image, so it still comes with all the limitations the system imposes.
