### ISSUE TITLE
This line causes assertion failures on debug/ASan builds

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/gzdoom#2109]
https://github.com/ZDoom/gzdoom/blob/99850ea216ef13d56fb6e65e927aabd76d91b601/src/common/engine/serializer.cpp#L696

Shouldn't this line be removed? It causes assertion failures on debug/ASan builds, and causes the game to quit.

**Comment by coelckers** [comment]
Yes, it should be removed, of course.

That line was added to trigger a break into the debugger on Windows.
If non Windows system would handle assert correctly instead of just aborting it wouldn't be such a problem.

**Comment by Talon1024** [comment]
With regards to cross-platform debugger breakpoints in C/C++ code, I [found this on StackOverflow](https://stackoverflow.com/questions/4326414/set-breakpoint-in-c-or-c-code-programmatically-for-gdb-on-linux).
