### ISSUE TITLE
[BUG] Slight distortion of UI elements

### ISSUE THREAD

**Issue by samlay** [ZDoom/gzdoom#2111]
### GZDoom version

4.10

### Which game are you running with GZDoom?

Doom 2 and Heretic

### What Operating System are you using?

Windows 11 Home

### A clear and concise description of what the bug is.

Let me know if I've just missed something in my config ([here](https://gist.github.com/samlay/42693a269720071ef97d0af50e42bf8a)) but there's a couple of things I can't get looking quite right.

I run the game 320x200 windowed and then integer scale using Magpie or Marat Tanalin's integer scaler. I'm not trying to emulate tall DOS pixels or anything - just want simple 1:1 unscaled.

This affects Heretic more than Doom, specifically the ammo image for the equipped weapon and selected inventory item (interestingly on the inventory selection bar these render perfectly).

Here's the bad ammo on weapons 4 and 6:

https://i.postimg.cc/bYGdBDKh/badammo4.png

https://i.postimg.cc/43rj40Nw/badammo6.png

Here's the flask and tome rendering correctly in the item selection bar - this is how they should look:

https://i.postimg.cc/0y4BZ4mx/correct.png

And how they actually look when selected:

https://i.postimg.cc/NF063sqn/badflask.png

https://i.postimg.cc/kXvVQr06/badtome.png

In Doom it's just the end-of-level screen - most text here renders flawlessly but the map name is distorted:

https://i.postimg.cc/252F2bgW/doomtext.png

**Comment by samlay** [comment]
Only reason I'm posting this is that GZDoom gets SO close now to pixel-perfect faithfulness to the original it would be great to see it get the final 1% of the way (it's the only reason I still choose Zandronum).

**Comment by samlay** [comment]
I should also mention I've not tested Hexen or Strife but they are likely affected too.

**Comment by madame-rachelle** [comment]
I can confirm this bug is present, I will see what needs to be done to fix it but I can't make any promises.

**Comment by coelckers** [comment]
I'mk not going to bother with this. We really need full separation of 2D and 3D parts in the engine so that the 2D scaling artifacts can be kept to an absolute minimum.
