### ISSUE TITLE
[BUG] User's LightMode setting isn't migrated properly

### ISSUE THREAD

**Issue by nashmuhandes** [ZDoom/gzdoom#2117]
### Which game are you running with GZDoom?

None

### What Operating System are you using?

None

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Going from GZDoom 4.10 (with no devbuilds in between), upgrading straight to https://github.com/ZDoom/gzdoom/commit/f4dc16b27a1df3d8717b316276b8cac1ce323a17 has my lightmode set to `Uknown`. I was previously using `Vanilla` in 4.10.

Coincidentally, whatever the lightmode that `Uknown` seems to use appears to be the most visually unattractive. This may confuse a lot of users into thinking that GZDoom's lightmodes may be broken.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. 
2.
3.

**Comment by madame-rachelle** [comment]
I really was never a huge fan of that commit at all.

**Comment by nashmuhandes** [comment]
After some digging around, it seems @prof-hastig was responsible for this change - perhaps you could look into this, prof?

**Comment by prof-hastig** [comment]
This one is weird. It looks like the config migration does not work for CVARs that get range checked and clamped in their handler function. I think the only way to handle it is to rename the underlying CVAR so that proper migration can be performed

**Comment by coelckers** [comment]
The PR did not do what it advertised. Ultimately I stil don't know how this problem could surface. The handler function of gl_lightmode does proper validation.

@nashmuhandes Can you tell me what value gl_lightmode ended up for you? I'm at a loss how the bad value could get through the checks.

**Comment by coelckers** [comment]
Should be fixed now. The main problem here was a bad combination of CVAR flags that screwed up the migration.
And due to the changed meaning of this CVAR
