### ISSUE TITLE
[Feature] Steam release for GZDoom

### ISSUE THREAD

**Issue by palaashatri** [ZDoom/gzdoom#2120]
### GZDoom version

master

### Which game are you running with GZDoom?

Doom

### What Operating System are you using?

Windows 11

### Is your feature request related to a problem? Please describe.

It's sometimes frustrating to not have cloud saves support when using any Doom-engine based game using a source port. 

### Describe the solution you'd like

I was wondering if we could have a Steam release of GZDoom, something like a [RealRTCW](https://store.steampowered.com/app/1379630/RealRTCW/) mod for RTCW, which integrates with the base game as a mod, has achievements and cloud saves support.

Also having a GZDoom marketplace for featured mods would be INSANE.

**Comment by coelckers** [comment]
This is far, far beyond the scope of an open source engine for a 30 year old game.

**Comment by mc776** [comment]
incorporating this into the main GZDoom project sounds like an administrative nightmare... could this not be done already as an independent project?

**Comment by RicardoLuis0** [comment]
>  it automatically scans every WAD present in directories it has access to [...] something to go over to further improving the User Experience of an average Steam user who might be trying to play Doom on a Steam Deck/Console-style device

gzdoom already scans the steam/gog/etc directories for iwads, but the issue is that for it to be viable to launch as a steam game, it'd need to have a proper launcher built-in, since the current one only lets you pick iwads, not pwads, plus managing the steam page/updates/etc
