### ISSUE TITLE
[Request] is there gzdoom 4.8.2 binary under win 32?

### ISSUE THREAD

**Issue by eltakin** [ZDoom/gzdoom#2128]
### Which game are you running with GZDoom?

None

### What Operating System are you using?

Windows 7

### Relevant hardware info

CPU Intel Atom

### Is your feature request related to a problem? Please describe.

I could not build published source gzdoom 4.8.2 (Jul 4, 2022) for win32 os. where can i find win32 gzdoom 4.8.2 binaries?

**Comment by coelckers** [comment]
4.7.1 was the last release with 32 bit binaries. There won't be any more in the future.
