### ISSUE TITLE
[BUG] 4.11 crashing when run with Project Brutality 2.03

### ISSUE THREAD

**Issue by GrayFace** [ZDoom/gzdoom#2129]
### GZDoom version

gzdoom-x64-g4.11pre-275-g2261dde79

### Which game are you running with GZDoom?

Doom

### What Operating System are you using?

Windows 7

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When run with [Project Brutality 2.03](https://www.moddb.com/addons/project-brutality) or [Project Brutality 2.03 Performance Edition](https://www.moddb.com/mods/brutal-doom/addons/project-brutality-203-performance-edition)(smaller download), gzdoom-x64-g4.11pre-275-g2261dde79 version from https://devbuilds.drdteam.org/gzdoom/ crashes when loading into any level.

Here is the command line:
`"./gzdoom.exe" -iwad "../freedoom1.wad" -file "../PB/Project Brutality 2.03.pk3" +sv_cheats 1`

Same with doomu.wad.
Same with an empty gzdoom.ini.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Run specified command line
2. Press Enter 6 times to enter the first level in default mode
3. The game crashes

### Provide a Log

[CrashReport.zip](https://github.com/ZDoom/gzdoom/files/12364932/CrashReport.zip)

**Comment by RicardoLuis0** [comment]
Just tested on the latest commit, and i can't reproduce the crash, can you try it again on the latest commit, and if it still crashes, maybe send over your ini file?

**Comment by GrayFace** [comment]
Indeed the latest build works fine.
