### ISSUE TITLE
[BUG] Phocas Island 2 MAP01 teleporter bug

### ISSUE THREAD

**Issue by Dynamo128** [ZDoom/gzdoom#2140]
### GZDoom version

GZDoom 4.8.2, GZDoom 4.10.0

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

NOTE: I realize this is a problem involving a mod, rather than the engine itself, but the reason I am posting this here is because this to me sounds like something that could easily be fixed through automatic compatibility.

I have been playing the 2006 GZDoom mod, Phocas Island 2 (https://doomwiki.org/wiki/Phocas_Island_2), and I have encountered a map problem on MAP01. I am running version 4.8.2 (but I did quickly test version 4.10.0 and can confirm that the problem happens there also). At one point during the map, you have to descend a staircase in a tower which will teleport you to another side of the map. The problem is, on recent GZDoom versions, it will teleport you directly on top of an instakill floor. I tested an older GZDoom version I had lying around (1.6.0) and this does not occur there.

https://cdn.discordapp.com/attachments/496751869960650772/1146088474349420704/gzdoom_bugs.zip here are save games for both versions, correctly named so you know which is which. To reproduce, simply walk down a step to the right and you will be teleported on top of the 3d floor correctly in 1.6.0, or killed outright in 4.8.2.

Now, I've also looked at the actual map itself in Ultimate Doom Builder. The teleporter is triggered via linedef action (linedef 5367) which, upon being crossed, through action special 80 calls a script (script 6) which, looking at the script lump accompanying the map in Ultimate Doom Builder, is this:

//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
//Yet another height check for a telport line (tower)
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
script 6 (int whichway) {
	if(whichway == 1) {if(GetActorZ(255)/65336 > 1680) { terminate; } Teleport_NoFog(10); }
	if(whichway == 2) {if(GetActorZ(255)/65336 < 1556) { terminate; } Teleport_NoFog(11); } 
}

Worth noting that there are a few more similar scripts for height checking in the same map. Anyway, the first line in this script points to the relevant Mapspot thing (669, thing type 9001). But it works if I edit the map and replace the Map spot with a Teleport Z-Height thing (thing type 9044). So maybe this can be done via automatic compatibility? I will play the rest of the mod and report if I find similar issues, but given that the author of Phocas Island 2 has, I believe, long left the community, and if automatic compatibility can be used for this, it would solve the problem for everyone without requiring an external fan patch. I will meanwhile play the rest of the mod (I was able to overcome that section through the fly cheat) and report if there are any other problems.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load up either of the save games I have provided, in the 4.8.2 one you will die as soon as you step to the right, whereas on the 1.6.0 you will be correctly transported on top of a 3d floor.

**Comment by coelckers** [comment]
fixed in 81e42142af5cada7074d58775a101ff534bf48b7

Next time, please be more concise. That entire backstory is not really relevant for fixing the bug. All I needed was the mapchecksum and the action to be taken. BTW, it's thing 699, not 669 that needed changing.
