### ISSUE TITLE
[BUG] Some Blade of Agony text papers do not render

### ISSUE THREAD

**Issue by Username-N00b-is-not-available** [ZDoom/gzdoom#2147]
### GZDoom version

https://github.com/ZDoom/gzdoom/commit/c6e2e0add29b6d24949f3e954bacf8cc524fd361

### Which game are you running with GZDoom?

Other

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

(found by @x3003 in https://github.com/Realm667/WolfenDoom/issues/1349)
In the current Blade of Agony development version some text papers on levels do not render any text, as seen on C2M6_C (6100, 26100), and some render correctly (for example, in the starting area of C3M0_A). The problem was spotted in https://github.com/ZDoom/gzdoom/actions/runs/5953953081 and is absent in https://github.com/ZDoom/gzdoom/actions/runs/5951131680.
<details><summary>Screenshot</summary>

![empty](https://github.com/Realm667/WolfenDoom/assets/77861029/673621ae-de55-4330-a195-11a858c3d302)

</details>

### Steps to reproduce the behaviour.

This is definitely not a minimal working example, however compared to BoA it is small enough: 
[boa.zip](https://github.com/ZDoom/gzdoom/files/12506638/boa.zip)
1. Rename the file to `boa.ipk3`.
2. Launch game and go to `map c2m6_c`.
3. The arrows point at an invisible textpaper. Come close and press `Use`.
4.1. On the older version, you will see some Blade of Agony story text.
4.2. On the newer version, you will see an empty sheet of paper.

**Comment by coelckers** [comment]
fixed in ef8fd472a8d1e2996828b0d5184e87d14254d527
