### ISSUE TITLE
[BUG] Missing flat on E1M9

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/gzdoom#2148]
### GZDoom version

g4.11pre-348-g ef8fd472a8

### Which game are you running with GZDoom?

Doom

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 22.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The sector which contains the red keycard on Ultimate Doom E1M9 is missing its floor and ceiling flats.

![Screenshot_Doom_20230903_191228](https://github.com/ZDoom/gzdoom/assets/6550500/d56fdd85-51d1-41f4-a627-86063f40059c)

It looks just fine on GZDoom 4.10.0, however. And in both cases, I'm running the game without mods.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Start a new game on E1M9
2. Get the yellow key card
3. Open the yellow key door
4. Notice the missing flats where the red keycard is

### Your configuration

```ini
vid_preferbackend=1 (Vulkan)
```

**Comment by Blue-Shadow** [comment]
There's a report about it [here](https://forum.zdoom.org/viewtopic.php?t=77757), too.

**Comment by coelckers** [comment]
fixed in de770faeb1476fa8d1801e3acdbfe5f5fb4d56ff
