### ISSUE TITLE
[BUG] Some TagManager line functions are checking the "allTags" FTagItem array

### ISSUE THREAD

**Issue by FishyClock** [ZDoom/gzdoom#2152]
### Which game are you running with GZDoom?

None

### What Operating System are you using?

None

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

If I understand the TagManager system right,
all sector FTagItems are in the "allTags" array and
all line FTagItems are in the "allIDs" array, correct?

If so, then the following functions are broken:
[RemoveLineIDs is altering FTagItems in "allTags" instead of "allIDs"](https://github.com/ZDoom/gzdoom/blob/bf0e74447db01aab896561c84f72aa12c892328b/src/playsim/p_tags.cpp#L105-L119)
[CountLineIDs is checking "allTags" instead of "allIDs"](https://github.com/ZDoom/gzdoom/blob/bf0e74447db01aab896561c84f72aa12c892328b/src/playsim/p_tags.cpp#L368-L389)
[GetLineID  is checking "allTags" instead of "allIDs"](https://github.com/ZDoom/gzdoom/blob/bf0e74447db01aab896561c84f72aa12c892328b/src/playsim/p_tags.cpp#L391-L405)

### Steps to reproduce the behaviour.

N/A

**Comment by coelckers** [comment]
Fortunately it's all functions that are not that common. Fixed in f6c3ce6b154723faf90ecd17388e0cf57660ea6a
