### ISSUE TITLE
[BUG] GZDoom instantly crashes when trying to open a map

### ISSUE THREAD

**Issue by inkoalawetrust** [ZDoom/gzdoom#2155]
### GZDoom version

g4.11pre-364-gb75a8ed8f

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

It seems that the latest master commit as of 12/9/2023 causes GZDoom to instantly crash very early in the startup process if the game is opened with [my city sandbox map.](https://www.doomworld.com/forum/topic/126802-gz_bigcity-a-gzdoom-city-sandbox-map-update-115-released-1952022/). It just crashes super early in the startup process. I have also attached the full stack trace of the crash and the files to reproduce it.

[string crash.zip](https://github.com/ZDoom/gzdoom/files/12581032/string.crash.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Download the attached file.
2. Load the included files together.
3. Game crashes.

### Provide a Log

gzdoom.exe!FileSys::StringPool::Strdup(const char * str) Line 125
	at C:\Users\inkoalawetrust\Documents\Github Repositories\gzdoom\src\common\filesystem\source\fs_stringpool.cpp(125)
[Inline Frame] gzdoom.exe!FileSys::FDirectory::{ctor}(const char *) Line 99
	at C:\Users\inkoalawetrust\Documents\Github Repositories\gzdoom\src\common\filesystem\source\file_directory.cpp(99)
gzdoom.exe!FileSys::CheckDir(const char * filename, bool nosubdirflag, FileSys::LumpFilterInfo * filter, int(*)(FileSys::FSMessageLevel, const char *) Printf, FileSys::StringPool * sp) Line 230
	at C:\Users\inkoalawetrust\Documents\Github Repositories\gzdoom\src\common\filesystem\source\file_directory.cpp(230)
gzdoom.exe!FileSys::FResourceFile::OpenDirectory(const char * filename, FileSys::LumpFilterInfo * filter, int(*)(FileSys::FSMessageLevel, const char *) Printf, FileSys::StringPool * sp) Line 325
	at C:\Users\inkoalawetrust\Documents\Github Repositories\gzdoom\src\common\filesystem\source\resourcefile.cpp(325)
gzdoom.exe!FileSys::FileSystem::AddFile(const char * filename, FileSys::FileReader * filer, FileSys::LumpFilterInfo * filter, int(*)(FileSys::FSMessageLevel, const char *) Printf, _iobuf * hashfile) Line 403
	at C:\Users\inkoalawetrust\Documents\Github Repositories\gzdoom\src\common\filesystem\source\filesystem.cpp(403)
gzdoom.exe!FileSys::FileSystem::InitMultipleFiles(std::vector<std::string,std::allocator<std::string>> & filenames, FileSys::LumpFilterInfo * filter, int(*)(FileSys::FSMessageLevel, const char *) Printf, bool allowduplicates, _iobuf * hashfile) Line 271
	at C:\Users\inkoalawetrust\Documents\Github Repositories\gzdoom\src\common\filesystem\source\filesystem.cpp(271)
gzdoom.exe!CheckGameInfo(std::vector<std::string,std::allocator<std::string>> & pwads) Line 1933
	at C:\Users\inkoalawetrust\Documents\Github Repositories\gzdoom\src\d_main.cpp(1933)
gzdoom.exe!D_DoomMain_Internal() Line 3719
	at C:\Users\inkoalawetrust\Documents\Github Repositories\gzdoom\src\d_main.cpp(3719)
gzdoom.exe!GameMain() Line 3777
	at C:\Users\inkoalawetrust\Documents\Github Repositories\gzdoom\src\d_main.cpp(3777)
gzdoom.exe!DoMain(HINSTANCE__ * hInstance) Line 268
	at C:\Users\inkoalawetrust\Documents\Github Repositories\gzdoom\src\common\platform\win32\i_main.cpp(268)
gzdoom.exe!wWinMain(HINSTANCE__ * hInstance, HINSTANCE__ * nothing, wchar_t * cmdline, int nCmdShow) Line 558
	at C:\Users\inkoalawetrust\Documents\Github Repositories\gzdoom\src\common\platform\win32\i_main.cpp(558)
[External Code]

**Comment by coelckers** [comment]
No crash for me with the latest master. There have been some fixes around the code where it crashed, did you really use the latest build?

**Comment by inkoalawetrust** [comment]
> No crash for me with the latest master. There have been some fixes around the code where it crashed, did you really use the latest build?

Yes, I compiled g4.11pre-364-gb75a8ed8f, which is based on the currently latest b75a8ed commit. @FDinolfo is also apparently having a similar problem with his mod too, so it's not just me.

Based on the stack trace, could it be something to do with my directories ? Because this is what my load order looks like for the map.

```
-iwad "C:\Users\inkoalawetrust\Desktop\Doom\Source Ports\GZDoom\Doom2.wad" -skill "4" -file "C:\Users\inkoalawetrust\Desktop\Doom\My Projects\Mapmaking Resources\Voxel Vehicles.pk3" "C:\Users\inkoalawetrust\Desktop\DOOM Tools\Obsidian\games\doom\data\ObAddon_Textures.wad" "C:\Users\inkoalawetrust\Desktop\Doom\My Projects\Maps\SandboxTesting Maps\gz_bigcity" "C:\Users\inkoalawetrust\Desktop\Doom\My Projects\Maps\SandboxTesting Maps\gz_bigcity\Maps\OPENCITY.wad" +map OPENCITY 
```

**Comment by nashmuhandes** [comment]
I figured out what the problem is.

GZDoom crashes when you try to -file a directory.

.pk3 and .wad mods won't crash. It's just the unpacked directories that will crash when you attempt to start GZDoom with them.
