### ISSUE TITLE
[BUG] Open menu/Console key is broken in Korean IME

### ISSUE THREAD

**Issue by gkswngh05** [ZDoom/gzdoom#2168]
### GZDoom version

g4.11pre-411-gf55e388d3

### Which game are you running with GZDoom?

Doom

### What Operating System are you using?

Windows 11

### Please describe your specific OS version

Windows 11 Pro Insider 23H2 22631.2338

### Relevant hardware info

Intel Core i7 12700K, AMD Radeon RX 6750 XT

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The new Korean IME from Windows 11 22H2 has broken some input like Open Menu(Esc) and Open Console(`).

Opening Menu requires holding the ESC key for 3 seconds and trying to open console just opens menu.

This issue does not happen when 'Use previous version of Microsoft IME' is enabled.

Changing open console key to different key like 'Numpad 0' seems to work around the issue.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Install and switch to Korean Microsoft IME.
2. Launch GZDoom and try to open menu or console.

**Comment by coelckers** [comment]
Please report this as a bug with Microsoft. If their software intercepts key input in a way that breaks existing applications they have to fix it.
