### ISSUE TITLE
Імплементація Української Локалізації / Ukrainian Localization Implementation  

### ISSUE THREAD

**Issue by CsyeCokTheSolly** [ZDoom/gzdoom#2175]
### GZDoom version

Any

### Which game are you running with GZDoom?

Doom

### What Operating System are you using?

Windows 10

### Is your feature request related to a problem? Please describe.

Hello, I simply play doom and mods with this source port.
I know about the language option in the Miscellaneous section.
I've been wondering if there are ppl working on the Ukrainian localization.
And I've checked [this spreadsheet I found in the forums](https://docs.google.com/spreadsheets/d/1pvwXEgytkor9SClCiDn4j5AH7FedyXS-ocCbsuQIXDU/edit?usp=sharing) and it finds out it has Ukrainian, but wasn't even implemented.

I've seen TSF (Fan translation team) release their own localization of GZDoom games (Doom, Chex Quest 3, Hexen, etc.)
that works, although without the menu and HUD font.

I'm doing this just so the developers/contributors get the Ukrainian localization officially.
Thanks.

**Comment by coelckers** [comment]
We had an Ukrainian translator working on and off this for about a year, but currently he's not active, The simple matter of fact is that the translation is very incomplete, i.e. there's roughly 30% of the required text being done, Currently only half his work is available on the spreadsheet.

Regarding the TSF translation you mention, where can I get it, including permission to use in GZDoom?

**Comment by CsyeCokTheSolly** [comment]
> We had an Ukrainian translator working on and off this for about a year, but currently he's not active, The simple matter of fact is that the translation is very incomplete, i.e. there's roughly 30% of the required text being done, Currently only half his work is available on the spreadsheet.
> 
> Regarding the TSF translation you mention, where can I get it, including permission to use in GZDoom?

This translation was done by Andriy Svystun of TSF (Traductores Sin Fronteras). It's available in the [team's website's catalogue](https://tsfukraine.wixsite.com/main/general-catalogue)
[Website is in Ukrainian (but the in-browser translator should help, I hope). Find "Антологія Doom" and click on the "Українізатор" link which will take you to the executable that may modify either gzdoom or the wads. It also features [replacing textures](https://tsfukraine.wixsite.com/main/the-doom-anthology).]

If you want to contact Svystun directly, his telegram pseudonym (Telegram)@SilverWarden_PL and (Discord)@andriisvystun

**Comment by CsyeCokTheSolly** [comment]
Oh yeah they also got a [trailer](https://www.youtube.com/watch?v=TLHV8v45m4g) for their localization.
They might possibly notice your comment. (I also think you might also need to prove that you're the gzd developer)
