### ISSUE TITLE
[BUG] Issues with Hexen's obituaries

### ISSUE THREAD

**Issue by PerdGateEnjoyer** [ZDoom/gzdoom#2186]
* "%o succumbed to a bishop's dark power." 
Should be "a dark bishop's power.", since they are *dark* bishops in particular. If they weren't dark, they'd be regular bishops.
* "%o was scalded by a serpent." 
Scalded means "[to] injure with very hot liquid or steam", and "serpent" should be changed to "chaos serpent"
* Demon1 uses normal Obituary as HitObituary
I suggest "%o was maimed by a chaos serpent."
* "%o was poisoned by a serpent."
"Serpent" should be changed to "chaos serpent", and "poisoned" to "gassed" since the gas ball they shoot does fire damage instead of poison.
* Demon2 uses normal Obituary as HitObituary
I suggest "%o was maimed by a chaos serpent.", once again
* "%o was incinerated by the death wyvern."
There is more than one death wyvern (as seen in DkotDC), so "the" should be "a". 
* "%o couldn't absorb Menelkir's mana." 
This is phrased weirdly and can give people the wrong idea when fighting him. I suggest changing it to "%o couldn't escape Menelkir's magic."

**Comment by prof-hastig** [comment]
You are overthinking it. Some of these texts are just plays on the enemy names and intentionally do these twists for added fun.
Also don't be too literal, like with the 'chaos' serpent.

The one legitimate issue I see here is the missing hit obituary for the chaos serpents.
The rest is merely a matter of taste.

**Comment by mc776** [comment]
I am a native English speaker and I agree with OP entirely.

**Comment by madame-rachelle** [comment]
Closing for the same reasons as #2187
