### ISSUE TITLE
Make GZDoom Linux builds more portable

### ISSUE THREAD

**Issue by bfg01** [ZDoom/gzdoom#2202]
Is there a reason for why there are no GZDoom Linux "portable" builds like the ones for Raze?

I already tried building myself GZDoom from source following the wiki's guidelines, but I'm stuck with the little issue with ZMusic: it seems to be stuck to one single absolute path at building time (cmake settings?), thus built GZDoom is broken if I move it to another location. This even if doing make install.

Thanks.

**Comment by madame-rachelle** [comment]
Primarily they seemed much lower priority to generate because there is an .AppImage that functions as a portable build. But another reason was because the 4.11.0 tag has some issues and I am hoping for a 4.11.1 to do a more proper release.

**Comment by madame-rachelle** [comment]
You can set the RPATH of precompiled executables using patchelf. It lets you view certain variables set within the executable as well. An RPATH of `.:$(patchelf --print-rpath)` will add "." to the front of an executable's existing rpath.

https://manpages.debian.org/bullseye/patchelf/patchelf.1.en.html

**Comment by Eonfge** [comment]
@bfg01 I maintain the [Flatpak on Flathub](https://flathub.org/apps/org.zdoom.GZDoom) and while it has one or two oddities, I hope that it helps many regular users.

@madame-rachelle Waiting for that 4.11.1. Right now I manually patch the package for ARM64v8 distribution, but it would be nice to have a patched version, including the latest soundfont.

**Comment by bfg01** [comment]
Just tried latest 4.11.1, both AppImage and portable tar.xz.

The AppImage doesn't accept command line parameters (for example, the "-config" one for GZDoom does not work at all), and the tar.xz simply yells "Segmentation fault".

I'm using Debian 12 Bookworm.

**Comment by bfg01** [comment]
Not sure how old is it, but I think it was already solved in this part of the CMake:
https://github.com/ZDoom/gzdoom/blob/master/src/CMakeLists.txt#L1370
which seem to do the role of the flags "-Wl,-rpath".

I'm sorry, I still don't know much about C coding, but I'm gradually learning.
