### ISSUE TITLE
[BUG] UMAPINFO BossAction not working if MAPINFO also present

### ISSUE THREAD

**Issue by SirBofu** [ZDoom/gzdoom#2208]
### GZDoom version

GZDoom 4.11.0

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 11

### Please describe your specific OS version

Windows 11 Home

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I am currently making a GZDoom/complevel 21-compatible WAD that utilizes UMAPINFO. In the original (attached) WAD, a MAPINFO lump that was originally there as a fallback for compatibility with non-UM-supporting ports.
I am consistently unable to get bossaction to trigger, but only in GZDoom; Woof and DSDA-Doom do not have this issue.

While I have been trying to use this on monsters added via Dehacked, I have also reproduced it using stock Doom 2 actors. Incomplete version of the WAD attached.

Attempted with different compatibility settings, including Default, Doom (Strict) with MBF21 features enabled, and MBF with MBF21 features enabled. Also tested enabling and disabling the compatibility setting to enable bossdeath on any level, but that seemed to have no effect.

[DominusDWithBossBug.zip](https://github.com/ZDoom/gzdoom/files/12841548/DominusDWithBossBug.zip)

Removing the MAPINFO lump resolves the issue, and in the case of this WAD, is a viable option.

### Steps to reproduce the behaviour.

**Reproduction Steps**
1. Load attached WAD using compatibility settings that support MBF21.
2. Enter MAP30 using console/idclev/etc.
3. Kill Deh_Actor_152, either via console, mdk, or some other method. (Monster is still incomplete.)
4. Observe that sector 69 does not lower when the monster calls BossDeath, even though it does in other ports.

**Comment by SirBofu** [comment]
Determined that this is only reproducible if a MAPINFO lump is also present. Updating reproduction steps and bug title; this doesn't seem to be too much of an issue.

**Comment by prof-hastig** [comment]
The mapinfo loading code states this:

// MAPINFO and ZMAPINFO will override UMAPINFO if in the same WAD.

It looks like this is an intentional restriction. For ZMAPINFO this definitely makes sense, but I'm not so sure about MAPINFO because mods may add this for other ports., but that's now what this mod does.
It contains a MAPINFO setting some global options and then defines the real data in UMAPINFO. Even in the best of cases this constitutes undefined behavior.

**Comment by SirBofu** [comment]
Yeah, unfortunately, the feature parity between UMAPINFO and MAPINFO isn't yet complete. I can't disable things like jumping or crouching via UMAPINFO, but I can't do things like define BossAction in MAPINFO.

Looks like ZMAPINFO is the best practice for this particular functionality, and this is working as designed. It would be nice to have GZDoom handle these conflicts the same way other ports do in the case of MAPINFO vs. UMAPINFO (though I do think ZMAPINFO should always take precedence, as it currently does), but as this is specifically intended, I'm going to close this as not a bug.
