### ISSUE TITLE
[BUG] Boom generalized crusher not working

### ISSUE THREAD

**Issue by bamq** [ZDoom/gzdoom#2214]
### GZDoom version

4.11.1

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 11

### Please describe your specific OS version

Windows 11 Pro

### Relevant hardware info

AMD Ryzen 7 3700X, NVIDIA GeForce RTX 2070 Super

### Have you checked that no other similar issue already exists?

- [x] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Using the Boom generalized crusher action causes the floor to raise to slightly below the ceiling instead of causing the ceiling to crush on GZDoom 4.11. I tested with the 4.10 release and this issue is not present.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Setup Boom format map in Ultimate Doom Builder
2. Use the generalized crusher line action
3. Instead of starting the crusher, the floor is raised to slightly below the ceiling

**Comment by prof-hastig** [comment]
I hate to break this to you, but "Build a map that contains the error" has historically been the #1 reason that causes an issue not to be addressed. If you know of a place in some map where it happens, please post a link to that map.

**Comment by bamq** [comment]
I'm guessing it happens with any map that uses the generalized crusher. The behavior is not present in the 4.10 release, only 4.11 and later.

I've attached a map which is just a single room and a button. In GZDoom 4.10, Woof, and DSDA-Doom it behaves as expected. In latest GZDoom the floor just raises to the ceiling and does nothing else.
[crushtertest.zip](https://github.com/ZDoom/gzdoom/files/13116541/crushtertest.zip)
