### ISSUE TITLE
[BUG] Vertical & Horizontal Rotation apparently use Absolute Positioning instead of Delta Positioning on Linux

### ISSUE THREAD

**Issue by octoalex** [ZDoom/gzdoom#2218]
### GZDoom version

4.11.1, Custom Build (no changes) & Official Build

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Ubuntu 22.04 LTS and Linux Mint 21.2 Cinnamon

### Relevant hardware info

AMD Ryzen 7 3700x + Nvidia 3060 Ti or Oracle VirtualBox (VMSVGA)

### Have you checked that no other similar issue already exists?

- [x] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When entering the game, a minimal mouse movement will become a massive player rotation, that increases in speed the further away you get from the top-left angle.
This has lead me to believe that, on Linux platforms, the game may be rotating the player by the current absolute mouse position instead of the current mouse delta

Couldn't replicate issue on Windows

Hardware configurations:
1. Ubuntu 22.04 LTS on WSL2 (Windows 10 22H2 build 19045.3570)  
   AMD Ryzen 3700x  
   32 GB RAM  
   Nvidia 3060 Ti  
   Vulkan
2. Linux Mint 21.2 Cinnamon on Oracle VirtualBox 7.0.10  
   2 Cores  
   4 GB RAM  
   VMSVGA  
   OpenGL

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Boot up the game
2. Start a new game
3. Move the mouse

### Your configuration

```ini
https://gist.github.com/octoalex/d3ab7fdec31fd651f7a9db9fa909dd6a
```

### Provide a Log

No logs currently available

**Comment by RicardoLuis0** [comment]
does it only happen in VMs? it's a known issue in WSL2 at least, due to it not actually capturing the mouse

**Comment by octoalex** [comment]
it happens both in VMs (atleast Oracle VirtualBox ones) and in WLS2, but in the menus the mouse works perfectly, in both scenarios.

**Comment by RicardoLuis0** [comment]
WSL **is** a VM, it runs under HyperV, this is most likely just an issue with VMs not handling mouse capture properly

**Comment by octoalex** [comment]
Thank you for your help, i will investigate further

**Comment by madame-rachelle** [comment]
Can't really do anything with this. If you want to play in a VM you must use mouse emulation that properly captures mouse movement.

The following software is suitable for such things:
* NoMachine
* Parsec
* Sunshine/Moonlight pairing
* Barrier (when locked to a single screen)

Closing this as this is otherwise unworkable. The same problems would present for any OS when emulating another OS - anything that uses absolute mouse pointing will be unable to use mouse aiming that is present in almost nearly any FPS game.
