### ISSUE TITLE
[BUG] Doom Software Renderer is broken with Vulkan rendering API

### ISSUE THREAD

**Issue by gaborbata** [ZDoom/gzdoom#2222]
### GZDoom version

GZDoom 4.11.1

(GZDoom 4.11.0 also has this issue with Vulkan renderer)

### Which game are you running with GZDoom?

Doom

### What Operating System are you using?

Windows 11

### Please describe your specific OS version

Windows 11 22H2 (22621.2428)

### Relevant hardware info

12th Gen Intel Core i7-1270P (with integrated graphics card)

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Image using software renderer mode is broken in 4.11.1:

![image](https://github.com/ZDoom/gzdoom/assets/8159164/226b08e1-9207-4e18-9a66-3ed1d94b9e58)

### Steps to reproduce the behaviour.

Explain how to reproduce:
1. Start game (with any episode)
2. Go to display options
3. Select render mode: Doom Software Renderer
4. Make sure Vulkan rendering API is selected and active

Notes:
* True color SW renderer is broken as well but not for all resolutions.
* It seems that only Vulkan rendering API is affected.

**Comment by madame-rachelle** [comment]
This bug seems to be specific to that driver and/or chipset, but just to rule out configuration issues would you be willing to post your .ini?

**Comment by gaborbata** [comment]
Thanks for your quick response. Unfortunately, I had to bring back that machine and I missed to get the .ini file... I have checked the problem with another setup (Ubuntu 22.04, with a 11 Gen Core i5, with integrated graphics) and I could not reproduce the issue. Based on that it seems to be a driver issue. I'm closing the ticket.
