### ISSUE TITLE
[BUG] GZDoom allocates a lot of memory and gets stuck starting

### ISSUE THREAD

**Issue by hedgehog1029** [ZDoom/gzdoom#2223]
### GZDoom version

GZDoom g4.11.1-m - 2023-10-11 14:13:35 -0400 - SDL version

### Which game are you running with GZDoom?

None

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Arch Linux (kernel 6.5.6-arch2-1)

### Relevant hardware info

Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Previously I've been able to successfully launch gzdoom. However when attempting to start it today it eats up all available memory, before eventually getting killed by the OOM killer.

Not really sure where to start looking for debugging - I guess I could run it under valgrind?

In some attempt to see if it would eventually boot, I ran gzdoom via the following command:  
`systemd-run --scope -p MemoryMax=4G -p MemoryHigh=3G -p MemorySwapMax=0 --user gzdoom`  
This limited the memory that gzdoom could allocate to prevent it locking up my system. It doesn't appear to progress any further this way though.

### Steps to reproduce the behaviour.

1. Open gzdoom
2. The gzdoom window opens, but nothing is drawn to it (it does that X server thing of "screenshotting" the view behind it as it opens)
3. Wait

### Your configuration

https://gist.github.com/hedgehog1029/3f21cc76bdd21d463264d608748c344c

### Provide a Log

https://gist.github.com/hedgehog1029/84b0dc9e3a62b0f77522de5ebed1a246

Gets stuck with some kind of loading bar displaying at the end of this log.

**Comment by coelckers** [comment]
It's very likely the same issue as this one: https://github.com/ZDoom/Raze/issues/966
Right now the only recommendation we can make is to switch to Vulkan. To investigate this we need someone with access to an affected system and knowledge how to track down this issue.

**Comment by hedgehog1029** [comment]
Setting `vid_preferbackend = 1` does indeed solve the issue, cheers.

I'd be happy to provide further debugging info if required, though from the sounds of the referenced issue it's up to upstream mesa maintainers now?

**Comment by LoneFox78** [comment]
This code here:
https://github.com/ZDoom/gzdoom/blob/212adabe2bde7d6b30ef64a74ad6df6795b4ac1a/src/common/rendering/gl/gl_shader.cpp#L398-L402

adds these lines to the resulting shader:
```
#define NUM_UBO_LIGHTS 134217727
#define NUM_UBO_BONES 33554431
```
and later it does:
```
		#elif defined NUM_UBO_LIGHTS
		uniform LightBufferUBO
		{
			vec4 lights[NUM_UBO_LIGHTS];
		};
		#endif
```

I don't know much about OpenGL, so I don't know what this is trying to do, but an array of 134 million elements is obviously not right. And indeed, if I force `lightbuffertype = true;`, the game starts normally.

**Comment by coelckers** [comment]
Closed as duplicate.
