### ISSUE TITLE
[BUG] Misnamed setting in HUD options

### ISSUE THREAD

**Issue by RicardoLuis0** [ZDoom/gzdoom#2224]
### GZDoom version

4.11.1, probably many older versions as well

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

the cvar `wbobfire`, that controls weapon bobbing while firing, is described as "**View** bob" in the hud options (the LANGUAGE string is `$DSPLYMNU_BOBFIRE`)

![image](https://github.com/ZDoom/gzdoom/assets/15188209/5008c5fe-a570-4323-89d9-0caf588fbf0f)

**Comment by prof-hastig** [comment]
I corrected those which I could and checked all others using Deepl.
Czech, Esperanto, Spanish and Russian are still bad, several others were right from the start and a few were neutral enough that they can apply to both weapons and the view.

With the 4 abovementioned languages I cannot do much except machine translations so I left them.
