### ISSUE TITLE
GZDoom Linux Portable tar.xz builds are NOT running on recent stable Linux distributions

### ISSUE THREAD

**Issue by bfg01** [ZDoom/gzdoom#2232]
Tried with Debian 12 Bookworm and openSUSE Leap 15.5.

Debian just "Segmentation fault" with no further output; SUSE asks for glibc 2.35 at least, when Leap 15.5 ships glibc 2.31.

This is happening since release 4.11.1, I think since @madame-rachelle took over the builds...

Is there something really going wrong with recent builds, or just coincidence?

**Comment by B-Nerd** [comment]
I'm on arch linux & get this error
./gzdoom: /home/user/Games/Doom/Runners/gzdoom/libc.so.6: version `GLIBC_2.38' not found (required by /usr/lib/libasound.so.2)
./gzdoom: /home/user/Games/Doom/Runners/gzdoom/libc.so.6: version `GLIBC_2.38' not found (required by /usr/lib/libglib-2.0.so.0)
FYI it is bleeding edge & the version i have on my system is glibc 2.38

**Comment by bfg01** [comment]
Yet another tar.xz release shortly after this issue was posted, and still exact same problem...

**Comment by itaranto** [comment]
Classical glibc incompatibility.... I believe the only way to provide truly portable versions for Linux is to provide an AppImage or similar.

**Comment by bfg01** [comment]
There **are** GZDoom AppImage versions, just by another maintainer.

I myself use AppImage for some applications; the only current issue at least with GZDoom images is that command line parameters cannot be used with them, they're simply ignored.
For example, trying to run "gzdoom -config some/config.ini".

**Comment by bfg01** [comment]
I think I managed to solve the issue, and owe some apologies to @madame-rachelle .

In the end what I tried and proved to work was renaming/deleting *all* the .so libraries in the tar.xz, *except* for libzmusic.so.1 itself of course (and possibly libpcre.so.3 as well, since at least Debian 12 Bookworm doesn't seem to have this version of the library).

I was kind of dumb, I should have noticed before that all those included libraries sounded familiar regarding their names: except for the already mentioned two ones, all of them are normally included (or installable) in most Linux distributions.
The issue in the OP could further support the fact that one same library build for one particular distribution will almost never work in another different one.

Anyway, sorry miss Rachelle, and hope you can continue the good work.
