### ISSUE TITLE
[BUG] Mapinfo does not allow zero gravity

### ISSUE THREAD

**Issue by kraflab** [ZDoom/gzdoom#2235]
### GZDoom version

gzdoom-x64-g4.12pre-82-g2fb41a795

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 11

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When setting gravity to zero in mapinfo, gzdoom uses default gravity.

### Steps to reproduce the behaviour.

Here is a minimal mapinfo.lmp:
```
map map01 "gravity" {
  Gravity = 0
}
```

Load this file and start a new game on map 1. Run off the ledge and witness default gravity where there ought be none.

**Comment by coelckers** [comment]
Unfortunately this cannot be fixed because 0 means 'use the sv_gravity CVAR' and this behavior is so old that changing it now may cause unforeseen problems. We'll have to find another way to specify zero gravity, I fear.

**Comment by kraflab** [comment]
Maybe a `NoGravity` flag would suffice in that case.
