### ISSUE TITLE
[Feature] Steam "Master Levels for DOOM II" contains DOOM2.WAD, allow this for IWAD detection

### ISSUE THREAD

**Issue by Kroc** [ZDoom/gzdoom#2239]
Looking at "src/win32/i_steam.cpp", no detection is provided for Steam "Master Levels for DOOM II".
The Steam App ID is 9160 and the path to the wad is "Master Levels of Doom/doom2/DOOM2.WAD"

**Comment by prof-hastig** [comment]
The Master Levels are not a regular IWAD, to make them work you need some added handling for a level selector and special treatment of in-game progression. It's probably better suited for user mods as a result.

**Comment by Kroc** [comment]
That's not what I'm saying -- Master Levels also contains a copy of DOOM2.WAD, it's *that* that should be detected. If, by whatever turn of happenstance, a player has *only* The Master Levels (Steam) installed, GZDoom will be able to detect a working DOOM2.WAD
