### ISSUE TITLE
[BUG] Startup screen does not disappear if the game fails to start

### ISSUE THREAD

**Issue by Player701** [ZDoom/gzdoom#2256]
### GZDoom version

4.11.3 and g4.12pre-105-g22203cbc1

### Which game are you running with GZDoom?

Hexen

### What Operating System are you using?

Windows 11

### Please describe your specific OS version

Windows 11 Pro 22H2

### Relevant hardware info

NVIDIA RTX 4090

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

**NB:** This happens in Hexen, Heretic, Strife and likely any other game that features an animated startup screen.

If the game fails to start for some reason (for example, due to a script error in a lump), the startup screen does not disappear, making the script error unreadable without using `+logfile`:

![image](https://github.com/ZDoom/gzdoom/assets/9046118/3428954b-02ae-4fa8-9241-80a2aa5a9c93)

Alternatively, it is possible to copy-paste text from the window by using e.g. Ctrl+A, but this is still not very convenient.

This seems to happen only with the Vulkan backend and with `vid_vsync` set to true. Using any other backend and/or setting `vid_vsync` to false makes the issue go away.

### Steps to reproduce the behaviour.

Explain how to reproduce

1. Set backend to Vulkan and `vid_vsync` to true.
2. Run GZDoom with any mod/lump that will cause it to error out with a script error.

### Your configuration

```ini
This can be reproduced with a freshly-generated INI, see description and reproduction steps above.
```

### Provide a Log

N/A

**Comment by MajorCooke** [comment]
This happens to me as well. It's very annoying to deal with so I have to disable all gameinfo screens.

**Comment by madame-rachelle** [comment]
Fixed with new startup code
