### ISSUE TITLE
[Feature] Strife: improve stealth

### ISSUE THREAD

**Issue by tukkek** [ZDoom/gzdoom#2258]
### GZDoom version

Any

### Which game are you running with GZDoom?

Strife

### What Operating System are you using?

Other

### If Other OS, please describe

Universal

### Is your feature request related to a problem? Please describe.

Some enemies don't respect stealth.

### Add any other context or screenshots about the feature request here.

I came across Night Dive's repository for *Strife: Veteran Edition* today and wrote a feature request with ideas on how to improve the game's half-baked stealth gameplay and why I believe it was only partially-implemented in the original game.

Obviously, the same changes would be possible in ZDoom too (which is my Doom engine of choice, big thanks to you all)!

Instead of copy-pasting the entire thing here, I will just link to the original https://github.com/svkaiser/strife-ve/issues/11

Sorry if this breaks the intended formatting (but most of the fields here don't apply to this sort of feature request anyway).

**Comment by coelckers** [comment]
This is something for a gameplay mod as it'd require changing all actor logic for the robots, it cannot be simply grafted onto the existing code..

**Comment by tukkek** [comment]
Does make more sense as a mod than an engine option for sure. Didn't think of that, thanks!
