### ISSUE TITLE
[BUG] ZScript: keys of Map<name, ...> should be serialized as strings instead of numbers

### ISSUE THREAD

**Issue by Player701** [ZDoom/gzdoom#2259]
### GZDoom version

4.11.3 and 4.12pre-106-ga04f909d0

### Which game are you running with GZDoom?

None

### What Operating System are you using?

None

### Please describe your specific OS version

N/A

### Relevant hardware info

N/A

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

As of now, keys of `Map<name, ...>` are serialized as numbers  in save files. This may cause them to resolve to incorrect values if the total number of names changes when the save file is loaded. Such a change might not necessarily result from user error: for example, when a new GZDoom release comes out, the save file is very likely to break.

Note that this is almost certainly a bug because fields and array values of type `name` are correctly serialized as strings. The `Map` type was implemented more recently - perhaps this scenario was simply not accounted for. Also, if a `Map` is used to store names as values, they are also correctly serialized. (All of this is demonstrated further below.)

### Steps to reproduce the behaviour.

The following ZScript implements a class that demonstrates the bug with map keys while simultaneously showing that fields, arrays, and map values remain stable:

```
version "4.11"

class TestInv : Inventory
{
    name TestField;
    Array<name> TestArray;
    Map<name, name> TestMap;

    override void BeginPlay()
    {
        TestField = 'TestName';
        TestArray.Push(TestField);
        TestMap.Insert(TestField, TestField);
    }

    override bool Use (bool pickup)
    {
        Console.Printf("TestField == %s", TestField);
        Console.Printf("TestArray[0] == %s", TestArray[0]);

        MapIterator<name, name> it;
        it.Init(TestMap);
        it.Next();

        Console.Printf("TestMap == %s => %s", it.GetKey(), it.GetValue());
        return false;
    }
}
```

If you type `give testinv`, then `use testinv`, you should see the following:

```
TestField == TestName
TestArray[0] == TestName
TestMap == TestName => TestName
```
Now save the game, and modify the script by adding an empty method before `BeginPlay`:

```
void Bug() {}
```
Note that this method is never actually called, however, it is enough to trigger the bug, because during compilation it automatically defines a new name "Bug".

It is also important to understand that for the bug to trigger, it is ***absolutely not necessary*** for the change to be made in the same file where the test class is defined. Suppose some ZScript code in gzdoom.pk3 changes when a new GZDoom version comes out, and the save file automatically becomes incompatible.

Loading the save file and typing `use testinv` again, you should see this:

```
TestField == TestName
TestArray[0] == TestName
TestMap == Bug => TestName
```

All values stayed the same except for the key in `TestMap` because it was serialized as a number. This would not have happened if it had been serialized as a string.

### Your configuration

```ini
N/A
```

### Provide a Log

N/A

**Comment by RicardoLuis0** [comment]
This can't be solved easily, since a name map is just an int map internally, but i'll see what i can do

**Comment by Player701** [comment]
Hey @RicardoLuis0, thank you very much for a quick fix, but I just realized that `Map<sound, ...>` has a similar issue. It is harder to break since it requires to add new sound definitions to `SNDINFO`, but the bug is still there.

And even worse: if 2 or more sounds in the map become invalidated somehow (i.e. the definitions for them get removed), then after loading the save the engine will crash when attempting to access the contents of such a map. Probably because it now contains 2 keys with the same value (the invalid sound ID).

Should I open another report for this?
