### ISSUE TITLE
[BUG] ZScript: keys of Map<sound, ...> should also be serialized as strings

### ISSUE THREAD

**Issue by Player701** [ZDoom/gzdoom#2263]
### GZDoom version

4.11.3, g4.12pre-108-g747e55ce6

### Which game are you running with GZDoom?

None

### What Operating System are you using?

None

### Please describe your specific OS version

N/A

### Relevant hardware info

N/A

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Basically, the same issue as #2259, but with sounds. I first wrote about it [here](https://github.com/ZDoom/gzdoom/issues/2259#issuecomment-1807577573), but due to the lack of replies I then decided to open a separate issue.

Just like names, fields and array elements of type `sound` are serialized as strings, but this is not true for map keys, which are serialized as numerical sound IDs. When a save file is loaded, they may start pointing to something different or become invalid entirely. In the latter case, attempting to play such sounds or even just print their names will likely result in a crash.

Note that if this gets fixed, a special case must be taken into consideration when two or more sounds in the map are no longer valid and thus resolve to the same value of "no sound". Since a map cannot have duplicate keys, this should probably be handled either by simply discarding excess keys (and potentially also issuing a warning), or by erroring out with a non-fatal error (and refusing to load the save).

### Steps to reproduce the behaviour.

Similar to #2259, but to trigger the bug, sound definitions must be altered.

Example ZScript:
```
version "4.11"

class TestInv : Inventory
{
    sound TestField;
    Array<sound> TestArray;
    Map<sound, sound> TestMap;

    override void BeginPlay()
    {
        TestField = "TestSound";
        TestArray.Push(TestField);
        TestMap.Insert(TestField, TestField);
    }

    override bool Use (bool pickup)
    {
        Console.Printf("TestField == %s", TestField);
        Console.Printf("TestArray[0] == %s", TestArray[0]);

        MapIterator<sound, sound> it;
        it.Init(TestMap);
        it.Next();

        Console.Printf("TestMap == %s => %s", it.GetKey(), it.GetValue());
        return false;
    }
}
```

Example SNDINFO:
```
TestSound dsempty
```

Load up both ZScript and SNDINFO, do `give testinv`, `use testinv`:

```
TestField == TestSound
TestArray[0] == TestSound
TestMap == TestSound => TestSound
```

Now save the game and load just the ZScript. Because our sound no longer exists, the sound ID in the map has become invalid. Do `use testinv`, and GZDoom will either print a random string in the third line, or just crash. (For me, it does the latter.)

If you remove or comment out the last `Console.Printf` call, you can see that the crash is gone, and in other places the sound name resolves to an empty string:

```
TestField == 
TestArray[0] == 
```

### Your configuration

```ini
N/A
```

### Provide a Log

N/A

**Comment by RicardoLuis0** [comment]
i'll fix this up as well, but since it's a less-severe issue compared to names (only breaks if the load order changes), it'll take a bit longer 'cause i want to properly rework how keys are saved for maps, instead of just special casing it directly like i did for names
