### ISSUE TITLE
ZDoom for Arm64 for Windows?

### ISSUE THREAD

**Issue by exocyt0sis** [ZDoom/gzdoom#2265]
### Which game are you running with GZDoom?

Doom

### What Operating System are you using?

Windows Other

### If Other OS, please describe

Windows 11 for ARM

### Is your feature request related to a problem? Please describe.

Hi everyone. Would it be doable to provide a binary of ZDoom for Windows for Arm, too?

**Comment by madame-rachelle** [comment]
The reason why this hasn't happened is the build script so far was unable to reconcile the architecture differences when cross-compiling. I never compile arm64 natively, only test it on a GalaxyBook that I have.

Once the build script is fixed and able to properly trigger a cross-compile, I can start posting arm64 windows builds again.
