### ISSUE TITLE
[BUG] invertmouse should not affect movement

### ISSUE THREAD

**Issue by janvkn** [ZDoom/gzdoom#2268]
### GZDoom version

GZDoom 4.11.3

### Which game are you running with GZDoom?

Doom

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Arch Linux

### Relevant hardware info

n/a

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

It seems that on GZDoom 4.11 the invertmouse behavior has changed in a way that is disruptive to my playing style, which includes using the mouse for quick movements.

How it always used to be: if you set `invertmouse=true`, the Y axis would be inverted for looking around, but not for moving around. This is my desired behavior, and how I configured all my shooters ever since Quake introduced mlook back in 1996.

How it currently is: if you set `invertmouse=true`, the Y axis gets inverted for looking around _as well_ as for moving around. That is: if freelook is turned off or if the strafe button is held, doomguy walks backwards when the mouse is pushed forward.

In my opinion, the invertmouse setting should affect looking around only and should not affect movement with the mouse as it is not intuitive and there is no precedent for this in any other game that I can think of. At the very least this behavior should be configurable.

The change appears to have been introduced in commit f1f6e3a607f72bec84ddf678127387c28032dc80

### Steps to reproduce the behaviour.

1. Set `invertmouse=true`
2. Start a level, hold the strafe button and push the mouse forward: doomguy will walk backwards.

### Your configuration

```ini
invertmouse=true
invertmousex=false
```

### Provide a Log

n/a

**Comment by janvkn** [comment]
You guys are awsome... thanks!

**Comment by mjr4077au** [comment]
@janvkn I'm sorry about that, oversight on my part while trying to make something more consistent. It's understandable that you wouldn't want axes to be inverted for mouse movement.
