### ISSUE TITLE
[BUG] Backwards compatibility breakage with Translation comparisons

### ISSUE THREAD

**Issue by MajorCooke** [ZDoom/gzdoom#2270]
Since TranslationIDs used to be ints, this breaks mod backwards compatibility. I was using a comparison via an int before since that's what they were.

I think adding in a built-in conversion type and adding in a warning may help, otherwise: `Incompatible operands for != comparison`.

The code in question: `if (owner.Translation != CurrentTranslation)` and `CurrentTranslation` is an int. This code is from a long time ago.

**Comment by coelckers** [comment]
This change should be version specific, i.e. old code with pre 4.12 versions should treat translation IDs as int. If you update version to 4.12 you will have to adapt how you handle it. The automatic conversion operators were intentionally not added to avoid hidden errors.

The thing here is, these types need to be distinct to allow implementation of custom translation serialization, if you mix and match again this cannot be done.

**Comment by MajorCooke** [comment]
My code is set for 4.10. Assignments work but comparisons do not.

**Comment by coelckers** [comment]
fixed in 8e319a766953de6958fbf5fc630809aec7540872
