### ISSUE TITLE
[BUG] V-Sync limits FPS to 2x(refresh rate) on laptop

### ISSUE THREAD

**Issue by Player701** [ZDoom/gzdoom#2271]
### GZDoom version

4.11.3 and g4.12pre-121-gc73f80511

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 11

### Please describe your specific OS version

Windows 11 Pro 22H2

### Relevant hardware info

MSI Raider GE78HX 13VH (Intel i9-13950HX, RTX 4080 Laptop)

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I recently got a new laptop with a 240 Hz screen. I've noticed that if I turn on V-Sync in GZDoom display options, then I get up to 480 FPS in-game, which is exactly twice the refresh rate of the screen. This happens both with OpenGL and Vulkan.

Note that this issue occurs only when using the built-in GZDoom option. Forcing V-Sync on in the NVIDIA control panel correctly limits my FPS to 240.

Running the latest NVIDIA driver (546.17 as of now).

### Steps to reproduce the behaviour.

1. Run GZDoom with a fresh INI
2. Enable V-Sync in display options
3. Also, set "Max FPS" to a high enough value so that FPS is not limited by it

### Your configuration

```ini
Reproducible with a fresh INI (see repro steps above)
```

### Provide a Log

[OpenGL](https://gist.github.com/Player701/96b086e65641c83698fc724027bb34c8)

[Vulkan](https://gist.github.com/Player701/a76cab766a87b51b88e24cc4a94216af)

**Comment by coelckers** [comment]
This is out of the engine's hands. The vsync duration is controlled by the graphics driver internally.

**Comment by Player701** [comment]
I'm certain that you know better, but so far I have not been able to reproduce this behavior in any other game I own - that is why I reported it in the first place.

**Comment by coelckers** [comment]
I have no idea. The vsync  gets applied in the presentation step. there is no waiting on the engine side if vsync is active, it's all done in either the Vulkan or OpenGL driver.

**Comment by Player701** [comment]
I no longer have the laptop mentioned in the original report, so I propose closing this issue as no one else appears to have been able to reproduce it.
