### ISSUE TITLE
[Feature] transparently enable cheats for mods that actively prohibit using cheats

### ISSUE THREAD

**Issue by obernil** [ZDoom/gzdoom#2275]
### GZDoom version

GZDoom 4.10

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 10

### Is your feature request related to a problem? Please describe.

It came to my knowledge that there are mods out there (namely "Doom Infinite", https://www.moddb.com/mods/doom-infinite) that actively check for cheats to be enabled and forbid to run / "crash" the game if one tries to use them

Apparently going as far as corrupting on purpose the savegame

From what I've read around this is much very against the spirit of ZDoom

### Describe the solution you'd like

A switch that enables cheat while at the same time making them appear like they are not enabled

### Describe alternatives you've considered

Forbid mods to run if they actively implement ways to prohibit enabling cheats

**Comment by coelckers** [comment]
With so much of the game code running as scripts that is unfortunately not doable. Honestly, just boycott such mods, or ask on the forum if someone can help you neutralizing the anti cheat measures they employ.

**Comment by MajorCooke** [comment]
For that mod in particualr, turn on `debug_enabled` cvar by typing `debug_enabled 1`

**Comment by MajorCooke** [comment]
Also  you can edit out the "DisableCheats" in the mapinfo.

**Comment by obernil** [comment]
> With so much of the game code running as scripts that is unfortunately not doable. Honestly, just boycott such mods, or ask on the forum if someone can help you neutralizing the anti cheat measures they employ.

@coelckers will most likely do.
Note:  there were compiled ACS scripts __but no ACS sources included__

> For that mod in particular, turn on `debug_enabled` cvar by typing `debug_enabled 1` in console.

@MajorCooke I guess you found out yourself that if you edit `MAPINFO` with `DisableCheats` or the like, it will check for that too and "crash" with some handmade error screen

I found quite baffling the decisions made by the dev

Even more so as there is a general cultural switch in making games _more accessible_
Note: I worked in accessibility and it really grinds my gears when someone intentionally makes something less accessible, hence why I'd have liked a global feature to eradicate the issue at the root

Also, double baffling as it was pretty trivial to bypass by just using CheatEngine...

**Comment by MajorCooke** [comment]
Sometimes it's needed to prevent breaking the mod. Other times, it's made to make you suffer.

One of the mods that I have has an ancient system for weapon slot limits that you can disable, we had to disable the giving of weapons because it would otherwise break it. BUT... That's only because the system was utilizing a lot of ACS and DECORATE hackery. Now that we have ZScript, when I get back to it, I'll be removing it entirely.

**Comment by obernil** [comment]
I see your point, but it doesn't seem the case here (to prevent breaking the mod)

more like a dev too inebriated on the vapours of his own flatulences that believes his mod is the 2nd coming on Earth and decides _his way_ must be _the only way_ you play his mod
