### ISSUE TITLE
Custom game launch from "IWAD selection box"

### ISSUE THREAD

**Issue by Hexaae** [ZDoom/gzdoom#2285]
### GZDoom version

4.9.0

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 11

### Is your feature request related to a problem? Please describe.

Feature request to improve IWAD selection box

### Describe the solution you'd like

Can you expand the IWAD selection box, to let users add custom game config (= a sort of option to launch
<game_name> **-file <user_DLC>.pk3** ...). Having another launcher (or a lot of different launch shortcuts) is a nonsense and wasted HD space IMHO

### Add any other context or screenshots about the feature request here.

![image](https://github.com/ZDoom/gzdoom/assets/8591462/db70bc1d-38ad-42f0-9f23-1e211a9a4c55)

**Comment by Hexaae** [comment]
Maybe through an optional configurable "IWADclauncher.ini" (IWAD custom launcher.ini):
```
Original game: ... (choose from supported games, e.g. "Doom, Hexen, Strife...")
Custom game name: <My custom game label here>
Additional file(s): my_mod.pk3, brutalv21.pk3
...
```

**Comment by madame-rachelle** [comment]
First you should be aware that 4.9.0 is a dead branch and will never be updated. New versions of GZDoom are the only ones that get updates, sans a fork author doing this themselves. So - if this ever gets implemented - I do hope you won't mind moving on from 4.9.0.

On the flip side, the IWAD picker was objectively never designed for this kind of usage. I agree with you generally that the less third party apps the better though, and personally I have created stubs over the years to launch total conversions as independent games using the IWAD picker, but that was never its original intent. If you don't mind the idea of stubs though, you can have a look at my project here: https://forum.zdoom.org/viewtopic.php?t=64919 - if you edit the contained iwadinfo.txt's it effectively allows you to extend GZDoom's own iwadinfo.txt to include whatever files you want for each project + modset.

As for your original suggestion as suggested, while I do see merit to this, I don't feel the ultimate decision is up to me at least for the GZDoom port, and therefore I am going to let @coelckers review this and make a final determination. There's nothing prohibiting this from appearing in a fork, however, and depending on the merits versus the drawbacks of the current system that is a possibility.

**Comment by Hexaae** [comment]
Thanks, I was trying to do the same as nerve.ipk3 etc. for my purpose (a minimal ipk3 to automatically load also brutalv21.pk3), however an optional feature through simple INI editing would be better and more versatile IMHO.
I hope it will be taken into consideration.

**Comment by Hexaae** [comment]
> If you don't mind the idea of stubs though, you can have a look at my project here: https://forum.zdoom.org/viewtopic.php?t=64919 - if you edit the contained iwadinfo.txt's it effectively allows you to extend GZDoom's own iwadinfo.txt to include whatever files you want for each project + modset.

Mmmh, unfortunately I've found some problems running brutalv21.pk3 as a stub following your examples... In particular I've noticed a different pk3/wads loading order (?):
1. by drag'n'drop (same as "-file ..." command line option)
![Base Profile Screenshot 2023 12 05 - 19 39 13 64](https://github.com/ZDoom/gzdoom/assets/8591462/ccb76434-d304-42d6-992a-9dc3058ea089)
2. by stub
![Base Profile Screenshot 2023 12 05 - 19 40 44 00](https://github.com/ZDoom/gzdoom/assets/8591462/bfbb25f3-12a7-4d75-bef4-2e52dd9d7b28)

and then in game there are actually some differences... looks like some things have not been overwritten correctly by the stub or the fact it is seen as a stand-alone WAD game and hence bypasses some patches/fixes. E.g. [in this pic](https://imgsli.com/MjI0MjE3) you see a different HUD at the bottom, and in the pics above the titlepic in background is still 4:3 in 2 (it ignored the game_widescreen_gfx.pk3 patches?)... there are also some script differences as far as can understand: like the steps sound which is incorrectly prolonged in the stub after you stop running (correct in the -file xxxx loaded version instead).

This is the iwadinfo.txt stub I created:

```
IWad
{
	Name = "DOOM Registered Brutal"
	BannerColors = "a8 00 00", "a8 a8 a8"
	Load = "..\brutalv21.pk3"
	Required = "DOOM Registered"
	Autoname = "doom.brutal"
	Game = "Doom"
	Config = "Doom.brutal"
	Mapinfo = "mapinfo/doom1.txt"
	Compatibility = "Shorttex"
	//IgnoreTitlePatches = 1
	//LoadLights = 1
	//LoadBrightmaps = 1
	//LoadWidescreen = 1
}
```
 
Have had to use "..\" in front of the pk3 or it couldn't find the brutalv21.pk3 in the root (?) even though the paths are correct in the GZdoom_portable.ini.

**Comment by coelckers** [comment]
Unless someone can point me to a low overhead cross-platfom GUI library that won't get vetoed by the Linux crowd for whatever political reason, no work will be invested here. As long as the IWAD picker is platform dependent code it's a total waste of time changing it because it requires changing 3 different implementations.
