### ISSUE TITLE
[BUG] Memento Mori II MAP20 compatibility issues

### ISSUE THREAD

**Issue by Player701** [ZDoom/gzdoom#2289]
### GZDoom version

4.11.3 and g4.12pre-140-g43c70cdf9

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

None

### Please describe your specific OS version

N/A

### Relevant hardware info

N/A

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

A couple issues with MAP20 of [Memento Mori II](https://www.doomworld.com/idgames/?id=6562) discovered during my recent playthrough:

1. This map seems to contain an egregious amount of nodebuilding errors causing monsters to fall down through the floor in some places (mostly in the northern part). As an example, [here](https://github.com/ZDoom/gzdoom/assets/9046118/9eef6711-be03-4a3e-bbcc-206ffabd6292) my modded HUD is showing the health bar of an imp stuck in one of the nukage-filled sections. It is possible to kill these enemies, but it seems to happen quite often (for me it was 3 times in one playthrough), so I think this map should be added to the `rebuildnodes` compatibility list.

I'd have done the above myself via a PR, if not for the second issue:

2. It is not possible to get 100% kills if this map is played with GZDoom on HMP and above. To better explain this, here is a snippet from the [wiki article](https://doomwiki.org/wiki/MAP20:_The_Experiment_(Memento_Mori_II)#Other_points_of_interest):

> In the western teleporter room, on Hurt Me Plenty or higher, there is a former human (a sergeant on Hurt Me Plenty, and a chaingunner on Hurt Me Plenty or higher) inside of the northwest pillar who will shoot at you through the southeast side. To kill them, you must fire into that side yourself. In addition, if you run into that side, you will obtain a medikit.

There is actually no former human on easier difficulties - I guess I should correct that text. But anyway, the real issue is that in GZDoom, the southeast side of the aforementioned pillar blocks hitscan attacks, so the enemy cannot be killed. This does not happen in e.g. PrBoom+. Note that projectile attacks are always blocked; however, splash damage is propagated through the wall in PrBoom+ but, again, not in GZDoom.

It seems that enabling `gennodes` does not fix this. I've also checked this map in UDB: the geometry setup in that particular area seems quite unusual, and the only way the outer southeast linedef (number 159) differs from others is that it has the "double sided" flag set; despite that, however, all outer linedefs have both a front and a back side defined.

It is possible that some compability switch needs to be enabled for this map, but I have no idea which one. A simpler solution would be to remove the monster from inside the pillar entirely, but I'd prefer not to do that unless there is no way to implement a proper fix at all.

Here is the map hash for reference:

```
]mapchecksum map20
F1EB6927F53047F219A54997DAD9DC81 // mm2.wad map20
```

### Steps to reproduce the behaviour.

While issue no. 1 is mostly self-explanatory, here are a few more details about no. 2. The pillar is located at around the following coordinates in the map: X = 2816, Y = 3072. Warping there from map start and then turning left will make you facing the southeast side of the pillar. You can see that it blocks hitscan attacks, and explosions also don't damage the enemy.

### Your configuration

```ini
N/A
```

### Provide a Log

N/A

**Comment by Player701** [comment]
@coelckers
Unfortunately, `compat_hitscan` does not seem to help.

**Comment by coelckers** [comment]
It was compat_trace, with that being set the setup works.
