### ISSUE TITLE
[BUG] Bomb to console after defeating Traductus in MAP38 [Hexen] [Multiplayer]

### ISSUE THREAD

**Issue by awksie** [ZDoom/gzdoom#2296]
### GZDoom version

4.11.3

### Which game are you running with GZDoom?

Hexen

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

Windows 10 Pro 22H2

### Relevant hardware info

Ryzen 5800X3D, GeForce RTX 4080, 32GB DDR4-3600, Optane 905P

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

While playing Hexen in co-op, the game bombed to console for both co-op players with the error message "VM execution aborted: tried to read from address zero." The next line says "Called from HolySpirit.Slam at gzdoom.pk3:zscript/actors/hexen/clericholy.zs, line 349". This happned immediately after he (Traductus, boss) died while his latest attack's ghost projectiles were still damaging the players.
![image](https://github.com/ZDoom/gzdoom/assets/8469453/6e914364-ec5d-4dbd-879b-fa74d0fa4737)

Command lines used:
Host: `.\gzdoom.exe -iwad hexen +playerclass Mage -noautoload -host 2 -extratic -port 27015 -map map01 -skill 4`
Client: `.\gzdoom.exe -iwad hexen +playerclass Fighter -noautoload -extratic -join <myipaddress>:27015`
(27015 port was used because I already have it forwarded.)

### Steps to reproduce the behaviour.

Repro may be difficult because we were able to re-play the level and defeat Traductus with no problems on a second attempt.
It seems like a bug that may require this exact set of circumstances:

1. Fight your way to Traductus in Hexen MAP38 in co-op
2. Kill the boss just as he attacks with his Wraithverge
3. Get damaged or possibly killed by one of the ghost projectiles

### Your configuration

```ini
I can share the config or necessary portions of it on request. It is unbelievably long (over 4000 lines) and may possibly contain personal information. There shouldn't be anything of note for Hexen; I have some global autoloads but we launched with -noautoload (as noted above) to avoid sync issues. No mods loaded; game was running in OpenGL mode.
```

### Provide a Log

I do not seem to have a log.

**Comment by madame-rachelle** [comment]
Thank you for the report! It should be fixed now. :)
