### ISSUE TITLE
[BUG] MBF21 sector type 4128 doesn't kill player with rad suit

### ISSUE THREAD

**Issue by derekmd** [ZDoom/gzdoom#2297]
### GZDoom version

4.12pre-164

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I noticed this when watching a streamer play Eviternity II `MAP31` and they were unexpectedly able to bypass an MBF21 instakill sector LASER grid using a radiation suit.

There looks to be an MBF21 implementation issue with instakill floors but only for the rad suit. Entering the sector with the invulnerability power-up _does_ instakill as expected. https://github.com/kraflab/mbf21/blob/master/docs/spec.md indicates `4096` protects for rad suit or invuln, but `4096 & 32 = 4128` always kills with either power-up.

## Implementation references

I confirmed using the attached demo WAD that the latest DSDA-Doom, Eternity Engine, & Woof instakill with a rad suit in sector type 4128.

* https://github.com/ZDoom/gzdoom/commit/057cc0678b50c178a39a430c6a88f1190c116fe6
* https://github.com/kraflab/dsda-doom/pull/17/files
* https://github.com/team-eternity/eternity/commit/22862a6ccc9f5ba0cf75bb3ef869e46e27388d13 & https://github.com/team-eternity/eternity/commit/477c1f702fb2f109c392f1981e784cae531bdbc7

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Demo WAD for doom2.wad: [mbf21-instakill-sectors-test.zip](https://github.com/ZDoom/gzdoom/files/13662022/mbf21-instakill-sectors-test.zip)
2. Pick up rad suit
3. Enter middle doorway tagged with sector type 4128

**Comment by coelckers** [comment]
fixed in df35d6c7ea584757b5bf4109d4661e34349863d3
