### ISSUE TITLE
[BUG] WADs in ZIPs no longer readable

### ISSUE THREAD

**Issue by MajorCooke** [ZDoom/gzdoom#2300]
As of the December 13+ commits, [myhouse.pk3](https://drive.google.com/drive/folders/1IdH20R6bPg_Sp2Htu0Z-u_wP2AbKoaBz) can't boot up anymore.

HOWEVER... If the goal is to ultimately ween people off of taking the lazy route, I'm actually all in favor of this in its entirety because it'd force people to start doing things correctly instead of just slamming wads in a zip/pk3 and calling it a day, since that wreaks havoc on memory.

**Comment by mc776** [comment]
> If the goal is to ultimately ween people off of taking the lazy route, I'm actually all in favor of this in its entirety because it'd force people to start doing things correctly instead of just slamming wads in a zip/pk3 and calling it a day, since that wreaks havoc on memory.

OK but how many users can easily repackage everything into a pk3 for a mod that isn't maintained anymore?

**Comment by mc776** [comment]
Another use case: keeping lots of vanilla maps in zip files so they take up less hard drive space and they're neatly packaged with their text files

**Comment by coelckers** [comment]
fixed in 7ce63abe6cb1645a6e27859933096a67d9936cef

**Comment by coelckers** [comment]
> EDIT: or really _any_ pk3 mod that has a map inside it as wad... unless i'm misunderstanding the title of this issue...

Those are not embedded in the file system but loaded directly from the full WAD.

**Comment by gareppa** [comment]
This is still an issue, gzdoom 4.12.1 on linux

**Comment by RicardoLuis0** [comment]
> This is still an issue, gzdoom 4.12.1 on linux gzdoom -iwad Doom1.wad runs ok. gzdoom -iwad Doom1.zip gives the "Cannot find a game IWAD" error.

an **IWAD** won't work in a zip, for a zip file to be valid as an iwad (ipk3) it needs an [IWADINFO](https://zdoom.org/wiki/IWADINFO) lump

**Comment by gareppa** [comment]
> an IWAD won't work in a zip, since for a zip file to be valid as an iwad (ipk3) it needs an [IWADINFO](https://zdoom.org/wiki/IWADINFO) lump
(IWADs are treated differently from PWADs)

I see, thank you. The thing is, I downgraded gzdoom to 4.11.3, and now compressed **IWADS** do work.  Did they introduce stricter checks in 4.12? Were compressed **IWADS** even supposed to be working at a point?

**Comment by RicardoLuis0** [comment]
> Did they introduce stricter checks in 4.12?

yes
