### ISSUE TITLE
Latest commits are causing a crash

### ISSUE THREAD

**Issue by madame-rachelle** [ZDoom/gzdoom#2305]
Not sure what, how, or why, but the iwad picker always crashes for me.

![image](https://github.com/ZDoom/gzdoom/assets/18584402/816f7b93-0f64-4181-84b2-a6d89a1fd7df)

If I can find exactly what file causes this, I will update this issue.

**Comment by coelckers** [comment]
Works for me. Are you sure you compiled everything correctly? The first thing you should do is running 'clean solution'

**Comment by madame-rachelle** [comment]
It's crashing while reading iwadinfo texts from minimal archives.

[chex2-ipk3-crash.zip](https://github.com/ZDoom/gzdoom/files/13698412/chex2-ipk3-crash.zip)

**Comment by coelckers** [comment]
fixed in d2c395757cf5e25357ba85e501799465024ffbcd

**Comment by coelckers** [comment]
You should have said it needs a 7z file to crash.

**Comment by madame-rachelle** [comment]
Oh, I did not even know it was a .7z I did not check, my bad, sorry. Thank you for the fix!

**Comment by madame-rachelle** [comment]
Unfortunately, this still causes a crash if the file is named .ipk7.
