### ISSUE TITLE
[BUG] "DEH health settings like Doom2.exe" compatibility option doesn't work as intended

### ISSUE THREAD

**Issue by storkgreen25** [ZDoom/gzdoom#2309]
### GZDoom version

GZDoom 4.11.3

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When you turn on the setting, instead of treating "Max Health" and "Max Soulsphere" as two separate changes, it adds those two numbers together, resulting bigger max hp amount than intended

### Steps to reproduce the behaviour.

**How to reproduce**
1. Have a Dehacked lump with:
_Misc 0
Max Health = 400
Max Soulsphere = 400_
2. Set "DEH health settings like Doom2.exe" compatibility option to "Yes"
3. You are able to get 800 hp with HP bonuses

Map I used for testing as an example: https://www.mediafire.com/file/n4hm36xo8o0siuo/gzbug.wad/file

**Comment by coelckers** [comment]
fixed in 3f05f38a600307e443e9396ece8bcadd0d420cf1
