### ISSUE TITLE
Hexen - Can't access Bright Crucible

### ISSUE THREAD

**Issue by chrisdevosnet** [ZDoom/gzdoom#2321]
### GZDoom version

GZDoom version g4.11.3 64-bit

### Which game are you running with GZDoom?

Hexen

### What Operating System are you using?

Windows 11

### Please describe your specific OS version

Windows 11 Pro 22H2

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I'm playing with Hexen.wad 1.1 (and confirmed that it has the correct MD5).

Fighter, Berserker difficulty.

I've fulfilled the requirements to open the secret level Bright Crucible.  The message "Stones grind on the Seven Portals" has been displayed, but the stone columns are not twisting to allow access as they usually do.  I have used no cheats, console commands or mods to create this save file.

I've been unable to find any other issues (open or closed) mentioning Bright Crucible.

Many thanks in advance!

### Steps to reproduce the behaviour.

The attached .zip contains a save file and config file:

[hexenissue.zip](https://github.com/ZDoom/gzdoom/files/13761842/hexenissue.zip)

1. Unzip gzdoom-4-11-3.a.-Windows-64bit.zip from Releases to a folder.
2. Add Hexen.wad 1.1 (MD5: abb033caf81e26f12a2103e1fa25453f ) and attached zip file contents.
3. Start GZDoom from command-line: gzdoom -config gzdoom-hexen.ini -iwad hexen.wad -savedir .\
5. Load the attached save file (called "Berserker QS" in-game).
6. It places you just in front of the trigger on Guardian of Steel.  Jump up, collect the torch and display the message "Stones grind on the Seven Portals".
7. Return to Seven Portals.  
8. The stone columns do not rotate to allow access to the Bright Crucible level.

I have followed the above instructions myself and can confirm this reproduces the bug.

### Your configuration

```ini
See attached file.
```

**Comment by coelckers** [comment]
The messages here are a bit misleading, but the secret level requires TWO actions.
The second action is to press the switch in the westernmost area of the Guardian of Fire that says "one half of the puzzle has been solved."
If you do not press that, the passage won't open.
