### ISSUE TITLE
Crash involving direct folder loading on linux?

### ISSUE THREAD

**Issue by MajorCooke** [ZDoom/gzdoom#2322]
Apparently I'm being told there's an oddity with loading strange lumps in the latest commits on arch linux.

1. Create a folder, named whatever you want.
2. Add two empty files, one called CVARINFO and one called ZZCrashMe
3. Load the folder with GZDoom.

I can't comment further on this as I don't run linux.

**Comment by MajorCooke** [comment]
I've also been informed just now there's an unrelated crash where if you only have CVARINFO (must be in all caps), it'll also crash but for different reasons. One apparently triggers the other.

**Comment by coelckers** [comment]
I can't either, so I'll leave it to a Linux user with the ability to test.

**Comment by Blzut3** [comment]
Confirmed that merged pull request #2363 fixes the crash condition described.

**Comment by coelckers** [comment]
I ported the fix to Raze as well, it'd be nice if someone could check the multiple related reports there as well.
