### ISSUE TITLE
[BUG] Loading WAD as dir with `-file DIR` do not work while packed DIR.zip/.pk3 works (Part 2)

### ISSUE THREAD

**Issue by vsonnier** [ZDoom/gzdoom#2334]
First of, thanks to @vs-shirokii to have investigated #2319 previously, unfortunatly it was not enough to cover all cases.

----------------------------------

### GZDoom version

4.12 dev build https://github.com/ZDoom/gzdoom/commit/4273af80043d1415ffd134aa0725ba0f3dfb327c

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 11

### Please describe your specific OS version

x64 Home 23H2

### Relevant hardware info

Nvidia RTX 4070 run with Vulkan

### Have you checked that no other similar issue already exists?

- [X] same as #2322 ? Anyway, continuation of #2319, not fully solved.

### A clear and concise description of what the bug is.

Loading a WAD "as a directory" with the `-file` argument with complex sub-wads and resources still do not work (even after the lastest File system fixes), while the equivalent packed as .zip or .pk3 load properly.

Such structure can happen with Brutal Doom derivatives for instance.

This makes developpement on such versions quite cumbersome, forcing to pack the resources first into .zip to be able to run the wad. 

This works with GZDoom v4.11.3 release.

### Steps to reproduce the behaviour:

1. Download the following Brutal Doom derivative : https://www.moddb.com/mods/brutal-doom/addons/brutal-doom-v20b-black-edition
 Sorry for the download size, but there is no point in creating a point reproducer like last time, which in turn will only exhibit a problem with a particular lump. :(   This `.pk3` is composed of various ACS, DECORATE, Zscript data and various other resources, which hopfully will cover all cases this time.
  
2. Extract file `BDBE_v3.37.pk3`, the only file we are interested in here.
3. Try to load with command line `-config gzdoom-Normal.ini -file D:\xxxxxxxx\BDBE_v3.37.pk3` => OK
4. Unzip into a `BDBE_v3.37` dir, such as we have the following structure : 

```c
BDBE_v3.37/BESounds.wad, 
BDBE_v3.37/MAPS/TITLEMAP.wad...etc. 
```
5. Try to load with command line `-config gzdoom-Normal.ini -file D:\xxxxxxxx\BDBE_v3.37`  => The WAD do not load, with various errors : (GZDoom console output)
 
```c
OS: Windows 11 (or higher) (NT 10.0) Build 22631
    
GZDoom version g4.12pre-242-g4273af800
W_Init: Init WADfiles.
adding D:/xxxxx/gzdoom.pk3, 673 lumps
adding D:/xxxx/game_support.pk3, 3307 lumps
adding ./DOOM2.WAD, 2919 lumps
...
S_Init: Setting up sound.
I_InitSound: Initializing OpenAL
 ...
V_Init: allocate screen.
ST_Init: Init startup screen.
Checking cmd-line parameters...
S_InitData: Load sound definitions.
G_ParseMapInfo: Load map definitions.
Texman.Init: Init texture manager.
Invalid data encountered for texture D:/xxxx/BDBE_v3.37/:textures/haze.png
Invalid data encountered for texture D:/xxxx/BDBE_v3.37/:textures/idtech_l
Invalid data encountered for texture D:/xxxx/BDBE_v3.37/:textures/liondoor
Invalid data encountered for texture D:/xxxx/BDBE_v3.37/:textures/marblmn
Invalid data encountered for texture D:/xxxx/BDBE_v3.37/:textures/marblmn3
Invalid data encountered for texture D:/xxxx/BDBE_v3.37/:textures/marbman
Invalid data encountered for texture D:/xxxx/BDBE_v3.37/:textures/mars_gr2
Invalid data encountered for texture D:/xxxx/BDBE_v3.37/:textures/marssurf
Invalid data encountered for texture D:/xxxx/BDBE_v3.37/:textures/nitevis.png
Invalid data encountered for texture D:/xxxx/BDBE_v3.37/:textures/pentafac
Invalid data encountered for texture D:/xxxx/BDBE_v3.37/:textures/prevrender.png
Invalid data encountered for texture D:/xxxx/BDBE_v3.37/:textures/screenblood2.png
Invalid data encountered for texture D:/xxxx/BDBE_v3.37/:textures/sculcol2
Invalid data encountered for texture D:/xxxx/BDBE_v3.37/:textures/scullcol
Invalid data encountered for texture D:/xxxx/BDBE_v3.37/:textures/tcamtex0.png
Invalid data encountered for texture D:/xxxx/BDBE_v3.37/:textures/vc

Execution could not continue.

W_ReadFile: only read 0 of 295840 on 'textures.flare'

```

### Your configuration

[gzdoom-Normal.zip](https://github.com/ZDoom/gzdoom/files/13758638/gzdoom-Normal.zip)

**Comment by coelckers** [comment]
fixed in 5b90b2d80c6b976138472e8e389d76cb89282e37
