### ISSUE TITLE
[Feature] Return line distance culling, add "ALWAYSRENDERED" and "NOTDISTANCECULLED" flags for an idea on maps optimization to work the best

### ISSUE THREAD

**Issue by Darkcrafter07** [ZDoom/gzdoom#2366]
### GZDoom version

GZDoom 4

### Which game are you running with GZDoom?

Doom

### What Operating System are you using?

Windows 10

### Relevant hardware info

Ryzen 1600, RTX 3060

### Is your feature request related to a problem? Please describe.

Too slow performance has now been tackled with a set of big 3D models that pop on and off and still slowed down by BSP traversal so "void" sectors must be placed here and there to unload the CPU a bit.

Return line distance culling please and add
+ALWAYSRENDERED flag
+NOTDISTANCECULLED flag

### Describe the solution you'd like

Let's say I made a huge map and placed my big 3D model in there so that it contributes greatly to it OR I replaced the whole map with a 3D model so it's getting up to 8 times faster.

 One must define it a huge render radius so it doesn't pop on and on as you move around the map and look sides. The issue here is that the bigger render radius is the worse performance is - awfully worse, maybe because BSP should traverse through way more linedefs/sectors.

I'd like for such a flag to be present in decorate and zscript and all other similar things.

Here's an interesting catch though, as a level is now huge and has a dynamic skybox around it, line distance culling allows to bypass BSP traversal and greatly increase the rendering speed - due to level's important visible parts now are only rendered via those 3D actors. As soon as a needed line distance culling range is chosen, the skybox part is starting to get messy as it's too far for the renderer to reach it, that's why I'd suggest "+NOTDISTANCECULLED" flag, so the skybox sector linedefs could be marked with such and not messed up.

The map is available here: https://www.doomworld.com/forum/topic/131812-hell-renaissance-wip-v024a/
(Map15)

Some screenshots of the map: https://imgur.com/a/OqOwJio

### Add any other context or screenshots about the feature request here.

![GitHub_issue_GZDoom](https://github.com/ZDoom/gzdoom/assets/145045397/52b6c221-d03f-4b21-bd36-be3500f905a6)

**Comment by nashmuhandes** [comment]
Sorry, but no one on the team is interested in tackling this issue in the immediate future, _especially_ not in the way suggested in the original post.

If any optimization work was to be done to the engine in future, it certainly would be done differently (for example, utilizing a GPU-based level mesh constructor).

**Comment by Darkcrafter07** [comment]
Right now as I updated from my old setup R5 1600-1060-3gb to R7 5700x-RTX3060 GZDoom still lags on such maps, not as hard but still, what's about cheaper laptops and older systems? These are still capable to rock on in way older AAA games while such primitive maps really suck in GZDoom.

I thought including these features would not be so hard. I have discovered a nice workaround, did most of the job on my own and it gets declined, since you guys are not interested in such a massive speed up that it works on dumpster grade PCs. We don't really know when that "future" begins, isn't there really any incentive left in your team? Sorry if that hurts.

**Comment by MajorCooke** [comment]
Hurt? Wat. Sounds like you need to re-read what Nash said, particularly this part.
> If any optimization work was to be done to the engine in future, it certainly would be done differently (for example, utilizing a GPU-based level mesh constructor).

**Comment by coelckers** [comment]
Just because something "works now" does not mean it's a good idea to add it.
Once in, it can never be removed again and we'd be stuck with heavy baggage forever.
