### ISSUE TITLE
[BUG] UDMF props not documented in udmf_zdoom.txt

### ISSUE THREAD

**Issue by biwa** [ZDoom/gzdoom#2376]
### Which game are you running with GZDoom?

None

### What Operating System are you using?

None

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

There seem to be several UDMF properties missing from https://github.com/ZDoom/gzdoom/blob/master/specs/udmf_zdoom.txt:

Linedef
-------
arg1str

Sector
------
health3d
health3dgroup

Thing
-----
arg1str
friendlyseeblocks
nocount

**Comment by madame-rachelle** [comment]
fixed
