### ISSUE TITLE
SNDINFO: Ignore '=' for long sound names instead of erroring?

### ISSUE THREAD

**Issue by MajorCooke** [ZDoom/gzdoom#2399]
It's annoying having to relocate all long sound name definitions to a different SNDINFO just because of requiring = which isn't supported for long sound names. Can this be changed to simply ignoring them instead?

**Comment by coelckers** [comment]
Please report the actual PROBLEM in an understandable fashion instead of suggesting a workaround for something that's completely unclear from your description. This report is not helpful.
