### ISSUE TITLE
[Feature] Support Freedoom's new E4 soundtrack

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/gzdoom#2403]
### GZDoom version

GZDoom 4.11.3

### Which game are you running with GZDoom?

Other

### What Operating System are you using?

Linux x86_64

### If Other OS, please describe

Kubuntu 22.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Is your feature request related to a problem? Please describe.

Freedoom 0.13.0 was recently released, and Phase 1 includes a [new soundtrack](https://github.com/freedoom/freedoom/pull/971) for Episode 4 "Double Impact". Some ports can use the new E4 music, but GZDoom currently does not.

### Describe the solution you'd like

Make GZDoom use D_E4Mx for Ultimate Doom/Freedoom: Phase 1 episode 4 if it's available, but fall back to the existing E4 songs if an E4 soundtrack is not available.

### Describe alternatives you've considered

I've tried to add $musicalias commands to GZDoom's built-in SNDINFO lumps, since that seems to be the perfect solution for this sort of problem, but $musicalias commands in internal SNDINFO lumps do not work because GZDoom doesn't allow it.

### Add any other context or screenshots about the feature request here.

https://github.com/freedoom/freedoom/pull/971
https://www.doomworld.com/forum/topic/135660-release-double-impact-midi-pack-a-community-soundtrack-for-double-impact-and-freedoom-e4/

**Comment by coelckers** [comment]
$musicalias respects loading order so that it doesn't become exclusive.
It should work if you put it into 'after_iwad/sndinfo.txt' which forces the aliases into the correct position in the load order.
