### ISSUE TITLE
[BUG] GZDoom sometimes crashes when saving in a save file with several hours of playtime 

### ISSUE THREAD

**Issue by inkoalawetrust** [ZDoom/gzdoom#2407]
### GZDoom version

4.1.1

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 10

### Relevant hardware info

Ryzen 5600X, RTX 2060, the hardware doesn't really matter in this case.

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When I play for more than a few hours with Project Brutality in a save file, GZDoom will eventually begin crashing most times that I try saving, making it incredibly hard to play through the rest of the game. Probably not too relevant, but this also happens on mapsets generated with [Obsidian](https://github.com/obsidian-level-maker/Obsidian). This is the second time this has happened, and it doesn't happen with RelWithDebInfo builds.

[Here's all the files from the latest mapset this begun happening on.](https://cdn.discordapp.com/attachments/873837785382027285/1208318240837607444/Obsidian_Mapset.zip?ex=65e2d90e&is=65d0640e&hm=954dac8457735e2943716a4b8d5ed0082645ee8420315a60f088b48c9760f48a&) [For PB any version from this branch will do, I just load it directly as a folder.](https://github.com/pa1nki113r/Project_Brutality/tree/PB_Staging)

### Steps to reproduce the behaviour.

1. Generate a mapset with Obsidian.
2. Load it with Project Brutality.
3. Play for a few hours.
4. Eventually GZDoom will begin occasionally crashing when saving.

### Provide a Log

[CrashReport.zip](https://github.com/ZDoom/gzdoom/files/14318061/CrashReport.zip)

**Comment by RicardoLuis0** [comment]
> it doesn't happen with RelWithDebInfo builds

this doesn't make sense -- RelWithDebInfo builds are the exact same code as Release builds, except they have a pdb built alongside

**Comment by generic-name-guy** [comment]
It happens more often when in a map with lots of monsters and using the autoautosave addon, sometimes when autoautosave tries to save the game, it'll hard crash

**Comment by inkoalawetrust** [comment]
> > it doesn't happen with RelWithDebInfo builds
> 
> this doesn't make sense -- RelWithDebInfo builds are the exact same as Release builds, except they have a pdb built alongside

Well, I haven't played in a RelWithDebInfo build for several hours to have it occur. And frankly I'm not in the mood to waste like 6 hours of my time playing just to be unable to actually finish the mapset. Most I played trying to debug it is about half an hour.

**Comment by inkoalawetrust** [comment]
Okay, I finally got the fucker. The crash occasionally happens because GZDoom tries to get the characters of some name type variable, but the calling object somehow has a null class ?

Here is a link to [the stack trace](https://gist.github.com/inkoalawetrust/5912661413adc6db1496590ad2ebc9cf) and [my GZDoom build](https://cdn.discordapp.com/attachments/873837785382027285/1210122540870012970/CrashingBuild.7z?ex=65e96970&is=65d6f470&hm=97a5af209a10a07ef331466ba6f7525ab8282c2fbed9d4e1b3420e8d97537e4f&), and [the actual save file](https://cdn.discordapp.com/attachments/873837785382027285/1210126863981346826/save04.zds?ex=65e96d77&is=65d6f877&hm=b35bf4d7e2f7f2a5953ade19e2ffc08794fb89d0c76c28b790ad7564593d5953&). And this is [my PB version.](https://github.com/pa1nki113r/Project_Brutality/tree/6fa7c4443b1b7bbba0abca1d791ed3cd57f427f8)


The crash starts occasionally occurring when saving on the next map. So just try playing through and occasionally saving and it should start happening.

**Comment by RicardoLuis0** [comment]
@inkoalawetrust can you test/confirm that these crashes are fixed with https://github.com/ZDoom/gzdoom/commit/ef4c4ee503c2faa6a9c0ba2ed32613adfb01ce27 ?

**Comment by inkoalawetrust** [comment]
Well I'm not sure why, but I can't seem to replicate it even on my old buggy build anymore. But if you could replicate it before and now can't, then that probably means it's fixed.

**Comment by RicardoLuis0** [comment]
i'll close this then 👍
