### ISSUE TITLE
[BUG] Loading Project Brutality on GZDoom 4.12pre triggers a crash.

### ISSUE THREAD

**Issue by inkoalawetrust** [ZDoom/gzdoom#2408]
### GZDoom version

g4.12pre-378-gf3669cd7f6-m

### Which game are you running with GZDoom?

Doom

### What Operating System are you using?

None

### Please describe your specific OS version

Windows 10 Pro 21H2

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When loading [the latest version of Project Brutality](https://github.com/pa1nki113r/Project_Brutality/tree/PB_Staging) with [the specific build attached](https://cdn.discordapp.com/attachments/873837785382027285/1209089201069490226/RelWithDebInfo.zip?ex=65e5a711&is=65d33211&hm=948a93d97ec3601fb0ebf61e188cad9eb28a74a8f377fdd4d4aa65f552af8b9e&). GZDoom will crash while trying to read the MD5 checksum of the BEHAVIOR lump (Of the mods' TITLEMAP presumably).

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Download the latest version of Project Brutality and my specific debug build.
2. Run PB.
3. The game should crash when it finishes loading.

### Provide a Log

Stack trace of the crash:
>	gzdoom.exe!MapData::GetChecksum(unsigned char * cksum) Line 411	C++
 	gzdoom.exe!P_SetupLevel(FLevelLocals * Level, int position, bool newGame) Line 471	C++
 	gzdoom.exe!FLevelLocals::DoLoadLevel(const FString & nextmapname, int position, bool autosave, bool newGame) Line 1454	C++
 	[Inline Frame] gzdoom.exe!G_DoLoadLevel(const FString &) Line 1340	C++
 	gzdoom.exe!G_InitNew(const char * mapname, bool bTitleLevel) Line 655	C++
 	gzdoom.exe!D_DoAdvanceDemo() Line 1470	C++
 	gzdoom.exe!TryRunTics() Line 2007	C++
 	gzdoom.exe!D_DoomLoop() Line 1225	C++
 	gzdoom.exe!D_DoomMain_Internal() Line 3767	C++
 	gzdoom.exe!GameMain() Line 3793	C++
 	gzdoom.exe!DoMain(HINSTANCE__ * hInstance) Line 266	C++
 	gzdoom.exe!wWinMain(HINSTANCE__ * hInstance, HINSTANCE__ * nothing, wchar_t * cmdline, int nCmdShow) Line 563	C++
 	[External Code]

**Comment by madame-rachelle** [comment]
It really helps to define "latest version" - because as is the nature of software that changes over time (Project Brutality being no exception) "latest" can mean something very different when the bug is addressed and at that point it may be much more difficult to pin down the version causing this issue, especially if a change is made within the mod to work around this error.

**Comment by inkoalawetrust** [comment]
I mean the latest version as of the time I made the bug report. Or [this version](https://github.com/pa1nki113r/Project_Brutality/tree/6fa7c4443b1b7bbba0abca1d791ed3cd57f427f8) which is the one I have right now. I'd include a download link for it but it'd be like 200 MB.

**Comment by madame-rachelle** [comment]
Yes - commit hash, always, please. :) That works, thank you.

**Comment by inkoalawetrust** [comment]
Actually, I think I should probably close this, because I compiled a newer build of GZDoom and it not longer occurs. So I guess whatever caused the startup crash was fixed ?

**Comment by madame-rachelle** [comment]
looks like this was already fixed in another PR
