### ISSUE TITLE
"The solution you provided was incorrect" forum error

### ISSUE THREAD

**Issue by Candlemass** [ZDoom/gzdoom#2409]
### GZDoom version

N/A

### Which game are you running with GZDoom?

None

### What Operating System are you using?

None

### Please describe your specific OS version

Android

### Relevant hardware info

N/A

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

@madame-rachelle

As I have already made perfectly clear, I can not create any posts or threads on the forum so why would you link to the forum to contact someone about this problem? I also already stated that discord is not an option. So how do I get in touch with someone that can fix the broken mess of the forum other than here if you refuse to provide an email address?

You said the forum uses google captcha but not a single time when attempting to create a post or a thread am I provided with a captcha prompt to complete. Again, I use MANY forums which are all based on the same platform and this is the ONLY one where this issue exists which indicates it's a problem on your end. I'm seeking a solution to the problem, not excuses or to be ignored and brushed aside so closing the report without doing anything is not acceptable.

### Steps to reproduce the behaviour.

Login to the forum
Attempt to create a post/thread

**Comment by coelckers** [comment]
You were already told that this place is only for issues with the GZDoom project, not the website which is independently operated.

**Comment by Candlemass** [comment]
> You were already told that this place is only for issues with the GZDoom project, not the website which is independently operated.

@coelckers

And I already told you that I can't contact the a moderator via the forum because the forum is broken and keeps throwibg a vague error so how about providing a valid solution instead of deflecting the problem?

**Comment by MajorCooke** [comment]
Why is Discord not a choice for you?

**Comment by Candlemass** [comment]
> Why is Discord not a choice for you?

@MajorCooke

Requires a phone number.
