### ISSUE TITLE
The solution you provided was incorrect" forum error

### ISSUE THREAD

**Issue by Candlemass** [ZDoom/gzdoom#2412]
### GZDoom version

N/A

### Which game are you running with GZDoom?

None

### What Operating System are you using?

None

### Please describe your specific OS version

Android

### Relevant hardware info

N/A

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

This problem is still ongoing and telling me to contact a moderator on the forum when I can't create any posts or threads due to said vague error makes zero logical sense.

Need a solution please.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Login to account
2. Attempt to create a post/thread

### Provide a Log

N/A

**Comment by madame-rachelle** [comment]
There is nothing we can do, and annoying us about it just gets you blocked.
