### ISSUE TITLE
"The solution you provided was incorrect" forum error

### ISSUE THREAD

**Issue by Focus221** [ZDoom/gzdoom#2420]
### GZDoom version

N/A

### Which game are you running with GZDoom?

None

### What Operating System are you using?

None

### Please describe your specific OS version

Android

### Relevant hardware info

N/A

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Rachael, Why are you attempting to deflect and sweep this under the rug as if it isn't a problem and nothing happened? Do you think you're fooling anyone when you make bullshit excuses to do nothing? Didn't you learn anything from your disgraceful pedofile grooming coverup last year?

### Steps to reproduce the behaviour.

Explain how to reproduce
1.  Login to forum account
2. Attempt to create post/thread

**Comment by coelckers** [comment]
For the fourth or fifth time: THIS IS NOT THE PROPER PLACE TO REPORT PROBLEMS WITH THE WEBSITE!!!!!!

The people  maintaining this repository have no access to it, THAT INCLUDES RACHAEL!!!

So please, try to contact them via other means, nobody with the power to fix this comes here and nobody who comes here can do something about it
