### ISSUE TITLE
"The solution you provided was incorrect" forum error

### ISSUE THREAD

**Issue by Focus235** [ZDoom/gzdoom#2426]
### GZDoom version

N/A

### Which game are you running with GZDoom?

None

### What Operating System are you using?

None

### Please describe your specific OS version

Android

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

@coelckers And therein lies the problem. Instead of understanding and contributing to a solution you STILL choose to double down your ignorance and do nothing. You are part of the problem and the reason this issue has taken the course it has.

@madame-rachelle That's rich coming from the biggest "karen" on gzdoom that literaly nobody can stand and to top it off you're still trying to hide the fact that you protect and enable pedofile grooming predators. Logic would dictate you disappear but here you are desperately clinging to what's left of your broken ego. You may like to think that you've swept your past scandals under the rug but the internet never forgets.

And just to clarify in contrast to your moronic conclusion, I asked you guys nicely for help 2-3 times but you kept choosing to do nothing. You are to blame for what has transpired by being a lazy bitch the entire time. I have also had an account on the forum for 7 or 8 years. Took a year off from posting and came back to this laughably broken misconfigured mess with no way to contact anyone outside of github about it. Nice theory though. Maybe step down if you have no intention of actually helping anyone rather than putting on this pretentious facade. What a joke.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Login to forum account
2. Attempt to post/create thread

**Comment by MajorCooke** [comment]
I'm going to do them a favor and just start auto closing these for them so they don't have to be burdened by you anymore.
