### ISSUE TITLE
[BUG] Crouching in the deep water effect in STRAIN (maybe other WADs too) crashes

### ISSUE THREAD

**Issue by StefanoP85** [ZDoom/gzdoom#2428]
### GZDoom version

GZDoom version g4.11.0

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

Windows NT 10.0 Build 19045

### Relevant hardware info

Prozessor	Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz, nVidia(R) GeForce(R) GTX 950M

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I played the STRAIN.WAD and STRAIN.DEH from Alpha Dog Alliance, 1997, map MAP21 Maintenance; the "deep water" effect near the yellow key has always caught my attention, so I decided to get to the bottom of my curiosity, literally: if I crouch in that sector, the game crashes. In the original (MS-DOS) game, you could not do that, and even now with modern GZDoom you really should not do that, so this is not really a problem.
This is the crash report.

GZDoom version g4.11.0 (d07de089c0c205c50c9d8e74b5f7d7866770a9f5)
Command line: D:\GZdoom\gzdoom.exe -deh D:\WAD\STRAIN.DEH -file D:\WAD\STRAIN.WAD
Wad 0: gzdoom.pk3
Wad 1: game_support.pk3
Wad 2: DOOM2.WAD
Wad 3: lights.pk3
Wad 4: brightmaps.pk3
Wad 5: STRAIN.WAD

Current map: MAP21

viewx = 272.065997
viewy = -1169.039921
viewz = 52.500000
viewangle = 162.070313

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load STRAIN.WAD, I'm using the original one, with its DeHackEd patch, warp on MAP21.
2. Navigate through the yellow key, either normally or with the NOCLIP cheat.
3. When you are in the "deep water" effect sector, just crouch.

### Your configuration

```ini
https://gist.github.com/StefanoP85/240ae9652bdf1a3a1b750d35ef67534d
```

### Provide a Log

https://gist.github.com/StefanoP85/32c6493d90c5db1f619b5732330deb03

**Comment by RicardoLuis0** [comment]
you're using an outdated version of the engine, can you confirm that it still happens in [4.11.3](https://github.com/ZDoom/gzdoom/releases/tag/g4.11.3), and if it does, if it still happens in a [devbuild](https://devbuilds.drdteam.org/gzdoom/)?

**Comment by StefanoP85** [comment]
Great!
Thank you, but I was unable to answer in github, so I could only answer via
e-mail.

Il Lun 8 Apr 2024, 12:54 Christoph Oelckers ***@***.***> ha
scritto:
