### ISSUE TITLE
[Feature] Support for more than .WAD files with GAMEINFO's LOAD feature

### ISSUE THREAD

**Issue by MajorCooke** [ZDoom/gzdoom#2438]
It only became clear now that apparently LOAD only works on .WAD files. I have no idea why it's restricted to this

**Comment by coelckers** [comment]
That's because you made some error. I have it working with other file types. Please post your setup.

**Comment by MajorCooke** [comment]
(DamageHudIndicator.pk3[https://drive.google.com/file/d/1IP1qUdPe3OSxwMZ8KTsX8D-6W3qByeHj/view?usp=drive_link]
(LoadMyJunk.pk3)[https://drive.google.com/file/d/14xuyFrso4kyahHtmsEf3rXe4Gso7jjva/view?usp=drive_link] has a single line, `LOAD="DamageHudIndicator.pk3"`

But when loading LoadMyJunk.pk3 only, it doesn't load DamageHudIndicator.pk3.

**Comment by RicardoLuis0** [comment]
is LoadMyJunk the only file you're loading with a `GAMEINFO`? GAMEINFO is **not** a cumulative lump, so only the the last defined one is respected

**Comment by MajorCooke** [comment]
Yes. Also, I wish it was cumulative.

**Comment by MajorCooke** [comment]
Oooh I see. Maybe there could be a LOADFILE lump that indicates what should be loaded with it instead?

**Comment by MajorCooke** [comment]
I'll open another ticket for this actually.
