### ISSUE TITLE
[Feature] LOADFILE lump

### ISSUE THREAD

**Issue by MajorCooke** [ZDoom/gzdoom#2442]
I think GZDoom would benefit greatly from having a simple lump where you can define the locations of files, relative to the same directory similar to ZScript's `include` where a '.' represents the same directory to start the search, or people can enter the whole thing manually if they desire.

Then on each line it'd be as simple as this:
```
"./DamageHudIndicator.pk3" // Same directory
"./TripleM.pk3" after
```

These would be processed in the order they're loaded and the files are added before processing everything in the archive with the LOADFILE lump.

Could likely throw in some flags too like changing when to load it - before or after the current file, for example.

**Comment by andOlga** [comment]
GZDoom [already has this](https://zdoom.org/wiki/GAMEINFO) (see the "LOAD" option).

**Comment by MajorCooke** [comment]
[Which doesn't work if more than one GAMEINFO is present.](https://github.com/ZDoom/gzdoom/issues/2438#issuecomment-1986277697

**Comment by coelckers** [comment]
I deliberately skipped this to avoid the inevitable dependency hell that will ensue. Once we start allowing mods to load other mods it is unavoidable to run into versioning conflicts that no end user will be able to resolve.
