### ISSUE TITLE
[Feature] A_SetCrosshair values below 0 should hide the crosshair

### ISSUE THREAD

**Issue by tunbridgep** [ZDoom/gzdoom#2443]
### GZDoom version

g4.12-pre-436-g3033fafaa

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 10

### Is your feature request related to a problem? Please describe.

More and more gameplay mods are shipping with enhanced weapon features like scopes, iron sights, and other features, which necessitate hiding the crosshair temporarily while they are in effect.

Currently, the only way to do this is to ship a custom blank crosshair. This is not only tedious, it also reduces compatibility between mods, as multiple mods may ship the same blank crosshairs under different numbers.

### Describe the solution you'd like

There should be a universal way to hide the crosshair, since it is a commonly needed feature among more and more mods.

I propose that calling A_SetCrosshair with a value of -1 will hide the crosshair completely (unless the player has force default crosshair turned on). Currently negative values are the same as passing 0 and will reset the crosshair back to the users default.

This will mean some mods no longer have to ship blank crosshair files, and we have a universal standard for hiding the crosshair.

The "force default crosshair" setting could also be extended with a third state where no custom crosshairs will be used, but mods can still hide it, allowing mods with ironsights or scopes to hide the crosshair when it's meaningful, without letting mods affect their standard crosshair.

Project Brutality is especially bad in this regard because it ships 99 extra crosshairs (which are used for various weapon charge states, etc), so it's "invisible crosshair" replaces crosshair 5.

### Describe alternatives you've considered

A new action function A_HideCrosshair could work too, however I think using -1 for A_SetCrosshair is neater

**Comment by madame-rachelle** [comment]
[added](https://github.com/ZDoom/gzdoom/commit/8fe58db31101fbe5054f5c0e3f1abb04d6bb8f5f)
