### ISSUE TITLE
[BUG] Crash when exiting a demon in d4t

### ISSUE THREAD

**Issue by x3003** [ZDoom/gzdoom#2449]
### GZDoom version

gzdoom-x64-g4.12pre-449-g730ef1a23

### Which game are you running with GZDoom?

Other

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

Win 10 x64 22h2

### Relevant hardware info

amd r5 1060 gtx

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When playing d4t v2.5 together with freedoom 2, exiting a demon crashes gzdoom.
It gives an access violation error.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Shoot a demon
2. Enter a demon
3. Try to exit a demon

### Provide a Log

Crashreport and savefile provided.

[CrashReport_d4t.zip](https://github.com/ZDoom/gzdoom/files/14565599/CrashReport_d4t.zip)

**Comment by Boondorl** [comment]
Could you be more specific on the steps for reproducing? I'm not sure what "enter a demon" means in this context and this mod appears to be quite complex.

**Comment by x3003** [comment]
Some of the demons give an icon, which you can 'pickup'. That is when you enter a demon.
When loading the savefile, you see the icon direct in front of you.

![Screenshot_Doom_20240313_231931](https://github.com/ZDoom/gzdoom/assets/77861029/74e8c928-ef0c-4f1a-a65c-6c7eb35f41c0)

![Screenshot_Doom_20240313_231949](https://github.com/ZDoom/gzdoom/assets/77861029/b608e579-3971-4a52-8308-f6752aa32b10)

When you are in one, you might wanna exit the demon to play on. That's were gzdoom crashes.

**Comment by Boondorl** [comment]
Fixed as of https://github.com/ZDoom/gzdoom/pull/2459.
