### ISSUE TITLE
[Feature] Return the removed sector light modes

### ISSUE THREAD

**Issue by skdursh** [ZDoom/gzdoom#2450]
### GZDoom version

4.11.3.a

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 10

### Is your feature request related to a problem? Please describe.

I just now updated to the most recent mainline version (4.11.3.a) in order to play Eviternity II. Prior to doing so I was using primarily v4.8.2. After starting the game I immediately noticed that the lighting looked off. I had copied over my previous .ini to the new installation so I assumed it should for the most part remain as I had already previously configured it, but then I saw that several of the sector light mode options have been removed entirely and I'm at a loss as to why. I sometimes have a very difficult time seeing using certain sector light modes as often things a short distance from the player will fade to darkness too rapidly and so in v4.8.2 I primarily used the "Doom" sector light option, but with the gamma bumped up to around 1.5, the brightness raised slightly and saturation also increased and this provided a happy balance for me which wasn't too difficult on my eyes. Why were the extra light modes removed? It feels nonsensical to arbitrarily remove from the player graphical customization options which were already implemented, so unless there is some technological reason for their removal I'd like to request that they be returned to the engine. If there is no intention to return them, for whatever reason, then if someone could please direct me to where the code for the various sector light modes is located so I may attempt to reimplement them myself for private use I would appreciate it. In the meantime I'll be returning to v4.8.2 as although I want to play Eviternity II, I don't want to have to strain my eyes to do it.

### Describe the solution you'd like

I'd like to see the various additional sector light modes returned.

### Describe alternatives you've considered

Not using the current version of the engine.

**Comment by coelckers** [comment]
They were removed for good reasons, the way they are handled now is how it always should have been.
