### ISSUE TITLE
[BUG] Thing_Hate messes up path finding

### ISSUE THREAD

**Issue by FishyClock** [ZDoom/gzdoom#2451]
### GZDoom version

GZDoom g4.12pre-449-g730ef1a23

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

If a monster is set to attack another monster via Thing_Hate then it refuses to use the path finding system

### Steps to reproduce the behaviour.

Load this test map (replaces MAP01 - launch Doom 2)
[nodepath-thinghate-test.zip](https://github.com/ZDoom/gzdoom/files/14577737/nodepath-thinghate-test.zip)

You will notice a revenant to the left, and a pinky to the right. The revenant is modded so it constantly logs its "goal" and "target" pointers.
Shoot your weapon to wake them normally - here the path finding works just fine as it should.

Now, hit the switch right in front of you to make the revenant and pinky hate each other. If you do this before you wake the monsters normally, notice the revenant's goal pointer stays null for some reason.

Even if there was a path before, just simply making them hate each other via the switch disables the pathing logic; the revenant's goal never seems to change.
This just doesn't seem right.

**Comment by MajorCooke** [comment]
One thing to keep in mind here is that monsters will discard their paths completely upon seeing their targets. If you want them to keep their paths, you'll need to use +KEEPPATH.

**Comment by MajorCooke** [comment]
Fix provided with PR.
