### ISSUE TITLE
[Feature] Sort the iwad dialogue list by name

### ISSUE THREAD

**Issue by vanessakindell** [ZDoom/gzdoom#2477]
### GZDoom version

g4.11.3

### Which game are you running with GZDoom?

Other

### What Operating System are you using?

Linux x86_64

### Relevant hardware info

OS: Pop!_OS 22.04 LTS x86_64  Host: Oryx Pro oryp5  Kernel: 6.8.0-76060800daily20240311-generic  Uptime: 1 day, 6 hours, 48 mins  Packages: 3881 (dpkg), 223 (flatpak), 9 (snap)  Shell: bash 5.1.16  Resolution: 1920x1080, 1920x1080  DE: GNOME 42.5  WM: Mutter  WM Theme: Pop  Theme: Pop-dark [GTK2/3]  Icons: Pop [GTK2/3]  Terminal: gnome-terminal  CPU: Intel i7-8750H (12) @ 4.100GHz  GPU: Intel CoffeeLake-H GT2 [UHD Graphics 630]  GPU: NVIDIA GeForce RTX 2060 Mobile  Memory: 5524MiB / 15704MiB 

### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

Sort the iwad list by name.
Currently it puts its autodetected iwads first in a semi-random order, then everything else is added afterwards.
It would be easier to find stuff if it was alphabetized. The compatible iwad list has grown immensely since the introduction of the iwadinfo feature so it's becoming increasingly easier to have a ridiculous list of iwads to search through.

### Describe alternatives you've considered

N/A

### Add any other context or screenshots about the feature request here.

![image](https://github.com/ZDoom/gzdoom/assets/16767721/ac354d5c-495c-4a98-96de-e80644ed9dd1)

**Comment by coelckers** [comment]
The current sort order is to put the official IWADs first, sorted by importance, and changing that will surely draw far more complaints than you might expect.
