### ISSUE TITLE
[BUG] [4.10.0?] Array changes causing crashes in Reelism 2

### ISSUE THREAD

**Issue by TheKins** [ZDoom/gzdoom#2484]
### GZDoom version

GZDoom 4.10.0 onwards

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Reelism 2 uses a custom lump (SLOTINFO.TXT) to define actors to spawn under certain events. This worked great under 4.9.0. As of 4.10.0, this has changed slightly resulting in the last character in the last name somehow not being included, causing potential crashes when using the "Jackpot Dice" item. This is still present in the devbuilds of the engine.

(If you're curious or just want to see if it's _our_ screw up, the relevant code is in zscript/gametype/splotnorm.zsc starting at line 87 or so)

### Steps to reproduce the behaviour.

1. Load [Reelism 2](https://reelism.dog/)
2. Set the cvar `splot2_devbarf` to 1
3. Load a map.
4. Open the console and check the list of actors registered. The final entry should read "SlotJack_Car", but instead is registered as "SlotJack_Ca"

### Provide a Log

https://gist.github.com/TheKins/b16cec33a4281e45d0f1b9fde153949e

**Comment by coelckers** [comment]
I'm sorry, but you will have to fix your mod. You were depending on a logic error in older GZDoom's with this and now you are cutting off the last character of the lump's content yourself with this line:

slotdata = slotdata.Left(slotdata.Length()-1);

If you want to retain compatibility with older versions you may only do this if the last character is 0.

**Comment by TheKins** [comment]
Thanks for diagnosing the cause, we'd been scratching our heads about this for a while now!
