### ISSUE TITLE
ACS "Warp" function doesn't work as intended [BUG] 

### ISSUE THREAD

**Issue by TonynUBares** [ZDoom/gzdoom#2489]
### GZDoom version

it broke in gzdoom2.2.0 (worked fine before)

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When using a positive value for the xofs argument of the ACS "Warp" function with MOVEPTR flag, the reference actor spawns behind the calling actor, instead of spawning in front.
This seems to be broken and not consistent with the wiki description and with the behaviour in Zandronum since gzdoom2.2.0; every version before that, starting from gzdoom2.1.1 works as intended and a positive xofs warps the reference actor in front of the calling actor.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. I'm using a simple "Warp(ghosttid,40.0,0,32.0,0.5,WARPF_NOCHECKPOSITION|WARPF_MOVEPTR);" in an ACS script.
Ghosttid is the tid of a non-interactive ghost-alike monster, nothing special.

**Comment by coelckers** [comment]
Please post a runnable example that reproduces the crash.

**Comment by TonynUBares** [comment]
After more testing, it appears that the angle offset is broken not the xofs.
According to wiki and to Zandro's behaviour, when I use the angle argument of Warp, that angle is supposed to be added to the warping actor's angle (either the calling actor or the reference actor when using WARPF_MOVEPTR), unless you are using WARPF_ABSOLUTEANGLE
So, supposing I use a 0.5 angle argument, the calling actor is the player and the reference actor is a monster with tid "montid":

 Warp(montid,40.0,0,0,0.5,0);
or
 Warp(montid,40.0,0,0,0.5,WARPF_MOVEPTR);

- with the first function, the  player is supposed to warp 40 units in front of the monster, facing the monster (monster angle + 180°)
- with the second function, the monster is supposed to warp 40 units in front of the player, facing the player (player angle + 180°)

In gzdoom 2.2.0+ it looks like instead of applying the "angle" argument as an angle offset of the warped actor, it is applied to the direction(?)

**Comment by TonynUBares** [comment]
To test it, I'm using this ACS script.
`script "anything" ENTER
{
 delay(35);
 int montid = UniqueTID();
 SpawnForced("Zombieman",0,0,0,montid,GetActorAngle(0)>>8);
 Thing_Deactivate(montid);
 Warp(montid,40.0,0,0,0.5,WARPF_NOCHECKPOSITION|WARPF_MOVEPTR);
}`
In theory the Zombieman should warp in front of the player, then turn its angle of 180°, ending up facing the player.
Without using WARPF_MOVEPTR, player should warp in front of the Zombieman and then turn its angle of 180° to face the Zombie.
In any gzdoom above 2.2.0 (included) this doesn't happen and either Zombieman warps behind the player, or (without WARPF_MOVEPTR) the player warps behind the zombie

**Comment by prof-hastig** [comment]
You were asked to post a RUNNABLE example. The reason being that this will allow others than the main developers to check your problem.
I would have liked to check this, but I can't do that because because I do not have a readily accessible editor setup and also do not want to spend the time figuring out what to do to get the test case right, so I'm going to have to pass on this one.

**Comment by TonynUBares** [comment]
My bad (had no clear idea of "runnable example") 
[bugtest.zip](https://github.com/ZDoom/gzdoom/files/14903582/bugtest.zip)

The only thing you have to do is to run this and type "pukename anything" in console. It spawns a Zombieman in the map origin and should warp it in front of the player and facing the player; what happens, instead, is that it spawns behind the player

**Comment by prof-hastig** [comment]
What this does with a position offset is that it offsets the teleported actor by 40 units in the direction it is facing - the angle being taken here is after offsetting it. You make the teleported Zombieman face towards the player so it is offset in the opposite direction behind it. This means it looks correct what the function is doing.

I cannot get the old project state from 2.1 compiled anymore, so I cannot do comparisons.

**Comment by TonynUBares** [comment]
Ok, this means that even without the USECALLERANGLE flag, the expected behaviour when using the angle argument is needed for making the warping angle orbit around the warped-to.

**Comment by coelckers** [comment]
I do have old versions floating around. One build made right after the 2.1.0 release shows the exact same behavior as the current master, the next oldest one I have doesn't even have the feature. If there ever was a chance it was extremely short-lived and bears no relevance because the current behavior is over 8 years old by now.
