### ISSUE TITLE
[BUG], UDMF, HW,SW renderers, hi-res textures misaligned if scale is not equal 1.0

### ISSUE THREAD

**Issue by Darkcrafter07** [ZDoom/gzdoom#2495]
### GZDoom version

GZDoom 4.11.3

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 10

### Relevant hardware info

Ryzen 7 5700X, RTX 3060

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

hi-res texture replacements get textures misaligned both in software and hardware renderers of GZDoom if sidedef/linedef texture scale is not 1.0. Btw, Doom Builder behaves the same.

![Screenshot_Doom_20240411_204544](https://github.com/ZDoom/gzdoom/assets/145045397/ae79d80c-b823-40d0-b313-0baa57cd876c)
![Screenshot_Doom_20240411_204554](https://github.com/ZDoom/gzdoom/assets/145045397/34e5730e-4871-485c-b51f-8cb1eb5ba8a1)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Create a perfect hi-res texture
2. Apply it over any sidedef
3. Set texture scaling not equal to 1.0, e.g. resize it.

**Comment by coelckers** [comment]
This is the result of some unfortunate design decisions of the long gone ZDoom past. When this problem was first discovered it wasn't fixed but turned into a sort-of feature that never worked right. Unfortunately, fixing it would mean breaking every map out there that uses its own hires textures or texture scaling in UDMF. :(

**Comment by Darkcrafter07** [comment]
> This is the result of some unfortunate design decisions of the long gone ZDoom past. When this problem was first discovered it wasn't fixed but turned into a sort-of feature that never worked right. Unfortunately, fixing it would mean breaking every map out there that uses its own hires textures or texture scaling in UDMF. :(

Good to know, there should be a way to implement a workaround with a zscript or something, isn't?
