### ISSUE TITLE
[BUG] "Additional Parameters" in the new launcher does nothing

### ISSUE THREAD

**Issue by andOlga** [ZDoom/gzdoom#2516]
### GZDoom version

g4.12.0

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 11

### Please describe your specific OS version

23H2 (OS Build 22631.3447)

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

GZDoom 4.12 got this fancy new launcher with, among other things, a textbox for "additional parameters".

![image](https://github.com/ZDoom/gzdoom/assets/462484/26f55533-59e1-4ce1-9392-1ba596b34b70)

In the example shown above, which was my initial test, I expected GZDoom to start with the DOOM2 IWAD and the `D2TWID.WAD` file loaded on top (the actual files are irrelevant). `D2TWID.WAD` is located in one of my configured PWAD paths. Full paths do not work either.

I then tried out a bunch of others: `+map`, `+logfile`, `-warp`, `-skill`. None of them do anything.

### Steps to reproduce the behaviour.

1. Start GZDoom 4.12 by double-clicking its .exe file.
2. In the launcher, type any parameters one might sensibly pass as arguments to `gzdoom.exe` in the "Additional Parameters" textbox.
3. Click "Play game".
4. Observe that none of the parameters you typed in have been applied.

### Your configuration

```ini
The issue occurs with the default configuration.
```

### Provide a Log

This is impossible as the issue relates to the launcher's parameter box, and that ignores `+logfile` among other things.
There is nothing interesting in the console though, apart from the fact that if I pass in something like `-file` I do not see it in the list of files being loaded.

**Comment by madame-rachelle** [comment]
Hidden for now, this feature is planned but there is not enough time to test it before the next release.
