### ISSUE TITLE
[BUG] [4.12] -norun no longer pauses at console, only closes the game

### ISSUE THREAD

**Issue by zhs2** [ZDoom/gzdoom#2521]
### GZDoom version

GZDoom 4.12.1

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

-norun no longer pauses at console, only closes the game when the norun point is encountered.

### Steps to reproduce the behaviour.

1. Use -norun as a command line parameter
2. Launch any game
3. Game closes

**Comment by mcauley-penney** [comment]
I am currently experiencing this issue on Arch Linux. GZDoom's output is

```
GZDoom g4.15pre-247-gd3f965e862-m - 2025-05-21 23:50:21 -0400 - SDL version
Compiled on May 23 2025

OS: Arch Linux, Linux 6.14.6-arch1-1 on x86_64
GZDoom version g4.15pre-247-gd3f965e862-m
W_Init: Init WADfiles.
adding /usr/share/gzdoom/gzdoom.pk3, 706 lumps
adding /usr/share/gzdoom/game_support.pk3, 3308 lumps
adding /home/m/doom/iwads/DOOM2.WAD, 2919 lumps
adding /usr/share/gzdoom/game_widescreen_gfx.pk3, 214 lumps
S_Init: Setting up sound.
I_InitSound: Initializing OpenAL
  Opened device Starship/Matisse HD Audio Controller Analog Stereo
  EFX enabled
Using video driver x11
Number of detected displays 3 .
Vulkan device: AMD Radeon RX 570 Series (RADV POLARIS10)
Vulkan device type: discrete gpu
Vulkan version: 1.4.311 (api) 25.1.1 (driver)
Max. texture size: 16384
Max. uniform buffer range: -1
```
