### ISSUE TITLE
[BUG] Can`t delete save files from GZDoom itself

### ISSUE THREAD

**Issue by RonDallas** [ZDoom/gzdoom#2526]
### GZDoom version

GZDoom 4.12.1

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 11

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

If you make a save file, then delete it in GZDoom it`s seems deleted, but files are still there. On the next launch deleted save files be there.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Make save file;
2. Delete save file;
3. Close and open GZDoom again (or just check the files).

**Comment by nashmuhandes** [comment]
Fixed with https://github.com/ZDoom/gzdoom/commit/f2d582f680b72eb50480e7c704f90b9bd38c7529
