### ISSUE TITLE
[BUG] Cannot assign a variable from Level.SectorPortals

### ISSUE THREAD

**Issue by mc776** [ZDoom/gzdoom#2527]
### GZDoom version

4.12.1

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Debian

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

See comments in "Steps...".

If this is intended behaviour please explain just *how* we're supposed to point to this thing so we're not constantly copypasting code like in the workaround.

### Steps to reproduce the behaviour.

```
version "4.12"

class bbb:doomimp{
	override void PostBeginPlay(){
		super.PostBeginPlay();

		//this works fine in 4.11, but crashes in 4.12 with
		//"Trying to assign readonly value to writable type."
		SectorPortal portal=Level.SectorPortals[CurSector.Portals[Sector.Floor]];
		vector3 newPos=(pos.xy+portal.mDisplacement, 0);

		//this works fine in either version
//		vector3 newPos=(pos.xy+Level.SectorPortals[CurSector.Portals[Sector.Floor]].mDisplacement, 0);

	}
}
```

**Comment by madame-rachelle** [comment]
Same as this issue https://github.com/ZDoom/gzdoom/issues/2439

**Comment by RicardoLuis0** [comment]
> Same as this issue #2439

since it's only reading the portal, it can be fixed, would just need to be either:
`readonly<SectorPortal> portal = ...`
or
`let portal = ...`

**Comment by mc776** [comment]
> > Same as this issue #2439
> 
> since it's only reading the portal, it can be fixed, would just need to be either: `readonly<SectorPortal> portal = ...` or `let portal = ...`
> 

Confirmed both of these work, closing this (and hoping there are enough search terms somewhere in the OP and replies for whoever else runs into this problem)
