### ISSUE TITLE
[BUG] Game selection/launcher window crashes (SDL_WaitEvent failed)

### ISSUE THREAD

**Issue by michaelneverwins** [ZDoom/gzdoom#2529]
### GZDoom version

GZDoom g4.12.1 installed with APT from DRD Team repo (https://debian.drdteam.org/)

### Which game are you running with GZDoom?

None

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Linux Mint 21.3 Cinnamon Edition

### Relevant hardware info

Intel i5-4570, AMD Radeon HD 7950

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

If I leave the GZDoom game selection window open for a short time, it crashes and the pictured error appears.

![SDL_WaitEvent failed](https://github.com/ZDoom/gzdoom/assets/73746653/41ea008f-7005-43bb-a34d-922514222053)

I played through The Ultimate Doom's E1M1 without issues, so this does not appear to be a problem that occurs during games. Additionally, it seems to occur only when the game selection window is left idle, as it has not happened while I'm actively clicking things within the window. Then again, the amount of time before the error appears is not consistent — sometimes it happens within a couple of seconds, and other times it takes a minute even if I'm not touching the window — so maybe it's just a coincidence that I've seen it only when leaving the window idle.

I have tested only the copy of GZDoom that I installed from DRD Team's Debian repo, which I updated to g4.12.1 yesterday. I would test the "portable" Linux release as well, but it looks like the portable version 4.12.1 has not been published yet.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Run `gzdoom` to open the game selection window.
2. Wait.

### Your configuration

Happens with default configuration (after renaming `gzdoom.ini` and letting GZDoom make a new one).

### Provide a Log

If I run `gzdoom` from a terminal and wait for the error to occur, no additional errors are printed to the terminal when it does.

**Comment by madame-rachelle** [comment]
Already fixed in master
