### ISSUE TITLE
[BUG] Pink title screens with Vulkan renderer in macOS

### ISSUE THREAD

**Issue by Aldwinbay** [ZDoom/gzdoom#2532]
### GZDoom version

GZDoom 4.12.1

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Mac OS

### Please describe your specific OS version

macOS Sonoma 14.4.1

### Relevant hardware info

M3 Pro MacBook Pro 14", 12/18c, 18GB

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When launching any game with the Vulkan renderer, the title screen will be pink. Colors return to normal after starting a game. 

<img width="1512" alt="Screenshot 2024-04-25 at 6 37 34 PM" src="https://github.com/ZDoom/gzdoom/assets/85921643/7d56953b-b7e9-425d-9b01-f4c8d5d9a76f">

<img width="1512" alt="Screenshot 2024-04-25 at 6 56 56 PM" src="https://github.com/ZDoom/gzdoom/assets/85921643/307fa2f3-c446-42f2-9077-f5def705d0df">

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Launch any supported game with the Vulkan renderer (selected by default)

### Provide a Log

[pinkscreenlog.txt](https://github.com/ZDoom/gzdoom/files/15107895/pinkscreenlog.txt)

**Comment by lead0r** [comment]
Can confirm, I experience this as well on an M1 Mac Studio

**Comment by alexey-lysiuk** [comment]
Is it better with GZDoom 4.12.2?

**Comment by Aldwinbay** [comment]
> Is it better with GZDoom 4.12.2?

Yes, it does seem to be fixed in 4.12.2. Titles screens for all IWADs look normal.

**Comment by billhollings** [comment]
This issue was re-posted as a [regression issue](https://github.com/KhronosGroup/MoltenVK/issues/2220) to MoltenVK.

I'm happy to see it was successfully patched here!

However, can you let me know the nature of your patch, so we can determine if something in MoltenVK really should be fixed there? Thanks.

**Comment by RicardoLuis0** [comment]
> This issue was re-posted as a [regression issue](https://github.com/KhronosGroup/MoltenVK/issues/2220) to MoltenVK.
> 
> I'm happy to see it was successfully patched here!
> 
> However, can you let me know the nature of your patch, so we can determine if something in MoltenVK really should be fixed there? Thanks.

AFAIK the only fix that was done was downgrading MoltenVK

**Comment by skooch** [comment]
I have a PR open that may fix this, closing https://github.com/KhronosGroup/MoltenVK/issues/2220 in MoltenVK: https://github.com/KhronosGroup/MoltenVK/pull/2724

Feel free to try the patch from my fork—please let me know if you notice anything amiss. I also noticed there's an [equivalent Raze issue.](https://github.com/ZDoom/Raze/issues/1086)
