### ISSUE TITLE
[Feature] g4.12.# Launcher lacks radio buttons

### ISSUE THREAD

**Issue by Acts19quiz** [ZDoom/gzdoom#2548]
### GZDoom version

GZDoom g4.12.2

### Which game are you running with GZDoom?

Other

### What Operating System are you using?

Windows 10

### Relevant hardware info

Intel 6700k, Nvidia 980 Ti

### Is your feature request related to a problem? Please describe.

The launcher has had, and continues to have, sections for boolean values as well as one-or-the-other radio selections.

However, beginning with the g4.12.# launcher, the radio section (specifically, "Video settings"/"Rendering API") has check boxes the same as the various boolean values ("Fullscreen", "Lights", etc.). This can create some confusion on the possibility of selecting multiple options in the video section (which is of course impossible, as veteran, experienced GZDoom users know).

### Describe the solution you'd like

Change the "Rendering API" section from using check boxes to radio buttons.

From:
🗹
To:
🔘

### Describe alternatives you've considered

N/A

### Add any other context or screenshots about the feature request here.

![g11_Launcher_edit](https://github.com/ZDoom/gzdoom/assets/63941237/9a4d04d1-bdcd-4e8f-8bb3-4c4647c2746d)
The g4.11.# launcher. Note that the one-or-the-other video section has clearly-marked and differentiated radio buttons.
![g12_Launcher_edit](https://github.com/ZDoom/gzdoom/assets/63941237/80ccf527-d61e-443b-a514-e34e20878b35)
The g4.12.# launcher. There's no differentiation between multiple-selection sections and the one section with only one choice.

**Comment by coelckers** [comment]
Considering that the render backend selection will be removed once we actually split the engine in two this is not really worth bothering. Keep in mind that the widgets are all rather simple, there is nothing that can draw circles right now and it's unlikely to be added for such a short lived feature.
