### ISSUE TITLE
[Feature] show the start up menu by default with one wad

### ISSUE THREAD

**Issue by pirate486743186** [ZDoom/gzdoom#2554]
### GZDoom version

g4.12.2

### Which game are you running with GZDoom?

None

### What Operating System are you using?

Linux x86_64

### Is your feature request related to a problem? Please describe.

First time that i run gzdoom. It froze because it was automatically set to stuff my hardware didn't support. Because i was using it for the first time, i didn't know what to do to fix it.

### Describe the solution you'd like

when gzdoom start for the first time with just one wad, it should still show the initial menu, to give us the chance to configure it in a gui if it doesn't work.

### Add any other context or screenshots about the feature request here.

This is only relevant for people that start using gzdoom.

**Comment by madame-rachelle** [comment]
This is definitely desirable with standard installs of GZDoom, but with redistributions in games it's definitely not desirable. Not really sure how best to handle this.

**Comment by madame-rachelle** [comment]
[url=https://github.com/ZDoom/gzdoom/commit/bcad040fd341e78f1f32c83d0ad8b0143dd4aa51]Added[/url]

Fork maintainers must now set a flag in version.h to decide whether to show the iwad picker by default or not.

**Comment by Acts19quiz** [comment]
https://github.com/ZDoom/gzdoom/issues/1814 I previously broached this subject. Even when the selection of renderer changes scope to separate releases and is no longer relevant to the IWAD Selection dialogue, it's still necessary for configuring GZDoom to start with dynamic lights, widescreen graphics, and (as of g4.12) language. I can't really think of why, if IWAD Selection dialogue is set to display by default, why it demands two IWADs be present if it controls more than IWAD selection. If that's all it did, then that would be a natural limitation.
