### ISSUE TITLE
Please let me run my game files by dragging and dropping/double clicking the wad>WITHOUT< needing to go through the file selection menu

### ISSUE THREAD

**Issue by Taftle10** [ZDoom/gzdoom#2571]
### GZDoom version

4.12.2

### Which game are you running with GZDoom?

Hexen

### What Operating System are you using?

Windows 10

### Is your feature request related to a problem? Please describe.

I am constantly trying to run my games from steam but the menu pops up for whatever reason and it forces me to click one of the wads (IE. Hexen, Doom, Doom 2) But if I click anything other than the wad I am trying to run the entire screen is messed up. 

### Describe the solution you'd like

I just want there to be some sort of setting that lets me double click my wad and run gzdoom (which is already possible) but without having to go through the obsolete file selection menu. If this is possible please tell me, thank you :)

### Describe alternatives you've considered

I don't have any alternatives; I feel like this could be fairly easy (I apologize if it is difficult or is already possible).

**Comment by madame-rachelle** [comment]
Have you tried this?
![image](https://github.com/ZDoom/gzdoom/assets/18584402/d7f55d09-d2d3-4875-9a0d-22ed8cbd173b)

**Comment by Taftle10** [comment]
Yeah, I tried that before but all it does is launch whatever wad I play after clicking that button any time I launch GZDoom making it so even if I try and open another wad with GZDoom it ends up messing everything up.

**Comment by RicardoLuis0** [comment]
> Yeah, I tried that before but all it does is launch whatever wad I play after clicking that button any time I launch GZDoom making it so even if I try and open another wad with GZDoom it ends up messing everything up.

gzdoom can't automatically know which iwad a mod is supposed to be played with, that's why the selection box is there in the first place

**Comment by Taftle** [comment]
Sorry for the confusion, it is not a mod it is the wad file itself. Such as hexen.wad or doom.wad not one such as brutal 
doom.pk3. Is it not possible for GZDoom to detect I am trying to run this specific game wad?
