### ISSUE TITLE
[WEBSITE] Zdoom.org incorrectly lists latest download for GZDoom as v4.12.1

### ISSUE THREAD

**Issue by prettyFist** [ZDoom/gzdoom#2580]
### Which game are you running with GZDoom?

None

### What Operating System are you using?

None

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Latest GZDoom download is correctly for v4.12.2, but /downloads mislabels it as v4.12.1.
![erroniousVersionNumber](https://github.com/ZDoom/gzdoom/assets/47872169/d7712779-df40-47ef-be31-da7a5f099602)

**Comment by madame-rachelle** [comment]
fixed
