### ISSUE TITLE
[BUG] Hexen the "give" command shouldn't give to the player the morph ovum

### ISSUE THREAD

**Issue by LuciferSam8086** [ZDoom/gzdoom#2583]
### GZDoom version

g4.13pre-66-gae28eeae9

### Which game are you running with GZDoom?

Hexen

### What Operating System are you using?

Windows 11

### Please describe your specific OS version

Windows 11 Professional 10.0.22635.3640

### Relevant hardware info

Nvidia RTX 4070 , Amd Ryzen 5900x

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

In Hexen the porkalator works correctly the enemy is being morphed into a pig, but the morph ovum morphs the actor into an invisible one.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Start Hexen
2. on a console get the items with a "give all"
3. Use the morph ovum against an enemy
4. The enemy becomes invisible, but it seems you can still hit it, since I see a blood splash if I attack where the enemy should be.
5. With the porkalator, instead, everything works correctly

In Heretic, instead, everything works correctly. The enemy is morphed into a killable chicken.

### Your configuration

```ini
https://gist.github.com/LuciferSam8086/c1a285b6abe416ac465ad95c742c413e
```

### Provide a Log

No error is shown in the console

**Comment by hfc2x** [comment]
That's not a bug. HeXen does not have chicken graphics, since that's from a completely different game.

**Comment by LuciferSam8086** [comment]
Holy! You're right, then the give command is booked, it shouldn't give the morph ovum then. I'm going to update the issue. Thanks for pointing it out.
