### ISSUE TITLE
[BUG] CTD on Linux/Haskell/NVidia-Quadro mobile with only Doom2 loaded

### ISSUE THREAD

**Issue by MartinHowe426** [ZDoom/gzdoom#2586]
### GZDoom version

4.12.2

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Linux Mint 21.3

### Relevant hardware info

i7-4800MQ, NVidia Quadro K2100M

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

GZDoom crashed to the crash reporter window after starting the engine with Doom2 and no other wads loaded. Rebuilt from source immediately afterwards, same result.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Start gzdoom from Linux terminal
2. Select DOOM2.WAD from dialogue
3. Click Play Game

### Your configuration

```ini
[gzdoom-ini.txt](https://github.com/ZDoom/gzdoom/files/15500160/gzdoom-ini.txt)
```

### Provide a Log

[gzdoom.log](https://github.com/ZDoom/gzdoom/files/15500153/gzdoom.log)
[gzdoom-crash.log](https://github.com/ZDoom/gzdoom/files/15500154/gzdoom-crash.log)

**Comment by MartinHowe426** [comment]
Just realised it set the screen size wrongly:
**Creating window [3072x1728] on adapter 0**
My desktop computer is 4K but this laptop is only FHD.
But even then, neither computer uses that resolution and I always play fullscreen.

ALSO HAPPENS IF NO gzdoom.ini FILE EXISTS

**Comment by madame-rachelle** [comment]
Can you compile as RelWithDebInfo and try again? Without symbols we can't see what's happening.

`cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo --build .`

**Comment by MartinHowe426** [comment]
OK will do; will update this evening as have to go back to work now
Happens with RAZE also, BTW.
BTW, other game engines (e.g, Ironwail, EDuke32) not affected.

**Comment by MartinHowe426** [comment]
Hello again; please find attached the GZDoom, and because it may well be the same bug in some shared code, Raze logs:

[gzdoom.log](https://github.com/ZDoom/gzdoom/files/15505100/gzdoom.log)
[gzdoom-crash.log](https://github.com/ZDoom/gzdoom/files/15505104/gzdoom-crash.log)
[gzdoom-ini.txt](https://github.com/ZDoom/gzdoom/files/15505105/gzdoom-ini.txt)

[raze.log](https://github.com/ZDoom/gzdoom/files/15505110/raze.log)
[raze-crash.log](https://github.com/ZDoom/gzdoom/files/15505111/raze-crash.log)
[raze-ini.txt](https://github.com/ZDoom/gzdoom/files/15505114/raze-ini.txt)
[grpcrccache.txt](https://github.com/ZDoom/gzdoom/files/15505125/grpcrccache.txt)

(both compiled with RelWithDebInfo)

**Comment by madame-rachelle** [comment]
The information there is a great deal more useful, though I don't have much understanding what is going on because that is code that I do not often tinker with. My best guess is the device is running out of VRAM, try lowering the screen resolution to see if it helps any, and ensure that you are not using texture scaling.

**Comment by MartinHowe426** [comment]
PS: FWIW, The Quadro K2100M has 2GB of VRAM, same as my old desktop GT1030 card, and that ran GZDoom with Vulkan just fine.

**Comment by madame-rachelle** [comment]
Well then VRAM might not be the issue. This will require taking a look at by someone else.

Texture scaling I am only referring to things like XBRz, Normal2x/3x/4x, Scale2x/3x/4x, etc.

**Comment by MartinHowe426** [comment]
Thanks for looking into it. Let's hope someone is able to have a look; in the meantime it should be possible to fallback on OpenGL.

As to scaling, if that means high resolution texture packs, then no this is with just plain old 1994 DOOM2.WAD :)

**Comment by MartinHowe426** [comment]
In the latest version of GZDoom, the bug has disappeared.

Furthermore, I have now got a suspicion of what might have caused it; however, if it's what I think it is, it's on NVidia not recognising the chipset and assigning the wrong driver. In any case, this can be closed.
