### ISSUE TITLE
[BUG] Regression: UnMorphActor or adjacent logic is broken, as seen in Brutal Doom.

### ISSUE THREAD

**Issue by GrayFace** [ZDoom/gzdoom#2590]
### GZDoom version

GZDoom 4.12.2

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Going from GZDoom 4.11.3 to 4.12.2 makes Brutal Doom's vehicles stop working properly.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Download https://www.moddb.com/mods/brutal-doom/downloads/brutal-doom-v21-beta
2. Run the game with it (e.g. `"gzdoom.exe" -iwad doom2.wad -file "brutalv21.pk3"`)
3. In the game write `summon tank` in console.
4. Press Use key to enter, then Use key again to exit the tank.
5. Try switching between fist and rifle, it wouldn't work.

### Your configuration

[gzdoom_portable.ini.txt](https://github.com/user-attachments/files/15525788/gzdoom_portable.ini.txt)

**Comment by RicardoLuis0** [comment]
can you test with a dev version? pretty sure this was fixed already in 27eb78f4374a431e5181564fdec9f923c4e89bc1

**Comment by GrayFace** [comment]
Yes, in dev build I'm not having issues thus far. Something in SBARINFO support got broken though. I'll make an issue about it.
