### ISSUE TITLE
[BUG] SBARINFO regression in "DrawString" function

### ISSUE THREAD

**Issue by liPillON** [ZDoom/gzdoom#2594]
### GZDoom version

git version,  current master branch

### Which game are you running with GZDoom?

Doom

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

Win 10 LTSC 2021 x64

### Relevant hardware info

Intel i7-1260p, Intel IrisXE 96eu

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The SBARINFO's DrawString function seems to have been broken by some code committed after the 4.12.2 release.
All text displayed using DrawString seems to be shifted to the right.
Specifying the "alignment" flag does not seems to help.

This has been noticed by user of my custom huds and shared on zdoom's discord servers; I investigated and found this to be an issue with the engine, not with specific sbarinfo-powered huds.

It affects both the "Normal" and the "Fullscreen" statusbar mode, both when using the "FullscreenOffset" clause or the fixed 320x200 coordinates notation.

I've created a no-frills sbarinfo mod to demonstrate the issue:
[sbarinfo_drawstring_test.pk3.zip](https://github.com/user-attachments/files/15596061/sbarinfo_drawstring_test.pk3.zip)

Use it with any Doom commercial IWAD.
  

### Steps to reproduce the behaviour.

1. download the official 4.12.2 gzdoom release for windows and unzip it somewhere
2. create an empty `gzdoom_portable.ini` file alongside the gzdoom.exe file
3. put a Doom commercial IWAD in the same folder as the executable
4. drag and drop the `sbarinfo_drawstring_test.pk3` file over gzdoom.exe
5. start a map and notice how the text being displayed by the hud occupies the four screen corners as expected
6. change values for the following cvars: `screenblocks` (10/11), `sbarinfo_test_mode` (1/0), `sbarinfo_alignment_enabled` (true/false) in order to test different statusbar modes, under different circumstances (drawstring vs drawnumber, explicit alignment flags)
7. now download the latest github action artifacts and repeat steps 2 through 6 using this dev build
8. notice how the results when setting `sbarinfo_test_mode=1` (drawnumber) are the same as those we got when using the 4.12.2 release; using `sbarinfo_test_mode=0` (drawstring) on the other hand lead to inconsistent behaviour 

### Your configuration

```ini
DOOM2.WAD
gzdoom_portable.ini generated from scratch
```

### Provide a Log

not applicable: neither warnings or errors are logged, the sbarinfo lump is being parsed correctly

**Comment by GrayFace** [comment]
DrawNumber is unaffected, resulting in e.g. "/" in a string "0 / 3" to be drawn above "3", as observed in UDV 2.13.

**Comment by liPillON** [comment]
I went through the 4.13.x commits and found out where the issue came up for the first time.

this build is unaffected
https://github.com/ZDoom/gzdoom/actions/runs/8770997284

the subsequent build presents the issue
https://github.com/ZDoom/gzdoom/actions/runs/8771393054

I suspect this commit introduced the bug, since the comment mentions some SBARINFO impact
https://github.com/ZDoom/gzdoom/commit/ebd4ebf29836ce6d87bcf8af389cd65513426dc9
