### ISSUE TITLE
[Feature] Add system searching for WebP

### ISSUE THREAD

**Issue by Hex4dec** [ZDoom/gzdoom#2608]
### GZDoom version

CMakeLists.txt from g14.12.2

### Which game are you running with GZDoom?

None

### What Operating System are you using?

None

### Is your feature request related to a problem? Please describe.

There is no FORCE_INTERNAL_WEBP or for that matter, any system searching for the webp library.

### Describe the solution you'd like

It would be nice if there would be a FORCE_INTERNAL_WEBP flag I could disable so I can use the system WebP library. I trust my package manager more than GZDoom.

**Comment by RicardoLuis0** [comment]
pretty sure you can revert these 3 commits to make it use the system libraries:
26fe8f020e71d2a03ac8f8ca112fceb792458dda
648b1a1f26086de1a5558fe7d2b895e75f54c628
140ad88003c6748e569f1c997471c0a20de23d07

**Comment by RicardoLuis0** [comment]
(i'll also add it to cmake, but will take a bit of testing/time)

**Comment by Hex4dec** [comment]
The reason for it being internal-only (or even internal-optional) is quite ridiculous. Package managers are supposed to do their job and you shouldn't worry about it. If vcpkg's package "breaks overnight", you shouldn't touch it and instead yell at vcpkg's maintainers to fix it.


Anyway, thank you.

**Comment by RicardoLuis0** [comment]
the reason for using vcpkg was to simplify package management on windows, since vcpkg broke, vcpkg was removed and the library was embedded

**Comment by coelckers** [comment]
Note: If you revert those 3 commits you void your warranty.

Of course we could change it, but why should we make things harder for us by haviing to deal with third party induced problems?

**Comment by Hex4dec** [comment]
Like it isn't already voided by the GPL, ha
