### ISSUE TITLE
[Feature] `QuatStruct` missing `ToAngles(Quat from)` function

### ISSUE THREAD

**Issue by nashmuhandes** [ZDoom/gzdoom#2611]
### Which game are you running with GZDoom?

None

### What Operating System are you using?

None

### Is your feature request related to a problem? Please describe.

A built-in function to get `Angle`, `Pitch` and `Roll` value from a quat.

**Comment by FishyClock** [comment]
Just for reference this is how gutamatics does it
https://gitlab.com/Gutawer/gzdoom-gutamatics/-/blob/master/Gutamatics/Quaternion.zsc?ref_type=heads#L72-101

**Comment by Gutawer** [comment]
this was left out on purpose for reasons about gimbal lock at the pitch extremities and how that affects gzdoom’s euler angle interpolation, i’d recommend still keeping it out on purpose. people who really want to can implements this function inside zscript. id recommend keeping it this way

regardless please absolutely do not just copy this from gutamatics, im not sure at all of that codes quality

**Comment by FishyClock** [comment]
Understood
