### ISSUE TITLE
[BUG] Morphing broken

### ISSUE THREAD

**Issue by JimmyZD** [ZDoom/gzdoom#2621]
### GZDoom version

4.12.1/4.12.2

### Which game are you running with GZDoom?

Heretic

### What Operating System are you using?

Windows 11

### Please describe your specific OS version

Windows 11 Home

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Using a morph ovum on an enemy makes the enemy morph but still enables them to attack. Missile appear to not spawn from the monster's origin - as though the enemy is still able to move outside of its morphed form.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Boot a game using Heretic as the IWAD.
2. Summon "artiegg", pick it up, and then summon or encounter any monster.
3. Morph the monster.
4. Observe its behavior. It will continue attacking. Missiles will spawn outside of the morphed actor's body. Melee attacks can be performed by an apparently invisible version of the monster.
![Screenshot_Heretic_20240709_211004](https://github.com/ZDoom/gzdoom/assets/6960157/e5bcf5a3-c009-46a8-8bbe-d5acb79b7a11)

**Comment by RicardoLuis0** [comment]
fixed already in da4752d7ec74534c4de3618894447f9fbcd58d06

**Comment by JimmyZD** [comment]
Great! Sorry if I missed an update on this issue that was somewhere obvious. (I searched the GitHub and the ZDF and found nothing that seemed relevant.)
