### ISSUE TITLE
Impossible to register to neither forum nor discord

### ISSUE THREAD

**Issue by zwzsg** [ZDoom/gzdoom#2623]
### Which game are you running with GZDoom?

None

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I am sorry to use this wrong place, but I can't report it on neither the forum nor discord for obvious reason:

When I try to register on the forum, my browser spins for a while, then I get in the middle of the page in red:
The solution you provided was incorrect
and at the top of the page:
[phpBB Debug] PHP Warning: in file [ROOT]/vendor/google/recaptcha/src/ReCaptcha/RequestMethod/Post.php on line 80: file_get_contents(https://www.google.com/recaptcha/api/siteverify): failed to open stream: Connection timed out

When I try to join the discord server, I get:
The invite is invalid or has expired.
Tried with both https://dsc.gg/zdoom and https://dsc.gg/zdoom-server

### Steps to reproduce the behaviour.

Explain how to reproduce
- Attempt to register a new account on the forum

- Attempt to join the discord server as a new user

### Your configuration

```ini
For the forum registration, tried with Firefox ESR and Palemoon.

For the discord, tried with the big client, on windows:
stable 308381 (a65c916) Host 1.0.9153 x64 (49397) Build Override: N/A Windows 10 64-bit (10.0.19045)
```

**Comment by RicardoLuis0** [comment]
for #1, i think you need to enable third party cookies on firefox? otherwise recpatcha is blocked

and as for #2 [the invite seems to be valid](<https://discord.com/invite/zdoom-edge-raze-official-268086704961748992>), are you sure you haven't been banned from the server before?

**Comment by RicardoLuis0** [comment]
<details>
<summary>Invite</summary>

![image](https://github.com/user-attachments/assets/a117ab8f-92a3-4efb-9f26-74da8ac1887d)


</details>

**Comment by zwzsg** [comment]
It's a pretty stock Firefox, with tracking setting left at "Balanced".

Yes, I am sure I have never been banned from any discord, and from any doom related anything, ever, before.

https://discord.com/servers/zdoom-edge-raze-official-268086704961748992 does let me in.

If y'all moved there, then maybe update the forum thread to tell newcomers to use that one instead of  https://dsc.gg/zdoom or https://dsc.gg/zdoom-server

Thanks, now that I can chat on Discord I can stop polluting github issues.

**Comment by zwzsg** [comment]
Ah!

I think I understand what was the issue with the discord invite.
https://dsc.gg is a third party site that offer URL redirection.
When run from a browser, the browser gets redirect to https://discord.com/something and only then it contacts Discord.

Instead I tried to put those https://dsc.gg directly into the Discord client, as an invite.
And Discord client won't follow redirect from url inside the invite popup menu.
It wants proper https://discord.com/stuff there.

I would suggest editing https://forum.zdoom.org/viewtopic.php?f=48&t=54921 to show the full:
https://discord.com/invite/zdoom-edge-raze-official-268086704961748992
in addition to the third party shortened https://dsc.gg/zdoom

**Comment by RicardoLuis0** [comment]
> It's a pretty stock Firefox, with tracking setting left at "Balanced".

Yeah, pretty sure that still breaks the "invisible" version of recaptcha since it blocks third party cookies
![image](https://github.com/user-attachments/assets/1d08d740-9b35-4e3e-8e4c-2d0a2dde99a9)
