### ISSUE TITLE
[BUG] Failed to build on Debian12 i386

### ISSUE THREAD

**Issue by zwzsg** [ZDoom/gzdoom#2624]
### GZDoom version

GZDoom from git on tag g4.12.2 or g4.11.3

### Which game are you running with GZDoom?

None

### What Operating System are you using?

Linux x86

### Please describe your specific OS version

Debian GNU/Linux 12 (bookworm)  (but 32 bits)

### Relevant hardware info

Asus EEE-PC 1001HA

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Compilation of g4.11.3 fails on old PC with new Debian:

First error is:

/home/<user>/src/doom/gzdoom/src/common/platform/posix/sdl/sdlglvideo.cpp:403:54: error: cannot convert ‘std::nullptr_t’ to ‘VkSurfaceKHR’ {aka ‘long long unsigned int’} in initialization
  403 |                         VkSurfaceKHR surfacehandle = nullptr;

But I just casted the nullptr as (VkSurfaceKHR) to silence that.

Then, when compiling /src/common/utility/palette.cpp I got many error: inlining failed in call to ‘always_inline’

I also tried with latest tag g4.12.2, there's the error with VkSurfaceKHR nullptr and then some other error which I forgot to save.

### Steps to reproduce the behaviour.

git clone https://github.com/ZDoom/gzdoom.git
cd gzdoom
git tag --sort=-creatordate 
git checkout g4.12.2
\# or
git checkout g4.11.3
mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Release
make

### Your configuration

```ini
CPU: Intel(R) Atom(TM) CPU N270 @ 1.60GHz
GPU: Mobile 945GSE Express Integrated Graphics Controller
```

### Provide a Log

src/gitinfo.h is up to date at commit g4.11.3-m.

/home/<user>/src/doom/gzdoom/src/common/utility/palette.cpp: In function ‘void DoBlending_SSE2(const PalEntry*, PalEntry*, int, int, int, int, int)’:
/home/<user>/src/doom/gzdoom/src/common/utility/palette.cpp:147:21: warning: SSE vector return without SSE enabled changes the ABI [-Wpsabi]
  147 |         blending256 = _mm_set_epi32(0x100, 0x1000100, 0x100, 0x1000100);
      |         ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/<user>/src/doom/gzdoom/src/common/utility/palette.cpp:120:
/usr/lib/gcc/i686-linux-gnu/12/include/emmintrin.h:794:1: error: inlining failed in call to ‘always_inline’ ‘__m128i _mm_setzero_si128()’: target specific option mismatch
  794 | _mm_setzero_si128 (void)
      | ^~~~~~~~~~~~~~~~~
/home/<user>/src/doom/gzdoom/src/common/utility/palette.cpp:159:33: note: called from here
  159 |         zero = _mm_setzero_si128();
      |                ~~~~~~~~~~~~~~~~~^~
/usr/lib/gcc/i686-linux-gnu/12/include/emmintrin.h:1142:1: error: inlining failed in call to ‘always_inline’ ‘__m128i _mm_subs_epu16(__m128i, __m128i)’: target specific option mismatch
 1142 | _mm_subs_epu16 (__m128i __A, __m128i __B)
      | ^~~~~~~~~~~~~~
/home/<user>/src/doom/gzdoom/src/common/utility/palette.cpp:157:36: note: called from here
  157 |         blendalpha = _mm_subs_epu16(blending256, blendalpha);   // one minus alpha
      |                      ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/gcc/i686-linux-gnu/12/include/emmintrin.h:1160:1: error: inlining failed in call to ‘always_inline’ ‘__m128i _mm_mullo_epi16(__m128i, __m128i)’: target specific option mismatch
 1160 | _mm_mullo_epi16 (__m128i __A, __m128i __B)
      | ^~~~~~~~~~~~~~~
/home/<user>/src/doom/gzdoom/src/common/utility/palette.cpp:156:37: note: called from here
  156 |         blendcolor = _mm_mullo_epi16(blendcolor, blendalpha);   // premultiply blend by alpha
      |                      ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/gcc/i686-linux-gnu/12/include/emmintrin.h:602:1: error: inlining failed in call to ‘always_inline’ ‘__m128i _mm_set_epi32(int, int, int, int)’: target specific option mismatch
  602 | _mm_set_epi32 (int __q3, int __q2, int __q1, int __q0)
      | ^~~~~~~~~~~~~
/home/<user>/src/doom/gzdoom/src/common/utility/palette.cpp:153:35: note: called from here
  153 |         blendalpha = _mm_set_epi32(a, color, a, color);
      |                      ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
/usr/lib/gcc/i686-linux-gnu/12/include/emmintrin.h:602:1: error: inlining failed in call to ‘always_inline’ ‘__m128i _mm_set_epi32(int, int, int, int)’: target specific option mismatch
  602 | _mm_set_epi32 (int __q3, int __q2, int __q1, int __q0)
      | ^~~~~~~~~~~~~
/home/<user>/src/doom/gzdoom/src/common/utility/palette.cpp:150:35: note: called from here
  150 |         blendcolor = _mm_set_epi32(r, color, r, color);
      |                      ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
/usr/lib/gcc/i686-linux-gnu/12/include/emmintrin.h:602:1: error: inlining failed in call to ‘always_inline’ ‘__m128i _mm_set_epi32(int, int, int, int)’: target specific option mismatch
  602 | _mm_set_epi32 (int __q3, int __q2, int __q1, int __q0)
      | ^~~~~~~~~~~~~
/home/<user>/src/doom/gzdoom/src/common/utility/palette.cpp:147:36: note: called from here
  147 |         blending256 = _mm_set_epi32(0x100, 0x1000100, 0x100, 0x1000100);
      |                       ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/gcc/i686-linux-gnu/12/include/emmintrin.h:737:1: error: inlining failed in call to ‘always_inline’ ‘void _mm_storeu_si128(__m128i_u*, __m128i)’: target specific option mismatch
  737 | _mm_storeu_si128 (__m128i_u *__P, __m128i __B)
      | ^~~~~~~~~~~~~~~~
/home/<user>/src/doom/gzdoom/src/common/utility/palette.cpp:175:41: note: called from here
  175 |                         _mm_storeu_si128((__m128i *)to, _mm_packus_epi16(color1, color2));
      |                         ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/gcc/i686-linux-gnu/12/include/emmintrin.h:998:1: error: inlining failed in call to ‘always_inline’ ‘__m128i _mm_packus_epi16(__m128i, __m128i)’: target specific option mismatch
  998 | _mm_packus_epi16 (__m128i __A, __m128i __B)
      | ^~~~~~~~~~~~~~~~
/home/<user>/src/doom/gzdoom/src/common/utility/palette.cpp:175:41: note: called from here
  175 |                         _mm_storeu_si128((__m128i *)to, _mm_packus_epi16(color1, color2));
      |                         ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/gcc/i686-linux-gnu/12/include/emmintrin.h:1243:1: error: inlining failed in call to ‘always_inline’ ‘__m128i _mm_srli_epi16(__m128i, int)’: target specific option mismatch
 1243 | _mm_srli_epi16 (__m128i __A, int __B)
      | ^~~~~~~~~~~~~~
/home/<user>/src/doom/gzdoom/src/common/utility/palette.cpp:174:48: note: called from here
  174 |                         color2 = _mm_srli_epi16(color2, 8);
      |                                  ~~~~~~~~~~~~~~^~~~~~~~~~~
/usr/lib/gcc/i686-linux-gnu/12/include/emmintrin.h:1243:1: error: inlining failed in call to ‘always_inline’ ‘__m128i _mm_srli_epi16(__m128i, int)’: target specific option mismatch
 1243 | _mm_srli_epi16 (__m128i __A, int __B)
      | ^~~~~~~~~~~~~~
/home/<user>/src/doom/gzdoom/src/common/utility/palette.cpp:173:48: note: called from here
  173 |                         color1 = _mm_srli_epi16(color1, 8);
      |                                  ~~~~~~~~~~~~~~^~~~~~~~~~~
/usr/lib/gcc/i686-linux-gnu/12/include/emmintrin.h:1094:1: error: inlining failed in call to ‘always_inline’ ‘__m128i _mm_adds_epu16(__m128i, __m128i)’: target specific option mismatch
 1094 | _mm_adds_epu16 (__m128i __A, __m128i __B)
      | ^~~~~~~~~~~~~~
/home/<user>/src/doom/gzdoom/src/common/utility/palette.cpp:172:48: note: called from here
  172 |                         color2 = _mm_adds_epu16(blendcolor, color2);
      |                                  ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
/usr/lib/gcc/i686-linux-gnu/12/include/emmintrin.h:1094:1: error: inlining failed in call to ‘always_inline’ ‘__m128i _mm_adds_epu16(__m128i, __m128i)’: target specific option mismatch
 1094 | _mm_adds_epu16 (__m128i __A, __m128i __B)
      | ^~~~~~~~~~~~~~
/home/<user>/src/doom/gzdoom/src/common/utility/palette.cpp:171:48: note: called from here
  171 |                         color1 = _mm_adds_epu16(blendcolor, color1);
      |                                  ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
/usr/lib/gcc/i686-linux-gnu/12/include/emmintrin.h:1160:1: error: inlining failed in call to ‘always_inline’ ‘__m128i _mm_mullo_epi16(__m128i, __m128i)’: target specific option mismatch
 1160 | _mm_mullo_epi16 (__m128i __A, __m128i __B)
      | ^~~~~~~~~~~~~~~
/home/<user>/src/doom/gzdoom/src/common/utility/palette.cpp:170:49: note: called from here
  170 |                         color2 = _mm_mullo_epi16(blendalpha, color2);
      |                                  ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
/usr/lib/gcc/i686-linux-gnu/12/include/emmintrin.h:1160:1: error: inlining failed in call to ‘always_inline’ ‘__m128i _mm_mullo_epi16(__m128i, __m128i)’: target specific option mismatch
 1160 | _mm_mullo_epi16 (__m128i __A, __m128i __B)
      | ^~~~~~~~~~~~~~~
/home/<user>/src/doom/gzdoom/src/common/utility/palette.cpp:169:49: note: called from here
  169 |                         color1 = _mm_mullo_epi16(blendalpha, color1);
      |                                  ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
/usr/lib/gcc/i686-linux-gnu/12/include/emmintrin.h:1028:1: error: inlining failed in call to ‘always_inline’ ‘__m128i _mm_unpacklo_epi8(__m128i, __m128i)’: target specific option mismatch
 1028 | _mm_unpacklo_epi8 (__m128i __A, __m128i __B)
      | ^~~~~~~~~~~~~~~~~
/home/<user>/src/doom/gzdoom/src/common/utility/palette.cpp:168:51: note: called from here
  168 |                         color1 = _mm_unpacklo_epi8(color1, zero);
      |                                  ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
/usr/lib/gcc/i686-linux-gnu/12/include/emmintrin.h:1004:1: error: inlining failed in call to ‘always_inline’ ‘__m128i _mm_unpackhi_epi8(__m128i, __m128i)’: target specific option mismatch
 1004 | _mm_unpackhi_epi8 (__m128i __A, __m128i __B)
      | ^~~~~~~~~~~~~~~~~
/home/<user>/src/doom/gzdoom/src/common/utility/palette.cpp:167:51: note: called from here
  167 |                         color2 = _mm_unpackhi_epi8(color1, zero);
      |                                  ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
/usr/lib/gcc/i686-linux-gnu/12/include/emmintrin.h:701:1: error: inlining failed in call to ‘always_inline’ ‘__m128i _mm_loadu_si128(const __m128i_u*)’: target specific option mismatch
  701 | _mm_loadu_si128 (__m128i_u const *__P)
      | ^~~~~~~~~~~~~~~
/home/<user>/src/doom/gzdoom/src/common/utility/palette.cpp:165:49: note: called from here
  165 |                         color1 = _mm_loadu_si128((__m128i *)from);
      |                                  ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
/usr/lib/gcc/i686-linux-gnu/12/include/emmintrin.h:731:1: error: inlining failed in call to ‘always_inline’ ‘void _mm_store_si128(__m128i*, __m128i)’: target specific option mismatch
  731 | _mm_store_si128 (__m128i *__P, __m128i __B)
      | ^~~~~~~~~~~~~~~
/home/<user>/src/doom/gzdoom/src/common/utility/palette.cpp:193:40: note: called from here
  193 |                         _mm_store_si128((__m128i *)to, _mm_packus_epi16(color1, color2));
      |                         ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/gcc/i686-linux-gnu/12/include/emmintrin.h:998:1: error: inlining failed in call to ‘always_inline’ ‘__m128i _mm_packus_epi16(__m128i, __m128i)’: target specific option mismatch
  998 | _mm_packus_epi16 (__m128i __A, __m128i __B)
      | ^~~~~~~~~~~~~~~~
/home/<user>/src/doom/gzdoom/src/common/utility/palette.cpp:193:40: note: called from here
  193 |                         _mm_store_si128((__m128i *)to, _mm_packus_epi16(color1, color2));
      |                         ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/gcc/i686-linux-gnu/12/include/emmintrin.h:1243:1: error: inlining failed in call to ‘always_inline’ ‘__m128i _mm_srli_epi16(__m128i, int)’: target specific option mismatch
 1243 | _mm_srli_epi16 (__m128i __A, int __B)
      | ^~~~~~~~~~~~~~
/home/<user>/src/doom/gzdoom/src/common/utility/palette.cpp:192:48: note: called from here
  192 |                         color2 = _mm_srli_epi16(color2, 8);
      |                                  ~~~~~~~~~~~~~~^~~~~~~~~~~
/usr/lib/gcc/i686-linux-gnu/12/include/emmintrin.h:1243:1: error: inlining failed in call to ‘always_inline’ ‘__m128i _mm_srli_epi16(__m128i, int)’: target specific option mismatch
 1243 | _mm_srli_epi16 (__m128i __A, int __B)
      | ^~~~~~~~~~~~~~
/home/<user>/src/doom/gzdoom/src/common/utility/palette.cpp:191:48: note: called from here
  191 |                         color1 = _mm_srli_epi16(color1, 8);
      |                                  ~~~~~~~~~~~~~~^~~~~~~~~~~
/usr/lib/gcc/i686-linux-gnu/12/include/emmintrin.h:1094:1: error: inlining failed in call to ‘always_inline’ ‘__m128i _mm_adds_epu16(__m128i, __m128i)’: target specific option mismatch
 1094 | _mm_adds_epu16 (__m128i __A, __m128i __B)
      | ^~~~~~~~~~~~~~
/home/<user>/src/doom/gzdoom/src/common/utility/palette.cpp:190:48: note: called from here
  190 |                         color2 = _mm_adds_epu16(blendcolor, color2);
      |                                  ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
/usr/lib/gcc/i686-linux-gnu/12/include/emmintrin.h:1094:1: error: inlining failed in call to ‘always_inline’ ‘__m128i _mm_adds_epu16(__m128i, __m128i)’: target specific option mismatch
 1094 | _mm_adds_epu16 (__m128i __A, __m128i __B)
      | ^~~~~~~~~~~~~~
/home/<user>/src/doom/gzdoom/src/common/utility/palette.cpp:189:48: note: called from here
  189 |                         color1 = _mm_adds_epu16(blendcolor, color1);
      |                                  ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
/usr/lib/gcc/i686-linux-gnu/12/include/emmintrin.h:1160:1: error: inlining failed in call to ‘always_inline’ ‘__m128i _mm_mullo_epi16(__m128i, __m128i)’: target specific option mismatch
 1160 | _mm_mullo_epi16 (__m128i __A, __m128i __B)
      | ^~~~~~~~~~~~~~~
/home/<user>/src/doom/gzdoom/src/common/utility/palette.cpp:188:49: note: called from here
  188 |                         color2 = _mm_mullo_epi16(blendalpha, color2);
      |                                  ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
/usr/lib/gcc/i686-linux-gnu/12/include/emmintrin.h:1160:1: error: inlining failed in call to ‘always_inline’ ‘__m128i _mm_mullo_epi16(__m128i, __m128i)’: target specific option mismatch
 1160 | _mm_mullo_epi16 (__m128i __A, __m128i __B)
      | ^~~~~~~~~~~~~~~
/home/<user>/src/doom/gzdoom/src/common/utility/palette.cpp:187:49: note: called from here
  187 |                         color1 = _mm_mullo_epi16(blendalpha, color1);
      |                                  ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
/usr/lib/gcc/i686-linux-gnu/12/include/emmintrin.h:1028:1: error: inlining failed in call to ‘always_inline’ ‘__m128i _mm_unpacklo_epi8(__m128i, __m128i)’: target specific option mismatch
 1028 | _mm_unpacklo_epi8 (__m128i __A, __m128i __B)
      | ^~~~~~~~~~~~~~~~~
/home/<user>/src/doom/gzdoom/src/common/utility/palette.cpp:186:51: note: called from here
  186 |                         color1 = _mm_unpacklo_epi8(color1, zero);
      |                                  ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
/usr/lib/gcc/i686-linux-gnu/12/include/emmintrin.h:1004:1: error: inlining failed in call to ‘always_inline’ ‘__m128i _mm_unpackhi_epi8(__m128i, __m128i)’: target specific option mismatch
 1004 | _mm_unpackhi_epi8 (__m128i __A, __m128i __B)
      | ^~~~~~~~~~~~~~~~~
/home/<user>/src/doom/gzdoom/src/common/utility/palette.cpp:185:51: note: called from here
  185 |                         color2 = _mm_unpackhi_epi8(color1, zero);
      |                                  ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
/usr/lib/gcc/i686-linux-gnu/12/include/emmintrin.h:695:1: error: inlining failed in call to ‘always_inline’ ‘__m128i _mm_load_si128(const __m128i*)’: target specific option mismatch
  695 | _mm_load_si128 (__m128i const *__P)
      | ^~~~~~~~~~~~~~
/home/<user>/src/doom/gzdoom/src/common/utility/palette.cpp:183:48: note: called from here
  183 |                         color1 = _mm_load_si128((__m128i *)from);
      |                                  ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
make[2]: *** [src/CMakeFiles/zdoom.dir/build.make:5566: src/CMakeFiles/zdoom.dir/common/utility/palette.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:694: src/CMakeFiles/zdoom.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by RicardoLuis0** [comment]
32-bit platforms aren't supported by gzdoom

**Comment by zwzsg** [comment]
Aww. At least I still have LZDoom.

Would it be possible to have the build system print some clear message about the futility of attempting to build on a 32 bit system?
