### ISSUE TITLE
[Feature] Prevent command line cvar arguments from physically updating config file

### ISSUE THREAD

**Issue by DecapitatedKneecap** [ZDoom/gzdoom#2625]
### GZDoom version

4.12.2.0

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 11

### Relevant hardware info

Radeon RX 7900XTX

### Is your feature request related to a problem? Please describe.

When setting a cvar through command line like so:

`doom +gl_fxaa 1`

...it physically updates the `gl_fxaa` value in the config on exit. It seems like command line arguments should be temporary per running instance, resetting back to their config values on exit. This would allow the user to have a batch file that uses a set of cvars or other args specific to a particular mod. Or perhaps they would want to have multiple batch files that execute the same mod with different arguments. This would allow them to use alternate variables without affecting their other mods.

This could be a breaking change for those who expect this behavior, so maybe introduce a new command line switch that tells the engine to throw away the command line values on exit rather than save them.

**Comment by RicardoLuis0** [comment]
`+` doesn't set cvars specifically, it just runs a command, so it has all the same ramifications as setting cvars from the console (ex. it can also be used for loading maps with `+map mapXX`, etc)

> This would allow the user to have a batch file that uses a set of cvars or other args specific to a particular mod

if you want that, you can just use a separate config file with `-config FILENAME.ini` for each mod combination
