### ISSUE TITLE
[BUG] Actor.DisableLocalRendering does not disable Actor Lights set by gldefs

### ISSUE THREAD

**Issue by Lemon-King** [ZDoom/gzdoom#2641]
### GZDoom version

GZDoom g4.12.2

### Which game are you running with GZDoom?

Other

### What Operating System are you using?

Windows 11

### Please describe your specific OS version

Windows 11 Pro

### Relevant hardware info

NVidia, AMD CPU, 32 GB System Ram

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When you disable local rendering of an Actor. The problem with disabling local rendering is it does not disable local lights for an Actor with lights defined by gldefs or Defaults.

![Screenshot_HXDD_20240725_224820](https://github.com/user-attachments/assets/01df5fea-2a25-4025-9fc1-189c28328daf)

### Steps to reproduce the behaviour.

`    GoldWandAmmo ammo = Spawn("GoldWandAmmo");
    ammo.DisableLocalRendering(0, false);`

And observe ingame, just a simple point light with no actor sprite.

### Your configuration

```ini
Default gzdoom ini with lights enabled.
```

**Comment by nashmuhandes** [comment]
Done https://github.com/ZDoom/gzdoom/pull/2651
