### ISSUE TITLE
[BUG] Deterministically rendering black world geometry/sprites/models

### ISSUE THREAD

**Issue by zhs2** [ZDoom/gzdoom#2648]
### GZDoom version

4.12.2

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

Windows 10 Pro

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I know [this thread exists](https://forum.zdoom.org/viewtopic.php?t=79081&sid=06a464b3be21825ac7b616d30ef4070d) but I have just been poked with information that the black screen bug has been tracked to [this commit](https://github.com/ZDoom/gzdoom/commit/b469770eccf306ff9a3c4c9a253e1a805ae5fd90). Therefore, I have deemed it prudent to beep @Boondorl for familiarity to the commit in question. See steps below for how to reproduce it yourself quickly.

### Steps to reproduce the behaviour.

1. Load [Deathstrider](https://gitlab.com/accensi/deathstrider), preferably on a map without a hot start
2. Walk up to a wall, hold any key bound to "+speed", and press "+moveleft" or "+moveright" to lean.
3. Set i_timescale to 100
4. Wait a few seconds
5. Black screen
6. Leaning again resets the viewpoints and thus the issue, temporarily.

**Comment by Boondorl** [comment]
Loaded it into vanilla Doom 2 and followed the instructions and didn't notice anything. Is there something specific that needs to be done beyond that?

**Comment by zhs2** [comment]
Yes, the bug affects Deathstrider in particular (see steps above). I could not say exactly why and have too many theories, but tonight finally pinned the cause down to something funky with render viewpoints in that mod. Because of shaders? Because of the mod's complexity? Who knows. I tried a vanilla Doom 2 run probably a month ago with 4.12.2 and absolutely could not cause this black screen bug there either.

**Comment by Boondorl** [comment]
Sorry, by "vanilla Doom 2" I meant no other map packs. I've tried setting the timescale to even 10000 and nothing seems to happen after wait ~30 seconds

**Comment by zhs2** [comment]
I apologize. I just went through the steps myself and yes, you apparently must lean at least once before the bug starts occurring. Further leaning must reset the viewpoint because that starts the process all over again.

**Comment by Boondorl** [comment]
Very interesting. Guessing this is some kind of problem with ViewPos then which would explain why the chase cam is fine (it ignores the view cam's values since those are only for first person viewing)

**Comment by zhs2** [comment]
More apologies, this was apparently definitely a mod bug and a fix for it is coming up shortly. Thanks for the insight!
