### ISSUE TITLE
[BUG] A_RadiusDamage not functioning as intended on 4.12.X

### ISSUE THREAD

**Issue by TsukiZero** [ZDoom/gzdoom#2660]
While looking for info on Legacy of Rust (recent release), found a thread claiming it doesn't work on GZDoom, although I was able to launch it just fine a moment ago. So, decided to put to test with the Banshee enemy (Deh_Actor_151), that uses A_RadiusDamage in its attack and... Worked fine.

Then I decided to do the stupid thing and update GZDoom to v4.12.2 and... Yeah, that breaks it, Banshee turned harmless because it can't cause harm. Immediately went back to 4.11.3a after this to unbreak it for me, and 4.11.3a handled the Banshee as it should.

Windows 64-Bit version.

**Comment by MasterO2** [comment]
https://www.doomworld.com/forum/topic/146914-are-the-new-screaming-fireball-enemies-in-legacy-of-rust-not-supposed-to-deal-any-damage/ is the thread in question, @TsukiZero.

**Comment by XaserAcheron** [comment]
This was just fixed in #2659 -- Banshees are all working nicely in the next release (and any new devbuilds).

**Comment by TsukiZero** [comment]
Guess this is all good to close then.
