### ISSUE TITLE
[Feature] Option to define a null TextureID

### ISSUE THREAD

**Issue by jekyllgrim** [ZDoom/gzdoom#2663]
### GZDoom version

GZDoom 4.12.2

### Which game are you running with GZDoom?

None

### What Operating System are you using?

None

### Is your feature request related to a problem? Please describe.

It's currently not possible to define a null TextureID. In a code block this is solved by manually calling SetNull() or SetInvalid() on a previously declared TextureID, but this doesn't cut it for functions: it's not possible to define an *optional* TextureID-type argument, since neither `TextureID tex = 0` nor `TextureID tex = null` are recognized.

**Comment by coelckers** [comment]
Of course this does exist, use FNullTextureId().
It could be done better these days but what's there is working.

**Comment by RicardoLuis0** [comment]
the thing is, FNullTextureId isn't exported to ZScript, and that's what this is asking for
