### ISSUE TITLE
[BUG] invisible walls inside some doors in gzdoom 4

### ISSUE THREAD

**Issue by light-and-ray** [ZDoom/gzdoom#2667]
### GZDoom version

4.11.3, 4.12.2

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Other

### Please describe your specific OS version

Android, Delta Touch

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

In a mod "WolfenDoom: Operation: Arctic Wolf" it's not possible to go through a door on the first level (map09). Also I've found a guy with the same bug on WAD: Community Chest 2, MAP 19: https://www.youtube.com/watch?v=QZkDp6rpt24

I've tested all versions of gzdoom in delta touch:
v1.9.1: no bug
v3.2.9: no bug
v3.8.2: no bug
**v4.11.3: bug
dev v4.12.2: bug**

v4.11.3 VIDEO:
https://github.com/user-attachments/assets/c2644518-6a7c-41ec-9bd3-098a4e3c2178

### Steps to reproduce the behaviour.

Explain how to reproduce
1. download http://lazrojas.com/wolfendoom/index2.html
2. load files:
DOOM2.WAD
ARCTIC.WAD
ARCTLEV.WAD
ARCTGFX1.WAD
ARCTIC1.DEH
4. launch with cmd args: `-warp 9 -nomonsters`
5. find the only door that doesn't require a key

**Comment by prof-hastig** [comment]
You may have to disable MBF21 features in the compatibility menu. At least one old Doom editor set all unused linedef flags to 1 instead of 0 and this may cause some problems with newly added flags in MBF21.

**Comment by madame-rachelle** [comment]
No feedback after proposed solution, closing
