### ISSUE TITLE
[Feature] Allow launcher to show Kex version as separate just like Original, BFG & Unity

### ISSUE THREAD

**Issue by MarkoD2K** [ZDoom/gzdoom#2669]
### GZDoom version

GZDoom 4.12.2 (and latest dev release also)

### Which game are you running with GZDoom?

Doom

### What Operating System are you using?

Windows 10

### Is your feature request related to a problem? Please describe.

In [recent commit with title "Support the new Doom + Doom II update"](https://github.com/ZDoom/gzdoom/commit/bd2027ee4b44468fc78ff9674e250ca89f15dd8e) some changes are there in `wadsrc_extra/static/iwadinfo.txt` to add new launcher entries for Kex versions of Doom, Doom 2, TNT and Plutonia. But like I am saying in [my comment](https://github.com/ZDoom/gzdoom/commit/bd2027ee4b44468fc78ff9674e250ca89f15dd8e#commitcomment-145315632), if same WAD names are there like doom.wad, doom2.wad, tnt.wad and plutonia.wad, then we can have in launcher only original version WAD files, **OR** Kex version WAD files, but **NOT** together both versions.

When new entries were being added for BFG and Unity then WAD names were being kept different only (like doombfg, doom2bfg, doomunity, doom2unity, tntunity, plutoniaunity), so in launcher right now GZDoom is showing properly original Doom versions and also Doom BFG, Unity versions all separate.

![357309070-d8ec5088-fec9-4e50-a409-f87788d255a4](https://github.com/user-attachments/assets/ea7b9d64-cac5-4b3f-941f-985cd60e0b36)

So just like this please make Kex version WAD files have different names also (doomkex.wad, doom2kex.wad, tntkex.wad and plutoniakex.wad), so all 3 versions can show properly in launcher menu. Thank you.

### Describe the solution you'd like

See ⬆. Also please add space and fix title from "Hacx: Twitch'n Kill" to "HacX: Twitch 'n Kill"! 😃

**Comment by yum13241** [comment]
Why would I want to use the specifically KEX IWADs outside of the KEX port anyway?

**Comment by MarkoD2K** [comment]
@yum13241 Why not? New Kex port WADs are not special or locked to Kex port only. They are following WAD, MBF21 and ID24 standards, so anyone can be using same WADs with any Doom port they are liking if that port is following also same standards.

If you are not wishing to use GZDoom or other favourite port for Kex port WADs then why you are here? No-one is forcing you so just use Kex port only. We who are wanting to use Kex port WADs with GZDoom will use. Someone else is wanting to use Kex port WADs with DSDA Doom will use. This is why Doom is great - freedom is there to use any port.

**Comment by madame-rachelle** [comment]
done

**Comment by MarkoD2K** [comment]
@madame-rachelle Thank you! Please can you do some minor edits also?

1. Doom, Doom 2 , TNT and Plutonia all should be having same order like Kex and then Unity, or Unity and then Kex. Will look neater. 🙂
![image](https://github.com/user-attachments/assets/4836cb15-f4d9-482f-94d6-0299e39825ca)

2. Please add space and fix title from "Hacx: Twitch'n Kill" to "HacX: Twitch 'n Kill"! 😎
