### ISSUE TITLE
[BUG] Vulkan renderer applies an antialiasing filter that cannot be disabled

### ISSUE THREAD

**Issue by ksio89** [ZDoom/gzdoom#2679]
### GZDoom version

g4.12.2

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 11

### Please describe your specific OS version

Windows 11 Home

### Relevant hardware info

CPU: Intel Core i5-1135G7 // GPU: Iris Xe Graphics 80 EUs

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I'm not sure whether it's a bug or intended behaviour, but when Vulkan is set as rendering API, there's what appears to be an antialiasing filter applied to sprites that makes the image very blurry. I have looked everywhere on the menus and couldn't find any option that allows me to disable that filter. At first I thought it was "Texture Filter mode", but it was already set to None and changing to Linear/Bilinear/Triliniear seems to have no visible effect, unlike on how it is with OpenGL.

TBH, this issue has been present as far as Vulkan support has been implemented on GZDoom. Here its two screenshots comparing how it looks with both APIs:

Vulkan:
![Vulkan menu](https://github.com/user-attachments/assets/73133142-e4d8-4a0f-97a6-285f2a42c28f)
![Vulkan gameplay](https://github.com/user-attachments/assets/b3605c71-8a45-482e-91c2-6aa14aa9b604)

OpenGL: 
![OpenGL menu](https://github.com/user-attachments/assets/1be473ad-39e9-48de-a0df-5a2074672c6c)
![OpenGL gameplay](https://github.com/user-attachments/assets/d8cd7ffd-ef37-4380-bff3-9985748fede3)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Change "Preferred Rendering API" to Vulkan
2. Restart GZDooom
3. Image is very blurry

### Your configuration

```ini
https://gist.github.com/ksio89/bbcaa86d77320cf3bdf1f592b6dc5a99
```

### Provide a Log

https://gist.github.com/ksio89/0de6047fa3f1556ff293139c5481ecaf

**Comment by RicardoLuis0** [comment]
pretty sure that that is an intel vulkan bug _when you have anisotropic filtering enabled_, not a gzdoom bug, so you can try setting anisotropic filtering to off to work around it

**Comment by RicardoLuis0** [comment]
(if this persists even with anisotropic filtering off, just say here and i'll reopen the issue)

**Comment by ksio89** [comment]
You're right, I changed Anistropic Filtering to "Let application choose", and voilá, everything is crystal clear again! Thank you very much and apologies for implying it was a GZDoom bug.
