### ISSUE TITLE
[BUG] dehacked/bex strings always take precedence over language

### ISSUE THREAD

**Issue by GeorgePieVG** [ZDoom/gzdoom#2681]
### GZDoom version

GZDoom 4.12.2

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

None

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Dehacked/BEX strings always overwrite strings from LANGUAGE, even if both lumps are present in the same wad file. This makes it impossible to translate freedoom, for example

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Add the language lump to freedoom iwad or load it via pwad

**Comment by RicardoLuis0** [comment]
if you're only using the dehacked scripts for translation, IIRC you can add `DeleteLumps = <LUMPNAME>` to your IWADINFO to force gzdoom to ignore it

**Comment by RicardoLuis0** [comment]
done an initial implementation for a fix, will test more tomorrow

**Comment by RicardoLuis0** [comment]
it works 🎉
![image](https://github.com/user-attachments/assets/2f69fe6f-f639-42f8-a06c-08abc8cf5e13)
[freedoom2.zip](https://github.com/user-attachments/files/16685489/freedoom2.zip)
