### ISSUE TITLE
[BUG] Issue with pistol start gameplay option

### ISSUE THREAD

**Issue by FishyClock** [ZDoom/gzdoom#2699]
### GZDoom version

GZDoom g4.13pre-122-g76c8b6da5

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Trying to run Beautiful Doom with the pistol start gameplay setting causes a VM abort error

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Get Beautiful Doom here https://github.com/jekyllgrim/Beautiful-Doom/releases
2. set sv_pistolstart to true - start map01
3. give yourself everything and then use the changemap command to go to any map it should error out here

### Provide a Log

Log started: 2024-09-05 20:05:59
]sv_pistolstart 1
]map map01

----------------------------------------

MAP01 - Entryway

]give all
]changemap map02
VM execution aborted: tried to read from address zero. In function parameter "self"
Called from Weapon.CheckAmmo at gzdoom.pk3:zscript/actors/inventory/weapons.zs, line 943
Called from PlayerPawn.GiveDefaultInventory at gzdoom.pk3:zscript/actors/player/player.zs, line 1973
Called from PlayerPawn.PlayerFinishLevel at gzdoom.pk3:zscript/actors/player/player.zs, line 2154
Called from Actor.FindInventory [Native]
]quit

**Comment by madame-rachelle** [comment]
Should be fixed, maybe? This one is a tricky issue. It seems ClearInventory() was leaving some dangling pointers so I tried to clean those up a little bit.

**Comment by madame-rachelle** [comment]
Had to revert my fix - it solved this issue, but it introduced more issues.

**Comment by Boondorl** [comment]
Is this a bug with GZDoom or Beautiful Doom? All the pistol start option does is set the existing level flags to clear the player's inventory and reset their health, both of which are gameplay options that can be enforced by the level itself to my knowledge. This seems like it's probably an oversight with how something is being handled on the mod's end, especially if neither vanilla nor other mods are showing it.

**Comment by madame-rachelle** [comment]
Probably the latter. Pistol start works fine in anything that is vanilla, so I am going to go ahead and close this.
