### ISSUE TITLE
[BUG] A custom difficulty, with SpawnMulti property on MAPINFO, ignores "Not Cooperative" thing flag

### ISSUE THREAD

**Issue by antares031** [ZDoom/gzdoom#2701]
### GZDoom version

g4.12.2

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

Windows 10 Home

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Hey there! Our team released the RC6 of Eviternity II (MBF21) recently, and we included a new custom difficulty, called "Annihilate Me". It's basically UV difficulty with -coop_spawns option, spawning actors with "Multiplayer only" flag, but removing actors with "Not Cooperative" flag. We designed the difficulty with MAPINFO lump, and added SpawnMulti property to our new difficulty:

![mapinfo](https://github.com/user-attachments/assets/1968f298-2b79-45ae-8b8a-791c9d589bea)

This new difficulty works fine on dsda-doom as intended, removing actors with "Not Cooperative" flag in the levels. But the latest version of GZDoom ignores "Not Cooperative" flag, and spawns the actors with that flag anyway. This causes unintended bugs and glitches throughout the levels with "Not Cooperative"-flagged actors. It'd be appreciated if you fix this issue, by letting the source port abide "Not Cooperative" flag, when the custom difficulty has SpawnMulti property. Thanks, and have a nice day.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Make a custom difficulty with SpawnMulti on MAPINFO, like the one from the screenshot above
2. Design a MBF21 level with actors, flagged as "Not Cooperative"
3. Run the level with a custom difficulty, and check if the actors are spawned

**Comment by RicardoLuis0** [comment]
are you sure this is a gzdoom bug and not a dsda bug? because AFAIK it specifically treats spawnmulti as **coop** spawns, not deathmatch spawns https://github.com/ZDoom/gzdoom/blob/master/src/playsim/p_mobj.cpp#L5840-L5843

**Comment by RicardoLuis0** [comment]
added `SpawnMultiCoopOnly` this should be enough to make it work https://github.com/ZDoom/gzdoom/pull/2703 (though hopefully it's fixed in dsda with the new flag is added as well, but if it isn't, it should still override SpawnMulti if both are defined)

**Comment by Gaerzi** [comment]
I think "solo-net" or "solonet" would be a better fit for "spawnmulticooponly", as it corresponds to the [parameter actually used](https://doomwiki.org/wiki/Source_port_parameters#-solo-net) in many source port; which is also probably the logic DSDA mapped spawnmulti to, since it was preexisting.

IIRC, spawnmulti appeared as a response to the Unity port's UV+ difficulty. Unfortunately, that one didn't have the Boom "not coop" and "not DM" flags; only the vanilla "not single" flag. So we can't use it as a reference.

**Comment by RicardoLuis0** [comment]
I'm not sure if naming a mapinfo option after a commandline parameter works too much, and wouldn't be very descriptive

**Comment by madame-rachelle** [comment]
This was added
