### ISSUE TITLE
[BUG] Auto aim can not be disabled permanently

### ISSUE THREAD

**Issue by gsanjin** [ZDoom/gzdoom#2711]
### GZDoom version

4.12.2, 4.13.pre-124, 4.13.pre-134

### Which game are you running with GZDoom?

Brutal Doom 64, Others

### What Operating System are you using?

Windows 11

### Please describe your specific OS version

Windows 11 Pro

### Relevant hardware info

Ryzen 7 5800X3D, RTX 3800 10 GB, 32 GB RAM, SSD

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Setting up "Allow autoaim" to NO is not saved. After every GZDoom restart its enabled again.
I had to use autoexec.cfg to disable this annoyance.
I expected this to be saved in my ini file - it does, but it is enabled again after restarting GZDoom.
Tested with latest stable and test build - same issue. Searching online I am finding it looks like this issue is present for sometime.

### Steps to reproduce the behaviour.

Options - Full menu - Gameplay settings - Allow autoaim to NO. Than quit gzDoom and open it - setting is again enabled and in use. Expected is to be disabled once it's set in menu.

Current workaround was to create autoconfig.cfg in gzdoom directory with content:
set dmflags 0
set dmflags2 8388608
set dmflags3 0
but this is not practical/easily known solution for average user.

Even setting autoaim=0 in ini file doesn't survive new start of gzdoom.exe. It just ignores ini setting and on exit, it writes back to ini autoaim=1.

**Comment by madame-rachelle** [comment]
Gameplay settings are set up per game session and not saved to the config file.

Have you tried the user setting instead? "autoaim 0" in the console.

**Comment by gsanjin** [comment]
Hi! I used autocfg workaround to disable autoaim in singleplayer game.

IMHO, this is not a game session option, but gameplay option - I do not want to have any autoaim ever enabled (I use freelook and kb/mouse and don't play classic Doom). Why is there an option in menu then (which doesn't work)?

**Comment by madame-rachelle** [comment]
Currently it is a player setting. You turn it on and off in player setup.

The gameplay setting is about restricting it in multiplayer when you are the net arbitor.

**Comment by gsanjin** [comment]
Ok, but to clarify - turning off setting in player setup doesn't disable auto-aim in single player. It gets disabled only when setting in gameplay setting is disabled also ( player setup auto aim && gameplay setup auto aim = disabled auto aim in single player). Since gameplay setting gets restored on every gzdoom restart, auto aim in singleplayer also gets always restored on every gzdoom restart.
