### ISSUE TITLE
[BUG] cant launch

### ISSUE THREAD

**Issue by pantsgt** [ZDoom/gzdoom#2715]
### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

windows 10

### Relevant hardware info

rtx 4080

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

![error](https://github.com/user-attachments/assets/f4a5b6e5-0ad7-434b-823a-d9881edc98fd)
fresh install, nothing added in folder

### Steps to reproduce the behaviour.

Explain how to reproduce
1. launch gzdoom program
2.
3.

**Comment by Blue-Shadow** [comment]
Already [fixed](https://github.com/ZDoom/gzdoom/commit/3a5838c8f5a24bbe198faa41574736694848992e).

**Comment by madame-rachelle** [comment]
Which is why we really really really really need GZDoom 4.13.0 released.
