### ISSUE TITLE
[BUG] Legacy of Rust: Fences on MAP14 have no collision

### ISSUE THREAD

**Issue by dariusdan** [ZDoom/gzdoom#2720]
### GZDoom version

g4.12.2

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 11

### Please describe your specific OS version

Windows 11 Pro 23H2

### Relevant hardware info

Ryzen 5 5600X, RX 6600XT, 16GB RAM

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

On map 14 of the new Legacy of Rust content, a fence at the very beginning of the level does not have a proper collision (picture attached), allowing the player to fall in the pit below without possibility of returning, forcing you to restart the level.
This fence also appears at a section near to the start, with a blood lake on both sides of a path (picture attached).
I tested it on g4.12.2 and g4.13pre-139-g712dd1133 and it is the same on both versions.

### Steps to reproduce the behaviour.

How to reproduce the issue:
1. Run Legacy of Rust with the command `gzdoom.exe -noautoload -iwad DOOM2.WAD -file id1`
2. In the console, input `map map14`
3. Move along the fence into the pit below
![Screenshot_Doom_20240830_‏‎081848](https://github.com/user-attachments/assets/66df24c0-2012-4f75-a55b-8f66d135e843)
![Screenshot_Doom_20240919_092916](https://github.com/user-attachments/assets/e8f70275-6e01-4537-8296-2ddd853751f8)
![Screenshot_Doom_20240919_093145](https://github.com/user-attachments/assets/8798022a-4bb8-4716-8b2f-3ca8de5732d5)
![Screenshot_Doom_20240919_093205](https://github.com/user-attachments/assets/4b00c42c-0fd8-4690-af2d-1f0d5f806ffc)

### Your configuration

```ini
gzdoom.exe -noautoload -iwad DOOM2.WAD -file id1
```

### Provide a Log

[log.txt](https://github.com/user-attachments/files/17059001/log.txt)

**Comment by Owlet7** [comment]
You must have compat_nombf21 set to true. Try disabling map/action behaviour compatibility options.

**Comment by dariusdan** [comment]
OMG that's right! I changed compat mode to MBF21 on the options and that corrects the fence behavior. I should've done this before as I knew this content was MBF21 compat. Sorry for my confusion.
