### ISSUE TITLE
[Feature] Enable Github Sponsorship, Take Our Money

### ISSUE THREAD

**Issue by guyewhite** [ZDoom/gzdoom#2722]
### Which game are you running with GZDoom?

None

### What Operating System are you using?

None

### Is your feature request related to a problem? Please describe.

We want to sponsor this project. Please enable [GitHub sponsorship](https://docs.github.com/en/sponsors/getting-started-with-github-sponsors/about-github-sponsors) so we can send funds.

**Comment by MajorCooke** [comment]
Sponsorships usually don't come without strings. Out of an abundance of caution I've closed this, but whatever @madame-rachelle or @coelckers decides is what will happen.

**Comment by madame-rachelle** [comment]
So to expand on what Major Cooke said - my biggest worry is the entanglements money would cause. I've done a lil of this here and there for payment and needless to say - I don't have focus enough to deliver on the kinds of things people would want to donate money to me for, while still being able to deliver for my jobs. I am not against the principle alone of taking money - but money always has strings attached, even when it doesn't. And the last thing I want to do is waive my own entitlement to myself, and to my time, by turning this into a commitment where the stakes for failure would run a little too high. As it stands not having the donations lets me feel a little more relaxed and able to try new things out and it allows me to be more daring while simultaneously allowing me to - god forbid, have a life also outside of GZDoom at the same time.

That being said, if you have a project in mind that you would like to hire one of the developers for, you're free to post about it and if someone feels up to it you're welcome to discuss terms and stuff with them. But opening donations in general - just for the time being, I may change my mind about this later (but at the moment I am not foreseeing why I would) - I don't think they will offer much benefit versus the potential issues that they could cause.

**Comment by guyewhite** [comment]
@MajorCooke and @madame-rachelle, I completely understand. Indeed, support by hiring/contracting with one of the devs may be a better alternative. Thank you for your contributions to this project. I point my students often to the work you all are doing here and your work has been a blessing. Thanks for your time and thoughts here.

**Comment by coelckers** [comment]
Believe me, I'd love to earn money like this. But aside from what Rachael already said, there's other issues as well.

The biggest issue, of course, is if it is enough to make a living. If someone could guarantee me a reliable income for the next 10 or so years, I'd happily jump into it, but if it is not, I still have to keep my daytime job which effectively means I'm constantly short on time and never in the right mindset to develop the engine - but with money being on the table there'd be constant pressure to work on it which is simply not a viable proposal right now.
