### ISSUE TITLE
[CRASH]  with code: C0000005 when playing Alice:ToM mod

### ISSUE THREAD

**Issue by CortexReaver** [ZDoom/gzdoom#2724]
### GZDoom version

4.12.2 and 4.13-pre

### Which game are you running with GZDoom?

Doom 2 with mods

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

22H2 19045.3448

### Relevant hardware info

Intel Xeon E5-2673 v3, Radeon RX 6600

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

GZDoom crashes with these two mods in particular: [Alice: Toys of Madness v1.0.1](https://forum.zdoom.org/viewtopic.php?t=79287) and [mercilessmonsv0.7](https://allfearthesentinel.com/zandronum/wads.php?order=id_desc&name=mercilessmonsv0.7.pk3) .

In fact, any mod that replaces monsters combined with Alice will do the trick, I got crashes even with [this](https://www.mediafire.com/file/jzlnamq5p0h776s/HexFantasymonster_V2.2.wad/file)

it is related somehow to big enemy hordes and dealing damage to them (and taking damage as well). It building up throughout play time and in some point can result in crash, like some sort of counter overflow. If you a killing enemies fast enough it might be just fine.

There are other mods in crash report, but they seems make no difference - I tried to disable them one by one, leaving only three mentioned above, and the game still crashes.

![20-09-2024 180315](https://github.com/user-attachments/assets/a6ef3341-37ac-4632-be4a-6b0535f21c9a)

For a mod manager I've used DoomLauncher: https://github.com/nstlaurent/DoomLauncher
GPU drivers has been updated to the latest version.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. load mods in order: mercilessmons and Alice:ToM (tested: these two is enough to get crashed)
2. play around 6-40 minutes using Alice:ToM slot 5 weapon and then switch to slot 4/slot 7 on a big slaughtermaps with hordes of enemies. I don't know if quicksaving\quickloading is necessary to get this crash reproduced.
3. It should freeze with "not responding" in task manager, and if you are very lucky you'll get a crash with a C0000005 error report

### Your configuration

```ini
https://gist.github.com/CortexReaver/9fd5f60de367ad787221b0c3d0b1c212
```

### Provide a Log

[CrashReport.zip](https://github.com/user-attachments/files/17077204/CrashReport.zip)

**Comment by RicardoLuis0** [comment]
does this happen with 4.13-pre?

**Comment by CortexReaver** [comment]
> does this happen with 4.13-pre?

yes

**Comment by madame-rachelle** [comment]
This is crashing because the `shape` parameter is null in `F2DDrawer::AddShape` - not sure what to do here other than bail, so I am going to add a bail for that. At the very least it should provide a backtrace for what caused it.

**Comment by CortexReaver** [comment]
Updated GZdoom version to 4.13.2, my GPU drivers and mod itself - the game still crashes.

**Comment by CortexReaver** [comment]
A little update on the situation: I've reinstalled Windows, updated my GPU drivers, GZDoom itself to v4.14.0 and Alice mod to 1.1.1  and seems like crashes are gone.
But I getting this error from time to time, when I try to load a quicksave:
![05-01-2025 080549](https://github.com/user-attachments/assets/e3c03ad0-8347-4eae-8702-50bc3a5434ed)
And by the look of it it is a mod problem and not an engine problem.
