### ISSUE TITLE
[BUG] Some surfaces don't render when looking up in 16:9 aspect ratio

### ISSUE THREAD

**Issue by Macil** [ZDoom/gzdoom#2726]
### GZDoom version

Gzdoom master branch, 3524d06813cd4841056901111bf649b023274255

### Which game are you running with GZDoom?

Doom

### What Operating System are you using?

Windows 11

### Please describe your specific OS version

Windows 11 Home

### Relevant hardware info

Nvidia

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

![Screenshot_Doom_20240922_050552](https://github.com/user-attachments/assets/fe24de8d-0d8d-4ca9-b7ca-f1f2b5601eae)

Sometimes when you look up a bit, certain surfaces near the top edge of your screen fail to render. (In the above screenshot, the walls are supposed to go fully around and not have an opening to the sky at the top.) This bug is dependent on the map, your position, your viewing angle, and your screen's aspect ratio. I have only been able to reproduce the bug when using 16:9 resolutions.

This bug is not present in Gzdoom 4.12.2, but it is present in the current master branch (including on b2976444c95455e11bfedbb08e94361034a35e74 and 3524d06813cd4841056901111bf649b023274255).

Shortly prior to b2976444c95455e11bfedbb08e94361034a35e74, I saw this bug somewhat often, but the specific previous reproduction cases I had found were fixed by this commit.

---

I have encountered this bug in [Ultimate Doom In Name Only](https://www.doomworld.com/idgames/levels/doom/Ports/megawads/udino) map E2M6. I've attached a game save exactly where I can see the bug from.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Place this game save in your saved games directory (`%USERPROFILE%\Saved Games\GZDoom\doom.id.doom1.ultimate`): [save06-viewbug.zds.zip](https://github.com/user-attachments/files/17089744/save06-viewbug.zds.zip)
2. Start Gzdoom with Doom 1 and [Ultimate Doom In Name Only](https://www.doomworld.com/idgames/levels/doom/Ports/megawads/udino).
3. Make sure the game is running in a resolution with a 16:9 aspect ratio (1280x720, 1920x1080, etc).
4. Load the "viewbug" game save on map E2M6. The bug should be immediately on screen. If you move or look around, then the bug may go away or come back. If you unpause the game, be aware that the player is on a lift that will start moving up in a few seconds.

**Comment by SanyaWaffles** [comment]
Can confirm this is a thing experienced in some parts of our fork after merging this.

**Comment by SanyaWaffles** [comment]
Can confirm this happens.

**Comment by SanyaWaffles** [comment]
by doing some digging on recent commits from GZDoom to my fork, it seems the isometric additions is when the issue started happening, unfortunately.

Reverting any related commits fix the pitch clipping issue.

**Comment by madame-rachelle** [comment]
At least this helps narrow it down, but right now the issue seems so minor compared to the issues before, that it's not worth yet another full revert. Still though - it sounds like the view frustum math got messed up and if that's the case then that's all that has to be fixed.

**Comment by SanyaWaffles** [comment]
Glad to see this feature could be retained, genuinely.
