### ISSUE TITLE
[Feature] Mouse polling rate support range

### ISSUE THREAD

**Issue by devilduo** [ZDoom/gzdoom#2735]
### GZDoom version

last version

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 10

### Is your feature request related to a problem? Please describe.

Hello.
I searched hard because it seemed like it would be a hassle, but I couldn't find any related information, so I'm posting my question here.

These days, mice support a reporting rate (polling rate) of 125hz to 8000hz.

How much does gzdoom support?

**Comment by mjr4077au** [comment]
GZDoom already polls for mouse input as fast as you can spin frames.
