### ISSUE TITLE
[Feature] change difficulty on save in progress.

### ISSUE THREAD

**Issue by XenoJiiva0053** [ZDoom/gzdoom#2736]
### GZDoom version

g4.13pre-144-g326480cb3

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 10

### Is your feature request related to a problem? Please describe.

its frustrating when you have been playing a megawad and a long time into it you realise its way to hard and if you want to keep the progress with ammo/weapons you have found during the playthrough you need to restart from the begining.

### Describe the solution you'd like

The Ability to change difficulty on a save in progress. making it reload the map your on to the new difficulty with the same items and ammo that you entered the map with. 

### Describe alternatives you've considered

tried changing manually and through commands but only workjs on a new game so cant carry over ammo/ weapons from the previous maps

**Comment by Blue-Shadow** [comment]
There's a `changeskill` console command, whose effect takes place on map change, according to the specs, rather than on starting a new game. Have you tried that?

**Comment by XenoJiiva0053** [comment]
> There's a `changeskill` console command, whose effect takes place on map change, according to the specs, rather than on starting a new game. Have you tried that?

Yes. it did not work unless i started a new game

**Comment by madame-rachelle** [comment]
It appears that `special changeskill <#>` works better right now than that ccmd, which makes me wonder why it was even added at all.

**Comment by Boondorl** [comment]
> It appears that `special changeskill <#>` works better right now than that ccmd, which makes me wonder why it was even added at all.

While it wasn't the intended purpose, it's actually nice for online games since it gives the option to change between maps instead of having to restart the entire game (the CVar is latched and unfortunately you can't even force restart a map in multiplayer meaning the only option was to make an entirely new game session).

**Comment by XenoJiiva0053** [comment]
No i was on skill 3 and used skill 2 but it didnt change when i went to the next map

**Comment by madame-rachelle** [comment]
> Although oddly if it works online, that means it should be working on new map offline as well. Are we sure they were using the right skills? The CVar is 0 indexed so I wonder if they were changing it to the exact same difficulty on accident.

Does it? I didn't see any code at all connected to the response from the network stream. As far as I can tell the command is sent over the network but never executed at all.

**Comment by Boondorl** [comment]
I just tested `changeskill` and it works so I'm not sure what else to say about this bug. It sets `NextSkill` which is the same as the special.

**Comment by RicardoLuis0** [comment]
> The CVar is 0 indexed so I wonder if they were changing it to the exact same difficulty on accident

> No i was on skill 3 and used skill 2 but it didnt change when i went to the next map

seems like that's exactly what happened, 0-indexed skill 2 **is** skill 3

**Comment by JacksonRoberts-Git** [comment]
I am working on a project for class (software engineering) and I need a GitHub task to complete. Not sure if this makes you more or less likely to assign me to this, but I hope you understand where I'm coming from. Thanks.

**Comment by MajorCooke** [comment]
I suspect this person is a bot. ^

**Comment by XenoJiiva0053** [comment]
What could be gained by such a bot in any way. Im so confused

**Comment by XenoJiiva0053** [comment]
Hit the wrong button. Why does it look like a dropdown on mobile if it closes when you hit it...

**Comment by JacksonRoberts-Git** [comment]
I'm not a bot I just need to get a project assigned to me. I'm freaking out a little. I barely know how to use github and my professor is vague as hell about what we need to do next. Just assign this to me for the love of god so she stops breathing down my neck

**Comment by RicardoLuis0** [comment]
> I'm not a bot I just need to get a project assigned to me. I'm freaking out a little. I barely know how to use github and my professor is vague as hell about what we need to do next. Just assign this to me for the love of god so she stops breathing down my neck. Sorry if I'm being rude I just don't want to fail this class. I hate my professor so I don't want to re-take this bullshit class

if you need something, looking through the issues, this one #2264 should be quite easy to do -- adding a cvar, and removing the BFG IWADs from the path if it's set

**Comment by RicardoLuis0** [comment]
(if you're completely new to programming however, i'd suggest looking for a different project -- gzdoom uses C++, which isn't really a good language for beginners, but even so, you're still welcome to try)

**Comment by RicardoLuis0** [comment]
> I just tested `changeskill` and it works so I'm not sure what else to say about this feature. It sets `NextSkill` which is the same as the special. Using `changeskill` and then using `changemap currentmap` should more or less do this, albeit the entire map will have to be restarted given the nature of how skill levels work.

and yeah, this isn't even a valid issue, `changeskill` works, it just uses a 0-index instead of a 1-index

**Comment by XenoJiiva0053** [comment]
The question is if you do this do you get the same weapons and ammo counts as when ypu entered it

**Comment by RicardoLuis0** [comment]
> The question is if you do this do you get the same weapons and ammo counts as when ypu entered it

just do it from the autosave if you want to restart the map, load the autosave, changeskill, changemap
