### ISSUE TITLE
[BUG] New 'label' field in MAPINFO ignores automap options

### ISSUE THREAD

**Issue by Owlet7** [ZDoom/gzdoom#2741]
### GZDoom version

g4.13pre-175-gad4eef3b6

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [x] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Maps that have their label defined in MAPINFO will display the label on the automap even if am_showmaplabel is set to 0.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Run `id1.wad`
2. Set the option "Show map labels" in Automap Options to "Never".
3. Start a new game.
4. Open the automap.

**Comment by coelckers** [comment]
The commit contains a comment which says this is intentional, which makes sense: if the mapper specifies such a name they expect it to be displayed.
