### ISSUE TITLE
GZDoom depends on unreleased version of ZMusic

### ISSUE THREAD

**Issue by alexey-lysiuk** [ZDoom/gzdoom#2747]
Since https://github.com/ZDoom/gzdoom/commit/413aefb0abce28f7123ac33291fe28d736ae1302, GZDoom depends on unreleased version of ZMusic because of [`zmusic_mod_preferredplayer`](https://github.com/ZDoom/gzdoom/blob/413aefb0abce28f7123ac33291fe28d736ae1302/src/common/audio/music/music.cpp#L792) enumeration value usage.

Linux and macOS CI jobs fail to build because of this.

**Comment by madame-rachelle** [comment]
This has been solved, but ci_deps needs an update for the Mac OS version - for some reason my Mac can't seem to compile the .dylibs properly (it only produces .a's)

**Comment by z1atk0** [comment]
> This has been solved, but ci_deps needs an update for the Mac OS version - for some reason my Mac can't seem to compile the .dylibs properly (it only produces .a's)

Sorry for replying to a closed issue, but how exactly has this been solved? The Linux build of the yesterday released 4.13.0 fails with this error:
```
/usr/local/src/gzdoom-g4.13.0/src/common/audio/music/music.cpp: In function ‘bool S_ChangeMusic(const char*, int, bool, bool)’:
/usr/local/src/gzdoom-g4.13.0/src/common/audio/music/music.cpp:792:39: error: ‘zmusic_mod_preferredplayer’ was not declared in this scope; did you mean ‘mod_preferred_player’?
  792 |                 ChangeMusicSettingInt(zmusic_mod_preferredplayer, mus_playing.handle, mod_player, &scratch);
      |                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                       mod_preferred_player
```
The only references of `zmusic_mod_preferredplayer` are where the build error occurs, and in `bin/windows/zmusic/include/zmusic.h`, which is probably irrelevant to building on Linux. As of today, the latest released version of ZMusic is still 1.1.3 from September 2020, and the [relevant commit to ZMusic](https://github.com/ZDoom/ZMusic/commit/6c5cf572aa5447e08a27b87e96a955c27098f542) is from last week. :thinking: :man_shrugging:

**Comment by alexey-lysiuk** [comment]
Ignore Releases page, check Tags instead, https://github.com/ZDoom/ZMusic/releases/tag/1.1.14

**Comment by z1atk0** [comment]
> Ignore Releases page, check Tags instead, https://github.com/ZDoom/ZMusic/releases/tag/1.1.14

Oh, I missed that one ... thanks, and sorry for the noise ... :innocent: :wink:
