### ISSUE TITLE
[BUG] True Color Software does not run well on linux 4k

### ISSUE THREAD

**Issue by michaeljhkim** [ZDoom/gzdoom#2749]
### GZDoom version

4.12.2-m

### Which game are you running with GZDoom?

None

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Arch Linux (Endeavor OS)

### Relevant hardware info

Intel 12700f, amd 6900xt, 4k monitor

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

If you try to run true color software on linux, it does not have great performance. Vulkan has the worst performance, opengl is much better, and opengl es is 90% the way there. You also need to enable v-sync. Sometimes though, there are performance drops. The frames don't drop by much, so I am assuming the problem is in the frame timings. This is concerning because the issue seems to be random sometimes. I even had some drops in doom 1.

The best way to describe it is that it FEELS like it has fps drops, but the counter always stays close to 60 fps. It drops by 5 frames at the most during these times, if at all

### Steps to reproduce the behaviour.

Just run gzdoom in true color software. Opengl es with v-sync is the best you're gonna get it. Open gl with v-sync is second best, and vulkan is unplayable. 

Try with 4k monitor.

### Your configuration

```ini
https://gist.github.com/michaeljhkim/74e5e2e974e3343de0c1540974c283ce
```

**Comment by madame-rachelle** [comment]
I won't close this right away but I am going to have this little bit of commentary about it...

Your CPU is definitely one of the better ones but there is a bit of a bottleneck with how much it can actually perform. It's not a GPU. That being said, 3840*2160 = 8294400 - multiply that by 4 and you get 33177600. Why does this matter? - That's a metric fuckton of data for a CPU to handle 60 times per second, not only that but to move that data from traditional storage (RAM) to a remote location (the GPU's RAM). That's not even counting all the overdraw that it has to handle - the software renderer does a single pass for the opaque objects (walls and flats) and then another pass for the transparent and masked objects (sprites, 2-sided lines, etc). My CPU is no slouch either but it has trouble with this, too.

What's likely happening here is you're missing the frame deadlines and it causes the vsync to rollover to the next frame. You might be rendering at a fairly decent frame rate but if you miss the vsync deadline it still has to wait a frame to process the next frame. You can try and turn vid_vsync off to mitigate this (and if you want to cap the framerate you can use vid_maxfps 60 or something). This will  improve things but it probably won't solve the problem completely.

Either way though, I'd be surprised if any game does well at 4k in truecolor with pure software rendering. Unreal certainly can't handle it too gracefully - I know that for sure.

**Comment by coelckers** [comment]
I will close it right away. There is no magic that can make this faster. CPU power is not endless and at some point the limit will be reached.

**Comment by michaeljhkim** [comment]
Why does the other renderers suck at this though? Shouldn't vulkan in theory run the best?
