### ISSUE TITLE
[BUG] Actor.GetSpecies is in wrong context, must be in "data", not "play"

### ISSUE THREAD

**Issue by GrayFace** [ZDoom/gzdoom#2752]
### GZDoom version

GZDoom g4.13pre-119-g70cf70725

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I'm trying to use LineTracer, but it's complicated by inability to get actor species. This code doesn't work:
```
class MyBulletTracer : LineTracer
{
	override ETraceStatus TraceCallBack()
	{
		if(results.hittype == TRACE_HitActor)
			if(!results.hitactor.bShootable || results.hitactor.GetSpecies().MakeLower() == "hitbox")
				return TRACE_Skip;
		return TRACE_Stop;
	}
}
```
GetSpecies, like any function without side effects, has to be in "data" context.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Add the code above to a ZScript file.
2. An error is produced: `Can't call play function GetSpecies from data context`.

**Comment by JacksonRoberts-Git** [comment]
I am working on a project for class (software engineering) and I need a GitHub task to complete. Not sure if this makes you more or less likely to assign me to this, but I hope you understand where I'm coming from. Thanks.

**Comment by madame-rachelle** [comment]
No, this request isn't worth investing your energy into as an aspiring student as the solution is a one-liner fix (that seems to have already have been done anyway). If you are looking for something let me know your skill level and I can try and fit you with something more appropriate.
