### ISSUE TITLE
[Feature] Static variables (or singleton classes)

### ISSUE THREAD

**Issue by GrayFace** [ZDoom/gzdoom#2754]
### Which game are you running with GZDoom?

None

### What Operating System are you using?

None

### Is your feature request related to a problem? Please describe.

Obvious huge problem in ZScript's design is lack of global variables.

For example, I have an EventHandler that draws effects like blood on the screen. ScriptCall can only call a static function in the class, thus in order to store a value I'd need to iterate over all objects using ThinkerIterator in that static function every time it's called.

### Describe the solution you'd like

Simply allow non-const static variables.
```
class MyClass
{
	static int SomeVar;
	static void SetSomeVar(int v)
	{
		SomeVar = v;
	}
}

In ACS:
	ScriptCall("MyGlobalVars", "SetSomeVar", 5);
```

### Describe alternatives you've considered

Another alternative I thought about is a static `Singleton()` function that would create once and remember an instance of a class. So, you'd do it like
```
class MyGlobalVars
{
	int SomeVar;
	static void SetSomeVar(int v)
	{
		MyGlobalVars.Singleton().SomeVar = v;
		// or MyGlobalVars(MyGlobalVars.Singleton()).SomeVar
	}
}

In ACS:
	ScriptCall("MyGlobalVars", "SetSomeVar", 5);
```

Regarding my use case, I'm using 2 user int CVARS with bitmasks of effects as a work-around. Ugly, but simple and fast.

**Comment by coelckers** [comment]
This was a deliberate decision to omit globals because they are perfect recipe for problems.

**Comment by GrayFace** [comment]
> This was a deliberate decision to omit globals because they are perfect recipe for problems.

No, they're not. No logic to this argument. It's like omitting kitchen knives because they can be used to stab somebody. Global variables are way less dangerous than kitchen knives though. All actors are mutable state, none are safer than global variables.

**Comment by RicardoLuis0** [comment]
you can already do singletons, either per save, or statically per engine run, just use event handlers
https://zdoom.org/wiki/ZScript_global_variables#Creating_global_variables

**Comment by GrayFace** [comment]
> https://zdoom.org/wiki/ZScript_global_variables#Creating_global_variables

Oh, hackish workaround with EventHandler's is even advised in the Wiki!

[coelckers](https://github.com/coelckers)'s assertion that globals cause problems made me think of what problems they could cause and the only ones I can see is when globals are used instead of per-player data. Without globals this problem obviously doesn't have a good solution even more so. The singleton proposal can be outfitted to solve it: `Class.GetSingleton(PlayerNumber)` to return per-player instance (would need a better name), potentially with the ability to outfit it with STAT_STATIC flag as well.

P.S. Disregard my use case in the initial post, I forgot about SendInterfaceEvent.

**Comment by madame-rachelle** [comment]
I think the problem with globals that he was referring to is how easy it can turn code into spaghetti and harder to isolate blocks whether you need to transpose them from one project to another or to refactor a specific block to be more flexible in the long term. I'm pretty sure he means well, and there are definitely pros and cons to having them, but I can tell you that coming on so strong with him like that in your disagreement with him is definitely not going to yield anything positive - it almost never does with developers.

**Comment by RicardoLuis0** [comment]
> > https://zdoom.org/wiki/ZScript_global_variables#Creating_global_variables
> 
> Oh, hackish workaround with EventHandler's is even advised in the Wiki!
> 
> [coelckers](https://github.com/coelckers)'s assertion that globals cause problems made me think of what problems they could cause and the only ones I can see is when globals are used instead of per-player data. Without globals this problem obviously doesn't have a good solution even more so. The singleton proposal can be outfitted to solve it: `Class.GetSingleton(PlayerNumber)` to return per-player instance (would need a better name), potentially with the ability to outfit it with STAT_STATIC flag as well.
> 
> P.S. Disregard my use case in the initial post, I forgot about SendInterfaceEvent.

the issue isn't per-player data, per-player data can just be stored in the player pawn or in an item in the player's inventory -- the issue is -- static fields will not be saved, unlike thinkers/non-static event handlers, so it's very prone to breakage compared to those 2 alternatives

**Comment by RicardoLuis0** [comment]
and if you want semi-const static fields (can be set in class defaults, but not during runtime), you can also use meta fields -- those fields are readonly and stored directly on the class instead of on object instances
