### ISSUE TITLE
Dev public builds show 0 bytes

### ISSUE THREAD

**Issue by hawkwind3** [ZDoom/gzdoom#2756]
### Which game are you running with GZDoom?

None

### What Operating System are you using?

Windows 11

### Please describe your specific OS version

Windows 11 home

### Relevant hardware info

N/A

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Not a bug per-se, and not sure if this is the right place to mention, but the latest public dev builds all show 0 bytes ...

https://devbuilds.drdteam.org/gzdoom/

### Steps to reproduce the behaviour.

Explain how to reproduce
1. 
2.
3.

**Comment by madame-rachelle** [comment]
@Blzut3 manages the dev builds, it looks like something went wrong with the build process.

**Comment by hawkwind3** [comment]
wow ... that was quick !

**Comment by Blzut3** [comment]
Disk was full.  Pruned old builds.

**Comment by madame-rachelle** [comment]
Sorry I should have checked that!
