### ISSUE TITLE
[BUG] Accessing Level.MapName in StaticEventHandler NewGame() results in Hard Lock

### ISSUE THREAD

**Issue by Lemon-King** [ZDoom/gzdoom#2771]
### GZDoom version

GZDoom g4.13

### Which game are you running with GZDoom?

Other

### What Operating System are you using?

Windows 11

### Please describe your specific OS version

Windows 11 Pro

### Relevant hardware info

NVidia 3080, AMD CPU, 32 GB System Ram

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

In a StaticEventHandler which is calling NewGame() which contains Leve.MapInfo results in the engine hard locking and becoming unresponsive without opening console showing the related error.
+LOGFILE is the only way to get the relevant info.

```
class HardLockEventHandler: StaticEventHandler {
    override void NewGame() {
        console.printf("%s", Level.MapName);
    }
}
```

### Steps to reproduce the behaviour.

Add HardLockEventHandler to your events, start a new game, engine should seize up.

### Provide a Log

VM execution aborted: string format failed. Expected a string for format %s.

**Comment by coelckers** [comment]
Works fine for me. Please provide a **runnable example** that shows the described behavior.

**Comment by Lemon-King** [comment]
I reran the test today. Its working, must have been conflicting with something else outside of my test. I'll close this ticket.
