### ISSUE TITLE
[Feature] GZDoom ignores any predefined iwad exsept doom2.wad described in gameinfo

### ISSUE THREAD

**Issue by sportsterv90** [ZDoom/gzdoom#2777]
### GZDoom version

4.12+

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 11

### Relevant hardware info

r7 5700x/32gb ddr4/r6800

### Is your feature request related to a problem? Please describe.

Since ver. 4.12 GZDoom ignores any predefined iwad described in gameinfo, i.e.: string 
IWAD = "doom2.wad"
loads doom2.wad automatically, any other iwads described leads to lading GZD's iwad selecting dialog. Previous versions of GZD works fine. Please, fix it! 
Thank You!

**Comment by RicardoLuis0** [comment]
yes, this is an intentional change, not a bug
https://github.com/ZDoom/gzdoom/commit/e562111a514d41cb237c968b891f9d3a5ede9528
