### ISSUE TITLE
[BUG] Performance issues when a vanilla sky/portal is in view

### ISSUE THREAD

**Issue by sneakernets** [ZDoom/gzdoom#2781]
### GZDoom version

g4.14pre-36-ga0b0db6f6

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

Windows 10 Pro

### Relevant hardware info

i3-10110U, UHD Graphics, Vulkan 1.3, D3D 12_1 feature level, Intel(R) Display Audio

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Using any rendering API with "hardware accelerated" render mode - if any sky/portal is in view, framerate suffers immediately. I have supplied two screenshots with stats enabled which shows this in action. This can reduce performance significantly in some setups. Setting `gl_portals` to `false` remedies the issue for now, at the expense of no sky.

![Screenshot_Doom_20241022_095406](https://github.com/user-attachments/assets/02c422fb-fd16-4eb4-ab9a-b89e522f8233)
![Screenshot_Doom_20241022_095417](https://github.com/user-attachments/assets/c01201a5-57ff-40c1-86b7-8280d0401326)

Bonus screenshot of this scenario with renderdoc, showing draw calls blasting up to quadruple digits: 
![image](https://github.com/user-attachments/assets/13a32a99-2722-46f7-90a7-70a0f98d17ce)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. run gzdoom with Doom2 Map01, stock config
2. type `stat fps` in console
3. turn left and notice the framerate differences

### Your configuration

```ini
Stock config.
```

### Provide a Log

no log generated.

**Comment by sneakernets** [comment]
> is this new in 4.13/4.14?

No, this issue has existed since at least 2020, perhaps earlier.

**Comment by coelckers** [comment]
It's probably just the low end hardware at play here. The sky is drawn with a large polygon mesh consisting of hundreds of triangles rendered fullscreen below the actual map.

On any real graphics card the pixel fill rate is good enough to never notice this but Intel UHD without any number is at the lowest end of the low end where things are very different.
These chips are not made for gaming and it will definitely show.
