### ISSUE TITLE
[BUG] Cant compile gzdoom-g4.13.1 from source due to ZMusic missing definition

### ISSUE THREAD

**Issue by JoshuaPettus** [ZDoom/gzdoom#2784]
### GZDoom version

4.13.1

### Which game are you running with GZDoom?

None

### What Operating System are you using?

Linux x86_64  

### Please describe your specific OS version

Fedora 40

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

While compiling it fails at music.cpp.  I installed the current zmusic 1.1.14.  Is this not the supported version to use as it is clearly missing an expected function?

GCC version 14.2.1 20240912 (Red Hat 14.2.1-3)

> gzdoom-g4.13.1/src/common/audio/music/music.cpp:792:39: error: ‘zmusic_mod_preferredplayer’ was not declared in this scope; did you mean ‘mod_preferred_player’?
>   792 |                 ChangeMusicSettingInt(zmusic_mod_preferredplayer, mus_playing.handle, mod_player, &scratch);
>       |                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~
>       |                                       mod_preferred_player
> 

Clang version 18.1.8 (Fedora 18.1.8-1.fc40)

> gzdoom-g4.13.1/src/common/audio/music/music.cpp:792:25: error: use of undeclared identifier 'zmusic_mod_preferredplayer'
>   792 |                 ChangeMusicSettingInt(zmusic_mod_preferredplayer, mus_playing.handle, mod_player, &scratch);
> 

zmusic.h is in the expected place and was found at configure: /usr/include/zmusic.h

**Comment by madame-rachelle** [comment]
Have you tried updating your ZMusic, first?

**Comment by coelckers** [comment]
The constant is clearly present in the 1.1.14 version. For some reason you are using an old header file.

**Comment by JoshuaPettus** [comment]
As i mentioned, I have 1.1.14 installed. I made sure to uninstall the previous one.  After I posted i did find the declaration in /usr/include/zmusic.h but its ignoring it.   Is there some folder that takes prcedence that may have an older version?

**Comment by JoshuaPettus** [comment]
Sorry,  took me a bit to get back to this.  One find command later, I found an old copy of the zmusic.h in /usr/local/include....

**Comment by domdfcoding** [comment]
If one uses the `auto-setup-linux.sh` script from this repo it pulls down zmusic 1.1.12, which as noted is too old. That script (and possibly the other `auto-setup`s) need updating to use the newer zmusic. Using the script as it stands results in a failed build.
