### ISSUE TITLE
[Feature] Return the "Dark" Sector light mode.

### ISSUE THREAD

**Issue by ShroomiePerson** [ZDoom/gzdoom#2788]
### GZDoom version

GZDoom g4.13.1

### Which game are you running with GZDoom?

None

### What Operating System are you using?

None

### Is your feature request related to a problem? Please describe.

a while ago, a handful of options for Sector light mode were removed, and i believe a few were added. among these options was the "Dark" light mode. this is inconvenient, as multiple mods had it in mind when they were being designed, with some of the most notable mods being Ashes 2063, Ashes: Afterglow, and (i believe, there's some conflicting information,) GZ PT. 

this isn't something that's urgent, i've figured out i can use `gl_maplightmode 3` to get Dark back, but as i've said, it's inconvenient.

### Describe the solution you'd like

add it back lol

### Add any other context or screenshots about the feature request here.

https://www.moddb.com/mods/ashes-2063

https://batandy.itch.io/gz-pt

**Comment by MajorCooke** [comment]
[Here, use this](https://forum.zdoom.org/viewtopic.php?t=78307) in the mean time.

**Comment by RicardoLuis0** [comment]
> as multiple mods had it in mind when they were being designed
the light mode is still in the engine, so if a map is designed for it, it just needs to set the lightmode to dark in MAPINFO

**Comment by ShroomiePerson** [comment]
>the mapper just needs to set the lightmode to it in MAPINFO

but not every mapper is going to know to do that, and the mods i used as an example (for example) are unlikely to be updated.

**Comment by MajorCooke** [comment]
I'll update my mod as needed since I use it with every map I play with. I know it's not ideal, but it's the best thing you have in the mean time.
