### ISSUE TITLE
[BUG] Chex Quest: OB_MPLAZ_SPLASH isn't used in-game.

### ISSUE THREAD

**Issue by Acts19quiz** [ZDoom/gzdoom#2789]
### GZDoom version

GZDoom g4.13.1

### Which game are you running with GZDoom?

Other

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

Windows 10 LTSC

### Relevant hardware info

i6700k, GForce 980Ti

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When using the LAZ Device (BFG 9000) in Chex Quest net games, the tracer death doesn't trigger the `OB_MPLAZ_SPLASH` obituary. Instead, `OB_MPBFG_SPLASH` is used.

This doesn't affect direct projectile hits, which correctly call `OB_MPLAZ_BOOM`.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Start a Chex Quest deatmatch netgame. 
2. Get more than one player, or use bots.
3. Use the LAZ Device to kill an opponent via tracers (not a direct projectile hit).
![Screenshot_Chex_20241028_200410](https://github.com/user-attachments/assets/6c375f62-60a1-43e4-a5b1-77e20f5c8225)
![Screenshot_Chex_20241028_200426](https://github.com/user-attachments/assets/4bf0ad5f-42dd-434a-be39-e7c996858fad)

**Comment by coelckers** [comment]
Corrected the setup in the spreadsheet containing the text.

**Comment by Acts19quiz** [comment]
Thanks! If I may ask, what spreadsheet is updated or has the Chex strings?

https://docs.google.com/spreadsheets/d/1pvwXEgytkor9SClCiDn4j5AH7FedyXS-ocCbsuQIXDU/edit?usp=sharing

I viewed this, but couldn't find them.

**Comment by Acts19quiz** [comment]
Never mind. I found the tabs. Once again, thanks.
