### ISSUE TITLE
[BUG] [GZDoom 4.13.1] Loading save in multiplayer session results in odd breakage

### ISSUE THREAD

**Issue by zhs2** [ZDoom/gzdoom#2791]
### GZDoom version

GZDoom 4.13.1

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

Windows 10 Pro

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

![Screenshot_Doom_20241029_223912](https://github.com/user-attachments/assets/51fda4fa-8509-4db4-9a22-79e31929cb82)
There is a chance in using -loadgame in a multiplayer session that odd breakage occurs for player 2, including the render viewpoint to be rolled for no reason (this breaks strafing and looking from side to side as well), repeated OALSound errors (pictured above), and, most disappointingly, an instant desync.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Create a multiplayer game with `-host 2` and `-join 127.0.0.1`
2. Save the game during this session
3. Reload the save with `-host 2 -loadgame <savename>` and `-join 127.0.0.1 -loadgame <savename>` until the breakage occurs (this may take a few tries, it doesn't happen every time)

**Comment by nashmuhandes** [comment]
It happened to me on my second try of loading the game.

Using GZDoom 4.13.2.

cmdlines:

```
gzdoom.exe -noautoload -iwad doom2.wad -host 2 -loadgame save00
gzdoom.exe -noautoload -iwad doom2.wad -join localhost -loadgame save00
```

![Screenshot_Doom_20241103_224729](https://github.com/user-attachments/assets/9bf056e1-f259-4ae5-bcad-0c0027616818)

**Comment by nashmuhandes** [comment]
Fixed with https://github.com/ZDoom/gzdoom/commit/714eb8910c2f3360f1997304bb94d469c76f5c49
