### ISSUE TITLE
[BUG] Automap marking only works in Doom and Strife?

### ISSUE THREAD

**Issue by nashmuhandes** [ZDoom/gzdoom#2805]
### Which game are you running with GZDoom?

None

### What Operating System are you using?

None

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Seems like the automap marking feature (default bound to M on the automap screen) does not work in Hexen and Heretic. Seems to be an oversight and I see no reason why the feature has to be excluded from the Raven games in a modern source port.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. 
2.
3.

**Comment by Blue-Shadow** [comment]
The `AMMNUM0, AMMNUM1, AMMNUM2, ..., AMMNUM9` graphics seem to be missing from the Raven games, so you either provide them through a patch yourself or switch to a font to draw the marks with (you can find the option to do that in the Automap Options menu). You have a choice of small, large or console.

**Comment by madame-rachelle** [comment]
Maybe we can provide them in the default resource file? AFAIK they are simple 3x5 low-res font glyphs, for numbers that's as trivial to handle at that resolution as 7-segmented displays.

**Comment by madame-rachelle** [comment]
Fixed with https://github.com/ZDoom/gzdoom/commit/2bc561d135bd58e102f7bfe0156a6c134d3af26f
