### ISSUE TITLE
disable head bob / weapon bob in all games

### ISSUE THREAD

**Issue by retropwned** [ZDoom/gzdoom#2813]
### GZDoom version

4-13-2

### Which game are you running with GZDoom?

Heretic

### What Operating System are you using?

Windows 11

### Is your feature request related to a problem? Please describe.

i can't find any source port that allows heretic/hexen etc. to remove head/weapon bob.

### Describe the solution you'd like

remove head bob / weapon bob from all games

### Describe alternatives you've considered

i've tried other ports.. even finding a list of console commands to do so comes up nada.

**Comment by madame-rachelle** [comment]
This is already in. Use the console and enter these commands:
```
movebob 0
stillbob 0
```

**Comment by retropwned** [comment]
thank you so so much. works beautifully. i couldn't find reference for this anywhere.
