### ISSUE TITLE
[BUG] BishopFX has erroneous STRIFEDAMAGE flag

### ISSUE THREAD

**Issue by PerdGateEnjoyer** [ZDoom/gzdoom#2829]
### GZDoom version

4.13.1B

### Which game are you running with GZDoom?

Hexen

### What Operating System are you using?

Windows 11

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The DECORATE definition of BishopFX (the green-yellow magical balls fired by Hexen's Dark Bishop) are given the STRIFEDAMAGE flag, meaning it deals roughly half damage (1-4 instead of 1-8). I believe this to be a mistake caused by someone thinking that BishopFX was a projectile fired by the Strife boss known as the Bishop.

**Comment by coelckers** [comment]
The flag is not erroneous. The Bishop had the same behavior but differently coded so when the flag was added it was used to get rid of that special handling.
