### ISSUE TITLE
[BUG] UDMF Doom64-Style lighting disables brightmaps

### ISSUE THREAD

**Issue by disasteroftheuniverse** [ZDoom/gzdoom#2848]
### GZDoom version

GZDooom 4.13.2

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 11

### Please describe your specific OS version

Windows 11 Pro

### Relevant hardware info

AMD RX 780

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

This behavior was only observed with the UDMF format. It has not been tested with other formats, but I'm not sure if Doom64 style lighting is available in other formats. _Applying Doom64 lighting to a sector disables brightmaps on anything affected by that lighting in the sector_. This appears to also affect actors in the sector as well, when the corresponding "things" option is checked in Doom builder.

Applying Doom64 lighting like this:
![image](https://github.com/user-attachments/assets/eec9b3e8-a481-4e99-b048-330554595d01)

results in this:
![Screenshot_Doom_20241201_140233](https://github.com/user-attachments/assets/8de2f07c-3980-47e8-a1c0-2deab4722560)

This behavior does not occur for Non-Doom64-style colored lighting.

When sector colors are applied like so:
![image](https://github.com/user-attachments/assets/0c0b9183-4833-470b-b03d-302ab13fb0c4)

The brightmaps work correctly.
![Screenshot_Doom_20241201_140236](https://github.com/user-attachments/assets/5188433b-0b52-4147-8191-9e03fdfebd9e)

The obvious problem is that this makes it such that Doom64-style gradients unusablewith brightmaps, rendering Doom64-style lighting useless.

You can see the bug in action here
[D64bug.zip](https://github.com/user-attachments/files/17970379/D64bug.zip)

[Here is the config file being used](https://gist.github.com/disasteroftheuniverse/f698122b6f5330c5e351d15932b58066)

### Steps to reproduce the behaviour.

Simply launch the attached PK3 to see this in action. It should be self-explanatory. The room to the left of the player uses Doom64-style lighting. The room to the right uses the UDMF sector color for lighting.

### Your configuration

```ini
https://gist.github.com/disasteroftheuniverse/f698122b6f5330c5e351d15932b58066
```

**Comment by madame-rachelle** [comment]
This has been reported before and the response always is that Doom64 colors are not lights but materials.

https://forum.zdoom.org/viewtopic.php?t=68033
