### ISSUE TITLE
DropAmmoFactor value not working correctly in Ultimate Doom

### ISSUE THREAD

**Issue by Q3BFG10K** [ZDoom/gzdoom#2854]
On death, Doom shotgun grunts drop 4 shells by default. I cleared all skills and made a custom skill with SpawnFilter = 4. 

To get them to drop **2** shells I need to use **DropAmmoFactor** **.25**, and to get **8** I need to use **1.1**. This doesn't make any sense. Either the percentage calculation is wrong or something else is interfering with the value that I'm unaware of.

**AmmoFactor** works fine, with **.5** and **2** behaving as expected (**2** and **8** shells, respectively).

**Comment by RicardoLuis0** [comment]
working as intended, DropAmmoFactor is 0.5 by default, and multiplies the ammo, the shotgun has 8 ammo, so the 0.5 default times 8 is 4, times 0.25 is 2, times 1 is 8
