### ISSUE TITLE
[BUG] Failure to parse "label = clear" in UMAPINFO lump.

### ISSUE THREAD

**Issue by xiiixvv** [ZDoom/gzdoom#2858]
### GZDoom version

Release g4.13.2

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [x] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Hello. Been having an issue with using UMAPINFO in the latest release of GZDoom as of writing this.

In the wad file for a map I'm currently making, I have a UMAPINFO lump that has the line "label = clear" in order to clear the map designation in the automap. When trying to run the wad inside of GZDoom, it immediately pull up a "Fatal Error" window, with the error in question being that the engine "expected a string constant for the label variable but got 'clear' instead" (See the bottom of the log text provided). I've been running this a lot more in Woof! and Helion and both seem to run the wad just fine (Woof! correctly parses 'label = clear' and gives expected behavior, while Helion also seems to notice it, but ignores it and puts "MAP01" in the level's name anyway)

I did see that this error was encountered before (#2774), and a fix was administered, though I wouldn't be writing a bug report if that fix stuck.

[test.zip](https://github.com/user-attachments/files/18092075/test.zip)

The following wad file replicates the crash with an extremely simple UMAPINFO lump (only "levelname = "Test" and "label = clear" being provided) accompanied with a small room and a singular player spawn. Ive tested it with my install and it replicates the same error as it does with my map.

I also tested this without run parameters in ZDL (been using "-warp 01 -pistolstart -nomonsters" or ditto but without "-nomonsters" for the purpose of testing the map) with the thought that maybe, just maybe it causes a weird, weird quirk, but the crash still happens, regardless of parameters.

Hoping I'm not sounding crazy.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Download provided wad file
2. Run GZDoom 4.13.2 with the wad file and DOOM2 as the IWAD (ZDL is what I use, if needed)
3. Crash will happen

### Provide a Log

OS: Windows 10 (NT 10.0) Build 19045
    
GZDoom version g4.13.2
W_Init: Init WADfiles.
adding G:/Games/DOOM/gzdoom-4-13-2-windows/gzdoom.pk3, 679 lumps
adding G:/Games/DOOM/gzdoom-4-13-2-windows/game_support.pk3, 3308 lumps
adding G:/Games/DOOM/IWADS/DOOM2.WAD, 2919 lumps
adding G:/SteamLibrary/steamapps/common/Ultimate Doom/rerelease/id24res.wad, 530 lumps
adding G:/Games/DOOM/gzdoom-4-13-2-windows/game_widescreen_gfx.pk3, 214 lumps
adding G:/ModTools/mywads/test.wad, 12 lumps
S_Init: Setting up sound.
I_InitSound: Initializing OpenAL
  Opened device IOpenAL Soft on Speakers (Realtek High Definition Audio)
  EFX enabled
I_InitInput
I_StartupMouse
I_StartupKeyboard
I_StartupXInput
I_StartupRawPS2
I_StartupDirectInputJoystick
GL_VENDOR: Intel
GL_RENDERER: Intel(R) Iris(R) Xe Graphics
GL_VERSION: 4.6.0 - Build 31.0.101.4953 (Core profile)
GL_SHADING_LANGUAGE_VERSION: 4.60 - Build 31.0.101.4953

Max. texture size: 16384
Max. texture units: 32
Max. varying: 64
Max. combined shader storage blocks: 80
Max. vertex shader storage blocks: 16
Resolution: 1280 x 1024
I_Init: Setting up machine state.
CPU speed: 3696 MHz
CPU Vendor ID: GenuineIntel
  Name: Intel(R) Core(TM) i3-10105F CPU @ 3.70GHz
  Family 6, Model 165, Stepping 3
  Features: SSE2 SSE3 SSSE3 SSE4.1 SSE4.2 AVX AVX2 F16C FMA3 BMI1 BMI2 HyperThreading
V_Init: allocate screen.
ST_Init: Init startup screen.
Checking cmd-line parameters...
S_InitData: Load sound definitions.
G_ParseMapInfo: Load map definitions.

Execution could not continue.
Script error, "test.wad:UMAPINFO" line 3:
Expected string constant but got identifier 'clear' instead.

**Comment by Blue-Shadow** [comment]
The fix has yet to make it into an official release. It's only available in [development builds](https://devbuilds.drdteam.org/gzdoom/) currently.

**Comment by xiiixvv** [comment]
> The fix has yet to make it into an official release. It's only available in [development builds](https://devbuilds.drdteam.org/gzdoom/) currently.

Ah. very very wierd still. thank you.
