### ISSUE TITLE
[BUG] Force Aspect Ratio does not affect the actual aspect ratio of the screen

### ISSUE THREAD

**Issue by WoolieWool** [ZDoom/gzdoom#2860]
### GZDoom version

Git 4.14pre-76-gccd38afbc

### Which game are you running with GZDoom?

Hexen

### What Operating System are you using?

Other

### Please describe your specific OS version

Windows 11 23H2 and Arch Linux (bug affects both)

### Relevant hardware info

AMD Ryzen 7 3800X, nVidia GeForce RTX 2070

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Trying to use aspect ratio scaling to stretch or letterbox the screen to a specific ratio has been broken in GZDoom (and more recently LZDoom) for a long time--it still worked in LZDoom versions using the old 3.8 codebase, but the bug has crept into the newer fork used by devbuilds.drdteam.org, probably due to some change to the rendering backend pulled from GZDoom. I used to be able to run a resolution of 428x200 stretched to 16:9, which is similar to the widescreen low resolution mode of Crispy Doom, Woof, and DSDA-Doom. However, the aspect ratio of the screen canvas is now fixed, and Force Aspect Ratio just stretches/squashes the UI and FOV without changing the screen canvas. There is a workaround of sorts in the Vanilla Essence mod, but its scaling introduces many visual artifacts (like a dark line at the top of the status bar), is fussy to configure, and has to be manually set every time I play the game.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Set custom resolution scaling to any resolution desired (in my case: 428x200)
2. Force aspect ratio to desired ratio (in my case: 16:9)
3. Observe that neither the Letterbox nor Stretch styles change the shape of the screen

### Your configuration

```ini
vid_activeinbackground=false
vid_adapter=2
vid_aspect=1
vid_brightness=0
vid_contrast=1
vid_cropaspect=false
vid_defheight=2160
vid_defwidth=3840
vid_fullscreen=true
vid_gamma=1
vid_hdr=false
vid_maxfps=0
vid_preferbackend=1
vid_rendermode=0
vid_saturation=1
vid_scale_customheight=200
vid_scale_custompixelaspect=1
vid_scale_customwidth=428
vid_scale_linear=false
vid_scalefactor=1
vid_scalemode=5
```

**Comment by coelckers** [comment]
That was never the point here. This feature is to force mismatching resolutions to the sizes of unusual screens, e.g. if you have a 4:3 monitor but set it up to display a 16:9 image horizontally squashed.

**Comment by madame-rachelle** [comment]
The feature only works if `vid_scalemode` is 0 or 1. It will not work if you use a custom resolution.
