### ISSUE TITLE
[BUG] Script errors when starting BoA

### ISSUE THREAD

**Issue by x3003** [ZDoom/gzdoom#2864]
### GZDoom version

gzdoom-x64-g4.14pre-121-g325817afd

### Which game are you running with GZDoom?

Other

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

win10 home up-to-date

### Relevant hardware info

amd r5 2600 with gtx 1060 3GB

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When starting Blade of Agony (latest git version), gzdoom outputs some script errors.
The problem started with gzdoom-x64-g4.14pre-121-g325817afd, as version g4.14pre-120-gfb660fa3c was still good

GScript error, "boa_c3.pk3:scripts/actors/playerfollowers.zs" line 501:
GCannot convert Pointer<Class<Actor>> to Pointer<Class<PathMarker>>
GScript error, "boa_c3.pk3:scripts/actors/playerfollowers.zs" line 1239:
GCannot convert Pointer<Class<Actor>> to Pointer<Class<PathMarker>>

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Start Boa
2. Wait a little
3. Some errors start appearing.

**Comment by RicardoLuis0** [comment]
BoA is using an older version of zscript, which used to have a less restrictive (incorrect) type system for arrays kept around for compatibility, that incorrect type system was removed, due to correctness issues, so the mod needs to be updated now
https://github.com/ZDoom/gzdoom/commit/325817afdfef647a206488b7ee4a08d4eb3da299

**Comment by RicardoLuis0** [comment]
please take this up with BoA, not gzdoom

**Comment by x3003** [comment]
Ok, thx for explaining.
