### ISSUE TITLE
[BUG] myhouse.pk3 script error

### ISSUE THREAD

**Issue by JoMaZu787** [ZDoom/gzdoom#2874]
### GZDoom version

GZDoom g4.14.0-m

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Arch Linux (Hyprland)

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When I try to run the map myhouse.pk3, I get this error message in my terminal:
```Script error, "myhouse.pk3:zscript" line 75: Cannot convert to name```

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Download myhouse.pk3 from the [google drive](https://drive.google.com/drive/folders/1IdH20R6bPg_Sp2Htu0Z-u_wP2AbKoaBz)
2. Place it in ~/.config/gzdoom
3. Run gzdoom with `SDL_VIDEODRIVER=wayland gzdoom ~/.config/gzdoom/myhouse.pk3`

### Your configuration

```ini
gzdoom.ini is unmodified
```

### Provide a Log

[gzdoom.log](https://gist.github.com/JoMaZu787/4073a80a93583e0d399d00a616ef0488)

**Comment by RicardoLuis0** [comment]
necessary compat break, needs patching from mod author or third parties
https://forum.zdoom.org/viewtopic.php?p=1257137
