### ISSUE TITLE
[Feature] Ability to set player name and color from the command line

### ISSUE THREAD

**Issue by msmigiel** [ZDoom/gzdoom#2877]
### GZDoom version

GZDoom 4.11

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 11

### Is your feature request related to a problem? Please describe.

I often play multiplayer with friends and we have several computers that we each play on, though sometimes not always on the same computer. As of now, to change our names and colors, we need to go into the options and set them before we play. It would be very nice to have a way to set these when launching GZDoom.

### Describe the solution you'd like

It would be great if there were command line flags to set the player's name and colors. This way, it will be easier to launch multiplayer games from the command line or a launcher and changing our names and colors will be much easier than digging in the options every time we play.

### Describe alternatives you've considered

Aside from manually editing the options via the menus, I don't know of another way to do this.

**Comment by madame-rachelle** [comment]
Already in.

`GZDoom -host/join <whatever> +color "80 40 20" +name "your name"`
color  is a space-separated hex triplet that otherwise works just like HTML colors, but do not use the pound sign (#).

**Comment by msmigiel** [comment]
Thank you! I'm sorry that I missed this in the documentation.
