### ISSUE TITLE
[BUG] Missing text for JOYMNU_JOYENABLEINBACKGROUND

### ISSUE THREAD

**Issue by nashmuhandes** [ZDoom/gzdoom#2882]
### GZDoom version

4.14

### Which game are you running with GZDoom?

Doom

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

![image](https://github.com/user-attachments/assets/2fc34ea5-6d9d-4678-966f-cd87387f57e6)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. 
2.
3.

**Comment by madame-rachelle** [comment]
Looks like no one added it to the [translation sheet](https://docs.google.com/spreadsheets/d/1pvwXEgytkor9SClCiDn4j5AH7FedyXS-ocCbsuQIXDU/edit?gid=501044242#gid=501044242)

**Comment by madame-rachelle** [comment]
I'm going to close this as finished since it's on the translation sheet now, but it might be some time before people come in and do the translations for it in other languages.
